### ISSUE TITLE
Flatten IA for "New Source"

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-studio-classic#1002]
You need to click on "New Project" to get to a modal with the option "New Source" in it. Let's flatten it and have "New Project" and "New Source" at the same place in the hierarchy?

**Comment by samanpwbb** [comment]
See https://github.com/mapbox/mapbox-studio/pull/801#commitcomment-7697357 - which introduces this change. Earlier versions of the app were more like you describe. I am not sure which is better. There are advantages to both. 

> Let's flatten it and have "New Project" and "New Source" at the same place in the hierarchy?

In Studio we use the word "project" differently from how you're using it here. You can have two types of projects: a "style project" and a "source project". The semantics of this have always made me feel a little uneasy but I haven't come up with a clearer alternative.

**Comment by samanpwbb** [comment]
Lets keep this as is for now.
