### ISSUE TITLE
client tests hanging (osx 10.10)

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#1007]
Unable to run client tests on any of my dev branches or gh-pages. Client tests are hanging on phantom.js with no terminal output, no CPU activity. I have waited 10+ minutes.

I went through commit history to see if there was a point at which the tests began. No luck.

I tried using old versions of phantom.js, no luck

Here are the affected tests:

```
'source-tmp', // hangs
'source-upload', // pass with warning about Unsafe JavaScript
'source-export', // pass with warning about Unsafe JavaScript
'style-tmp', // hangs
'style-userlayers', // hangs
```

For me, the tests that pass give this warning:

```
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL 
file:///Users/i/tools/tm2/test/test-phantom.js. Domains, protocols and ports must match.
```

For @ian29 all tests passed and gave the same warning.

**Comment by ian29** [comment]
actually not all tests passed for me. 2 js-upload tests fail:

```
# .js-upload
ok 180 has .js-upload button
ok 181 no mapid
ok 182 #mapstatus
ok 183 #mapstatus.loading
not ok 184 model has mapid
  ---
    operator: equal
    expected: true
    actual:   false
  ...
not ok 185 UI has mapid
  ---
    operator: equal
    expected: true
    actual:   false
  ...
```

full output from test-client.js:
https://gist.github.com/ian29/2e3ab541e15c1405bb76

**Comment by ian29** [comment]
also im on MAC OS X 10.10

**Comment by samanpwbb** [comment]
Haven't seen after upgrading phantom version.

**Comment by samanpwbb** [comment]
Client tests are stalling on phantom for me again.  Tried phantom versions 1.9.16, v1.9.11, v1.9.10, v1.9.8 no luck.

_Edit: restarted my computer and now tests are working. Clearly, this is something on my end so I'm going to close._
