### ISSUE TITLE
Warn user if style is too slow

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#1016]
![screen_shot_2014-11-12_at_7_39_07_pm](https://cloud.githubusercontent.com/assets/108094/5021459/a3954ccc-6aa3-11e4-998c-73dcfb58ec4c.png)
- source mode as well. 

Should we disallow uploading if value is above limit?

**Comment by yhahn** [comment]
Samesame for source btw.

**Comment by samanpwbb** [comment]
@yhahn you say these limits are hardcoded somewhere? Can you point me to the right place?

**Comment by yhahn** [comment]
Yep we have to multiple limits:

```
# styles
average render time must be < 300ms
max render time (slowest tile) must be < 1000ms


# sources
max tile size must be < 500k
```

**Comment by samanpwbb** [comment]
--> #1017
