### ISSUE TITLE
Source UI: clarify meaning of buffer size

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#1026]
Buffer size is mysterious:
![screen shot 2014-11-17 at 1 53 37 pm](https://cloud.githubusercontent.com/assets/108094/5075487/2ce63a70-6e61-11e4-991c-b0772e9b18aa.png)

Inline copy? Something like:

> Increase the buffer size to increase the flexibilty of label, marker, and shield symbolizer placement at the cost of speed and efficiency.

A UI component that visualizes buffer size?
![image3540](https://cloud.githubusercontent.com/assets/108094/5075980/647443d4-6e65-11e4-9429-c529fec1fbc9.gif)

**Comment by ian29** [comment]
+1 for anything that communicates to users that source mode is basically making 1 vector tile at time

**Comment by alexrollin** [comment]
+1 for even more information than that :)

## 

Alex

**Comment by ian29** [comment]
er, to clarify @samanpwbb: i was specifically referring to the graphic of the buffer size increasing. i think this could be really helpful.

**Comment by amyleew** [comment]
Added inline copy explaining functionality and giving tips on defining it based on feature type.

![image](https://cloud.githubusercontent.com/assets/4587826/6117295/663f9a02-b081-11e4-96d6-66838bf6cbf5.png)

cc @samanpwbb @springmeyer

**Comment by amyleew** [comment]
Merged
