### ISSUE TITLE
Source UI: clarify meaning of minzoom/maxzoom

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#1027]
These innocuous looking sliders are powerful / dangerous:
![screen shot 2014-11-17 at 2 25 28 pm](https://cloud.githubusercontent.com/assets/108094/5076005/9e24c1c6-6e65-11e4-9784-ee556d40c4ca.png)
- Add explanatory copy.
- Visualize or display the size (in tiles?) of export for user as user changes export area.

**Comment by springmeyer** [comment]
:+1: Would love @amyleew 's ideas of good language for this.

**Comment by amyleew** [comment]
@samanpwbb @springmeyer how does these sound: 

Minzoom
- "Lowest zoom where data appears" 
- "Data first appears at this zoom"

Maxzoom
- "Highest zoom with _stored_ data, high quality  [overzooming](https://www.mapbox.com/mapbox-studio/source-manual/) available 4-6 levels beyond maxzoom."
- "Highest zoom where data is stored, check quality of [overzoommed](https://www.mapbox.com/mapbox-studio/source-manual/) data beyond maxzoom"
- "Highest zoom where data is stored, data is displayed beyond maxzoom, _see [overzoom](https://www.mapbox.com/mapbox-studio/source-manual/)_"

**Comment by ljbade** [comment]
I think a count of the number of tiles would be great, rounded to a postfix, e.g. k m

**Comment by amyleew** [comment]
Inline copy to define function and give tips on how to use it. Thoughts? @samanpwbb @springmeyer

![image](https://cloud.githubusercontent.com/assets/4587826/6117597/a0751344-b083-11e4-91db-ff7ad29ee121.png)

> Visualize or display the size (in tiles?) of export for user as user changes export area.

Can you explain? Will it function similar to file size over zoom level (seen below) and be based on cached tiles in view or be more generic value?

![image](https://cloud.githubusercontent.com/assets/4587826/6117676/4115ca5a-b084-11e4-85a7-ecdb9a60d87f.png)

**Comment by ljbade** [comment]
@amyleew, yeah it is similar in a way to the file size indicator (which I only discovered recently BTW).

I was thinking along the lines of more a generic values, ie the number of tiles instead of file size, but perhaps it should be file size? Number of tiles can be easily calculate but file size is harder.

The main idea is to have something that gets very huge as you slide the slider to the right to provide tactile feedback that you are doing something bad and you will be generating _a lot_ of tiles.

**Comment by ljbade** [comment]
Perhaps even a a colour hint, ie slider turns yellow/red as you get into the ridiculous number of tiles range.

**Comment by amyleew** [comment]
per chat w/ @yhahn @samanpwbb
- expand help copy to best practices 
  - _i.e._ point data minzoom shouldn't start until 9+, highest maxzoom is rarely 14+
- limiting slider values to optimal range and zoom levels outside that can altered manually in project.yml

**Comment by amyleew** [comment]
@ljbade the issue with generating a tile size is that it may not be exact to the particular data set and it'll be hard to determine in the settings tab. better to teach the process for determining the best values and work on building future functionality into the tool itself.

**Comment by ljbade** [comment]
Limiting the range in the UI but allowing override in the YML is a great compromise. Keeps it simple.

**Comment by ljbade** [comment]
I wouldn't limit the min zoom though since it doesn't have that much of an impact on generation time since anything too big in the single tile will error anyway. Although I did notice Map Studio does not complain until a vector tile is 64MB, where as after upload unpacker complains about > 200kb.

**Comment by amyleew** [comment]
Merged :+1:
