### ISSUE TITLE
Use remote GeoJSON API endpoint for Source Datasource

### ISSUE THREAD

**Issue by osxi** [mapbox/mapbox-studio-classic#1029]
I've tried adding a URL to the OGR File field in a Source as per:
![image](https://cloud.githubusercontent.com/assets/6734090/5078415/37937e40-6e72-11e4-8a79-cd589a09ffc9.png)

and I get: `OGR Plugin: connection failed: /<path/to/my.tm2source>/https://my.api.endpoint.com/features.geojson was not found or is not a supported format`.

I tried manually adding my URL endpoint in my data.yml file and get a similar error. Is there a way to specify a remote API endpoint instead of, in my case, a static GeoJSON file?

**Comment by springmeyer** [comment]
This is not a supported feature. The GeoJSON file needs to be local to your filesystem.

**Comment by osxi** [comment]
Any chance of this being implemented in the near future or is there a good alternative? (asked for posterity and then issue should probably be closed)

I was hoping to style GeoJSON from a remote API with CartoCSS.

**Comment by aaroncrawford** [comment]
:+1: to this request.  This would be a very powerful feature.

**Comment by springmeyer** [comment]
The reason this feature (which was supported in TileMill) is not implemented is that to do it properly is very involved and unit tests for it would need to be sophisticated and mock various types of http and network failures.

There is no doubt this is useful and powerful, but it would need a serious champion to implement in a way that would be viable to support long term.
