### ISSUE TITLE
0.2.0+ windows followup tasks

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#1030]
Capturing @springmeyer's tasks from https://github.com/mapbox/mapbox-studio/pull/1005.
- [x]  tag mapnik-omnivore (on master currently)
- [x]  fix appveyor to use our node.exe (default node.exe is 32 bit on appveyor vms) - https://github.com/mapbox/mapbox-studio/commit/4225324cb888944b97552774809ee8a6c38b661a
- [x]  Try to workaround problem setting of environment variables for c++ addons - https://github.com/springmeyer/node-addon-env-debug | done via https://github.com/mapbox/node/pull/5
- [x] new node-cpp11 binaries with putenv fix
- [x] Add validation commands to publishing scripts that check for and ensure all C++ binaries dynamically link to visual studio 2014 runtimes (`dumpbin`)?
-  [x] 32 bit builds of everything. - #1039

**Comment by springmeyer** [comment]
working on omnivore tag now

**Comment by springmeyer** [comment]
Looks like appveyor on windows is now passing all serverside tests and hitting errors that have been around since before the window-cpp11 merge:

```
node test/test-client.js

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, open 'c:\projects\tm2\.mapbox-studio\app.log'
```

**Comment by springmeyer** [comment]
gah: looked more into what is going on with environment variables and node on windows. It looks like if `process.env` is modified then node c++ addons:
- On unix `getenv` will see it no problem
- On windows with node.js node.exe then `getenv` will only see the variable if `process.env` was modified before the addon was `require`'d
- On windows with node-cpp11 node.exe then `getenv` will only see the variable if set in the shell that starts the node process

More details at https://github.com/springmeyer/node-addon-env-debug

**Comment by springmeyer** [comment]
I think I've found a fix which is to use `putenv` instead of `SetEnvironmentVariableW` in node: https://github.com/mapbox/node/commit/34d3d20624419f2100ba47118ec7dccb973177e5. Pushed https://github.com/mapbox/node-cpp11/commit/fe5f4d58745f39b90e37a63a312e283cbffbc588 to try to build this into a binary to test further.

**Comment by springmeyer** [comment]
> Add validation commands to publishing scripts that check for and ensure all C++ binaries dynamically link to visual studio 2014 runtimes (dumpbin)?

@BergWerkGIS - I wonder if you have ideas of how best to do this? The idea is that we want the appveyor builds of mbstudio to fail if either node.exe or any c++ addons are using anything other than visual studio 2014. So, if we made a mistake in packaging this would be the final catch to signal not to create a release yet. My best idea is that we'd glob the node_modules folder looking for files that end in `.node` and call dumpbin on them, parse the results, and throw if they don't look like msvs 2014. This script could be written in python or node.js.

**Comment by wilhelmberg** [comment]
@springmeyer 
I've done something similiar to determine MT/MTd/MD/MDd:
https://github.com/BergWerkGIS/mapnik-dependencies/blob/windows/linktype.ps1
It's Powershell, but shouldn't be a problem to port to Python/node.js.

**Comment by springmeyer** [comment]
update on putenv issue: I'm running around re-starting appveyor builds to make sure things are working and its looking good. Node v0.10.x with omnivore is working: https://ci.appveyor.com/project/Mapbox/mapnik-omnivore/build/1.0.182. Waiting for this build to finish https://travis-ci.org/mapbox/node-cpp11/jobs/41409644 and then I think v0.11.x will be working too.

**Comment by springmeyer** [comment]
@BergWerkGIS - thanks for the script reference. From that based I've started https://github.com/mapbox/mapnik-omnivore/blob/46e760293d819cb4f909ce047b9a8a6ea2689993/test/check_shared_libs.py

However, I'm not able to detect the presence of /MT linking. Take node.exe from nodejs.org as an example. It was surely linked with /MT against the 2013 C++ runtime, but how can we validate this?

The outputs of /DIRECTIVES and /DEPENDENTS do not show any sign:

```
c:\code\mapnik-omnivore>dumpbin "C:\Program Files (x86)\nodejs\node.exe" -DEPENDENTS
Microsoft (R) COFF/PE Dumper Version 14.00.22129.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Program Files (x86)\nodejs\node.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    WS2_32.dll
    KERNEL32.dll
    USER32.dll
    WINMM.dll
    ADVAPI32.dll
    IPHLPAPI.DLL
    PSAPI.DLL

  Summary

       1F000 .data
       32000 .pdata
      257000 .rdata
       10000 .reloc
       1B000 .rsrc
      3D6000 .text
        5000 data
        2000 text

c:\code\mapnik-omnivore>dumpbin "C:\Program Files (x86)\nodejs\node.exe" -DIRECTIVES
Microsoft (R) COFF/PE Dumper Version 14.00.22129.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Program Files (x86)\nodejs\node.exe

File Type: EXECUTABLE IMAGE

  Summary

       1F000 .data
       32000 .pdata
      257000 .rdata
       10000 .reloc
       1B000 .rsrc
      3D6000 .text
        5000 data
        2000 text
```

Nor does /IMPORTS: https://gist.github.com/springmeyer/e00cf2e33d1b5939e7a2

**Comment by springmeyer** [comment]
hmm, so node.exe is compiled with `WholeProgramOptimization` or `/GL` (https://github.com/joyent/node/blob/cfcb1de130867197cbc9c6012b7e84e08e53d032/common.gypi#L96) which may be why things are not showing up (http://stackoverflow.com/questions/25284513/check-what-run-time-static-library-or-dll-uses). However `-HEADERS` does not give much of interest either: https://gist.github.com/springmeyer/7e0e2b0776c57c2d08e7

**Comment by springmeyer** [comment]
win-ldd also does not show anything other than the dynamic libs so we may need to validate based on the lack of a dynamic link to the c++ runtime rather than a direct indication of /MT:

![screen shot 2014-11-18 at 4 30 19 pm](https://cloud.githubusercontent.com/assets/20300/5098831/644a6e66-6f40-11e4-96d9-8e1e7f4d065b.png)

**Comment by springmeyer** [comment]
all done here, tracking 32 bit support at #1039 (which can come later).
