### ISSUE TITLE
Styles for mapbox-gl-js

### ISSUE THREAD

**Issue by alexkurtz** [mapbox/mapbox-studio-classic#1032]
Hi!

I've found there is no way to use the Studio generated styles with mapbox-gl-js, since we can export only to mapbox (or mbtiles), which is no the json spec they use there. Is there any way of doing so? If not, could be a good feature to have (may require some coordination between the teams, though).

Thanks!

**Comment by samanpwbb** [comment]
Soon there will be tools for styling GL, stay tuned. https://twitter.com/Mapbox/status/530890936998322176
