### ISSUE TITLE
32 bit windows package

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1039]
In v0.1.6 we switched from providing a 32 bit package for windows to a 64 bit package.

We are very close to being able to provide a 32 bit package again for the few users still on 32 bit systems. Steps to get there:
- [x] - new node-mapnik tag that supports 32 bit
- [x] - push 32 bit node-srs binaries
- [x] - push 32 bit node-sqlite binaries
- [x] - push 32 bit node-gdal binaries
- [x] - tweaks to build-atom.sh and related scrips to switch on arch for windows
- [x]  - tweaks to `website/_includes/download.html` to display two arch downloads

**Comment by springmeyer** [comment]
All done here, except for actually revealing `mapbox-studio-win32-x86-v0.2.0.exe` on the website. @samanpwbb would you be able to do that? Basically we just need two windows binaries displayed at once.

**Comment by samanpwbb** [comment]
@springmeyer yeah, i'll take care of it this morning!

**Comment by samanpwbb** [comment]
Committed this to your `multiarch` branch:
![screen shot 2014-11-21 at 7 07 08 pm](https://cloud.githubusercontent.com/assets/108094/5151824/c14447ae-71b1-11e4-98f8-74b25d626047.png)
