### ISSUE TITLE
Pattern alignment not rendering accurately?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#105]
@springmeyer @ajashton 

While reviewing @EleanorLutz's woodcut project, I noticed that there were patterns using local polygon-pattern-alignment that looked seamless in TM2. In the deployed version the seams became visible (switching them to global alignment made the patterns in the deployed map seamless). Do you know what's going on? Thanks!

**Comment by springmeyer** [comment]
Interesting. I don't know what would cause this. It does not strike me as a version/mac vs linux build issue, but I guess it could be. Thanks for flagging this.

@nickidlugash - I'm working on a longer term solution to versioning issues right now - the milestone I'm hoping to hit by midweek is a new TM2 packaging workflow that will make it easier to keep in sync between local and deployed. Once that is in place I will circle back and try to research this issue more.

**Comment by springmeyer** [comment]
not had time to hit my packaging goals or review this in any more detail. let me know if its blocking or if you have any more details. Otherwise let's just keep this open and I will keep on my radar.

**Comment by samanpwbb** [comment]
This was fixed with an updated mapnik on mapbox.com

**Comment by springmeyer** [comment]
Sweet, thanks for confirming mapnik 2.3.x fixed @samanpwbb
