### ISSUE TITLE
Display geometry of layer in layer panel

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-studio-classic#1054]
Is it possible to show the geometry (icon) of a layer in the panel? Relying on layer name alone can be cumbersome for numerous layers with similar names.
![mapbox_studio](https://cloud.githubusercontent.com/assets/134753/5150898/079f5912-718c-11e4-84ba-e697d8408966.png)

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/issues/543
