### ISSUE TITLE
OS X fullscreen state not remembered

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#1057]
Unlike TileMill and Apple's OS X apps, if fullscreen mode is on when last quit, Studio doesn't restart in fullscreen.

**Comment by springmeyer** [comment]
@incanus this is causing this (seemingly harmless) error for me that pops up when the app starts:

![screen shot 2015-03-05 at 12 47 32 am](https://cloud.githubusercontent.com/assets/20300/6501771/4ee47ffa-c2d1-11e4-9041-4acaa47b5cc6.png)

**Comment by incanus** [comment]
Dupe & already addressing in https://github.com/mapbox/mapbox-studio/pull/1182.
