### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#1058]
Tried digging in a bunch of repos, but can't find out where this is sourced: 

![screen shot 2014-11-23 at 5 18 48 pm](https://cloud.githubusercontent.com/assets/17722/5160505/98f77f9a-7342-11e4-9e90-8aa0c9043073.png)

Should be "geometry extend" not "extent".

**Comment by samanpwbb** [comment]
@incanus -> https://github.com/mapnik/mapnik-reference/blob/master/3.0.0/reference.json#L644

**Comment by incanus** [comment]
https://github.com/mapnik/mapnik-reference/pull/88
