### ISSUE TITLE
Protobuf message too big

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-studio-classic#106]
I pointed tm2 at a PostGIS table containing a lot of complex polygons. The map churns for a bit before saying

> could not parse protobuf

The console shows this error once for each tile that was in view and would've contained data

> [libprotobuf ERROR google/protobuf/io/coded_stream.cc:171] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.

**Comment by springmeyer** [comment]
Yes, the libprotobuf library has a 64 MB internal limit for encoded size. We've considered loosening this, but settled on the fact that in all cases so far 64 MB tiles have indicated something wrong with the layer query. In short the SQL was not optimized and pulling way more data than intended for a given zoom. So, can you take a look at simplifying your polygons before encoding?

**Comment by rclark** [comment]
I definitely can simplify, and I can see the rationale behind not loosening the restriction. That's a tough usability problem though -- there's really nothing wrong per se with my layer query (select \* from mytable), but its definitely not optimized for this usage. Tough part is figuring out how to make that clear and easy.

Thanks!

**Comment by springmeyer** [comment]
longer term plan is built-in simplification, but yeah, tricky problem to solve for all cases.

**Comment by rclark** [comment]
Interestingly, just `st_simplify(geom, 10)` was enough to bring things down to size.
