### ISSUE TITLE
Win installer: make sure it can be run silently from command line

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1060]
This will come up as a required feature once labs need to install studio on multiple machines. Noting the trick with tilemill was done in https://github.com/mapbox/tilemill/commit/b862533cc00684356af7b4f921ca1c86e94e7381#diff-d494e52118ca448c0ec277e3d046bffa

Ideally we can hook up the appveyor script to test this once it is working.

Also, would be good to look into versioning ala https://github.com/mapbox/tilemill-win-launcher/commit/c3ba6bf142f9c5aabf2d8d9904f2a670d5cb219a

Refs #1020

**Comment by strech345** [comment]
i need it too!
wo have some pools to install ;-)

**Comment by wilhelmberg** [comment]
Installer now supports option `/S` (case sensitive, big S) to silently install/uninstall.

Will be available in the upcoming **`0.2.8`** release.

Use like this `start /wait mapbox-studio-win32-x64-v0.2.8.exe /S` to be able to check `%ERRORLEVEL%` for success/failure.
