### ISSUE TITLE
Broken app.db crashes Mapbox Studio at startup

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1062]
If you open app.db and add text to create a json syntax error then this crashes Mapbox Studio the next time it tries to start.

An abrupt crash can lead to a corrupt app.db (seen this several times with TileMill like https://github.com/mapbox/tilemill/issues/2013).

So, we need to either:
- allow the app to open even if the app.db cannot be opened (and perhaps overwrite it)
- have the uninstaller/installer clean up the app.db so that windows users will be able to get out of the trap of not being able to start Mapbox Studio without knowing about how to find app.db (since it is very common practice to re-install when something goes wrong on windows).

**Comment by yhahn** [comment]
I can take this. Should be easy to ignore/wipe a broken db as part of the compaction routine https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/tm.js#L52-L59.

**Comment by wilhelmberg** [comment]
FYI:
I faced this problem this morning when I accidentally started two instances of Studio.
I deleted `app.db` and renamed `app.db.compacted` to `app.db` and then it worked again.

**Comment by springmeyer** [comment]
13ef2af1226828e7d25bc405382b49abc860efba fixes the problem I was able to simulate. @BergWerkGIS the corruption of an app.db by starting two instances of studio sounds problematic. Can you ticket that out separately with details?
