### ISSUE TITLE
Error when wanting to install

### ISSUE THREAD

**Issue by mariusmustatea** [mapbox/mapbox-studio-classic#1068]
It's the first time I want to install it. I'm using a 64-bit Windows 7 Ultimate. The .exe is: mapbox-studio-win32-x86-v0.2.0.exe so should be the same.
But, nevertheless every time I want to instal it, this error appears:
![image](https://cloud.githubusercontent.com/assets/9947998/5201202/b9172c76-7577-11e4-810a-67cd5d61ebb7.png)
What to do?

**Comment by wilhelmberg** [comment]
@mariusmustatea Could you try re-downloading the installer from https://www.mapbox.com/mapbox-studio/#win64
And since you are on 64bit OS making sure you get the 64bit installer: 
"mapbox-studio-win32-**x64**-v0.2.0.exe"

**Comment by wilhelmberg** [comment]
Just verified that the downloads work for me.

Could you go into a commad prompt in the directory you downloaded the installer to and execute:
`mapbox-studio-win32-x64-v0.2.0.exe /NCRC`

**Comment by wilhelmberg** [comment]
Another thing to try (It's a known bug of NSIS to not work out of directories with special characters):

Move the installer into a directory, that doesn't have any special characters in it's path, only ASCII characters, and try from there.

**Comment by mariusmustatea** [comment]
Indeed I was trying to install it in a directory with non-ASCII characters. Once I have changed that> no more error and a swift install.
Thank you BergWerkGIS. You have been more then helpful.

**Comment by wilhelmberg** [comment]
@mariusmustatea No problem.
