### ISSUE TITLE
Error starting studio

### ISSUE THREAD

**Issue by yehiyam** [mapbox/mapbox-studio-classic#1069]
On windows 7 64 bit, with studio 0.2.0
when I start the application I get the following screen:

![image](https://cloud.githubusercontent.com/assets/6139491/5202433/96331bc0-7586-11e4-9b31-ab910f4fa194.png)

Clicking on Connect switches to the following screen:

![image](https://cloud.githubusercontent.com/assets/6139491/5202461/cc075ef0-7586-11e4-9c16-6732ef339809.png)

Do I need to enter a different URL at the first screen?
Is it possible wy workplace firewall is blocking the connection?

Thanks
Yehiyam

**Comment by wilhelmberg** [comment]
@yehiyam 
Do you connect to the internet through a proxy at your workplace?

We are still working on proxy support.

When looking at your connection settings in Internet Explorer/Firefox/Chrome do you see a proxy server and proxy port configured or is there a PAC (proxy auto-config) script?

**Comment by yehiyam** [comment]
Hi
Yes. I am connecting through a proxy server. I understand that this is not supported at the moment?

**Comment by wilhelmberg** [comment]
@yehiyam yes, at the moment connecting through proxies is not possible, but this problem should be solved soon.

**Comment by springmeyer** [comment]
Going to close this, let's track proxy support at #860.

**Comment by vindev01** [comment]
Hi, its been a while since this post. Has a proxy supported version released yet?

**Comment by wilhelmberg** [comment]
@lancevin13 not yet, but it should arrive in a few days.
Unfortunately proxies are not supported 100% yet: if you've already used it, everything will be fine.
But the very first start on a completely new install still has to be done without proxy.
