### ISSUE TITLE
Error uploading large mbtiles source

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-studio-classic#107]
After importing a .shp into tm2, exporting a .mbtiles and uploading to mapbox.com, my tileset seems to be non-functioning. Background:
- Large .shp 
- limiting zoom level to 0-10
- mbtiles 500mb
- Export to mbtiles seems to be successful; took appropriate amount of time (~45 minutes)
- Clicking the share button opens /data again
- mapid: `bobbysud.tvokcsor`

cc @yhahn

**Comment by bsudekum** [comment]
ah so it appears when I add the mapid in tm2, the data is in fact there. Thinking the should be made more clear on mapbox.com?

**Comment by yhahn** [comment]
This is a vector source?

We currently don't have anything (like an x-ray style) in place to visualize the data.

**Comment by bsudekum** [comment]
Yes, this is a vector source:

![](https://i.cloudup.com/HbqCdOdzDJ-3000x3000.png)
