### ISSUE TITLE
Application unresponsive on second export to PNG

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-studio-classic#1078]
Mapbox Studio becomes unresponsive when trying to export a second 24-bit png from a map project. The image files themselves are only ~500kb and export only takes a second when saving the first image. I looked up what was going on in Console and this is what it gave me:

```
11/27/14 2:34:36.460 AM com.apple.IconServicesAgent[89590]: main Failed to composit image for binding VariantBinding [0x29b] flags: 0x8 binding: FileInfoBinding [0x19b] - extension: png, UTI: public.png, fileType: ????.
11/27/14 2:34:36.460 AM quicklookd[90343]: Warning: Cache image returned by the server has size range covering all valid image sizes. Binding: VariantBinding [0x403] flags: 0x8 binding: FileInfoBinding [0x303] - extension: png, UTI: public.png, fileType: ???? request size:32 scale: 1
11/27/14 2:34:36.519 AM gkbisd[133]: Unable to collect cdhash for /Applications/Utilities/Console.app (error code 100024)
11/27/14 2:34:36.594 AM Console[90352]: setPresentationOptions called with NSApplicationPresentationFullScreen when there is no visible fullscreen window; this call will be ignored.
```

I'm running OS X 10.9.4 and the newest version of Mapbox Studio.

**Comment by amyleew** [comment]
@lyzidiamond Still running into this issue? Got another instance of this on OS Yosemite.

**Comment by lyzidiamond** [comment]
Woah @amyleew, totally forgot I opened this.

I haven't tried in a while, but I can later today.

**Comment by amyleew** [comment]
@lyzidiamond cool! I'll add the log if he's still having the issue.
