### ISSUE TITLE
Interactivity can't cross 180 deg E/W

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#108]
It only works on the 'middle earth'

**Comment by yhahn** [comment]
At least one case of this is when the map is panned past -180 or 180 -- the grid breaks.

First step here is to just upgrade mapbox.js -- might be fixed upstream.

**Comment by ajashton** [comment]
Confirmed that this was just caused by crossing 180. Updated issue to clarify.
