### ISSUE TITLE
Map files not uploading when using custom fonts

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1085]
I'm getting this on the MapBox site after I 'upload' from MBS. The path is where we have the fonts located for this project on our local machine. 
Any ideas how to resolve this issue?
![invalid upload](https://cloud.githubusercontent.com/assets/8440284/5272068/d65953f4-7a36-11e4-8801-315b399faaa0.JPG)

Thanks,
Mark

**Comment by yhahn** [comment]
@MarkWS you'll want to include these fonts in your project's style directory itself so they get packaged up with the style, for example in a `fonts` folder. Then use a relative path when using the `font-directory` rule:

```
font-directory: url('fonts/');
```

**Comment by MarkWS** [comment]
We have this path in our style directory: 
![dir](https://cloud.githubusercontent.com/assets/8440284/5305637/aad65800-7bba-11e4-853c-56212612a47c.JPG)
and the fonts we are using are loaded there.
they also show up under the fonts tab > Your Fonts.
So I must be missing something here.  Thanks, Mark

**Comment by yhahn** [comment]
@MarkWS the font files need to be in your style project directory. For example, it may be

```
C:\Working\Digital Work\my-style-project.tm2
```

**Comment by MarkWS** [comment]
great, that worked. i was one folder off for the font folder.
Thanks.
but now I'm getting this error on the MapBox site
![error](https://cloud.githubusercontent.com/assets/8440284/5305809/514af654-7bbc-11e4-8218-aeddda44ff39.JPG)
