### ISSUE TITLE
Invalid Upload; RangeError

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1087]
I'm getting this after I upload to the MapBox site:
![invalid upload](https://cloud.githubusercontent.com/assets/8440284/5306173/7169539c-7bbf-11e4-8585-4cc2999b4ec1.JPG)

**Comment by yhahn** [comment]
Are there very large fonts or other large files in your project? There's currently a 750k limit (compressed) on style uploads.

**Comment by MarkWS** [comment]
Yes, we have 2.2megs of fonts in that directory. That’s only 5 fonts with a total of 43 faces (Book, Oblique, Bold, etc)

Can we increase the limit somehow?

**Comment by yhahn** [comment]
Are you using all the combinations of fonts? The smaller the style the more rapidly it can be deployed to servers -- we may be increasing this limit in the future but not drastically.

**Comment by MarkWS** [comment]
I’ve removed all the faces we are not using. We have it down to 3 fonts with a total of 14 faces and that’s just under 750k. in fact it’s 680k

Thanks, Mark

**Comment by MarkWS** [comment]
so an increase would be helpful.

**Comment by yhahn** [comment]
:+1:

**Comment by MarkWS** [comment]
thanks young.
but now I'm getting this and this folder was removed long ago. There is no reference to it in any of the style sheets. ideas? 
![again](https://cloud.githubusercontent.com/assets/8440284/5306798/ab52ff04-7bc4-11e4-8ab9-75bb7c2aea5a.JPG)

**Comment by MarkWS** [comment]
I removed MBS and reloaded the program and that seems to have solved the problem.

**Comment by MarkWS** [comment]
Correction, I've removed MBS 3 times now and I'm still receiving this error. The folder listed above was removed long ago and there is no reference to it in the style sheets. Any ideas. it's driving me crazy!!!
