### ISSUE TITLE
Next release: Supporting HTTP proxies + usability

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1090]
Http proxy support is coming thanks to @BergWerkGIS and this will be big for many users. Once proxy support has landed (#860) I think a new release would be excellent. Timing TBD, maybe next week maybe early January.

What other low hanging tasks could we hit at the same time to hit to improve usability? Possible options that just came up in chat with @BergWerkGIS and @samanpwbb:
- Save global state of last folder accessed in file browser (@samanpwbb mentioned this might be easy with localstorage)
- UI/API for accessing other drives on Windows (https://github.com/mapbox/mapbox-studio/issues/824)

/cc @mtirwin @camilleanne @yhahn

**Comment by samanpwbb** [comment]
Saving state in file browser is done here: #1109 , should be merged today.

**Comment by ljbade** [comment]
Can I also request a button for creating a folder: https://github.com/mapbox/mapbox-studio/issues/1071

**Comment by springmeyer** [comment]
closing this since we are planning releases that don't need to wait for #860 to move (note: #860 is not moving currently because of other priorites and the overall challenge of the task).
