### ISSUE TITLE
Cannot find module mapnik_settings.js

### ISSUE THREAD

**Issue by crackernutter** [mapbox/mapbox-studio-classic#1091]
Trouble installing on Ubuntu 14.04 (Trusty).  Have run npm install --build-from-source  and have deleted node_modules and tried npm install again (works fine), but npm start always seems to fail because of "Cannot find module '/home/ubuntu/mapbox-studio/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik_settings.js'"
Suggestions?

**Comment by crackernutter** [comment]
I had to manually also run npm install mapnik, sqlite3, mbtiles, and mapnik-omnivore in order to get npm start to work. However, now I get Mapbox Studio @ http://localhost:3000 but no UI comes up.  Any suggestions here?

**Comment by springmeyer** [comment]
Can you step back and try `npm install` again without the `--build-from-source` and share the error (the whole terminal output)? It should work out of the box without source installs on trusty so I wonder if there was just some network blip that caused a problem.

**Comment by mcmillan** [comment]
We're also seeing this. Using the following code to provision a Vagrant 64-bit Trusty box:

```
# Update system, install NodeJS
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get update -y
sudo apt-get dist-upgrade -y
sudo apt-get install nodejs git -y

# Install Mapbox Studio
mkdir -p /srv/mapbox-studio
git clone https://github.com/mapbox/mapbox-studio.git /srv/mapbox-studio
cd /srv/mapbox-studio
sudo npm install --build-from-source
```

...and then running `npm start` yields the following:

```
> mapbox-studio@0.2.0 start /srv/mapbox-studio
> ./index.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/srv/mapbox-studio/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/mapbox-studio/node_modules/mapnik/lib/mapnik.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by crackernutter** [comment]
I tried npm install again (without build from source), and I got the same error.  The only things that worked for me is manually running npm install for mapnik, sqlite3, mbtiles, and mapnik-omnivore

**Comment by springmeyer** [comment]
the `sudo` may be the problem: try without `sudo` as per https://github.com/npm/npm/issues/3497. Please create new issues if still having problems and share the **entire** terminal output. The `Cannot find module` is not helpful: to know the cause of that we need the install logs.
