### ISSUE TITLE
Source clipped on remote

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#1097]
I'm experiencing clipping of point data at the extreme east and west of my UK source data on remote.

Source data file, westernmost points all visible (64 buffer, extents: -180,-85.0511,180,85.0511):

![original source](https://cloud.githubusercontent.com/assets/912721/5361047/a0ff7924-7fc0-11e4-9afc-8cbb4c439d55.png)

Points when using remote source in style - looks like clipping on a tile boundary:

![source from remote](https://cloud.githubusercontent.com/assets/912721/5361077/dc21214c-7fc0-11e4-9c72-fbc6beb029b9.png)

![source rendering from remote](https://cloud.githubusercontent.com/assets/912721/5361086/f45ae2a2-7fc0-11e4-94e6-b144da70e1c2.png)

Same source renders correctly when used locally. Similar problem with easternmost data. Any ideas?

Ash

**Comment by wilhelmberg** [comment]
@ashleyclough are you using a postgis layer with scale dependent filtering of features?

Have you tried re-uploading the points? Maybe there was a problem during transfer.

**Comment by ashleyclough** [comment]
Yes, it is using postgis scale dependent filtering - it is the only way to get so many points to work as a source across a large range of zoom levels. Could that be the problem?

I've re uploaded it but the same thing happens.

**Comment by ashleyclough** [comment]
It looks to me that whether a tile contains data is ascertained by its content at the lowest zoom level (6 in my case). As there are no large towns in the areas above, my data in the area only appears at zoom levels >9.

I've now reworked the SQL query to return small villages at level 6 and the tiles display correctly, even though the village points visibility isn't until zoom 12.

I suppose a solution at your end in order to assess whether a tile area contains data is to use the data available at the highest zoom level, not the lowest, if this is the issue?

Map is here:
https://a.tiles.mapbox.com/v4/parallel.jfjfh54k/page.html?access_token=pk.eyJ1IjoicGFyYWxsZWwiLCJhIjoicjFYa3czOCJ9.Jt1OfO_GwPFzXir9xAB95Q#10/50.3437/-4.7070

**Comment by wilhelmberg** [comment]
Your map is beautiful.

You are right about the cause of your problem.
This is a known issue at the moment with trying to be as speedy as possible.

**Comment by wilhelmberg** [comment]
Solution is to display some points on all zoomlevels.
How to control point density:
https://www.mapbox.com/guides/postgis-manual/#controlling-label-density
