### ISSUE TITLE
.app + auto updates

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#110]
@incanus - I'd like to put this on your radar.

I'm considering that future tm2 builds will soon:
- need to be become an actual .app (and need to be signed)
- will optionally be able to be created on a machine without xcode (no clang++ needed) as C++ modules will come via node-pre-gyp based binaries
-  should be able to auto-update: meaning every time a user opens TM2 their app would update to the latest (this is to ensure that TM2 components match exactly what we need for hosting on mapbox.com).

Not actionable yet. I still need to finish packaging work for c++ modules to enable auto-updates to be possible/fast. But it would be great if you could:
- Put thought to auto-updates - Does sparkle support? By design I presume sparkle is friendly and asks users. Is there precedent for successful auto-updates in open source/sparkle based apps?
- Put thought to a better approach for communication between osx app and the node process. I would love to put this pain fully behind us: https://github.com/mapbox/tilemill/issues/1606
- How can we do this cross-platform? Once node-pre-gyp binaries are ready for all c++ apps then `npm install` will finally work the same on all platforms. How could the update system therefore also be cross-platform?

**Comment by incanus** [comment]
I'm going to try to take a bite out of this during this coming week.

**Comment by yhahn** [comment]
@incanus @springmeyer let's voice on this this week.

**Comment by incanus** [comment]
Capturing chat notes: core engine stuff by @springmeyer needs to happen first, then we will tackle this. Our frame of reference right now is how things are done in TM1, but things could change. We'll use this ticket as a scratchpad for planning what a TM2 app should be when the time comes.

**Comment by incanus** [comment]
What are we currently thinking about this?

**Comment by incanus** [comment]
Let me get a little more specific: @yhahn @springmeyer what are your current thoughts on a native app housing for TM2? As I see it, this could go in two phases: 
1. Small, simple `.app` bundle for binary distribution that just kicks off the current `start.command` (on OS X). No auto-update, no subprocess management, just a dock-able launcher for the current Terminal-based one. 
2. TM1-style full-on bundle with updates, subprocess management, dock badge & notification export integration, App Nap, etc. 

Plus we need to discuss other platforms.

**Comment by yhahn** [comment]
- .app: We've gone with `atom-shell` for this across x3 platforms.
- auto updates: There's https://github.com/atom/atom-shell/blob/master/docs/api/auto-updater.md but it's only on os x atm. Let's wait and see what the atom team does -- ie. whether they do auto-updating on windows/linux as well or not. It would be great to have a single API across the platforms for this.

**Comment by incanus** [comment]
Awesome! Excellent to be able to leverage three-way platform consistency stuff without duplicating work. 

Also Squirrel.Mac (what auto updates are based on) is interesting — never heard of this; basically every OS X project I've ever seen in the past 6-8 years has used either Sparkle (what we use on TM1) or rolled their own for whatever reason (or the App Store, of course). 

> Instead of publishing a feed of versions from which your app must select, Squirrel updates to the version your server tells it to. This allows you to intelligently update your clients based on the request you give to Squirrel.

**Comment by yhahn** [comment]
Closing for now via https://github.com/mapbox/mapbox-studio/pull/698.

Will revisit when atom-shell's updates api develops or gives indication it won't be what we need.

**Comment by yhahn** [comment]
Looks like at least 2/3 platforms are being targeted.
- https://github.com/Squirrel
- https://github.com/atom/atom-shell/pull/614
