### ISSUE TITLE
Modals don't vertically scroll

### ISSUE THREAD

**Issue by artemp** [mapbox/mapbox-studio-classic#1104]
_Pedantic_

`Projects -> New Project`

![mapbox-studio-dialog-cutoff](https://cloud.githubusercontent.com/assets/59056/5437808/3acd03da-8473-11e4-9eb2-36ca26601db3.png)

**Comment by samanpwbb** [comment]
What were you expecting the positioning / sizing to be? This is intended to be a centered modal.

**Comment by artemp** [comment]
@samanpwbb - the screenshot above demonstrates what I see e.g the bottom row in 'New Style' dialog is obscured. To rectify this I need to resize main window and then all looks great. So I don't know if this is dialog size or main window size issue. I guess I'd expect 'centered modal' to centre vertically as well as horizontally. Current layout gives a false impression there can be more styles hiding underneath :). Pretty sure this is something to do with my retina monitor (15.4-inch (2880 x 1800))

**Comment by samanpwbb** [comment]
Ahhhh, I just checked this out. The modal is supposed to scroll. I'm pretty sure a base version update will fix this.
