### ISSUE TITLE
terrain-v2 not working

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1107]
anyone having trouble loading the new Terrain V2 that was released last week?
I've changed the source from v1 to v2 and the terrain disappears.
I'm also have problems with another terrain map where the layers are listed as 'Locked'.
it says "Source Locked (custom layer order)" how to unlock, I've not changed the layer order?

**Comment by peterqliu** [comment]
@MarkWS regarding terrain, check out this [blog post](https://www.mapbox.com/blog/terrain-mapbox-studio/). Make sure to update your terrain styling to reflect the v2 update.

As for the layer ordering, you can edit the layers by going into the `.tm2` folder on your computer, and opening `project.yml`. Inside you will see the list of layers.

**Comment by MarkWS** [comment]
Thanks Peter,
the blog post helped, we just removed all our coding and replaced it with the sample so that seems to have solved that. Although we will loose our custom style that we created on for the v1 but shouldn't be too hard to recreate it for v2 so thank you.
