### ISSUE TITLE
external GeoJSON source not showing polygons

### ISSUE THREAD

**Issue by wprater** [mapbox/mapbox-studio-classic#111]
are we supposed to see a outline of the polygons for a GeoJSON file after I add a layer to a new source?

**Comment by springmeyer** [comment]
Try saving the project to trigger rendering.

**Comment by wprater** [comment]
Ive tried to save the project and also use the 'refresh' button after I chose the data source from the hamburger menu.  I just get an empty screen.  I've tried a know to work GeoJSON and a Shapefile.

**Comment by yhahn** [comment]
@wprater have you set the projection for the layer to be WGS84?

**Comment by wprater** [comment]
@yhahn nice, that works for one dataset, but not the Zillow neighborhood boundaries which I converted from a shapefile to geojson.  Perhaps there was an issue with the conversions?  

They did display in TileMill.

Also tried an original shapefile from Zillow and it's also not displaying.

**Comment by wprater** [comment]
Removed all my projects data in ~./tilemill and tried the geojson files again.  Got them to render, but I have to save and also change zoom levels.
