### ISSUE TITLE
Mapbox studio orphan processes

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#1117]
somehow, somewhere, mapbox studio didn't exit properly:

![screen shot 2015-01-07 at 6 08 20 pm](https://cloud.githubusercontent.com/assets/3952537/5656878/628de06a-9698-11e4-989c-f446819231f7.png)

cc @yhahn

**Comment by camilleanne** [comment]
per convo with @springmeyer these processes don't seem to be busy or hung, just not properly stopped by atom-shell. I can make more of them happen by opening and closing the mapbox studio desktop app enough times. TBD is whether or not closing the app before it's fully loaded makes this more likely to happen or not.

**Comment by springmeyer** [comment]
Don't know what is wrong but noticing https://github.com/mapbox/mapbox-studio/blob/mb-pages/index-shell.js#L34. I wonder in what scenario `server` would be undefined on that line?

**Comment by camilleanne** [comment]
@springmeyer One thing that seems to happen is that if you quit Mapbox Studio/Atom Shell from the dock that doesn't trigger the `window-all-closed` event for atom and the server + process aren't killed, but the shell is.

![screen shot 2015-01-21 at 12 06 46 pm](https://cloud.githubusercontent.com/assets/3952537/5844101/3b997d7e-a166-11e4-89a1-651d59ccb7b4.png)
