### ISSUE TITLE
Windows: Crash on Upload Source/Download Mbtiles 

### ISSUE THREAD

**Issue by mohsentaleb** [mapbox/mapbox-studio-classic#1118]
May be I can provide the backtrace/log for further investigation if you tell me the log path in Windows.
@springmeyer

**Comment by wilhelmberg** [comment]
You find the file `app.log` in `C:\Users\<YOUR-USER-NAME>\.mapbox-studio`, or paste `%USERPROFILE%\.mapbox-studio` into Explorer's address bar.

**Comment by mohsentaleb** [comment]
Ok, I test that crashing situation again and nothing is put in log file. Any other options to increase the level of verbosity?

**Comment by wilhelmberg** [comment]
Sorry, no easy way to increase verbosity.
Seems in your case that the crash happens so fast/unexpected that nothing gets written to the log file.

Would be of great help, if you could work through this gist (does require some time and effort).

https://gist.github.com/BergWerkGIS/534a5e74301c5607af5c

Let me know, if you need further assistance.

**Comment by mohsentaleb** [comment]
Did all the steps till "Debug -> Go".
A command Shell opens with text `Mapbox Studio @ http://localhost:3000` on it but app doesn't start (I even waited for 5 minutes) to let me work with it and reproduce the crash situation.

**Comment by wilhelmberg** [comment]
@mohsentaleb 
Great! Looking forward to your input.
Just open a browser at http://localhost:3000

**Comment by mohsentaleb** [comment]
@BergWerkGIS App is halted at exporting mbtiles.. and here's the logs:
http://pastebin.com/LB5eFUGc

**Comment by wilhelmberg** [comment]
@mohsentaleb Thanks!

Could you repeat the steps and also issuing theses commands after the crash before sending the log file?

https://gist.github.com/BergWerkGIS/534a5e74301c5607af5c#after-the-crash

**Comment by mohsentaleb** [comment]
@BergWerkGIS oh shoot, my bad.
There you go: http://pastebin.com/pGErMcWt
Please let me know if you also need the dump file. It's quite bulky.

**Comment by wilhelmberg** [comment]
@mohsentaleb could you try once again?
But, after the crash click on `Debug -> Go` three times (if that command is still available).

How big is the dump file?

**Comment by mohsentaleb** [comment]
@BergWerkGIS done: http://pastebin.com/QFT3JnaA
clicking on `debug -> go` after crash does nothing much. Outputs in console: `No runnable debuggees error in 'g'`
Uncompressed dump file is ~160MB, compressed: 33MB

**Comment by wilhelmberg** [comment]
@mohsentaleb thanks, but it seems the call stack is corrupted and the listed methods are not correct.
I would need the dump to see if I can get more information out of it.
Could you provide it somehow?

**Comment by wilhelmberg** [comment]
BTW, are you using the latest 0.2.0 of Mapbox Studio?
https://www.mapbox.com/mapbox-studio/#win64

**Comment by mohsentaleb** [comment]
@BergWerkGIS Yes, I'm using the latest 32-bit version. (on Windows 7 - 32bit)
Dump file: http://www.mohsentaleb.com/mbs-crash.rar

**Comment by wilhelmberg** [comment]
@mohsentaleb Thanks for the dump file, will take a look.

Ah, 32bit. I would strongly recommend switching to 64bit (if that is possible for you), we've had some issues with node 32bit.

Could you monitor the memory usage of node.exe in the task manager and see if it goes towards 1GB and then crashes?
That's the limit for node 32bit.

Are you using a shapefile based project?
You could try to use `shapeindex.exe <PATH\TO\YOUR\SHAPEFILE.SHP>` to speed things up.
shapeindex can be found here (for 32bit):

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x86
```

**Comment by mohsentaleb** [comment]
@BergWerkGIS Well, I've also tested it on a 64bit machine with no luck.
I just reproduced the crash, while watching node.exe process and it didn't came up more than 84MB.

I'm using PostgreSQL as my source.

**Comment by wilhelmberg** [comment]
hm, very strange, there isn't any useable information in the dump file either.

Would it possible for you to provide "a perfect testcase" with db-dump, source- and style projects?

Like describe here:
https://github.com/mapnik/mapnik/wiki/A-perfect-testcase

**Comment by mohsentaleb** [comment]
@BergWerkGIS Well it's not that easy. The database is quite large (500K+ rows) and I'm not sure if a small portion of its rows would simulate the whole situation. Though I'm going to try it at least once and narrow down the rows to see how things would go. Will let you know soon.

Meanwhile is there any command line options to export tmstyle projects of mapbox studio to Mbtiles to skip the GUI and trace it more deeply?

**Comment by wilhelmberg** [comment]
**commandline export:**
As far as I know. that feature is not yet available (maybe @springmeyer  can chime in?).

**postgis:**
I suppose all your spatial (and other) indices are set and up to date?

You could try adding `geom && !bbox!` to your queries like so:

```
(SELECT
    gid
    ,geom
FROM
    mygeotbl
 WHERE
    geom && !bbox!
) as data
```

If could also try limiting your data using `z()` or `labelgrid()` functions defined in `lib.sql` from this repo:
https://github.com/mapbox/postgis-vt-util

**Comment by mohsentaleb** [comment]
@BergWerkGIS 
Yes, all indexes are up to date.
I'll play with those helper functions. Thanks.

**Comment by springmeyer** [comment]
> Well, I've also tested it on a 64bit machine with no luck. I just reproduced the crash, while watching node.exe process and it didn't came up more than 84MB.

Thanks for this testing and all the details @mohsentaleb. Can you double check this one more time? In other words: confirm that the 64 bit version does truly crash and how much memory it is using before it does. I'm surprised that only 84 MB was in use (this makes it seem like the app was not actually doing anything).

**Comment by mohsentaleb** [comment]
@springmeyer Just checked that in 64bit version and it was consuming only 132MB of RAM.

**Comment by wilhelmberg** [comment]
Stale, closing.
