### ISSUE TITLE
Apply sources doesn't work

### ISSUE THREAD

**Issue by Mcgrupp34** [mapbox/mapbox-studio-classic#1123]
I have a remote source I am trying to add to a style I am working on, but when I press apply after putting the map ID in, nothing happens. The apply button does not work. OSX 10.9.5.
![screen shot 2015-01-12 at 11 40 08 am](https://cloud.githubusercontent.com/assets/3867961/5706535/cb614590-9a4f-11e4-90c8-46c9c2ebd487.png)

**Comment by GretaCB** [comment]
Looks like there is a space between the listed sources (after the comma). If you hit Apply with a space in between sources, you should see a pop up similar to this:

![screen shot 2015-01-12 at 8 45 03 pm](https://cloud.githubusercontent.com/assets/1209162/5714820/f0aa48d2-9a9b-11e4-8437-9295809ca10a.png)

Try removing the space.

**Comment by camilleanne** [comment]
@Mcgrupp34 Currently Atom Shell (the package around Mapbox Studio as a desktop app) doesn't support the error message you see in @GretaCB's screenshot (#805) so there isn't good feedback for formatting errors. We're working on getting better feedback for this, in the meantime, make sure there aren't any spaces between your map ids.

**Comment by Mcgrupp34** [comment]
Did the trick, thank you.

On Wed, Jan 14, 2015 at 3:19 PM, Camille Teicheira <notifications@github.com

> wrote:
> 
> @Mcgrupp34 https://github.com/Mcgrupp34 Currently Atom Shell (the
> package around Mapbox Studio as a desktop app) doesn't support the error
> message you see in @GretaCB https://github.com/GretaCB's screenshot (
> #805 https://github.com/mapbox/mapbox-studio/issues/805) so there isn't
> good feedback for formatting errors. We're working on getting better
> feedback for this, in the meantime, make sure there aren't any spaces
> between your map ids.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapbox/mapbox-studio/issues/1123#issuecomment-69984027
> .

## 

Zack Walker
Cartographer

888 Brannan St
San Francisco,CA 94103

See my favorite listing https://www.airbnb.com/rooms/239790
