### ISSUE TITLE
Embedding timestamps in the app.log

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#1127]
Can we embed timestamps in the `app.log`? Would make quickly deciphering whether the errors are meaningful and recent or old and unimportant. Very useful in helping a customer troubleshoot.

cc @springmeyer

**Comment by springmeyer** [comment]
Also logging the error/return code would be handy to know if the application exited normally (error code 0) or abnormally (some other number)

Something like:

```
// http://nodejs.org/api/process.html#process_event_exit
process.on('exit', function(code) {
    console.log(process.title,'exited with',code);
})

// simulate an error causing exit
process.exit(-1);

```

**Comment by camilleanne** [comment]
added in #1135
