### ISSUE TITLE
`undefined` accountLevel hangs Studio (oauth error)

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#1129]
Failed user login saved as`undefined` accountLevel and Studio just hangs. Should trigger new login. (re: https://github.com/mapbox/mapbox-studio/issues/1128)

``` sql
500 'GET' '/oauth/mapbox?error=Cannot_read_property_%27accountLevel%27_of_undefined' 'AuthorizationError'
```

cc @springmeyer

**Comment by springmeyer** [comment]
Were you able to trigger the problem locally too (by intentionally editing `~/.mapbox-studio/app.db`)?

**Comment by amyleew** [comment]
@springmeyer No! It did stall for a bit then Studio launched. I'm requesting his `~/.mapbox-studio/app.db` for further investigation.

**Comment by springmeyer** [comment]
Okay, curious. Good call on getting the `app.db` before deleting.

**Comment by amyleew** [comment]
@springmeyer Here is the `app.db` 

``` sql
{"key":"version","val":4}
{"key":"MapboxAPIAuth","val":"https://api.mapbox.com"}
{"key":"MapboxAPITile","val":"https://a.tiles.mapbox.com"}
{"key":"MapboxAPITile","val":"https://a.tiles.mapbox.com"}
```

Looks like it was deleted before, would an error even read here for `oauth`?

**Comment by springmeyer** [comment]
that app.db looks normal and should not cause errors. Is the user still hitting it with that?

**Comment by amyleew** [comment]
> remove ~/.mapbox-studio/app.db and restart. 

@springmeyer That solved it. Studio starts now with no "unauthorized client" error.

**Comment by willwhite** [comment]
This was an Mapbox API issue.
