### ISSUE TITLE
Style not being uploaded to Mapbox account

### ISSUE THREAD

**Issue by ste-goldstein** [mapbox/mapbox-studio-classic#1132]
After clicking "Upload to Mapbox" button to upload the style, the green "Upload complete" message appears, and a style id is given.

But the style does not show up on my Mapbox account.

I repeated the process a few times from start to end (loading data, uploading vector tiles and creating style), creating new projects, with no success.

I also tried accessing the style from a web map, but I get a blank layer when calling it's.

I know that before upgrading from a Free to a Basic account, I did not have this problem. (Related?)

Ubuntu 14.04, Mapbox Studio 0.2.0 and 0.2.2

**Comment by willwhite** [comment]
@skualos can you check your upload history for errors? Visit https://www.mapbox.com/data/ and click on "upload" in the top right.

**Comment by ste-goldstein** [comment]
Indeed, I have an error message from each time I tried to upload:
"At least one tile exceeds the draw time limit of 1000ms. Please optimize your styles."
Should I close this issue as it seems to be related with
https://github.com/mapbox/mapbox-studio/issues/1120 ?

**Comment by willwhite** [comment]
Yes, let's track the core issue on https://github.com/mapbox/mapbox-studio/issues/1120. @skualos thanks for confirming and apologies for the confusion.
