### ISSUE TITLE
white screen, not loading after opening with mac package 2.2

### ISSUE THREAD

**Issue by jhubley** [mapbox/mapbox-studio-classic#1140]
Hi,

I downloaded the latest mapbox studio package for mac (mapbox-studio-darwin-x64-v0.2.2). I didn't have any previous versions of mapbox studio. My processor is 64 bit (Intel Core 2 Duo) and I'm using OSX Yosemite. 

When I open the application, I get a white screen with a spinning gray circle for a couple of seconds, and then it goes away and I just have a white screen. There is a menu bar with a few options (Edit, View, Window) but no option to create a new project. A screenshot of what I see is below:

![screen shot 2015-01-19 at 7 36 18 pm](https://cloud.githubusercontent.com/assets/1332789/5811011/985776dc-a01d-11e4-9f12-ae1e466fd6a8.png)

I went to Help -> Application Log. The only thing it says is, "Mapbox Studio @ http://localhost:3000/" However the page at localhost:3000 isn't found.

I think I'm missing something, but I'm not sure what. Any thoughts would be greatly appreciated. A final note- I tried installing on another computer (macbook air with basically the same setup) and got the same results.

Thanks,
Jill

**Comment by jhubley** [comment]
Never mind! I realized the issue was that I changed some stuff around in my hosts file for my virtual server config, and that's why localhost:3000 wasn't loading... Now it's working fine.

**Comment by springmeyer** [comment]
@jhubley aha, great. Glad you figured it out!
