### ISSUE TITLE
html anchors missing from doc pages

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1142]
It would be great to be able to link, for example, directly to `Attachment Ordering` at https://www.mapbox.com/mapbox-studio/symbol-drawing-order/

But currently anchors are missing so the best fallback is to just use the github wiki which is not optimal: https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-symbol-drawing-order.md#attachment-ordering

**Comment by duncangraham** [comment]
@springmeyer Yea I've noticed this too. I'll fix this today and tomorrow.

**Comment by duncangraham** [comment]
PR here: https://github.com/mapbox/mapbox-studio/pull/1155
