### ISSUE TITLE
Corrupt bookmarks yml file

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#1144]
It's possible for yaml files to be broken and prevent saving to bookmarks file. I have a project with: `!<tag:yaml.org,2002:js/undefined>` as it's only content.

https://github.com/mapbox/mapbox-studio/commit/99c2b6efb5a308fdacb0070834b3faed8f61ed6e does fix the problem by falling back to empty bookmarks array if the yml can't be read, but:
- This could be originally caused by something happening during file writing and therefore should be fixed.
- Or this could be caused by a project created with an old version of Mapbox Studio because the broken project was over 2 months old, and older versions of studio did not have bookmark validation.

**Comment by yhahn** [comment]
Is this not caught + errored? Looks like we have at least some expectation in our tests for these scenarios: https://github.com/mapbox/mapbox-studio/blob/mb-pages/test/style.test.js#L325-L331

**Comment by samanpwbb** [comment]
@yhahn i am thinking this project was created with an older version of studio, we originally launched places without the validation check.

**Comment by samanpwbb** [comment]
Should be fixed now, mapbox studio doesn't make empty project.yml's any more
