### ISSUE TITLE
crash on Windows 7 32bit on export .mbtiles

### ISSUE THREAD

**Issue by mdiener21** [mapbox/mapbox-studio-classic#1146]
uploaded a 190 MB   geotif   (.tif) and that worked but as I try to export to .mbtiles, it runs and runs then is done.  Click download then boom   EPERM, stat 'C:\Users\mdiener.mapbox-studio\cache\export-23b8681d.mbtiles'   looks like  a permissions problem on my machine :)

**Comment by wilhelmberg** [comment]
@mdiener21 
Could you try:
- close Studio
- delete contents of `C:\Users\mdiener\.mapbox-studio\cache\` manually
- start Studio 
- export again

**Comment by mdiener21** [comment]
I deleted the contents of both \cache   and \tmp   than ran it again all looks good.  Then click download, popup open I pick a location, click save...then nothing happens, no crash and now download found.

  I have tried to save in many different locations with always the same results.   The \cache folder does however include a new file called export-7a7cde30.mbtiles with 6 M  in file size.

**Comment by wilhelmberg** [comment]
Is it possible that you share your TIFF?
At the moment we are hunting down some hard to find errors specific to Windows and any data to reproduce errors would be helpful.

I suppose your TIFF is properly georeferenced?
Is it in WebMercator (EPSG:3857)?
If not, you could try to re-project your TIFF to WebMercator before adding it to Mapbox Studio, that it doesn't have to reproject on the fly.

Otherwise, for the time being, you could try the Linux version, if this is an option for you.

**Comment by wilhelmberg** [comment]
@mdiener21 

Another thing for you to try (see also https://github.com/mapbox/mapbox-studio/issues/1177):
- Update to the latest version. Would be great if you could use 64bit. https://www.mapbox.com/mapbox-studio
- Open command prompt
- enter `echo %PROJ_LIB%`
- if this shows a path, enter
  - on Win 32bit: `SET PROJ_LIB=C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-ia32\share\proj`
  - on Win 64bit: `SET PROJ_LIB=C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\share\proj`
- enter `mapbox-studio.exe` on that same command prompt

Does this solve your issue?

**Comment by mdiener21** [comment]
I will give it another go tomorrow in the office thx.  Sorry I cannot share the TIFF :( customer data not for public eyes

**Comment by mdiener21** [comment]
sorry 64Bit Win would be nice but I cannot expect my customer to do the switch..ie re-install windows. Path is a problem because I use it for osgeo4w...C:\Users\mdiener>echo %PROJ_LIB%
C:\OSGeo4W\share\proj
which I am using for other projects...but I will switch it over for the test...PS. I also run a Ubuntu Machine and all works nice there! silly Windows, but we need it for some customers :+1:    Test results coming shortly

**Comment by mdiener21** [comment]
Results are in status "Does not work" :   I used gdalwarp to convert to epsg:3857 and opened it up in QGIS to check all was good and it was good.  Then downloaded the newest mapbox 32 bit version 2.2.5..did all the fun steps as before...click download .mbtiles  then it simple never ends...I had to kill the process after 30min of doing nothing.

**Comment by mdiener21** [comment]
Update: I restarted my machine and ran it again just for fun and it worked !!  why I have no idea, I did the same steps 1 to 1 as before...more Windows fun...this helps nobody unfortunately

**Comment by wilhelmberg** [comment]
Glad you got it working. Maybe there were some zombie processes left from the upgrade. We had such problems with the previous installer.

Sorry, for the Windows inconvenience, but, rest assured, we **are** working on it.

And, you are not alone, I also stumbled over the W7 32bit machines of some customers (LaRegK :smirk: ).
