### ISSUE TITLE
Add embedding fonts to Studio docs

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#1147]
### Embedding Fonts

While we include directions for _embedding your own font_ directly in Mapbox Studio. There has been some confusion with this process. It could be helpful to include to also it the Studio docs, like on the [Style Quickstart](https://www.mapbox.com/mapbox-studio/style-quickstart/) page. 

Any objections @ajashton @geografa ?

![image](https://cloud.githubusercontent.com/assets/4587826/5879386/d4ce1562-a2fc-11e4-9649-88a87f2d502c.png)

**Comment by yhahn** [comment]
:+1: @amyleew want to add a final step after [Labelling roads](https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-style-quickstart.md#labelling-roads) that walks the user through downloading a font, adding it to their project and using it?

**Comment by amyleew** [comment]
@yhahn Sure! :+1: I know a well-made, _free & open-source_ font collective to download from [League of Moveable Type](https://www.theleagueofmoveabletype.com/).
