### ISSUE TITLE
Custom font name invisible

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1165]
Trying to load a custom font I noticed something is perhaps broken with the current display.

See with mbstudio latest + chrome Version 40.0.2214.94 (64-bit) (not using atom-shell.app)

1) After adding `font-directory` to my style the changes from the `To embed your own fonts in your style` to `Your fonts ..... 1 font`.

2) Clicking on `Your fonts` give me this view which lacks a face name:

![screen shot 2015-02-03 at 10 20 13 pm](https://cloud.githubusercontent.com/assets/20300/6036045/658aba0c-abf3-11e4-9104-f03f6332725d.png)

3) But I notice its actually there (just invisible) as when I click I can see the name show up:

![screen shot 2015-02-03 at 10 20 22 pm](https://cloud.githubusercontent.com/assets/20300/6036052/825af84a-abf3-11e4-8549-c9b2f2af71a0.png)

**Comment by yhahn** [comment]
Hrm does this happen for other fonts? Looks a bit like this font is named using characters that it itself doesn't support ... (each font displays its own name for the preview atm)

http://www.wazu.jp/gallery/views/View_UnikurdJino.html ?

**Comment by springmeyer** [comment]
@yhahn good point, that may be the case for this font (@nbaghm do you know if this font has any latin character coverage?). However @yhahn I'm seeing that even locally for DejuVu fonts I'm not getting a visual rendering.

**Comment by MarkWS** [comment]
It happens with all fonts. We have a number of projects that have custom fonts, the font is there just displayed in black, so it's not visible until you roll over it or select it. It's been a bug since v2 was released which supported a font directory

**Comment by MarkWS** [comment]
here is a screen shot using v 0.2.5 and the custom font type fill is black.
![capture 1](https://cloud.githubusercontent.com/assets/8440284/6252335/c86deed2-b756-11e4-86af-b2ef283c84f0.JPG)
but the fonts are there, just simply need to click on them and the highlighted font appears;
![capture 2](https://cloud.githubusercontent.com/assets/8440284/6252353/f1e27bac-b756-11e4-9827-8ea21256a150.JPG)
a minor bug at this stage.

**Comment by springmeyer** [comment]
Returning to this. Looks like there are multiple causes of this bug. One was fonts with characters in the `.ttf` name like spaces which was fixed by #1196. The others are:
- Using absolute paths to a `font-directory` on breaks silently (at least on OS X).  This is because paths must be relative (which I did not realize in my testing) due to this join: https://github.com/mapbox/mapbox-studio/blob/97a65487c46baa7df4a4aada0acc035ac6f5ef13/lib/server.js#L475 (Adding support for absolute paths is not a priority of course because the docs say to use relative paths)
- Loading a font like https://github.com/mapnik/mapnik/blob/master/fonts/unifont-7.0.05.ttf using relative paths works on OS X and 64 bit windows but fails on 32 bit windows (@BergWerkGIS replicated)

**Comment by wilhelmberg** [comment]
A "broken" display of fonts might also be due to the representation of the image of the font being cached.

On Windows, the font display re-appeared after doing:
- exit Mapbox Studio, if it is running
- delete all files in `%USERPROFILE%\AppData\Roaming\mapbox-studio\Cache`
- delete all files in `%USERPROFILE%\AppData\Roaming\mapbox-studio\GPUCache`
- delete all files in `%USERPROFILE%\.mapbox-studio\cache`
- delete all files in `%USERPROFILE%\.mapbox-studio\tmp`

**Comment by springmeyer** [comment]
Great discovery @BergWerkGIS - it sounds like this issue may be completely fixed then and just a caching problem. Therefore users of previous versions of studio that hit the original bug will simply have to clear their atom shell cache. I'm going to close this as fixed.
