### ISSUE TITLE
Windows: GDAL_DATA and PROJ_LIB not set correctly

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/mapbox-studio-classic#1177]
@springmeyer @yhahn 

For studio's `node.exe` process `%PROJ_LIB%` should point to 

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\share\proj
```

and `%GDAL_DATA%` should point to 

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\share\gdal
```

which they do not.

**Bonus task:**
Consolidate the shared data that ships with different modules e.g. `node-mapnik\share\gdal` and `node-srs\lib\srs_data`.

---
### PROJ_LIB

When starting Studio on a vanilla machine `%PROJ_LIB%` is set to

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\share\proj
```

When there is other software installed, that sets `%PROJ_LIB%` as a system variable (e.g. @bdiscoe 's great [Virtual Terrain Project](https://github.com/bdiscoe/vtp)), it is unchanged and remains as e.g. `C:\Program Files (x86)\VTP\PROJ4-data`.

Setting `%PROJ_LIB%` manually to the correct path before starting Studio reduced my number of sudden crashes dramatically.

It also solved https://github.com/mojodna/tl/issues/3 where the x86 process exited with the clear message `process out of memory` instead of just disappearing and the x64 process successfully finished rendering, which it sometimes did not before.
### GDAL_DATA

`%GDAL_DATA%` is overridden, even when set as system variable (e.g. `C:\Program Files (x86)\VTP\GDAL-data`), to

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik-omnivore\node_modules\srs\lib\srs_data
```

I think it should point to 

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\share\gdal
```

**Comment by springmeyer** [comment]
Thanks for uncovering this lurking problem @BergWerkGIS. It sounds like good short term steps are:
- add debugging output to node-mapnik, node-gdal, and node-srs that console.log what they are setting these env variables to and if they were set beforehand. Such that at the least the logs will show when variables are being clobbered.
- consider moving on https://github.com/mapbox/node-srs/issues/49 at least to reduce the scope of the problem.
- ???

**Comment by wilhelmberg** [comment]
@springmeyer I agree on short term steps and on implementing some, now native, modules as wrappers arround existing other native modules.
Will reduce possible problems/conflicts greatly.

But I think good long term solution will be difficult, as (I suppose) we can never guarantee the order modules are combined and are loaded:
e.g. `mapnik` loads and sets its env vars and then `srs` loads.
For `srs` the env vars are already set. No way for `srs` to know it they are system env vars or env vars set by the parent process.

One thing that comes to my mind is patching `proj` and `gdal` and defining custom env vars, like `MAPNIK_GDAL_DATA`, `MAPNIK_PROJ_LIB`.

**Comment by springmeyer** [comment]
> But I think good long term solution will be difficult, as (I suppose) we can never guarantee the order modules are combined and are loaded

I agree.

> One thing that comes to my mind is patching proj and gdal and defining custom env vars, like MAPNIK_GDAL_DATA, MAPNIK_PROJ_LIB.

Good option to keep in mind, but not easy to maintain. So let's not move on that yet.

One other idea:
- every module that needs GDAL_DATA or PROJ_LIB set, dynamically sets it ONLY if it is not already set in the ENV.
- then studio could set the environment settings itself after maybe moving all files (from node-srs, node-mapnik, node-gdal, etc) into a single known location.

This would allow:
- each module to work on its own
- apps that include each of these modules to have the final say on what directories of files they load

The gap/problem would be if another application (like `Virtual Terrain Project` as you mention) also sets the ENV settings globally. In this case would Studio setting GDAL_DATA and PROJ_LIB have no effect?

**Comment by wilhelmberg** [comment]
> The gap/problem would be if another application (like Virtual Terrain Project as you mention) also sets the ENV settings globally. In this case would Studio setting GDAL_DATA and PROJ_LIB have no effect?

It would work. Like it already does for `GDAL_DATA`. That one gets overriden to `srs\lib\srs_data` just for Studio's process.

One way to detect if an env var is already set (system wide or for the current user), would be to query those registry keys and check, if the corresponding key exists.
But that would be **very** Windows-only. :smirk: 

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\[PROJ_LIB|GDAL_DATA|ICU_DATA]
HKEY_CURRENT_USER\Environment\[PROJ_LIB|GDAL_DATA|ICU_DATA]
```

**Comment by wilhelmberg** [comment]
Stale, did not occur lately.
Maybe due to `proj4 setlocale` fix.
