### ISSUE TITLE
polygon-pattern-file with remote URL doesn't work

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-studio-classic#1180]
This code:

`polygon-pattern-file:url("http://freeseamlesstextures.com/images/4-old-brick-background-thb.jpg");`

(following the onboard documentation)

gave:

`file could not be found: '/Users/stevebennett/vicroads-purple.tm2/http://freeseamlesstextures.com/images/4-old-brick-background-thb.jpg' in style 'water' in PolygonPatternSymbolizer`

Using a local file worked fine.

0.2.5 on OS X Mavericks.

**Comment by ajashton** [comment]
This is an oversight in the documentation. CartoCSS itself does not support loading web resources - in TileMill this was handled by the `millstone` module, but we aren't using that in Mapbox Studio and all resources should be local. I've updated the online documentation in bc5eeac0d1e45595c203d13798d3d9fdccfee972 - did you see a web URL reference anywhere else?

**Comment by stevage** [comment]
Ah, that makes sense. If I run into something similar elsewhere I'll let you know.

Any plans to include Millstone or a successor? I found it pretty convenient in Tilemill.

**Comment by samanpwbb** [comment]
> Any plans to include Millstone or a successor? I found it pretty convenient in Tilemill.

No plans - all assets that you want to include in the style need to be in the style project folder.
