### ISSUE TITLE
Failed to parse expression in style 'country_label' in TextSymbolizer

### ISSUE THREAD

**Issue by franckalbinet** [mapbox/mapbox-studio-classic#1183]
Mapbox Studio version: 0.2.5
OSX: 10.9.4

When trying to add custom text containing space I get the following error:
"Failed to parse expression: "Brunei Darussal" in style 'country_label' in TextSymbolizer"

MSS for custom country names code for OSM is the following:

``` cartocss
#country_label[zoom>=4] {
  text-name: @name;
  text-face-name: @sans_bold;
  text-fill: #666565;
  text-halo-fill: #ffffff;
  text-halo-radius: 0.2;  
  text-size: 11;
  text-transform: uppercase;
  [name_en='Anguilla (UK)'] { // this is fine
    text-name: 'Anguilla'; 
  }
  [name_en='Brunei'] {
    text-name: 'Brunei Darussal'; // this is not fine. I get the error mentioned
  }
}
```

Did I miss something ?

**Comment by ajashton** [comment]
In order to distinguish it as literal text as opposed to an expression, you will need to quote Anguilla with both double and single quotes:

``` cartocss
text-name: '"Anguilla"';
```

**Comment by franckalbinet** [comment]
Perfect. It makes sense.
Thanks so much!
