### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by 3c** [mapbox/mapbox-studio-classic#1184]
System Windows 7 64-bit OS.
Version: 0.2.5

I found the path is "C:\Program Files\mapbox-studio"  not  "C:\Program Files (x86)\mapbox-studio" ,is this the problem ?  but installing is auto ,I can't select path

I install and uninstall many times, result is same ,crash on startup

**Comment by wilhelmberg** [comment]
@3c 

`C:\Program Files\mapbox-studio` is correct.
You are on a 64bit machine and installed the 64bit version of Studio.

Did you upgrade from a previous version without a reboot?
There could be some zombie processes hanging and blocking a clean install/start.

Could you try to:
- reboot
- delete `app.db` in `%USERPROFILE%\.mapbox-studio` <-- copy this into the address bar of the file explorer.
- install 0.2.5 again.

Let me know how it goes!

**Comment by 3c** [comment]
still crash ..

I have installed 0.1.5 ,it's ok

**Comment by MarkWS** [comment]
I'm having the same problem. 0.2.5 installed correctly, then when I started a New Project and saved it. MBS would not re-start, just crashes. It's something with the 'new project' but don't know how to remove without MBS starting up.

**Comment by springmeyer** [comment]
@MarkWS - find the `.mapbox-studio` folder in your user directory and try removing the `app.db` inside. Then let me know if Studio is able to start again?

**Comment by MarkWS** [comment]
Yes, that worked and I've reconnected my account and loaded back in the projects. thanks.

**Comment by MarkWS** [comment]
Dane, do you know the maximum number of fonts you can have in a directory, is it 16?

**Comment by springmeyer** [comment]
> Dane, do you know the maximum number of fonts you can have in a directory, is it 16?

There is no limit on # of fonts that I'm aware of (though @samanpwbb might have added a limit I'm unaware of). Rather the limit you are likely experiencing in on the size of the project upload. So, the smaller the font size the more font faces you can load.
