### ISSUE TITLE
Removing source causes crash

### ISSUE THREAD

**Issue by michaelsteffen** [mapbox/mapbox-studio-classic#1185]
I have a style that works fine with 3 sources (custom data source + mapbox.mapbox-terrain-v1 + mapbox.mapbox-streets-v5).  When I remove the first source, Studio crashes and then crashes on start. Manually re-adding the first source in project.yml makes everything work again.

**Comment by michaelsteffen** [comment]
Here's the error code from console:

```
2/12/15 9:16:15.428 AM com.apple.xpc.launchd[1]: (com.mapbox.mapbox-studio.132944[5218]) Service exited with abnormal code: 8
```

**Comment by springmeyer** [comment]
Sounds like another case of possible corruption of the `~/.mapbox-studio/app.db` file. Can you try replicating again and then:
- move `~/.mapbox-studio/app.db` aside and see if restarting then works again
- if so, can you post your app.db here (it's json) after stripping anything sensitive?

**Comment by springmeyer** [comment]
per chat with @michaelsteffen - he's going to try to reduce a testcase. He found that removing `app.db` did allow Studio to start, but of course Studio would still crash once he accessed the same project. The problem appears to be that editing the `layers` puts the style out of sync in a crashy way when it simply needs to provide some modal notice about what in the style needs removed (that might reference the removed layer). We found that shell.log and app.log contained no errors indicating why the crash happened.

**Comment by michaelsteffen** [comment]
Doesn't seem to be the stylesheet.  I've whittled the offending project down to a single stylesheet that contains just the following:

```
// Background //
Map {
    background-color: #fff;
}
```

The crash is still reliably reproducible by deleting one source.

**Comment by springmeyer** [comment]
o_0

**Comment by michaelsteffen** [comment]
Indeed

**Comment by michaelsteffen** [comment]
Could the problem have to do with the fact that the offending source belongs to someone else's Mapbox account? Adding sources to this project works fine, as does deleting either of the other two sources currently in the project.

**Comment by springmeyer** [comment]
I have no idea. Thanks get getting us this far. I presume @samanpwbb might know or have ideas about the issue.

**Comment by samanpwbb** [comment]
I tried to reproduce this and was not able to. 

@michaelsteffen where you making these changes with the web UI or in the project yml file? If you still remember, it would be super helpful for you to detail the steps you took before hitting the error.

**Comment by samanpwbb** [comment]
Same as https://github.com/mapbox/mapbox-studio/issues/1093

**Comment by springmeyer** [comment]
see also #1194

**Comment by samanpwbb** [comment]
@springmeyer i think #1194 is different. This is fixed by https://github.com/mapbox/mapbox-studio/pull/1195
