### ISSUE TITLE
postgis-vt-utils ?

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox-studio-classic#1188]
Our docs refer to a "postgis-vt-utis" that is nowhere to be found on the internet if it happens to be missing.

Docs say "This will require the z() function provided by the postgis-vt-utils package." https://www.mapbox.com/mapbox-studio/postgis-manual/

Studio says "Postgis Plugin: ERROR:  function z(numeric) does not exist
LINE 2:   z(3.40282e+38) >= 10 AND"

Google says: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22postgis-vt-utils%22

**Comment by lxbarth** [comment]
Realized this meant to say "postgis-vt-util" without the "s". 
- [x] Fix docs, link mention of postgis-vt-util to proper place.  https://github.com/mapbox/postgis-vt-uti ?
- [x] Add installation instruction on https://github.com/mapbox/postgis-vt-util

**Comment by ajashton** [comment]
Proper link and installation instructions are included in the [Getting Started](https://www.mapbox.com/mapbox-studio/postgis-manual/#getting-started) section, but can be added other places as well.

**Comment by ajashton** [comment]
[Link added](https://github.com/mapbox/guides/commit/642016496cfd62430958a11896b9a4e8bca88e88) and [main readme updated](https://github.com/mapbox/postgis-vt-util/blob/master/README.md)

**Comment by dieterdreist** [comment]
these links are dead now: 404
https://www.mapbox.com/mapbox-studio/postgis-manual/#getting-started
https://github.com/mapbox/guides/commit/642016496cfd62430958a11896b9a4e8bca88e88
