### ISSUE TITLE
Expose variable values in UI

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#119]
It's nice to be able to use variables across stylesheets, but awkward to refer back to variable values.

**Comment by nickidlugash** [comment]
@samanpwbb want to chat about how you see this functionality working? One thing I really want is a color palette UI (like the swatch window in Illustrator and Photoshop), but I'm not sure if this needs to be a unique UI, or if it's really just a combo of this functionality + having visible color swatches (https://github.com/mapbox/tm2/issues/125).

**Comment by yhahn** [comment]
Not going to do this.
