### ISSUE TITLE
Unable to create pipe "\\.\pipe\chrome.24676.0.173299390" in client mode: The system cannot find the file specified. (0x2)

### ISSUE THREAD

**Issue by JayDouglass** [mapbox/mapbox-studio-classic#1190]
Fresh install on windows 8. When I run mapbox-studio.exe I get:

C:\Program Files\mapbox-studio>[24676:0215/001629:INFO:CONSOLE(0)] <Sun, 15 Feb
2015 06:16:29 GMT> Mapbox Studio exited with 3221225781.
[23504:0215/001629:WARNING:ipc_channel_win.cc(309)] Unable to create pipe "\.\p
ipe\chrome.24676.0.173299390" in client mode: The system cannot find the file sp
ecified. (0x2)

**Comment by wilhelmberg** [comment]
@JayDouglass 

I had the same problem today

It occurred after installing `Visual Studio 2015 CTP6`.
CTP **6** seems to seriously mess up the system as I'm also not able to compile some software now.

Did you install some new software recently?

Could you try the following to see, if we get additional error messages?
- Open command prompt
  - Windows Key + `r`
  - type `cmd`, press Enter
- type `cd "c:\Program Files\mapbox-studio\resources\app"`, press Enter
- type `vendor\node index.js`, press Enter

Do you get any error messages, dialog boxes or anything else?

If it seems successful, open your browser at `http://localhost:3000`.
What do you see?

**Comment by wilhelmberg** [comment]
@JayDouglass 

I verified with a vanilla Windows install that `Visual Studio 2015 CTP 6` causes Mapbox Studio to stop working.

Even uninstalling CTP 6 and re-installing Mapbox Studio didn't solve this for me.

**Comment by JayDouglass** [comment]
I have Visual Studio community edition installed on that machine, so it looks like it's related to any Visual Studio install.

**Comment by wilhelmberg** [comment]
@JayDouglass Can you elaborate on which version of Visual Studio **exactly**?

For me, the problems just started after installing `VS 2015 CTP 6`.

If you are not sure about which version you have, you could post a screen shot of the dialog that comes up, when you click: `Help` -> `About Microsoft Visual Studio`.

**Comment by JayDouglass** [comment]
I've had two versions of Visual Studio installed on that machine. VS2013 Professional, and currently VS2013 Community (http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx).

**Comment by wilhelmberg** [comment]
@JayDouglass 

I haven't experienced any problems with VS 2008, 2010, 2012, 2013 and 2015 CTP2 to CTP5.
It just seems that the latest `VS2015 CTP6` is causing troubles and changing the operating system in undocumented ways.
So you are on the safe side concerning VS.

Could you try the following steps to see, to see if we get additional error messages?
- Open command prompt
  - Windows Key + `r`
  - type `cmd`, press Enter
- type `cd "c:\Program Files\mapbox-studio\resources\app"`, press Enter
- type `vendor\node index.js`, press Enter

Do you get any error messages, dialog boxes or anything else?

If it seems successful, open your browser at `http://localhost:3000`.
What do you see?

**Comment by wilhelmberg** [comment]
@JayDouglass 

Another thing to try, could you look into `Control Panel -> Add/Remove Programs` and see if you have one or several 

```
Microsoft Visual C++ 2015 CTP Redistributable
```

entries?

Like this:
![image](https://cloud.githubusercontent.com/assets/4549888/6488731/becd8bc8-c299-11e4-803b-f5d5ca905c37.png)

If yes, please try these steps:
- take a screenshot of the entries (I'm primarily interested in the version number, e.g. `14.0.22512` in my screenhsot
- un-install all those entries
- re-install Mapbox Studio

Does it work now?

**Comment by urbanhop** [comment]
Same problem here.

Win 8.1 clean install
VS CTP 5 and then update to
VS CTP 6 (RC) 

Diagnosis:

**1. running vendor/node index.js causes this exception message box:**

node.exe - System Error

The program can't start because APPCRT140.dll is missing from your computer. Try reinstalling the program to fix this problem.

**2. I have these 2 entries:**

![vc red](https://cloud.githubusercontent.com/assets/9371283/7596338/2e8bb280-f8ed-11e4-9121-dfecab192bd8.jpg)

version number is 14.0.22816.0

**Comment by wilhelmberg** [comment]
@urbanhop 

> then update to VS CTP 6 (RC)

Did you update to CTP 6 or RC?
RC is the lastest at the moment.

Problem is, that our provided binaries are still being built with VS2014 CTP4, requiring an install of VS2014 CTP4 or the CTP4 vcredist.

As there is no stable release of VS2015 yet, an install of a newer version, e.g. VS2015 RC1, automatically removes all previously installed 2014/2015 vcredists in the background, thus rendering our provided binaries unusable.

Right now I'm in the process of bringing everything to VS2015 RC, but it might still take some time as there are [quite some dependencies to take care of](https://github.com/mapbox/mapbox-studio/blob/mb-pages/package.json#L14-L55).

The only solution at the moment would be to remove everything newer than CTP4 and install CTP4 vcredist.
**Be warned tough, that VS2014 CTP4 has already expired and the VS IDE cannot be used anymore.**
The command line tools (that's what we use) still work.

**Comment by urbanhop** [comment]
Sorry, I am on RC now, so I guess it was:

Win 8.1 clean install
VS CTP 5 (maybe, not sure)
VS CTP 6
VS RC

Got Mapbox Studio running in a Hyper-V machine and will wait until things stabilize. Visual C++ libraries at the time of new releases are a hassle, for me you dont need to hurry fixing this issue.

Btw, find it cool to use an electron based application, looks and feels good.

**Comment by wilhelmberg** [comment]
@urbanhop 
great that you have the option to use a Hyper-V machine.
Microsoft provided us with quite a bumpy ride going through all those CTPs.
Hope that things have stabilized with the RC and that RTM will not provide new challenges.

**Comment by wilhelmberg** [comment]
**Applies to current version 0.2.7 of Mapbox Studio**
**Upcoming releases won't have this problem**

**Problem:** an install of Visual Studio 2015 messes with the c++ runtime needed by Mapbox Studio. 

**Solution:**

1.) download
https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64-mini.7z

2.) extract `vcredist_x64-mini.7z` into 
C:\Program Files\mapbox-studio\resources\app\vendor

3.) extract `vcredist_x64-mini.7z` into 
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64

**Comment by ghost** [comment]
Wow, unlucky me. Just installed vs community followed by mapbox-studio. Really wish it threw the error with a proper warning (It simply closed on start) Running the exe through commandline gave the pipe error (which landed me at this page) and then the .dll error after following your guide. Hope the new version is released soon.

**Comment by wilhelmberg** [comment]
@small-mallet great this solved it for you.
VS2015 unfortunately breaks the Mapbox Studio install.
Working on the new release with full steam.

**Comment by duizendnegen** [comment]
Same here, also resolved by copying the DLLs. Leaving this comment in a hope that this issue ranks higher up on search engines. When starting Mapbox, window disappears immediately.
