### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by ItsJoeTurner** [mapbox/mapbox-studio-classic#1197]
Search is hanging in MBS. Our local network is blocking the search, but I'm not sure why? I tethered my iPhone to my iMac and the search resumed. Here's a GIF: http://cl.ly/3u380B1s0y1g

**Comment by samanpwbb** [comment]
Can you [activate developer tools](http://cl.ly/image/360w3b1r451l), and look in the error console to see what kind of error you're getting?

**Comment by ItsJoeTurner** [comment]
@samanpwbb Sure, here's the error: http://cl.ly/image/391O132X0419 - Looks like its being blocked.

**Comment by ItsJoeTurner** [comment]
Fixed this by manually unblocking the code mentioned above on our Firewall. Not sure why it was blocked, as it seemed to happen after updating Mapbox.
