### ISSUE TITLE
Toggle for satellite layer

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#120]
It would be nice to be able to compare my style with satellite imagery to see how my road widths and other features compare with what's on the ground

**Comment by yhahn** [comment]
FYI there is a secret option -- you can add a `baselayer` key under `_prefs` in your project.yml to specify a mapbox layer ID to display under your style.

**Comment by edenh** [comment]
Grabbing this.

I'm thinking the most useful implementation of this is a satellite toggle that adds the satellite layer composited before the actively-styled layer and fills in all transparent areas with satellite.

@samanpwbb @yhahn is this what you had in mind?

**Comment by yhahn** [comment]
Hrm, I would prefer exposing a UI for the baselayer option first which is more generic.

**Comment by samanpwbb** [comment]
> Hrm, I would prefer exposing a UI for the baselayer option first which is more generic.

This _combined_ with layer visibility toggle to quickly turn my style on and off to compare with satellite would get me something close to what I want.
