### ISSUE TITLE
Is it possible to unlock the layer order when using Streets style

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1201]
Is it possible to unlock the layer order when using Streets style (or Outdoors, Run/Bike/Hike) so we can add custom data to map or are all the styles that utilize "terrain" sources locked?

**Comment by samanpwbb** [comment]
If you want to make modifications to these templates, you need to edit the project.yml file: https://www.mapbox.com/mapbox-studio/layer-and-data-order/#custom-layer-ordering

**Comment by MarkWS** [comment]
Hi Saman,
We added in a layer to the `project.yml` file but are getting this error on start-up.
Do you see anything that's incorrect with this URL string?
`Invalid characters in layer https://api.tiles.mapbox.com/v4/markwstroud.9bfc50d3.json?access_token=pk.eyJ1IjoibWFya3dzdHJvdWQiLCJhIjoiZmpqZk96TSJ9.5RmV0G2zZoCg_JQ2G6n4Gw`
