### ISSUE TITLE
Unable to replace Style at Starter plan level

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-studio-classic#1205]
When making a modification to an existing Style and uploading to a Starter account, Studio prompts to upgrade to Basic. Should allow for updates or replacement of Style.

![mapbox_studio](https://cloud.githubusercontent.com/assets/134753/6309669/0b8db014-b926-11e4-8100-1785e65186d2.png)

**Comment by kevin-garcia** [comment]
I'm running into this same issue (running the 32-bit version on WIndows 7):
![image](https://cloud.githubusercontent.com/assets/16250189/11735927/c73ed642-9f8c-11e5-9fca-bc8e54802866.png)

And also when trying to upload to the site:
![image](https://cloud.githubusercontent.com/assets/16250189/11736003/ed134dd4-9f8d-11e5-976a-62a587333b3f.png)

First off, I only have one style loaded, so I'm not at my limit of 10, and second, there is no "basic" plan anymore. Somethings clearly wrong here.

**Comment by geografa** [comment]
@kevin-garcia what version Classic are you using?

**Comment by kevin-garcia** [comment]
It's the 32-bit Windows version (on Windows 7).

**Comment by geografa** [comment]
@kevin-garcia and this is version 0.3.3, correct? Can you try this again and check if it's resolved? Also, Starter plans are limited to [one classic style](https://www.mapbox.com/help/style-limits/).

**Comment by kevin-garcia** [comment]
Yeah, it's 0.3.3. I didn't realize that Starter plans only give you one
classic style. I was thinking when it said ten styles that applied to
classic styles as well. I was able to replace my one classic style with a
new one. The issue was that I was at my style limit (1) without realizing
it. Thanks for checking into it!

**Comment by geografa** [comment]
Absolutely. Thanks for bringing this to our attention - we're clarifying the plans page and docs.
