### ISSUE TITLE
Source layers do not update in a style project

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-studio-classic#1206]
Changes made to source projects do not seem to immediately reflect in the style project that use them.

After making changes to the source project, I save and upload it, and the changes show when the data is viewed online.  However when I switch to the style project in studio that uses this source, there is no update even after refreshing the data source, removing and adding the source as well as reloading studio. It took over 15 minutes and multiple reloads for the data to refresh.

**Comment by duncangraham** [comment]
Hey @planemad after uploading you should check https://www.mapbox.com/uploads/?source=data. At certain times and with certain datasets It takes a bit of time to process data. We could be doing a better job to inform and educate users that the data is processing/propagating. I'll cut a PR for this.

**Comment by duncangraham** [comment]
closed with https://github.com/mapbox/mapbox-studio/pull/1308
