### ISSUE TITLE
Enable location search or lat/lon input

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#121]
I'd be great to be able to navigate around the map more efficiently.

**Comment by nickidlugash** [comment]
:+1:

**Comment by springmeyer** [comment]
@yhahn what do you think here? I think ideally this could be a plugin, but that would require porting over the plugin system from tm1.

**Comment by mojodna** [comment]
:+1:

Even just having the current view in the URL would help to start.

I've been using a modified version of [L.GeoSearch](https://github.com/smeijer/L.GeoSearch) in our browsing boilerplate and preliminarily added leaflet-hash to stamen/tm2#1, though it currently breaks panel functionality (@standardpixel and I have been thinking about using something along the lines of [veltman/hashnav](https://github.com/veltman/hashnav) to more generally address this type of thing).

Leaflet plugins might get far enough for this type of thing without having to go full-bore on the tm1 plugin system.

**Comment by samanpwbb** [comment]
@aaronlidman did this.
