### ISSUE TITLE
Update composite note on toggle from remote to local source

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#1212]
see comment here: https://github.com/mapbox/mapbox-studio/issues/856#issuecomment-76070288

We do not inform the user that you cannot composite local sources.

**Comment by duncangraham** [comment]
I made/merged this PR a few weeks back that fixes this: https://github.com/mapbox/mapbox-studio/pull/1174

This will be bundled into the next release, right?

**Comment by camilleanne** [comment]
Yessir! thanks @duncangraham!
