### ISSUE TITLE
Missing Vector Tiles After Uploading to Mapbox

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [mapbox/mapbox-studio-classic#1222]
I'm trying to figure out why my vector tiles look fine in Mapbox Studio in the source editor prior to upload, however, after upload they don't all appear in the style editor. 

![source view](https://cloud.githubusercontent.com/assets/3316678/6475998/89db3cc8-c1c5-11e4-97be-f09e50656ffe.PNG)
![style view](https://cloud.githubusercontent.com/assets/3316678/6476001/8e6f5256-c1c5-11e4-82f7-24ac41040489.PNG)

**Comment by springmeyer** [comment]
@wheredoesyourmindgo - can you share the sql you are using to query the features which have gone missing? The issue is likely the "pyramid" tile exporting that Studio does internally whereby if a tile lacks any data then all "children" (tiles below it at higher zooms) are skipped.

**Comment by wheredoesyourmindgo** [comment]
@springmeyer - I'm using the [postgis-vt-utils package](https://github.com/mapbox/postgis-vt-util)
Layers look like this..
_city-boundary_
`(SELECT *
         FROM mapbox.city_boundary_ms
         WHERE z(!scale_denominator!) <= 18
 ) AS bndy`
_row-parcel_
`(SELECT * 
         FROM mapbox.row_parcel_ms 
         WHERE z(!scale_denominator!) >= 16 AND z(!scale_denominator!) <= 18
) AS row_parcel`
_parcel_
`(SELECT * 
         FROM mapbox.parcel_ms 
         WHERE z(!scale_denominator!) >= 16 
                AND z(!scale_denominator!) <= 18
        ) AS parcel`
_parcel-line_
`(SELECT * 
         FROM mapbox.parcel_line_ms 
         WHERE z(!scale_denominator!) >= 16 
                AND z(!scale_denominator!) <= 18
        ) AS parcel_line`
_parcel-pt_
`(SELECT * 
         FROM mapbox.parcel_pt_ms 
         WHERE z(!scale_denominator!) >= 15 
                AND z(!scale_denominator!) <= 18
        ) AS parcel_pt`

**Comment by wheredoesyourmindgo** [comment]
Maybe I should try moving City Boundaries to the bottom of this order?

**Comment by wheredoesyourmindgo** [comment]
Dropping the use of z(!scale_denominator!) resolves the issue.

**Comment by springmeyer** [comment]
Using `z()` is fine. The trick is that you need to be careful to maintain some data at each zoom level so that the tiling scheme does not skip deeper zoom levels. So, if you only want data to start showing up at z22 you need to at least provide some data at all previous zooms (no matter how small, could be just one point). This requirement can lead to sql query design patterns like unioning different tables of data into a single layer on the fly. /cc @amyleew and @ajashton who have practical experience with this and can provide more detail.

**Comment by wheredoesyourmindgo** [comment]
@springmeyer I've been using the z() as a hack to use multiple datasets in a single tm2 source as a means of a workaround for "Tile exceeds maximum size of 500k at z#. Reduce the detail of data at..." upload errors that I get when I upload particular layers up to Mapbox at lower zoom levels.  I'm starting to wonder if using z() as a workaround for such errors should be avoided, instead, moving layers into separate source projects.

**Comment by wheredoesyourmindgo** [comment]
I believe I understand how this all works now.  What I will do in the future, when using z() to omit certain layers from lower zoom levels, is include a boundary that covers the entire extent of all the layers that will be found in that source project.  My issue appears to be that I was only drawing the city boundaries at lower zoom levels, and then, when "turning on" parcel boundaries at higher zoom levels using Z() those parcels that were not included in the tiles that contained city boundary layer information from the lower zoom were being omitted on upload.  So by including a polygon that is included in every zoom level used, all parcels get included at higher zoom levels cause every tile contains a piece of info about the boundary covering the tile.  In my case the sensible boundary to use was a county boundary.
