### ISSUE TITLE
Can't open mapBox Studio 0.2.5 on OSX

### ISSUE THREAD

**Issue by MatthewAW** [mapbox/mapbox-studio-classic#1224]
having issues getting started.
After a long wait with the spining white screen I get the blue screen connect prompt. Hitting connect I get (after several minutes) a screen saying:
"Cannot find Mapbox API at https://a.tiles.mapbox.com" and a prompt to list error here

any suggestions?
Thanks

**Comment by wilhelmberg** [comment]
@MatthewAW are you behind a proxy or a filtering firewall?

**Comment by wilhelmberg** [comment]
Stale, closing.

Latest (as of today) status on proxy enabled Mapbox Studio: https://github.com/mapbox/mapbox-studio/issues/860#issuecomment-112001682
