### ISSUE TITLE
Adding a .geojson with space in the name makes Mapbox Studio behave strangely

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-studio-classic#1229]
When I tried to add a layer called "united states.json" to my custom source, the layer ended up into to the list but I was not able to click on it anymore to edit the properties or save the project.

When closing and opening the project again, the layer is not there. No error message is shown.

**Comment by samanpwbb** [comment]
Closed with https://github.com/mapbox/mapbox-studio/pull/1235
