### ISSUE TITLE
Not able to add layers with filenames containing diacritical signs

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-studio-classic#1230]
The file is listed on the add layer dialog, can be selected an the name goes to the text box, but clicking on the Select button doesn't do anything.

Example:
São_Tomé_and_Príncipe.geojson

**Comment by samanpwbb** [comment]
this issue and https://github.com/mapbox/mapbox-studio/issues/1229 are both easy to fix. I can't get mapbox studio to run locally so i can't test my work, but I have this started here: https://github.com/mapbox/mapbox-studio/pull/1235

If you wanted to test it out, that would be super helpful :)
