### ISSUE TITLE
Windows + PostGIS: Bad connection

### ISSUE THREAD

**Issue by leffjesh** [mapbox/mapbox-studio-classic#1238]
I'm having trouble adding PostGIS data to MapBox Studio 2.5 on Windows 7.   I'm using all the same settings from my TileMill project which was working fine.  See attached image.  Error message is 

"Postgis Plugin: Bad connection
Connection string: 'host=localhost port=5432 dbname=postgis20 user=postgres connect_timeout=4'".  
As you can see in the image I can connect just fine to the postgis database from the command line.

![bug](https://cloud.githubusercontent.com/assets/3837528/6516877/9a9c12c2-c34a-11e4-8e6c-4cc6142dd0ce.png)

I have added you lib.sql functionality to my PostGIS database already.  My app.log has the following relevant message:

<Thu, 05 Mar 2015 23:15:05 GMT> error 500 { [Error: Postgis Plugin: Bad connection
Connection string: 'host=localhost port=5432 dbname=postgis20 user=postgres connect_timeout=4'
]
  method: 'PUT',
  url: '/source.json?id=tmsource://c:/MapBox_Studio/WeedWise_Sites/WW_Sites.tm2source&refresh=1' }

**Comment by leffjesh** [comment]
I saw on the forum that you have had some problems with Windows + PostGIS.  Unfortunately, I don't have the option of running this on Linux or MacOSX.

**Comment by wilhelmberg** [comment]
@leffjesh 

First advice on Windows, reboot :smirk: 

If that doesn't help, could you describe your data a bit?

Like:
- how many rows are in each table you are adding?
- how many attributes does each table have?
- which custom sql functions do you use to reduce the size of your data, e.g. `label_grid()`, `z()`, ...

**Comment by leffjesh** [comment]
Thanks for getting back.  I figured out the problem.   Mapbox Studio was not properly handling the case where no password is provided in the connection settings.  See below for details

First a note for others on how I debugged this.  I enabled connection logging on my PostgreSQL install by editing postgresql.conf.  I found that Mapbox studio appeared to be forcing a password when there was none for this user.  The error reported was:

2015-03-06 08:21:11 PST LOG:  connection received: host=::1 port=51317
2015-03-06 08:21:11 PST FATAL:  password authentication failed for user "postgres"

This user does not have a defined password. I fixed this my creating a new user with a defined password and granting the new role the same privileges as the previous (GRANT old TO new).  Then MapBox Studio was able to connect to my database and query and display my data (somewhat) successfully.

**Comment by springmeyer** [comment]
@leffjesh - thanks for sharing how you fixed the problem - surely will benefit many others. If you still have some bandwidth to debug a bit what I would recommend trying is to remove passing  a value of `host` ( I think you must be providing `localhost`?) So try leaving that blank. Postgres may be requiring a password when connecting over localhost but not when connecting over a local socket. At least on unix systems NOT supplying `localhost` means connecting on a local socket and I'm making the assumption that it is similar on windows.

**Comment by leffjesh** [comment]
Omitting the hostname when running on localhost did not help, nor did omitting both port and hostname with my user without a password.   With my user that requires a password I was able to omit the hostname and/or port successfully.

**Comment by springmeyer** [comment]
@leffjesh thanks for trying. Mapbox studio uses libpq internally, so it should be working exactly the same (same defaults, etc) as `psql` on the command line. So I'm not sure what is different. Our libpq build script is [here](https://github.com/mapbox/windows-builds/blob/master/scripts/build_libpq.bat) and we use  [9.4.0](https://github.com/mapbox/windows-builds/blob/79d8e6fbd00d639a697ec8e1bf284a9d3c55abd8/settings.bat#L35).

**Comment by springmeyer** [comment]
This helped uncover a subtle bug in Mapnik whereby the explicit error message returned from Postgres was not being reported. So instead of `Bad connection` after https://github.com/mapnik/mapnik/issues/2725 a better message will be reported. So, this means @leffjesh that the upcoming version of studio may help us uncover the reason for the issue. I'm going to close this ticket for now since I don't have any other ideas to fix the root problem for now.

**Comment by leffjesh** [comment]
Thanks @springmeyer.  By the way, I'm running 9.2.4.  If I get time to upgrade (not likely unless required) then I'll let you know if that helps this issue.
