### ISSUE TITLE
Less clicks to view fonts

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#124]
My brain gets confused sometimes trying to see my font listing. This would be nice:

![screen_shot_2014-02-21_at_3_01_53_pm-2](https://f.cloud.github.com/assets/108094/2234109/1ca53938-9b33-11e3-86df-47b90fba71e0.png)

**Comment by nickidlugash** [comment]
:+1: Um yes, please.

**Comment by samanpwbb** [comment]
done in mbbase

**Comment by samanpwbb** [comment]
Looks like this now:  
![screen shot 2014-03-01 at 11 47 36 pm](https://f.cloud.github.com/assets/108094/2303505/d4922bc6-a1c5-11e3-93fb-d92cf6449410.png)
