### ISSUE TITLE
„Upload to Mapbox“ fails with „Unknown filetype“

### ISSUE THREAD

**Issue by martin-eberle** [mapbox/mapbox-studio-classic#1249]
Project is saved locally and i want it to upload to mapbox. When i hit the „Upload to Mapbox“ button, an error message oocurs and says: „Unknown filetype“.

There is enough space in my mapbox account and the style upload limit should as well be okay.

I’m using the latest Mapbox Studio version 0.2.6 on Mac OS X 10.10.2 (14C1510)

**Comment by courierjournal** [comment]
Same issue here. Although oddly it only occurs in OSX version. Switched to Windows and was able to upload my project successfully.
![mbstudio_bug](https://cloud.githubusercontent.com/assets/7317231/6639404/b64871c0-c965-11e4-9820-d9d6464f0832.jpg)

**Comment by springmeyer** [comment]
Can both of you try again now and let us know if you are still seeing this problem? It may have been a temporary problem with mapbox.com /cc @willwhite

**Comment by martin-eberle** [comment]
In Mapbox Studio version 0.2.6 and in version 0.2.7 the error is till the same. :-(

**Comment by springmeyer** [comment]
@marteb - ok, thanks for testing. Can you share what level plan you are on?

/cc @samanpwbb @willwhite - could this error be happening do to plan level restrictions?

**Comment by martin-eberle** [comment]
The account i tested with is a on a „Starter“ plan level but it is the first style i want to upload and, according to the plan, 1 custom style is allowed.

**Comment by courierjournal** [comment]
Still doing it for me even with 0.2.7 in OSX 10.10.2. We're on a premium plan. The developer console reports this error `Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

**Additional info**: This is the query it's executing: `http://localhost:3000/style.upload.json?id=tmstyle:///Users/courierjournal/test.tm2`. Running that string in a browser yields `Cannot GET /style.upload.json?id=tmstyle:///Users/courierjournal/test.tm2`

**Update 2**: I missed the fact that the query its executing is using PUT, not GET. I PUT'ed it and get the response `Unknown Filetype` (basically the aforementioned 422 error)

**Comment by willwhite** [comment]
Thanks for the reporting this issue. I'm not able to replicate it at the moment, but an example file could help. Can you click "download package" and send the resulting file to support@mapbox.com? Please include your mapbox.com username. That should help us narrow down the problem faster.

Thanks!

**Comment by martin-eberle** [comment]
You should have got an email.

**Comment by martin-eberle** [comment]
Anything new about this Issue?

**Comment by courierjournal** [comment]
I just sent my project to you. I've tried wiping MB Studio from my system, reinstalling, and setting up a new project from scratch. Still no luck. This is just a really simple project, create a new one and pick a style. Not sure whats going on and why the server won't take it.

**Comment by courierjournal** [comment]
So I tried exporting the file from MB studio to a .tm2z file and manually uploading to the site and it still doesn't work.  I can't believe marteb and I are the only ones experiencing this. It's definitely an OSX related issue. I can take that same file and move it over to a Win 7 machine, open it in MB Studio, and upload the project successfully.
![untitled-1](https://cloud.githubusercontent.com/assets/7317231/6925827/39031b8a-d7b0-11e4-8dd9-40d374f4fa8e.jpg)

**Comment by springmeyer** [comment]
@courierjournal - thanks for all the details you've been providing. We are working on a fix and will let you know when you can expect this to start working.

**Comment by willwhite** [comment]
Is there anything unusual about your installation - specifically around paths? I'm seeing that the example files provided are prefixed with a relative path, which is unexpected and is causing the API to reject the file as unrecognized.

**Comment by martin-eberle** [comment]
I dont’t think so. It’s a „standard“ OS X 10.10 setup. And i tried a windows 8.1 pc as well and had the same problem…

**Comment by wilhelmberg** [comment]
@marteb 
Are you behind a cooperate proxy/firewall?
Some of these enterprise solutions often fiddle with web requests and change them in unexpected ways.

If yes, could you try with a direct connection to the internet?

**Comment by martin-eberle** [comment]
No, i’m not behind a proxy or a firewall. I also tried different internet connections but the problem is always the same.

**Comment by courierjournal** [comment]
I don't have anything unusual as far as my install goes that I know of. I have a bunch of dev stuff installed, but I'm not sure how that would affect pathing relative to mapbox. Some sort of change made to 10.10 maybe? Or since it's happening to @marteb on a windows machine maybe something funny with  Atom?

@BergWekrGIS we _are_ behind a corporate firewall. However using the same connection on a windows machine works fine.

**Comment by martin-eberle** [comment]
@willwhite can you tell me, where in the uncompressed files you found „that the example files provided are prefixed with a relative path“? Is it possible to fix this by hand in the .mss files?

**Comment by anderser** [comment]
I have the exact same issue on version 0.2.7 on Mapbox Studio on Mac OS X. I have sent a version of the tm2z file to support at mapbox if that helps.

**Comment by martin-eberle** [comment]
We upgraded to a paid „standard“ plan but it still doesn’t work. Is there any workaround for this issue?

**Comment by GretaCB** [comment]
Hi @marteb @anderser @courierjournal ,

You should now be able to upload your styles to your accounts. The problem was related to a particular `tar` header produced when zipping your styles. Let me know if you run into any other issues.

**Comment by martin-eberle** [comment]
Yes, it works. Great! :)

**Comment by gersonbergeth** [comment]
I'm also experiencing this issue when importing edited Maki icons. Error message: unknown file type. @GretaCB is this a related issue? Thanks for looking into this.

**Comment by GretaCB** [comment]
Hi @gcodeglife , a few questions that will help me troubleshoot: 
- What kind of file are you trying to upload? (ex: an `.svg` file, a `tm2z` file that contains your style edits, or another file format)
- Are you uploading via Mapbox Studio Classic?
- Or are you uploading via Studio from your mapbox.com account?

Thanks!
