### ISSUE TITLE
Color swatch + picker in code editor for hex colors

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#125]
I need to keep a scratch pad open in inkscape whenever I'm working with colors because my brain can't translate any color code syntax. I am in love with these things in code editors:
![screen shot 2014-02-21 at 3 09 21 pm](https://f.cloud.github.com/assets/108094/2234164/19aed8f0-9b34-11e3-98b4-9d5d015d87e8.png)

Here's a codemirror plugin that does this: http://enjalot.github.io/Inlet/

**Comment by nickidlugash** [comment]
:+1: 

For me, I'm indifferent as to whether we include a picker (I prefer using external pickers, anyway), but I'd LOVE to be able to see swatches for the colors I've picked.

**Comment by samanpwbb** [comment]
Started in - https://github.com/mapbox/tm2/pull/217

I would love to see:
- Swatches after variables if variables are colors.
- Swatches for output of color functions

**Comment by yhahn** [comment]
I'm going to discourage pursuing variable handling here for now.

The right approach to this would be to use carto to parse and materialize the colors from the stylesheets but this would require more or less constant carto compilation of the style and it's just not what carto is designed for atm.

We attempted cheap/hackish solutions in TM1 without going through the real parser and I would say those efforts failed : )

**Comment by tmcw** [comment]
Looks like this moved and is now complete and very fancy dancy

![2014-08-12 at 4 29 pm](https://cloud.githubusercontent.com/assets/32314/3897183/828be16c-225f-11e4-83f8-ba25e669404f.png)

**Comment by samanpwbb** [comment]
Almost too fancy dancy.

**Comment by heyitsgarrett** [comment]
It's very fancy dancy and very disruptive-ancy. I will raise some issues in a new ticket.

**Comment by tmcw** [comment]
![fun2](https://cloud.githubusercontent.com/assets/32314/3897286/6c9f25a2-2260-11e4-9bec-b2e45d7c68af.gif)

But it's so much funn
