### ISSUE TITLE
More contrast between full, docs, code template buttons

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#126]
These three buttons look too similar:

![screen shot 2014-02-21 at 3 14 17 pm](https://f.cloud.github.com/assets/108094/2234203/d3b45798-9b34-11e3-982f-fb56059d3923.png)

I get confused sometimes. Contrast between them should be increased. A different colored background or so on the docs icon would help.

**Comment by nickidlugash** [comment]
For me, the confusion has a lot to do with the fact that the icons are unclear, not just that there's not much contrast. Could we possibly making the code reference icon be a question mark? The current icon is confusing to me because I keep thinking it's referring to my mss code files.

**Comment by samanpwbb** [comment]
Done in mbbase
