### ISSUE TITLE
mapbox-studio-win32-x64-v0.2.6

### ISSUE THREAD

**Issue by rxb949** [mapbox/mapbox-studio-classic#1274]
I have hard time to install this package. I had mapbox-studio-win32-x64-v0.2.5, and worked fine. When I tried to upgrade it, the studio does not work, it just would not open at all.  I had uninstalled and reinstalled this version, but no luck to load it once I click on the icon. Does anyone know how to fix it?

**Comment by springmeyer** [comment]
Can you please find the log file, paste it to https://gist.github.com/, and then share the link here? The log file is at `~/.mapbox-studio/app.log`.

After that try:

1) restarting your machine
2) removing the `.mapbox-studio/app.db` in your user directory
3) Try opening studio again. Does the app start then?

**Comment by wilhelmberg** [comment]
@rxb949  Paste `%USERPROFILE%\.mapbox-studio` into the address bar of File Explorer to easily get to the files mentioned by @springmeyer

**Comment by rxb949** [comment]
Removal of the app.db under userprofile did the trick.  Thank you both.

**Comment by springmeyer** [comment]
@rxb949 - great, also when you upgrade to 0.2.6 or 0.2.7 the app will no longer default to opening the last used project. it may be that you have a broken project and the app was crashing when it tried to return to it. If this is so then you may still hit a crash when you manually navigate to the project. If so, then please create a new issue describing the project in detail and what kind of data it contained.
