### ISSUE TITLE
Saving style with local source leads to blank map

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1278]
Seen with the latest `space-walk` 64 bit windows binary on Win 7 in atom-shell app. This feels similiar to #1250 but creating a new issue here since I think #1250 should be fixed in the `space-walk` test build.

Steps to reproduce:
- created a local source from a world-merc shapefile
- exported to mbtiles as part of testing #1277  
- created a new style from the source
- preview of new style worked and looked good
- went to try to test the static image export, but grayed out since the style was not saved
- saved the style
- then the map went fully white and no data showed

Debugging this I found out that the layers showed only `Mapbox Streets V5` for the source instead of the correct/original local source. Somehow saving caused this fallback?

**Comment by springmeyer** [comment]
Debugging more: I found that the project.xml and project.yml actually has the right path stored to the local source. So it must be something wrong with loading it and falling back?

![screen shot 2015-03-23 at 1 34 26 am](https://cloud.githubusercontent.com/assets/20300/6776525/f8c9b9d4-d0fc-11e4-8d02-d6832ad3a6e8.png)

**Comment by yhahn** [comment]
y, just found the leakey flow: https://github.com/mapbox/mapbox-studio/commit/a24eaa89caa0e6e024f3e2aaa8641baa7d92eb53
- Gets set to backslashey path here: https://github.com/mapbox/mapbox-studio/blob/space-walk/app/style.js#L366-L367
- Style is loaded + cached using req.body.id which has backslashey path

Will sleep on whether to normalize the req.body (stopgap commit above) or whether we should also force the file browser on windows to also use normalized paths (forward-slash, lowercase drives).

**Comment by springmeyer** [comment]
Great, was about to comment with a bit more detail. Going to sleep in a sec so just in case its valuable in the morning I found:
- styles, after being saved, would have their paths flipped to use backslashes.
- if I restarted studio then the styles would magically start working
- However: the print icon was still gray'ed out

**Comment by yhahn** [comment]
Wound up going with both approaches (normalize paths in `req.body`, normalize file listing from `tm.dirfiles`).

https://github.com/mapbox/mapbox-studio/pull/1267

Will roll a new package for testing.

> However: the print icon was still gray'ed out

This is coming from the `on-local` class here https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/style.html#L307. Not sure what the reasoning behind this was but let's deal with that separately.

**Comment by springmeyer** [comment]
closing this as I've tested @yhahn's latest `space-walk` build from `2015-03-23 18:50:33` and the problem is solved. ticketed minor print icon issue at #1281
