### ISSUE TITLE
Fatter scrollbars, please!

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#128]
Maybe my mouse-handling skills are just not up to par, but I have trouble selecting the scrollbars because they're so narrow.

**Comment by incanus** [comment]
This will be OS-dependent. I should probably get cracking on https://github.com/mapbox/tm2/issues/110?source=cc to help address this.

**Comment by tmcw** [comment]
Er, it will be but it's a quick fix right now: https://github.com/mapbox/tm2/blob/master/app/base.css#L52-L54

**Comment by yhahn** [comment]
^^ @nickidlugash set this to whatever width/style you want pls

**Comment by nickidlugash** [comment]
Submitted pull req: https://github.com/mapbox/tm2/pull/131
