### ISSUE TITLE
Print icon incorrectly disabled?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1281]
This is happening with local sources. As per https://github.com/mapbox/mapbox-studio/issues/1278#issuecomment-85122632 it is unclear if this needs to be disabled for any good reason.

**Comment by samanpwbb** [comment]
Based on this commit by @camilleanne, looks like this was intentional: https://github.com/mapbox/mapbox-studio/commit/cfa190d88070b05ac33c945ee960bda19834baad

**Comment by springmeyer** [comment]
closing as duplicate of #975
