### ISSUE TITLE
Entry point not found ~MakeWeak~

### ISSUE THREAD

**Issue by sainsb** [mapbox/mapbox-studio-classic#1286]
Got this intense message today when trying to install the new version of MBS over the top of the old version...
![image](https://cloud.githubusercontent.com/assets/1097798/6831966/cd31135e-d2e0-11e4-9a5f-5a9c72aa7ad4.png)

**Comment by springmeyer** [comment]
@sainsb - wow, thank for reporting.  So you saw this at install time or after the install the first time you tried to start the app? Can you share what version of Windows you are running?

**Comment by sainsb** [comment]
After install trying to start the map.
Win7

Uninstalled and reinstalled and it works. I'm thinking the contingency step of removing the old version when installing a new one is faulty - or maybe it's just something about the way I am. :)

thanks Dane - u da man

**Comment by springmeyer** [comment]
wild, that is great that you fixed it, but not sure why. I wonder if mapbox studio was running when you when to run the upgrade maybe? (or perhaps one of its subprocesses was runaway in the background). Then the install may have only worked partially... This should not happen (we try to catch this situation in the installer) but perhaps is not fully working.

**Comment by wilhelmberg** [comment]
The error suggests, that there was an old version of Atom-shell still being loaded.
So, yes I think Mapbox Studio was still running, when the upgrade process was started.

I suggest to exit Mapbox Studio automatically as soon as the upgrade link is clicked.

**Comment by sainsb** [comment]
Yes, can confirm, old version was running. sorry for the trouble.

**Comment by rhansson** [comment]
Same problem when upgrading to 0.2.7 on Windows 7. Re-installing works.
Note: Hadn't fully started Studio yet. Only the dialog prompting to upgrade

**Comment by wilhelmberg** [comment]
@rhansson Thanks for letting us know.
The upgrade dialog is already part of Mapbox Studio.
Normally, the installer should bail out when Studio (Upgrade dialog) is still running.
