### ISSUE TITLE
Changing sources breaks mouse input in Chrome

### ISSUE THREAD

**Issue by TheMapSmith** [mapbox/mapbox-studio-classic#1291]
Hello,

For some reason when I add my remote source to the Basic Map template, MBS just sits there doing nothing. No spike in processing/memory/network activity. No error message. The page just becomes unresponsive. 
- Mid-2010 MBP with OSX 10.9.5
- Chrome Version 41.0.2272.104 (64-bit)
- Latest MBS version

[Process sample](https://gist.github.com/TheMapSmith/88b2526fc6d873744a41)

I'm able to add the source to a blank map, but as soon as I try to integrate it with mapbox-streets-v5 it hangs.

Update: Starting a new project and not worrying about my GeoJSON source now. Here are the steps I took:
1. Start a new project with the Basic style
2. Change source to Mapbox Streets + Vector Terrain
3. Upon clicking Apply no more mouse inputs are accepted. Keyboard shortcuts continue to work.

Tried to confirm this behavior in Firefox and Safari, but they both work just fine.

Tried it again in Incognitio with extensions disabled and the problem still occurs in Chrome.

**Comment by TheMapSmith** [comment]
This was fixed with either a fresh clone and install or one of the updates.

**Comment by samanpwbb** [comment]
Great, :+1: - pretty sure this was a webkit bug affecting our modal, where the element was visually hidden but still occupying space on the page.
