### ISSUE TITLE
Remove link to raw github content in PostGIS Manual

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-studio-classic#1293]
@amyleew There's a link to the `lib.sql` file in [postgis-vt-util](/mapbox/postgis-vt-util) in the PostGIS manual as a raw github file. These links are unreliable -- we should be hosting it somewhere else and linking to it there. /cc @katydecorah

**Comment by amyleew** [comment]
@lyzidiamond Public gist?  /cc @katydecorah

**Comment by lyzidiamond** [comment]
@amyleew or even just hosting it on the website file structure somewhere

**Comment by amyleew** [comment]
@lyzidiamond :thumbsup:

**Comment by ajashton** [comment]
lib.sql is updated from time to time and it would be nice to not have to think about mirroring updates to static website files. How unreliable is the raw link / in what way? What about just linking to the postgis-vt-util repo?

**Comment by lyzidiamond** [comment]
Okay, so, in this case it doesn't matter, but GitHub serves all of its content via these `raw.githubusercontent` links as MIME type `text/plain`, which can be an issue if you're trying to use it as a CDN. But in this case it's probably not a huge deal, cos it's just a file download... right? Maybe?

**Comment by amyleew** [comment]
@lyzidiamond Yes, just download. I'll let as is.
