### ISSUE TITLE
Windows: QuickFix: Mapbox Studio should close itself after link to upgrade is clicked

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/mapbox-studio-classic#1297]
Problem:
- user gets upgrade message
- clicks on upgrade
- browser pops to front
- user downloads new installer
- user has forgotten about running Mapbox Studio in the background
- user runs installer
- installer cannot overwrite all files, **but doesn't fail or notify user**
- user cannot start new Mapbox Studio, like here:
  https://github.com/mapbox/mapbox-studio/issues/1286

**Quick fix:**
If it's possible, exit Mapbox Studio after user clicked on upgrade link
@samanpwbb what do think?

**Long term solution:**
Improve installer to check for running studio processes before doing anything else.

**Comment by springmeyer** [comment]
> Improve installer to check for running studio processes before doing anything else.

I confirmed this worked at one time: https://github.com/mapbox/mapbox-studio/commit/f3415c0c066b5534326f72319bb594c3f4bf4c5c. Maybe it regressed somehow?

**Comment by wilhelmberg** [comment]
No, this hasn't regressed.
Installer presents error message and doesn't continue if Studio is already/still running.

There must have been another reason, e.g. un-installer didn't remove everything, because error `Procedure entry point not found` from https://github.com/mapbox/mapbox-studio/issues/1286 usually happens when DLLs don't match.

Closing, because I couldn't reproduce and installer check works.
