### ISSUE TITLE
add keybindings

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#130]
Would love to be able to do the following with my keyboard:
- Tab between stylesheets
- Open docs
- Open data sidebar
- Open project overlay
- _Controversial_ Expand code manipulation tools with codemirror (multi-line select, multi-line comment-out, ect)

**Comment by edenh** [comment]
https://github.com/mapbox/tm2/commit/126f36d245f315846b3a782467d2ecda2bc326af

<code>Cmd/Ctrl+[1-9]</code> Go to tab 1 - 9
<code>Cmd/Ctrl+H</code> Open docs
<code>Cmd/Ctrl+L</code> Open layers
<code>Cmd/Ctrl+I</code> Open settings

> Controversial Expand code manipulation tools with codemirror (multi-line select, multi-line comment-out, ect)

Let's wait until the cm upgrade for this one.

**Comment by samanpwbb** [comment]
:pray:

**Comment by ian29** [comment]
hrm, cmd+L selects the address bar in at least Chrome and Safari - which i (and maybe others?) use frequently.

**Comment by tristen** [comment]
Yeah ...  I use cmd+L a lot myself. I would be pretty hesitant overriding Cmd+I or Cmd[1-9] as well if tm2 remains a browser rendered application.

**Comment by samanpwbb** [comment]
Just switched to `cmd+,` for left layer palette.

Not seeing an obvious better alternative to `cmd+#` for tabs - I think it's okay to be aggressive about this. Adding a second modifier key or using a weird modifier adds complexity to keybindings, making them hard to remember. It would be nice to avoid this. TM2 should be treated like an app, whether it runs in the browser or not, and we shouldn't compromise too much just because it runs in the browser.

**Comment by ajashton** [comment]
Discussion from chat re: overriding Cmd-[1-9]

```
AJ Ashton: I don't think 'treat tilemill like an app' should also mean 'ignore/override the actual environment we're running in'

saman bemel-benrud: @aj do you have a suggestion?
http://saveforwebclaws.com/

AJ Ashton: ctrl-[1-9] seems to be safe for both linux & osx

saman bemel-benrud: drop cmd, move to crl as a modifier key for all keybindings?

AJ Ashton: I don't think that's necessary. Eg overriding Cmd-S seems ok since there is no practical use of the native function when using tilemill
but tab switching is too fundamental imo, I tab switch all the time when using tm
```

**Comment by incanus** [comment]
Using `ctrl`, period, on OS X is kind of foreign. It pushes TileMill that much further out of feeling like native app territory...

Overriding `Cmd-S` seems ok, though, as that's your typical "save this page", which isn't going to apply in TileMill.

**Comment by samanpwbb** [comment]
I just spent some time digging around in here, with https://github.com/mapbox/tm2/commit/8efe91bba1274ef08837b021bb990ecefbec0af6. This is what I did:
- Command or control + option + # for tabs
- Everything else still using command or control as modifier key
- Hold down shift to override TileMill's keybindings and use system keybindings

**Comment by samanpwbb** [comment]
Notes from #211: 
Conflicts that need to be addressed:
- cmd+d for data drawer
- Cmd+H
- Cmd+Alt+I

**Comment by samanpwbb** [comment]
~~cmd+/ conflicts with multi-line comment-out in codemirror~~ fixed with 413ba1488a7e82b8bb206334f261c61f69de3f2d

**Comment by yhahn** [comment]
@aaronlidman putting this in your hands to be ruthless with. For things that conflict I think people would be fine with just removing the bindings for now.

**Comment by samanpwbb** [comment]
Keybindings that I rely on heavily when working on maps:
- Save (obviously)
- Stylesheet switching (with cmd option #) 
- fullwidth map
- info panel
- data panel

The rest are less important, but can we try hard not to lose these.

**Comment by yhahn** [comment]
Taking over here.
- [x] add tests for all the keybindings
- [x] close out
