### ISSUE TITLE
Application closes right after start

### ISSUE THREAD

**Issue by stefda** [mapbox/mapbox-studio-classic#1303]
Mapbox Studio shows the initial screen with the spinner upon start, then closes.

Issue is identical for both Mapbox Studio x86 and x64 v0.2.7 on Windows 7 64-bit OS.

The issue can be resolved by deleting the files `app.db` and possibly `app.db.compacted` from the directory `C:\Users\<name>\.mapbox-studio`. However, the files are recreated upon the next start and the application will fail to load in the future.

Possibly related to #969.

**Comment by wilhelmberg** [comment]
@stefda 

Could you
- post your `app.log`, also in the `.mapbox-studio` folder
- start Mapbox Studio from the command line and post the output

Starting Mabox Studio from the commandline:
https://github.com/mapbox/mapbox-studio/wiki/Windows-Troubleshooting#start-mapbox-studio-from-the-commandline

**Comment by stefda** [comment]
Here are the contents of my app.log

```
<Thu, 02 Apr 2015 07:53:07 GMT> Mapbox Studio @ http://localhost:3000/
<Thu, 02 Apr 2015 07:55:33 GMT> Mapbox Studio @ http://localhost:3000/
<Thu, 02 Apr 2015 07:56:52 GMT> Mapbox Studio @ http://localhost:3000/
<Thu, 02 Apr 2015 08:03:29 GMT> Mapbox Studio @ http://localhost:3000/
<Thu, 02 Apr 2015 08:03:54 GMT> Mapbox Studio @ http://localhost:3000/
```

And here's the cmd output:

```
C:\Program Files\mapbox-studio>mapbox-studio.exe

C:\Program Files\mapbox-studio>[5132:0402/122428:INFO:renderer_main.cc(211)] Renderer process started
[12124:0402/122431:INFO:CONSOLE(0)] <Thu, 02 Apr 2015 10:24:31 GMT> Mapbox Studio exited with 8.
```

**Comment by wilhelmberg** [comment]
That's strange.

Please try this:
- make sure via Task Manager that there are no running `node.exe` or `mapbox-studio.exe` processes
  - if there are, kill them
- open command prompt
- `cd "C:\Program Files\mapbox-studio\resources\app"`, ENTER
- type `vendor\node index.js`, ENTER

Does it also exit?
- If yes, is there more output in the console?
- If not, open your browser (Chrome would be best, but FF should work, too) and go to `http://localhost:3000`

**Comment by stefda** [comment]
Running `.\vendor\node index.js` gives the following error:

```
C:\Program Files\mapbox-studio\resources\app>.\vendor\node index.js

C:\Program Files\mapbox-studio\resources\app\index-server.js:71
    if (err) throw err;
                   ^
Error: EPERM, rename 'C:\Users\David\.mapbox-studio\app.db'
```

**Comment by wilhelmberg** [comment]
Normally this should be resolved by deleting `app.db.compacted` (as you've already mentioned in your original post).

Could you once more verify that this happens every time?
- verify that no `node.exe` `mapbox-studio.exe` processes are running
- delete `app.db` and `app.db.compacted`
- start Mapbox Studio via `vendor\node index.js`
- "exit" studio via pressing `Ctrl+c` on the commandline
- start Mapbox Studio again via `vendor\node index.js`

Does it error again?
Only one instance of Mapbox Studio is allowed to run at a time.

**Comment by stefda** [comment]
Oddly enough, Studio now starts consistently (by following your procedure or by selecting it's icon from the menu). The one thing that has changed since I reported the problem is that I have deleted all Projects, Styles and Data from my Mapbox account.

I have managed to partly recreate the issue when I tried to upload tiles into my Mapbox account and the app crashed. Then, upon startup, I would get the same error as posted above. Deleting `app.db` and `app.db.compacted` would resolve the problem but the app crashed few more times when trying to upload the tiles leading to the same behaviour.

The tiles were created using the `westminster_const_region.shp` from the Boundary-Line dataset at https://www.ordnancesurvey.co.uk/opendatadownload/products.html.

Once I've managed to complete the tiles upload Studio loads fine on each startup.

**Comment by wilhelmberg** [comment]
Thanks for the analysis. 
I tried the mentioned data set, but didn't encounter any problems.

When working with lots of data, it is highly recommended to work with PostGIS to have more control over how much data is processed into vector tiles.
A guide to get you started, can be found here:
https://www.mapbox.com/mapbox-studio/postgis-manual/

Some best practices before you add a shapefile to Mapbox Studio:
- drop as many attributes as possible and keep only those that are absolutely necessary for styling
- reproject to Web Mercator:
  - `ogr2ogr -f "ESRI Shapefile" out.shp Your-Input-Shape-File.shp t_srs EPSG:3857`
- run `shapeindex Your-Reprojected.shp` after reprojection
  - `shapeindexe.exe` can be found in `"C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\`

**Comment by stefda** [comment]
Thanks for the tips, it all makes sense. I guess we can close this. If I encounter the same issue in the future I'll revisit the post and add new information.
