### ISSUE TITLE
Style Quickstart web Tutorial-- "JS-YAML" Error from UTF Grid Interactivity step

### ISSUE THREAD

**Issue by stevemcf** [mapbox/mapbox-studio-classic#1306]
Hello,
I'm going through the Mapbox Style QUickstart Tutorial at https://www.mapbox.com/mapbox-studio/style-quickstart/#uploading 

I am running into a JS-YAML error that stops me from re-opening the project after I've made the suggested changes to the text in the project.yml file. (Not sure why these changes are in a photo in the tutorial where the other changes are in copyable text).

The photo I've uploaded here shows the error and the changes I made to the yml file. 

Thanks!
Steve

![errorscreenshot](https://cloud.githubusercontent.com/assets/11825966/7014784/562fc690-dc97-11e4-97b1-76848c40c913.jpg)

**Comment by amyleew** [comment]
@stevemcf - You've got a  `+` instead of `=` for your `a href` tag. Full code:

```
template: |-
  <strong>{{name}}</strong>
  {{#type}}
  <br /><small>{{type}}</small>
  {{/type}}
  {{#address}}
  <br /><small>{{address}}</small>
  {{/address}}
  {{#website}}
  <br /><small><a href='{{website}}'>website</a></small>
  {{/website}}
```

**Comment by stevemcf** [comment]
Worked like a charm! Thanks for the sharp eyes @amyleew!
