### ISSUE TITLE
Railways and more

### ISSUE THREAD

**Issue by Forna73** [mapbox/mapbox-studio-classic#1316]
Hi!
Railways shows up only from zoom 12 and above (13, 14...)
I need to get them starting from zoom 10... how could I get?
I tried with:
# road [class='major_rail'][zoom>=10]

**Comment by Forna73** [comment]
Ok Guys!
I'm becoming a little crazy learning something only by examples without a real manual.
As above I need also to style type=trunk in the #road layer.
I can't understand how to do that!

My project is limited to zoom level 10, 11 and 12 but I'm thinking there are features in some way hardcoded to show only at predetermined zoom level.

Hel please!

**Comment by samanpwbb** [comment]
@Forna73 not all data is available at all zoom levels in Mapbox Streets. Railways are visible starting at zoom 12. 

To get a better sense of data availability, use x-ray mode:

![screen_shot_2015-04-21_at_1_17_44_pm](https://cloud.githubusercontent.com/assets/108094/7251149/e851a2a4-e828-11e4-9054-d4239dbfa40c.png)

If you want rail at higher zoom levels, you will need to [create your own data source](https://www.mapbox.com/guides/source-quickstart/).

**Comment by Forna73** [comment]
Thx... I don't understand why an important feature like railways aren't showed at the same zoom level as motorways.....

And what about the the second question? the trunk type for roads?

thanks

**Comment by samanpwbb** [comment]
> And what about the the second question? the trunk type for roads?

xray mode is interactive, you can explore by clicking on features:

![screen shot 2015-04-21 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/108094/7252691/9863cb32-e837-11e4-90e1-f4ded5af1886.png)

Documentation for mapbox sources is at https://www.mapbox.com/developers/vector-tiles/mapbox-streets/

**Comment by Forna73** [comment]
Sorry but I didn't understand the answer...
I know about the xray mode. infact I discovered that #road has also 'type' feature viewing this.
What I wish to know is How can I style all 'main' roads that are type = trunk
