### ISSUE TITLE
Codemirror text flashes in and out [Chrome]

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#132]
![screen shot 2014-02-24 at 11 18 10 am](https://f.cloud.github.com/assets/108094/2247486/4796fdaa-9d6f-11e3-9353-19aa39834c40.png)

**Comment by mikemorris** [comment]
I vaguely remember seeing similar issues with Prose that I believe ended up being bugs in Chrome's rendering engine.

**Comment by samanpwbb** [comment]
Probably something we'll have to live with then, thanks @mikemorris 

Going to close so people don't waste time on this.

**Comment by mikemorris** [comment]
@samanpwbb May be worth filing an issue in the CodeMirror repo if you can find a reliable test case https://github.com/marijnh/codemirror/issues?state=open

**Comment by yhahn** [comment]
Hold on that, we're on an old version and figuring out how to upgrade (without nuking performance) will take priority.
