### ISSUE TITLE
Error: getaddrinfo ENOTFOUND when working offline

### ISSUE THREAD

**Issue by jasonferrier** [mapbox/mapbox-studio-classic#1327]
Mapbox Studio v0.2.7 on OS X 10.10.2

Seems to be related to #446 

Here's the relevant section from _~/.mapbox-studio/app.log_

```
<Fri, 01 May 2015 04:32:51 GMT> Mapbox Studio @ http://localhost:3000/
<Fri, 01 May 2015 04:32:51 GMT> error 500 { [Error: getaddrinfo ENOTFOUND]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  method: 'GET',
  url: '/' }
```

![Mapbox error when there is no internet connection](http://i.imgur.com/UFlYd2e.png)

**Comment by springmeyer** [comment]
This should be fixed by https://github.com/mapbox/mapbox-studio/pull/1318

**Comment by jasonferrier** [comment]
Thanks, I'm subscribed to #1318, so I'll close this for now.
