### ISSUE TITLE
Coordinate ordering is inconsistent

### ISSUE THREAD

**Issue by nyurik** [mapbox/mapbox-studio-classic#1329]
Coordinates in the upper right corner are in one order, but if i copy them and search the map with them, they get reversed. Please make them consistent when copy/pasting. Thanks!

**Comment by springmeyer** [comment]
@amyleew noticed this too and is planning to fix. Thanks for creating a ticket!

**Comment by amyleew** [comment]
@nyurik - Fix is merged with `mb-pages` and will be included in v0.2.8 release.
