### ISSUE TITLE
Layer reordering vs layer instancing

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#133]
I know we've discussed this at varous points but I want to make sure I understand correctly...
- **We can _reorder_ layers** from a vector tile using mapnik XML. This is just a matter of changing the order in which the layers appear in the style XML.
- **We can? can't? declare multiple instances** of a layer from a vector tile using mapnik XML. I can't see how we would be able to do this, just want to confirm that's it's not possible atm to create two mapnik XML layers that both reference the same VT layer.

cc @ajashton

**Comment by springmeyer** [comment]
Yes to both: render order is determined by the layers as declared in the Mapnik XML and multiple Mapnik XML layers can be defined with the same name, which will effectively render that layer twice, applying its specific styles. If there is something blocking this from working I'd look at whether carto is enforcing unique layer names.

**Comment by yhahn** [comment]
o you just define it twice? xml is so dumb : )

**Comment by yhahn** [comment]
urgl https://github.com/mapbox/tm2/blob/master/lib/style.js#L181-L185 for in layer group-by property...

**Comment by yhahn** [comment]
@samanpwbb implemented display of custom layer order in UI.
