### ISSUE TITLE
Source mode docs in UI

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#1351]
Add **Docs** tab with reference list in Studio under **Settings**, similar to in _style mode_ with CartoCSS reference. Include basic definitions of PostGIS database fields, example SQL code snippets for queries, and general trouble-shooting tips.

![image](https://cloud.githubusercontent.com/assets/4587826/5923016/2a9cbd80-a61e-11e4-9d6f-a38f65be76b0.png)

/cc @springmeyer

**Comment by wilhelmberg** [comment]
@amyleew any news on this?
We want to release a new version soon.
https://github.com/mapbox/mapbox-studio/tree/vs2015 is the branch I'm working on.

**Comment by amyleew** [comment]
@BergWerkGIS - It's good to go! Working branch: https://github.com/mapbox/mapbox-studio/pull/1387. New [PR to merge with `vs2015`](https://github.com/mapbox/mapbox-studio/pull/1436)

**Comment by wilhelmberg** [comment]
Thanks, @amyleew, looks nice.
