### ISSUE TITLE
Add inline images for comp-op documentation 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#136]
Would save a lot of time to have descriptive images attached to each option:
![screen shot 2014-02-27 at 10 19 31 am](https://f.cloud.github.com/assets/108094/2283863/9cc08d5a-9fc2-11e3-8f40-0ed6b398fd9e.png)

**Comment by tmcw** [comment]
This would be in the domain of [mapnik-reference](https://github.com/mapnik/mapnik-reference), though it would be weird to maintain thumbs there. Maybe another project that's joined with mapnik-reference. `mapnik-visual-reference` :)

**Comment by springmeyer** [comment]
Joining sounds reasonable.  `mapnik-visual-reference` sounds good, or maybe just a link to other docs - in this case that would be https://www.mapbox.com/tilemill/docs/guides/comp-op/.

**Comment by wboykinm** [comment]
That existing docs page is awesome. Link it from everywhere you can.

**Comment by samanpwbb** [comment]
Now that docs and map are both visible at the same time, inline images not important. This would be hard to make work well anyway.
