### ISSUE TITLE
after updating to 2.7 MBS fails to start

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1361]
after updating to 2.7 MBS is failing to start-up. (just the splash screen then it's gone)
Win 7 Pro 64bit
any ideas?

**Comment by wilhelmberg** [comment]
@MarkWS 

Could you post your `app.log`?
And [start Mapbox Studio from the commandline](https://github.com/mapbox/mapbox-studio/wiki/Windows-Troubleshooting#start-mapbox-studio-from-the-commandline) (both ways) to see, if we can get more information about what's failing?

**Comment by MarkWS** [comment]
did not work from the command line either.
whats the best way to send the app.log, it's rather long.

**Comment by wilhelmberg** [comment]
> did not work from the command line either.

Yes, this is expected, but did you see any additional information on the command line?
Any difference in using 
- `mapbox-studio.exe` and the program coming up, or
- `vendor\node index` and then going to http://localhost:3000 in your browser?

> whats the best way to send the app.log, it's rather long.

Every line should have time stamp.
You can remove old entries from before it started to fail and post only the ones that are current.

**Comment by MarkWS** [comment]
thanks Wilhelm,
this is what I'm getting from the command line;
![cmd](https://cloud.githubusercontent.com/assets/8440284/7775132/a4d69e82-006d-11e5-8eff-59b295297851.JPG)

**Comment by MarkWS** [comment]
as for the app.log, the last entry is from yesterday when MBS worked and before we updated, which was this morning:
<Thu, 21 May 2015 16:54:55 GMT> Mapbox Studio @ http://localhost:3000/

**Comment by MarkWS** [comment]
sorry, here it is un-formated:
Thu, 21 May 2015 16:54:55 GMT> Mapbox Studio @ http://localhost:3000/

**Comment by MarkWS** [comment]
have removed 2.7 and re-loaded 2.6 and we are still having the same problem.
There is no entry in the app.log so it's not even running through the start-up process enough to write to the app.log

**Comment by wilhelmberg** [comment]
Please verify, that no `mapbox-studio.exe` or `node.exe` processes are running.

Then, via command line:
- `cd "C:\Program Files\mapbox-studio\resources\app"`
- `vendor\node index.js`

Wait a few seconds.

Do you see `Mapbox Studio @ http://localhost:3000/`?

**If yes:**
- open your browser
- go to `http://localhost:3000/`
- does it work?

**If no:**
- share the console output
- then go to `Control Panel -> Add/Remove Programs` and share a screenshot where I can see all **`Microsoft Visual C++ <VERSION> Redistributable`s**

**Comment by MarkWS** [comment]
Thanks Wilhelm.
it did not work so here is a screen shot of the command prompt:
![capture](https://cloud.githubusercontent.com/assets/8440284/7784973/32213d36-0138-11e5-87ff-5267e0641758.JPG)

and a screen shot of Visual C++ we have loaded:
![capture](https://cloud.githubusercontent.com/assets/8440284/7784976/5e0dbc9e-0138-11e5-9dca-2964022b538f.JPG)

Thanks for your help.
Mark

**Comment by wilhelmberg** [comment]
@MarkWS 
Hm, that's strange, everything looks fine (except the error of course).

There are only two things left I can think of at the moment:

1.)
- as always, make sure, that Mapbox Studio or a part of it is not running in the background (either reboot or check for mapbox-studio.exe and node.exe processes and terminate them).
- download https://mapbox.s3.amazonaws.com/windows-builds/try-bundled-vcredist/extracted-x64-mini.7z
- extract the files and copy them into
  - `C:\Program Files\mapbox-studio\resources\app\vendor\` **and**
  - `C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\`
- try to start Mapbox Studio from the commandline (both ways [`mapbox-studio.exe` and `vendor\node index`]). Does it work?

2.)

This one is a bit time consuming, but if you are interested in finding the cause, I could provide you with a special debug version of Mapbox Studio and then guide you through the steps outlined here:
https://gist.github.com/BergWerkGIS/6385afd9f6e240eeb074
https://gist.github.com/BergWerkGIS/534a5e74301c5607af5c

**Comment by MarkWS** [comment]
What if we just remove the .mapbox-studio located in the \users folder, I think that worked last time this happened.

Then just need to re-login to the Mapbox site and reload our maps, but that’s not that big a problem.

**Comment by wilhelmberg** [comment]
> What if we just remove the .mapbox-studio located in the \users folder, I think that worked last time this happened.

Of course, that's worth a try.
Let me know, if it helped.

**Comment by MarkWS** [comment]
this worked.
so I copied out (just in case) the .mapbox-studio folder out of the \users dir.
then restarted MBS and accepted the log-in credentials. Then I had to go and re-load the projects once MBS started, not a big deal as we only have 8 active map projects.

**Comment by wilhelmberg** [comment]
Very strange. Can't image why upgrading would destroy `.mapbox-studio` folder.

Could you share the faulty `.mapbox-studio` folder, that I can replicate and pinpoint the cause?
wilhelm@mapbox.com

**Comment by wilhelmberg** [comment]
Great, that this worked!

**Comment by MarkWS** [comment]
I sure can, how should I share it? Do you have an e-mail I can just zip and send it over.

**Comment by wilhelmberg** [comment]
Yes, I do have an email. See above :smile:

**Comment by MarkWS** [comment]
Okay, it’s attached.

Mark

**Comment by wilhelmberg** [comment]
@MarkWS you obviously started two instances of Mapbox Studio at the same time.
Sometimes they interfere and leave a `app.db.compacted` behind in `.mapbox-studio` folder.

After deleting `app.db.compacted` I could start without problems.

**Comment by MarkWS** [comment]
so if this happens again just removing the app.db.compacted would do the trick?

If so that’s great, thanks Wilhelm.

Mark

**Comment by wilhelmberg** [comment]
> so if this happens again just removing the app.db.compacted would do the trick?

Yes, this is one of the first things to check.
Sorry, that I missed it, but somehow I thought, I already had suggested that, but rereading this issue proves me wrong.
