### ISSUE TITLE
Can't see my marks on the map

### ISSUE THREAD

**Issue by ebegaj** [mapbox/mapbox-studio-classic#1362]
I opened a blank source, added a CSV file and did all of the directions that i learned from your earthquake tutorial. I uploaded it to MapBox (still some issues with the 100%), opened a new project with a Map Style and changed the source to the one i uploaded and save. 

At this opened i couldn't figure out why they didn't appear on the map, so i created a new stylesheet and added the same CartoCSS as the earthquake but i changed the # earthquake to my layer's name.

Still nothing, i can't see my marks. All i want is to add a couple of CSVs and view them on Mapbox.
Here is the link to my csv: https://dl.dropboxusercontent.com/u/98742059/TrafficSignals.csv

Thank you in advance.

**Comment by springmeyer** [comment]
I tried your file locally and things look okay:

![screen shot 2015-05-23 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/20300/7785600/b23d7ee0-014b-11e5-8fdc-2b8eb14b8e9d.png)

I'm running the development build of studio installed like https://github.com/mapbox/mapbox-studio#install-from-source. It may be that this is a bug you are hitting that is fixed and just needs to trickle into an official release.

**Comment by ebegaj** [comment]
Without a map style it works. But i need a map behind them so i can see all the streets.

**Comment by ebegaj** [comment]
Alright thank you.

**Comment by wilhelmberg** [comment]
@ebegaj 
Have you styled your points correctly as markers? e.g.

```
#TrafficSignals {
  marker-width: 10;
}
```

![image](https://cloud.githubusercontent.com/assets/4549888/7824054/573c7eb2-0400-11e5-8d1e-9fc5c99fcd12.png)

**Comment by ebegaj** [comment]
@BergWerkGIS wow!! No i haven't. So what you did was to replace the earthquake CartoCSS with: 

#TrafficSignals {
  marker-width: 10;
}

?

**Comment by wilhelmberg** [comment]
@ebegaj 
I started from scratch and didn't use the earthquake example.

With these steps you should be able to reproduce (abridged version of https://www.mapbox.com/guides/source-quickstart/):
- new source project
- add `TrafficSignals.csv`
- save
- settings
  - set `Minzoom` to e.g. `6` as at lower zoom level it doesn't really make sense to have data available
  - Upload to Mapbox
- goto https://www.mapbox.com/uploads/ and wait till the source upload has finished processing
- copy the map id (click on the clipboard icon). **Your id will be different!**

![image](https://cloud.githubusercontent.com/assets/4549888/7833829/11d52134-046a-11e5-9507-6c7613e1156e.png)
- go back to Mapbox Studio
- new style project -> select e.g. `High Contrast`
- Layers -> Change Source
- append a comma **`,`** and your copied map id 
  ![image](https://cloud.githubusercontent.com/assets/4549888/7833918/e0fb1e0a-046a-11e5-8c93-9beb35b5c0c6.png)
- Apply
- edit/paste the desired style into the CartoCSS editor, e.g.

```
#TrafficSignals {
  marker-width: 10;
}
```
- save

This should give you a map like this:

![image](https://cloud.githubusercontent.com/assets/4549888/7833664/dca68b84-0468-11e5-850a-ede8088f2084.png)

If you want to publish your map on the web:
- Settings -> Upload to Mapbox
- goto https://www.mapbox.com/uploads/ and wait till the style upload has finished processing
- goto https://www.mapbox.com/styles/
- click `View map` icon to see your map in the browser 
  ![image](https://cloud.githubusercontent.com/assets/4549888/7834185/1bb183ca-046d-11e5-8989-8c165c38f174.png)

**Comment by ebegaj** [comment]
@BergWerkGIS 
You sir are my hero! Thank you!
