### ISSUE TITLE
In Mapbox Studio, when adding new layer, can't browse to network drives on Windows

### ISSUE THREAD

**Issue by bkfunk** [mapbox/mapbox-studio-classic#1368]
When looking for source files to add as new layers, the browse window only allows you to go to the C root, not to other drives.

**Comment by wilhelmberg** [comment]
Accessing other drives is in the works and should be available with the next release.

In the meantime you could try to mount that drive into a folder on `C:`, ([Technet: Assign a mount point folder path to a drive](https://technet.microsoft.com/en-us/library/cc753321.aspx))

**Comment by wilhelmberg** [comment]
Upcoming release will allow to browse to other drives.
