### ISSUE TITLE
After running Mapbox studio as administrator, program crashes and won't open again

### ISSUE THREAD

**Issue by bkfunk** [mapbox/mapbox-studio-classic#1369]
I tried running Mapbox studio as an administrator on Windows 7, and the program opened but then immediately quit. From then on, I couldn't open it even normally.

**Comment by wilhelmberg** [comment]
@bkfunk 
- Make sure via Task Manger that there are no `mapbox-studio.exe` or `node.exe` processes running.
- Then delete folder `%USERPROFILE%\.mapbox-studio` (<- paste this into the address bar of Explorer).
- Start Mapbox Studio.

Does it work now?

**Comment by bkfunk** [comment]
Works now, thanks!
