### ISSUE TITLE
Better reference for cartoCSS color operations

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#137]
_not sure if this is the right place for this_

it's easy to miss that there are more color functions that the seven on this page:

![screen shot 2014-02-27 at 11 14 41 am](https://f.cloud.github.com/assets/108094/2284526/52d8551c-9fca-11e3-86a8-7a69f71bc10b.png)

I didn't realize it until today. This section of documentation to be extended to include more examples or at least link to relevant less.js documentation: http://lesscss.org/functions/#color-operations

**Comment by tmcw** [comment]
We're missing a function or two that we should add. I don't want to link to LESS docs since confusing carto & less has been a common point of user confusion & frustration.

**Comment by ajashton** [comment]
Also needs to be fixed in the primary documentation: https://www.mapbox.com/carto/api/2.1.0/#color
