### ISSUE TITLE
Support proxy authentication (Can't connect to the MapBox API)

### ISSUE THREAD

**Issue by node4** [mapbox/mapbox-studio-classic#1372]
Have you setup proxy authentication yet? I am attaching the screenshot. 
![2015-06-04 10_44_11-mapbox studio](https://cloud.githubusercontent.com/assets/12520599/7986677/d5d7860c-0aa6-11e5-9ea0-fb3427359e33.png)

**Comment by springmeyer** [comment]
Proxy support is still in development and not in an official release. See https://github.com/mapbox/mapbox-studio/issues/860#issuecomment-73123122 for the latest dev build to help test.
