### ISSUE TITLE
Bringing layers from an existing map project into mapbox?

### ISSUE THREAD

**Issue by annacerf** [mapbox/mapbox-studio-classic#1378]
I have a map project under my account on MapBox that was made in TileMill.  I copied the Map ID into MapBox and it opens the map without any of the layers/ CartoCSS visible.  I want to make simple changes to the CartoCSS (which I have locally) to then take effect.  The map runs online but the only change that registers (and does change the online map) is changing the basemap.  Within the project, I cannot find the CartoCSS stylesheet, and if I copy and paste it into a new CartoCSS tab and change something, nothing happens.  Any ideas?

**Comment by springmeyer** [comment]
TileMill projects are not compatible with Mapbox studio. If you want to combine into a single map layers created in each application then you could use Mapbox.js to refer to each of them via tile urls. Is that helpful? For further questions like this please reach out to https://www.mapbox.com/help/.
