### ISSUE TITLE
support of mapnik 2.3.x branch 

### ISSUE THREAD

**Issue by skorasaurus** [mapbox/mapbox-studio-classic#138]
Would love to start using some of the new features in mapnik 2.3 in tm2. 

I presume you're already working on this but I hadn't seen an issue for it.

**Comment by ian29** [comment]
binary builds for mac os x come with mapnik 2.3 if you're on mac @skorasaurus

**Comment by ian29** [comment]
err, link: https://github.com/mapbox/tm2#binary

**Comment by springmeyer** [comment]
Correct, currently targeting 2.3.x for the tm2 binary builds. If you want to use mapnik master (3.x) you'll need to compile from source currently.
