### ISSUE TITLE
Crashing when uploading a shapefile

### ISSUE THREAD

**Issue by Firenze11** [mapbox/mapbox-studio-classic#1382]
Mapbox Studio crashed when I uploaded a .shp file which has a .prj file of "NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001" ( https://github.com/Firenze11/empty_public_repo )

**Comment by springmeyer** [comment]
@Firenze11 - the shapefile you posted only has a `.shp` and `.prj` but a valid shapefile also needs files ending in `.shx` and `.dbf`.

**Comment by Firenze11** [comment]
Gotcha, now it seems to work with all of the 4 files. Thanks!
