### ISSUE TITLE
mapbox-studio-win32-x64-v0.2.7 does not run

### ISSUE THREAD

**Issue by aborruso** [mapbox/mapbox-studio-classic#1384]
Hi,
I have installed mapbox-studio-win32-x64-v0.2.7 on Windows 8.1, on a 64 bit machine

When I run it, I see a window for a short time (fractions of a second), and then nothing happens.

Any suggestions for me?

Thank you

**Comment by wilhelmberg** [comment]
**[EDIT]**
The steps outlined here are **not valid for newer versions**.
Try these instead: https://github.com/mapbox/mapbox-studio-classic/issues/1466#issuecomment-141938779
**[EDIT]**

Hi @aborruso 

Please try the following:
- download this archive ([vcredist_x64-mini.7z](https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64-mini.7z)) to a place of your choice
- extract the contained DLLs to
  - `C:\Program Files\mapbox-studio\resources\app\vendor` **and** also to 
  - `C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64`

Does it work now?

**Comment by dcar5323** [comment]
I didn't post the question, but I had the same problem and this did solve my issue.  Thanks!

**Comment by wilhelmberg** [comment]
@dcar5323 Great, thanks for letting me know.

**Comment by aborruso** [comment]
@BergWerkGIS it works, thank you very much.

I'm sorry to reply so late: I missed the notification.
