### ISSUE TITLE
tm.dbcompact: Error: Could not load corrupted row

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1386]
Appveyor/windows tests have been failing since #1292 was merged.

The failing line is: https://github.com/mapbox/mapbox-studio/blob/c5c21df2b3442166bb7f82a68a60c86bac5f576e/test/tm.test.js#L81

Resulting in:

```
tm.dbcompact: Error: Could not load corrupted row: {"key":"test","val":3},
```

**Comment by springmeyer** [comment]
per https://github.com/mapbox/mapbox-studio/pull/1292#issuecomment-112691371, @BergWerkGIS is going to take a look at this.

**Comment by wilhelmberg** [comment]
no seeing this error anymore.
