### ISSUE TITLE
Loading source hangs UI

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1388]
Seen with studio latest and while viewing in Google Chrome.

To replicate:
- Download and load in this geojson file https://gist.github.com/springmeyer/6764a14744b0929736bc
- After choosing file and clicking `select` the modal closes okay
- But after that the entire UI is hung and unresponsive

Debugging indicates that `map.fitBounds` never returns https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/source.js#L363-L366.

This file has an intentionally invalid coordinate and I noticed this hang in studio (and what now appears to be leaflet) because I'm working to test potential solutions for rendering despite the invalid coordinate: https://github.com/mapbox/mapnik-vector-tile/issues/120.

Mapnik-omnivore is detecting the extent as:

``` js
extent: [ -47.109375, 0, 2.9256264171659284e+25, 65.5129625532949 ],
```

And this may be triggering some kind of infinite loop in `map.fitBounds`.

**Comment by springmeyer** [comment]
This may be another manifestation of #1254

**Comment by springmeyer** [comment]
Leaflet master does not suffer from a hang, confirmed with this test:

``` diff
diff --git a/spec/suites/map/MapSpec.js b/spec/suites/map/MapSpec.js
index eeb033f..5455a8f 100644
--- a/spec/suites/map/MapSpec.js
+++ b/spec/suites/map/MapSpec.js
@@ -154,6 +154,18 @@ describe("Map", function () {
                });
        });

+       describe("#fitBounds", function () {
+               it("will not hang on invalid bounds", function () {
+                       var container = document.createElement('div'),
+                               map = new L.Map(container);
+                       expect(function () {
+                               map.fitBounds([-47.109375, 0, 29256264171659283709034496, 65.5129625532949]);
+                       }).to.throwException(function (e) {
+                               expect(e.message).to.eql("'undefined' is not an object (evaluating 'this._northEast.lat')");
+                       });
+               });
+       });
+
        describe('#setMaxBounds', function () {
                it("aligns pixel-wise map view center with maxBounds center if it cannot move view bounds inside maxBounds (#1908)", function () {
                        var container = map.getContainer();
```

**Comment by springmeyer** [comment]
clamping bounds fixes this (will commit fix in a moment). Confirmed that clamping bounds does not fix https://github.com/mapbox/mapbox-studio/issues/1254#issuecomment-113335328 so that issue is not directly related/not the same.

**Comment by laurenancona** [comment]
This just started happening to me yesterday, and now Studio 0.2.7 is occasionally unresponsive on load. Notably, this began after firing up a local server on 7000 for an Angular app in development with Browsersync - Studio was open and it got booted into Chrome, overriding the other app.

**Comment by laurenancona** [comment]
The Angular app _is_ using leaflet/mapbox.js (with some workarounds to keep directives from swallowing events). Not sure if that's at all relevant, but thought it worth mentioning.

**Comment by springmeyer** [comment]
Hi @laurenancona! Hmm, I cannot think of how an angular app running on 7000 would bother studio on 3000. Let me know if you find out any more info.

**Comment by laurenancona** [comment]
Thanks, @springmeyer! 
So it turns out, after some testing, that my problematic sources are really just any project I've tried to set custom layer order. Tried all permutations of closed/open/restart when editing YAML, listing every avail layer, only some layers, etc. Whenever a custom order is assigned, Studio crashes trying to open the project. Example styles where this has happened: `laurenancona.95b33dda` & `laurenancona.e8146fe3`

**Comment by wilhelmberg** [comment]
@laurenancona are you still experiencing these problems?

I couldn't find the mentioned ids (`laurenancona.95b33dda`, `laurenancona.e8146fe3`), neither as style nor as source.

I tried some of your sources with the latest dev build of Mapbox Studio and they work fine:

![image](https://cloud.githubusercontent.com/assets/4549888/9488278/09f7fa5c-4bd9-11e5-8bf4-1db2562ef5e4.png)

Could you point me to an ID, that doesn't work for you, that I can replicate?
