### ISSUE TITLE
Mapbox Studio won't upload Map Style

### ISSUE THREAD

**Issue by urbanikj** [mapbox/mapbox-studio-classic#1391]
I have paid for the standard plan and when I try and upload a map style it tell me it won't do it because I need to upgrade my plan.  I have no map styles uploaded at this point.  This is ridiculously frustrating - I am using the latest version of Mapbox Studio and I would like to know what the problem is and how to fix this asap.  Thank you.

**Comment by ajashton** [comment]
Hi @urbanikj - for issues related to your account please email help@mapbox.com and provide your Mapbox username. Someone will be able to look into things from there. Sorry for the trouble.
