### ISSUE TITLE
Crashes randomly at different times, with local sources - windows 7 64bit

### ISSUE THREAD

**Issue by freewheelCarto** [mapbox/mapbox-studio-classic#1394]
I am running in to an issue where Mapbox Studio crashes at random times, but consistently.  Often, it occurs when trying to upload a local source to Mapbox account, but sometimes it crashes during any part of using the 'local source' functionality. Using shapefiles as the source. 

I have uninstalled and installed.  I looked through other issues that mentioned crashing.  I've run Studio as admin and on my regular work domain/user.  I tested with small shapefiles, same result.  Only got one successful upload to Mapbox without Studio crashing, out of approximately 20 attempts. 

Nothing is written to the app.log in C:\Users<YOUR-USER-NAME>.mapbox-studio. 

Is there something in my source that could be causing this?  Shapefiles were modified and saved via QGIS.

**Comment by springmeyer** [comment]
First thing to try would be to reproject your shapefiles to EPSG:3857 or EPSG:4326. Then try loading into a fresh project. Let me know if you still experience crashes after doing that. The reason I recommend this is we are aware of a crash possible on windows during reprojection from source projections that are not the two above.

**Comment by wilhelmberg** [comment]
@freewheelCarto 

You can reproject your shapefiles in QGIS: 
- `right click on layer -> Save as...` 
- click on the icon that looks like a globe with a hat on it
- type `3857` in the new dialog
- click `WGS84 / Pseudo Mercator` -> `OK`

The `Save vector layer as...` should then look like this:
![image](https://cloud.githubusercontent.com/assets/4549888/8352025/4f3a3b34-1b32-11e5-8639-4f90cb5561c6.png)

Or, if you prefer the command line:

```
ogr2ogr -f "ESRI Shapefile" your-input.shp webmerc-output.shp -t_srs EPSG:3857
```

Also, could you share one of your smaller shape files, that we can take a look at the file and its projection?

**Comment by freewheelCarto** [comment]
Thanks for the responses, Indeed my sources are in different projection. I will save as the recommended and confirm if that solves my issues.

**Comment by freewheelCarto** [comment]
This appears to have solved the issue.  Thanks, closing issue.

**Comment by springmeyer** [comment]
Great to hear. Thanks for testing @freewheelCarto. For now I'm going to re-open this issue as the crash when reprojecting is not yet fixed. Will close this once we have a solution to that over at https://github.com/mapbox/mapnik-vector-tile/issues/127.

**Comment by wilhelmberg** [comment]
Cause of reprojecting crash was fixed in proj4:
https://github.com/OSGeo/proj.4/commit/2b5b97942016c2f18a0992b934d1b6b460391dac
