### ISSUE TITLE
README.md for sources/mbstreets

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#14]
How would you feel about an in-depth README.md at `sources/mbstreets/README.md` ? I think at some point we can probably at UI integration for reading and rendering such files for datasources.

To start, though, it would be a good place to point people who want more details beyond the source helptext.

**Comment by ajashton** [comment]
[Started](https://github.com/mapbox/tm2/blob/master/sources/mbstreets/README.md), will continue to add/refine info.

![](http://www.textfiles.com/underconstruction/mimidohttcimagesunder-construction-header.ani.10.gif)

**Comment by yhahn** [comment]
FYI there is a v3 schema source added now, I copied over v2s readme. Would be good to update this as well, and maybe UPGRADE.md or so.
