### ISSUE TITLE
Application suddenly quits when uploading source

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-studio-classic#1401]
Mapbox Studio quits any time I hit the “Upload to Mapbox” button on a local Postgres-backed source (not every source, however). The application doesn’t crash; this is the only thing printed to the console:

```
2015-07-06 12:16:50,336 com.apple.xpc.launchd[1]: (com.mapbox.mapbox-studio.41212[30955]) Service exited with abnormal code: 8
```

Mapbox Studio 0.2.7 on OS X 10.10.4.

**Comment by springmeyer** [comment]
This is a known bug in 0.2.7, was fixed in https://github.com/mapbox/mapbox-studio/pull/1199, and will be working in 0.2.8

**Comment by springmeyer** [comment]
specifically the bug was that for complicated reasons we cannot know the extent of postgis local source layers, and now this crash is avoided by defaulting to the global extent at https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/source.js#L333
