### ISSUE TITLE
Avoid breakage when Visual Studio 2015 installed

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1404]
The current release of Mapbox Studio v0.2.7 includes libraries internally that depend on Visual Studio 2014 CTP 4. This is fine is most cases. The libraries are installed on the system when the Mapbox Studio installer runs. And then Mapbox studio can use them and benefit from high performance rendering features that leverage the C++11 Standard (only available in pre-release Visual Studio versions).

However Microsoft has:
- Now released a Visual Studio 2015 RC (release candidate), and;
- Will be releasing official Visual Studio 2015 on [July 20](http://blogs.windows.com/buildingapps/2015/06/29/release-dates-and-compatibility-visual-studio-2015-and-windows-10-sdk/)

Both of these installations conflict with the 2014 CTP libraries Microsoft previously released. This is not fun, but expected. So, if anyone installs Visual Studio 2015 then Mapbox Studio will no longer open.

@BergWerkGIS and I have been working hard to anticipate this breakage and prepare the foundations for a new Mapbox Studio release that will work seamlessly with both:
- A Clean/vanilla Windows systems that do not have Visual Studio (of any version) installed, and;
- Windows systems that have either Visual Studio 2014 or 2015 already installed.

So, the upcoming Mapbox Studio v0.2.8 will fix this. For users who have a broken install of Mapbox Studio currently please share the details below of what Visual Studio version you have installed and we'll try to help you troubleshoot.

**Comment by wilhelmberg** [comment]
Till the next release is out, **a _temporary_ workaround for Mapbox Studio _0.2.7 64bit_ is to**:
- download https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64-mini.7z
- extract `vcredist_x64-mini.7z` to a temporary folder, e.g.: `C:\MBSDLLs` (can be deleted afterwards)
- copy all DLLs from `C:\MBSDLLs` into

```
C:\Program Files\mapbox-studio\resources\app\vendor
```
- copy all DLLs from `C:\MBSDLLs` into

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64
```

**Comment by slibby** [comment]
@BergWerkGIS That workaround worked like a charm for me - thanks for updating the issue.

**Comment by wilhelmberg** [comment]
@slibby Perfect!
Thanks for lettings us know, that this worked for you.

**Comment by P4z** [comment]
Thanks for this _quick'n'dirty_ but **useful** workaround, @BergWerkGIS ! Hope to see new release very soon.

In the meantime I created a very simple installation package as my NSIS homework for even easier application of your solution. The [libraries archive](https://crazy-tronners.com/P4/mapbox/mapbox.v0.2.7.x64-VS2014CTP4.7z) is available as a [self-extracting binary](https://crazy-tronners.com/P4/mapbox/mapbox.v0.2.7.x64-VS2014CTP4.exe) by [this](https://crazy-tronners.com/P4/mapbox/mapbox.v0.2.7.x64-VS2014CTP4.nsi) NSIS script thanks to the [Crazy Tronners](https://crazy-tronners.com). :)

**Comment by springmeyer** [comment]
noting that https://github.com/mapbox/mapbox-studio/compare/vs2015 is the branch that @BergWerkGIS  has been working on that will solve this and with the latest commit we've moved to node v0.10.40 and all tests are passing on travis and windows /cc @GretaCB @flippmoke

**Comment by wilhelmberg** [comment]
For workaround with current 0.2.7 see [above](https://github.com/mapbox/mapbox-studio/issues/1404#issuecomment-127011952).

Next release will include needed files.
