### ISSUE TITLE
Can´t open mapbox-studio in Win 7 64bits

### ISSUE THREAD

**Issue by sagazluiz** [mapbox/mapbox-studio-classic#1406]
------ WHAT'S YOUR ENVIRONMENT?
I'm on a French Windows 7 Enterprise 64bit.
I downloaded the 64bit installer, version 0.2.7,
from https://www.mapbox.com/mapbox-studio/

------ WHAT'S YOUR DATA?
I have no data

------ WHAT HAVE YOU DONE SO FAR?
All the following steps
https://github.com/mapbox/mapbox-studio/wiki/Windows-Troubleshooting
.

------ WHAT DO YOU WANT TO ACHIEVE?
How can I fix and start it?

------ LOG
Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\r337555>cd "C:\Program Files\mapbox-studio

C:\Program Files\mapbox-studio>mapbox-studio.exe

C:\Program Files\mapbox-studio>[5832:0711/073611:INFO:CONSOLE(0)] <Sat, 11 Jul 2
015 10:36:11 GMT> Mapbox Studio exited with 3221225785.
[7224:0711/073611:WARNING:ipc_channel_win.cc(309)] Unable to create pipe "\.\pi
pe\chrome.5832.0.192276493" in client mode: O sistema nÒo pode encontrar o arqui
vo especificado. (0x2)
cd "C:\Program Files\mapbox-studio\resources\app"

C:\Program Files\mapbox-studio\resources\app>vendor\node index.js

**Comment by wilhelmberg** [comment]
@sagazluiz thanks for your detailed report.

Please try this:

Make sure via Task Manager that no `mapbox-studio.exe` or `node.exe` processes are running.
If there are, and you already have exited Mapbox Studio please kill them via right click in Task Manager.

1.) download
https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64-mini.7z

2.) extract `vcredist_x64-mini.7z` into 
C:\Program Files\mapbox-studio\resources\app\vendor

3.) extract `vcredist_x64-mini.7z` into 
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64

If the above steps don't work, delete this folder:
`C:\Users\<YOUR-USER-NAME>\AppData\Roaming\mapbox-studio`

Any success?

**Comment by sagazluiz** [comment]
Hi BergWerkGIS, 
Thank you so much for your attention! It worked.
