### ISSUE TITLE
Studio hangs trying to render line-geometry-transform: skewX(90);

### ISSUE THREAD

**Issue by cleversprocket** [mapbox/mapbox-studio-classic#1409]
I have no idea what `line-geometry-transform: skewX(90);` will actually look like, I was just plugging in different values to see what it does. I had to remove the line in the .mss file so Studio could work again.

**Comment by springmeyer** [comment]
@cleversprocket - thanks a ton for the report. That should definitely not hang. I've replicated the problem locally and will be fixing shortly.

**Comment by artemp** [comment]
@springmeyer @cleversprocket - this is fixed in mapnik-core : 
https://github.com/mapnik/mapnik/commit/6d6cb15b4547539152c488fb7bfe7f9506c48d9a
