### ISSUE TITLE
arcgis to mapbox studio

### ISSUE THREAD

**Issue by llc12300913** [mapbox/mapbox-studio-classic#1414]
Hello everyone,i am a beginner of mapbox studio.i want to import shp file in the mapbox studio,but a error "vector layer[0] id must be a string of 255 characters or less" upon to me.
How can i solve this problem?

**Comment by springmeyer** [comment]
Hi there @llc12300913 - sorry about the problem, but thanks for reporting it here. Would it be possible to share the shapefile you are hitting this with? You can get in touch by email with me at dane@mapbox.com

/cc @geografa

**Comment by llc12300913** [comment]
Thanks for the reply! I've resolved the problem.The reason is my shp file name consists of numbers.

**Comment by geografa** [comment]
Glad to hear @llc12300913 ! Added this to our list of error message improvements.

**Comment by animaux** [comment]
Same goes for geojson.

**Comment by jameslaneconkling** [comment]
specifically (for those who run into this issue), the error is thrown when the file begins w/ a number, so prepending any letter should fix it.
