### ISSUE TITLE
Adding in web fonts

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#1415]
We have been asked if we can use this font for some features listed on the map.
https://www.google.com/fonts/specimen/Roboto
Does anyone know if MBS allows an outside font call? If so please help.
Thanks, Mark

**Comment by wboykinm** [comment]
@MarkWS We've been using custom fonts via static .otf files. I see that Google makes [Roboto .ttf files available here](https://github.com/google/roboto/tree/master/out/RobotoTTF), and they should work as well. Basically place them in the `projectname.tm2/fonts/` folder and then they'll be packaged and served along with the rest of the style.They've got [some good documentation on this](https://www.mapbox.com/blog/mapbox-studio-custom-fonts/)

**Comment by MarkWS** [comment]
this will work for now. this would be a nice feature to have as we have a client that pays for fonts on Fonts.com and thats tracked by a URL and a user key. but for now this will work. Thanks Bill.

**Comment by wboykinm** [comment]
:+1:

**Comment by ajashton** [comment]
>  this would be a nice feature to have as we have a client that pays for fonts on Fonts.com and thats tracked by a URL and a user key

Unfortunately web font licensing and distribution systems are not compatible with Mapbox Studio, which is much more comparible to Photoshop than HTML & CSS as far as font rendering is concerned. Web fonts are licensed to be temporarily stored on the computer of the person viewing the website, but custom fonts for Studio styles need to be stored on the servers that are generating the tile images.
