### ISSUE TITLE
How to show the labels of aeroways like Openstreetmap in Mapbox Studio

### ISSUE THREAD

**Issue by conmanet** [mapbox/mapbox-studio-classic#1419]
I'm using Mapbox Studio to create a Mapbox style.

However, I don't know how to show the labels of aeroways like [Openstreetmap](http://www.openstreetmap.org/#map=16/16.0520/108.2044).

You can see the labels are showing on the right side.

![The labels are showing on the right side](http://i.stack.imgur.com/eTJc4.jpg)

**Comment by arifklk** [comment]
It seems not possible for now because there is no defined "Runway Name" data type imported to Mapbox interface.

Maybe you can create a custom data which includes only Aeroway names and you can use it as an additional source layer.

**Comment by conmanet** [comment]
@arifklk Do you know how to do that?

> "Maybe you can create a custom data which includes only Aeroway names"

**Comment by arifklk** [comment]
It depends what kind of data do you need but you are gonna need some GIS software experience. For example if you need just one or two airports, you can create your own file with Google Earth or QGIS. Or maybe you can get a total planet data or World Roads data etc. and delete the data other than Aeroway Roads.

Maybe more practical ways could be generated. But as I said it is totally up to data type you need.

**Comment by planemad** [comment]
@conmanet you can export the data from OSM itself with the name and ref tags like http://overpass-turbo.eu/s/aM0

Then create a new datasource with it in Studio, and include it in your style project for styling. You can use this guide for help: https://www.mapbox.com/guides/source-quickstart/
