### ISSUE TITLE
MapBox Studio (mapbox-studio-win32-x64-v0.2.7.) won't open

### ISSUE THREAD

**Issue by cbdunc2** [mapbox/mapbox-studio-classic#1423]
Hello!

Upon opening mapbox studio my cursor shows the loading sign, then a dialog box opens and closes immediately (no text can be seen in the box). 

I have un-installed and re-installed with my intial download as well as re-downloaded and re-installed. Problem persists. 

Any ideas? 

Thanks in advance for the help.

**Comment by wilhelmberg** [comment]
Let me know, if this helps:
https://github.com/mapbox/mapbox-studio/issues/1406#issuecomment-120710691

**Comment by cbdunc2** [comment]
Hmmmm. Sorry I didn't see that topic - however I am getting this error:

!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\appcrt140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\concrt140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\desktopcrt140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\msvcp140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\vcamp140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\vccorlib140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\vcomp140.dll
    Access is denied.
!   C:\Users\Cameron\Downloads\vcredist_x64-mini.7z: Cannot open C:\Program Files\mapbox-studio\resources\app\vcruntime140.dll
    Access is denied.

I deleted the folder mentioned as well. Any ideas? I can't find an "extract as admin" option.

**Comment by wilhelmberg** [comment]
Try to extract the files to a temporary folder and then copy them.
This should give you an UAC prompt.

**Comment by cbdunc2** [comment]
Hmmm. I extracted into a temp folder then copy&pasted the files (vcamp140.dll, vccorlib140.dll, vcomp140.dll and vcruntime140.dll) into the two locations and delted the roaming folder. Now I get the same dialogue box but with a loading icon for about 1/2 a second then it closes. Any more suggestions?

Thanks so much for your help.

**Comment by wilhelmberg** [comment]
There are 8 files in the download:

```
appcrt140.dll
concrt140.dll
desktopcrt140.dll
msvcp140.dll
vcamp140.dll
vccorlib140.dll
vcomp140.dll
vcruntime140.dll
```

Did you copy them all or just the four you mentioned?
All 8 have to be copied into both folders:

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64
C:\Program Files\mapbox-studio\resources\app\vendor
```

You can leave the roaming folder as is, don't delete it.

**Comment by cbdunc2** [comment]
Berg - great I didn't see the other 4 files!

It appears to be working now. Thanks!

Cameron

**Comment by wilhelmberg** [comment]
:+1:
