### ISSUE TITLE
Mapbox Studio Crashes on Windows 10

### ISSUE THREAD

**Issue by andmimey** [mapbox/mapbox-studio-classic#1424]
Window appears and then disappears. Does not work under compatibility mode, either.

**Comment by springmeyer** [comment]
See https://github.com/mapbox/mapbox-studio/issues/1423 for the potential problem and solution in the near term.

**Comment by andmimey** [comment]
Wow - thank you!

**Comment by wilhelmberg** [comment]
Perfect!
Thanks for reporting back.
We hadn't had a chance yet to test on Windows 10.
