### ISSUE TITLE
Mapbox-studio crashes when opening it

### ISSUE THREAD

**Issue by k1wiosm** [mapbox/mapbox-studio-classic#1425]
I am running Windows 10 64-bits, athough this was ocurring also before updating from Windows 8.1 64-bits.

As soon as I run the app, it crashes. I have tried running it from console and I get this:

> Mapbox studio exited with 3221225785

When trying 'vendor\node index.js' I get an alert saying this. Nothing on console:

> The procedure entry point __vcrt_UnhandledException could not be located in the dynamic link library C:\Program Files\mapbox-studio\resources\app\vendor\node.exe

**Comment by wilhelmberg** [comment]
@k1wiosm please try this https://github.com/mapbox/mapbox-studio/issues/1404#issuecomment-127011952 and tell me if it works for you?

**Comment by k1wiosm** [comment]
It works! 

Thank you

**Comment by wilhelmberg** [comment]
Perfect!
Thanks for letting me know.
