### ISSUE TITLE
Windows 8.1 Mapbox Studio hangs on install

### ISSUE THREAD

**Issue by ksweetie** [mapbox/mapbox-studio-classic#1426]
I'm trying to install mapbox-studio-win32-x64-v0.2.7.exe on Windows 8.1, and it's hanging close to the end of the setup. Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/2036284/9151107/34e1c4e4-3dbc-11e5-9019-49c0cdac7ea6.png)

I tried running the installer as Adminstrator with the same results. Any ideas?

**Comment by wilhelmberg** [comment]
@DynamicDyno Never seen this exact installer hang before, but do you have `Visual Studio 2015` or the `2015 C++ Redistributable / vcredist` installed?
We are experiencing some problems when the above software is installed.
We are working hard on a new release to avoid this.

As a workaround could you try this:

1.)
Run installer till it hangs

2.) 
Copy folder `C:\Program Files\mapbox-studio` to a temporary folder, e.g. `C:\MBS-TEMP`.

3.)
Cancel the installer.

4.)
Copy the install folder from `C:\MBS-TEMP` back into `C:\Program Files\mapbox-studio`

5.)
Follow the instructions outlined here:
https://github.com/mapbox/mapbox-studio/issues/1404#issuecomment-127011952

Does it work now?

**Comment by wilhelmberg** [comment]
Upcoming release will not have this `vcredist` install problem.
