### ISSUE TITLE
Mapbox v 0.2.7 flashes on start then exits

### ISSUE THREAD

**Issue by deepankverma** [mapbox/mapbox-studio-classic#1429]
Hi,
I tried to use mapbox v0.2.7, but the application keeps on flashing for 1 second before disappearing again on running .exe. I'm using win 8.1.
I've also tried it on Mac and win 7.

WIN 7: In this case there is no flashing of window, but a blank window appears  which stays as it is in one of the PC.
In another PC, Window shows content, but on clicking "connect" it shows error that it can't connect to services. "failed to get API" or something.

Mac: The same flashing problem.

Mapbox was working good earlier, After I installed new Visual Studio, I think it stopped working since then. But even after removing visual studio, application failed to work. Also, here in institution all connections are behind proxy.

I tried installing it by command line. which shows log:

![capture](https://cloud.githubusercontent.com/assets/10321898/9251721/38ff5250-41f2-11e5-8879-6343548aa96d.PNG)

**Comment by wilhelmberg** [comment]
@deepankverma, you are hitting two known issues:

1.)
An install of new Visual Studio 2015 breaks Mapbox Studio 0.2.7.
A workaround is described here:
https://github.com/mapbox/mapbox-studio/issues/1404#issuecomment-127011952

Also, Mapbox Studio 0.2.8, that should not have any problems with VS2015 installed, will be out during the next weeks.

2.)
Proxies are a problem as Mapbox Studio relies on modules that are not maintained by us and do not support proxies properly.
You will have to start Mapbox Studio once without proxy to authorize.
Link and instructions here:
https://github.com/mapbox/mapbox-studio/issues/1393#issuecomment-119874790

Don't forget to set `HTTP_PROXY` and `HTTPS_PROXY` and to start Mapbox Studio from the commandline, when using the special `mapbox-studio-win32-x64-proxy-tilejson-with-request` version.

**Comment by deepankverma** [comment]
Yeah workaround did just fine. Thanks a lot for that.
But with proxy thing, still no success.
Will this new version of studio allow proxy connections?

**Comment by wilhelmberg** [comment]
Yeah, proxies are still a problem.

Currently, to work through proxy, you have to use [this special build](https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x64-proxy-tilejson-with-request.exe) as desribed here: https://github.com/mapbox/mapbox-studio/issues/1393#issuecomment-119874790

Upcoming version will include the fixes of the special build.
**One problem remains:** first start of Mapbox Studio has to be done without proxy.
Afterwards it will work fine through proxy.

The `first start problem` won't be solved with the next release, as we have to get patches into those upstream modules:
https://github.com/ciaranj/node-oauth
https://github.com/jaredhanson/passport
https://github.com/jaredhanson/passport-oauth2
