### ISSUE TITLE
use consistent button styles

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#143]
We should stay consistent with button styles/meanings. Seeing three hierarchy levels: 
1. blue (use rarely - an action that makes significant changes)
2. gray background (middle - an action that can be undone)
3. no background (reconfigures ui, does other trivial things)

**Comment by samanpwbb** [comment]
Pretty much set here.

**Comment by samanpwbb** [comment]
@edenh do you have thoughts on this?

**Comment by edenh** [comment]
I like the idea of a hierarchy of button styles, but binding them specific actions/meanings can be limiting sometimes.

**Comment by samanpwbb** [comment]
@edenh agreed - something to keep in mind. One thing I like about the tm2 UI is that it is very quiet and feels technical - it harkens to other tools made for extended use, like Photoshop or Sublime Text. I think we want to maintain that vibe. (I broke this rule hard with my fill blues, I know). The easy way to add emphasis to buttons is to add color, but we should try to resist this.

**Comment by edenh** [comment]
Cool, I'll get that fill-blue out of the close docs button. As someone who is relatively new to this interface, I was mostly reacting to interactions that felt fuzzy.

**Comment by edenh** [comment]
https://github.com/mapbox/tm2/commit/f4e2c2450e062fe6a1c7a44a74cb20a00afa8a84
