### ISSUE TITLE
Fix all buttons

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#1446]
Add `button` style class to all buttons in Studio

/cc @flippmoke

**Comment by katydecorah** [comment]
@amyleew I found and fixed a couple buttons in #1445

**Comment by amyleew** [comment]
nice thanks @katydecorah

**Comment by wilhelmberg** [comment]
@amyleew any buttons left?
I'm currently working on this branch
https://github.com/mapbox/mapbox-studio/tree/v0.2.8-alpha

**Comment by amyleew** [comment]
Looks good @BergWerkGIS

**Comment by wilhelmberg** [comment]
Thanks :+1:
