### ISSUE TITLE
why can't I export tiles to local disk?

### ISSUE THREAD

**Issue by wsf1990** [mapbox/mapbox-studio-classic#1453]
I use the Mapbox Studio on windows, But I can't export the tile data to local disk?Dose it must work on the server?

**Comment by wilhelmberg** [comment]
@wsf1990 any error message?

**Comment by wsf1990** [comment]
I cant find the function or the menu to export,Do you have the usage of studio?Many Thanks!

**Comment by wilhelmberg** [comment]
Links to tutorials are on the main page of this repository:
https://github.com/mapbox/mapbox-studio#getting-started

You can export vector tiles from a Source Project (after saving):

![image](https://cloud.githubusercontent.com/assets/4549888/9850770/25f85c08-5af5-11e5-9894-c6a9ffe7def0.png)

**Comment by wsf1990** [comment]
Thanks！I'll try it next day!Thanks

**Comment by wsf1990** [comment]
Dear BergWerkGIS：
 I have tried to export,It's success,but why this mbtiles just have raster tile not vector tile?the table of grid_data is empty.Dose it need any settings?

**Comment by wilhelmberg** [comment]
> why this mbtiles just have raster tile not vector tile?

I'm not quite sure I understand correctly, but are you saying that there are raster tiles in the exported mbtiles?

There shouldn't. It should contain vector tiles only, as you exported from the Source Project.

If you want to get raster tiles, you might want to look into @mojodna 's [tl](https://github.com/mojodna/tl).

You can pass an Mapbox Studio Style Project to it and get raster tiles:
https://github.com/mojodna/tl#usage

**Comment by wsf1990** [comment]
Thanks!
I means when I exprot mbtiles and download to local disk,I open the mbtiles by sqlite program,But I found that the view of grid_data is empty,Is this view stored vector tiles?the view of tiles have the data of raster tiles,So I suppose that can it export vector tiles!
Thanks!
