### ISSUE TITLE
v0.2.8 missing assets on S3

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-studio-classic#1456]
- [Some hours ago](https://github.com/mapbox/mapbox-studio/commit/aaa51902f114c73f4a31f15e5211c3ec87ec93f8) we changed the download link on https://www.mapbox.com/mapbox-studio/ to the new `v0.2.8`.
- As reported [on twitter](https://twitter.com/phirate/status/644095720903958528) and verified by me, there was no asset for `v0.2.8` on S3 though, thus leading to a broken download
- I've rolled back to `v0.2.7` via https://github.com/mapbox/mapbox-studio/commit/fd41e34f4ec072e88410279c7f7047d973761187 which fixed downloads
- @GretaCB  you got this?

**Comment by wilhelmberg** [comment]
Fixed!

@GretaCB FYI:

you tagged correctly and used the commit sha for that tag, but the build scripts use the GITSHA provided in the commit message and not the latest tag.
Thus creating downloads like `mapbox-studio-win32-x64-c63610c1141e292f2f8fbfb9e76ec3e1e8324800.exe`.

GITSHA in commit message can be branch name, commit sha or tag.

Correct commit message would have been: `[publish v0.2.8]`.

**Comment by GretaCB** [comment]
Thanks for jumping on this @freenerd and @BergWerkGIS!
