### ISSUE TITLE
Unable to add two custom layers in project.yml

### ISSUE THREAD

**Issue by flemmens** [mapbox/mapbox-studio-classic#1460]
I have two custom layers saved in pbf mbtiles. Everything is working fine if I use a single layer:
source: "mbtiles:/home/data/a.mbtiles"

However, when I try to use two layers, I got the following error message:
source: "mbtiles:/home/data/a.mbtiles,mbtiles:/home/data/b.mbtiles"
Error: SQLITE_CANTOPEN: unable to open database file

I tried several notations:
source: "mbtiles:/home/data/a.mbtiles,/home/data/b.mbtiles"
source: "mbtiles:/home/data/a.mbtiles,home/data/b.mbtiles"

But I always got the same error. If I use
"mbtiles:/home/data/a.mbtiles,b.mbtiles"
I got no error but nothing is loaded and my tiles are empty (actually it creates an empty file "a.mbtiles,b.mbtiles" so it does not recognize the 2 files.

What is the proper notation to mention two or more custom files in the project.yml ?

**Comment by wilhelmberg** [comment]
@flemmens are your sure, it works with 1 mbtiles file?
I couldn't even get it work with 1 on Windows or Linux and 0.2.7 or 0.2.8.
Which version are you using?

**Comment by flemmens** [comment]
Yes it works fine with a single mbtiles. However I use studio only to create the mbtiles, the render is done on my server with tilelive-vector and some other mapbox/mapnik components so I am not sure which one cause the error. What is the right syntax to add several custom layers in the project.yml ?
When using mapbox served tiles, you can use a comma to separate the layers, it seems this does not work with local sources.

**Comment by wilhelmberg** [comment]
I don't think this is going to work that way (2 mbtiles in `source` of `project.yml`).

You'd probably have to have an instance of `tilelive-vector` for each mbtiles file, then merge the resulting vector tiles and then do the styling/rendering.

**Comment by flemmens** [comment]
I also tried with several "Layer" sections in the project.yml but it does not work either. To have multiple instances of tl-vector is not really an option, actually this is what I was doing until now but it is not efficient, and if it works with multiple mapbox hosted sources, it should work also with local sources as the render process is the same. I probably will have to check and update the source code directly then, thanks anyway.

**Comment by wilhelmberg** [comment]
@flemmens I asked the `tilelive-vector` pros: it is not possible to pass in 2 mbtiles at once.
You have to merge them together yourself.
This is also how it is done when specifying multiple mapbox hosted sources: they are combined on the server.

**Comment by flemmens** [comment]
Ok thanks, in the meanwhile I found a simple solution using tilelive-merge, so the work is done in the background and I can use a single project and style sheet. However it should probably be a good thing to have the possibility to add more than one mbtiles source as this is a very common situation to use multiple sources to render a map.
