### ISSUE TITLE
Mapbox Studio Classic v0.28 doesn't open project file

### ISSUE THREAD

**Issue by Forna73** [mapbox/mapbox-studio-classic#1463]
Hi!
Just after update to v0.28 from 0.27 I can't open my project anymore.
The error message is: Couldn't open file at C:\Users.....\project.yml

**Comment by wilhelmberg** [comment]
Does this happen, when you click on the list of previously opened projects, or if you browse to the project via `Browse`?

**Comment by Forna73** [comment]
Hi!
Both of them!

Il 17/09/2015 12:12, Wilhelm Berg ha scritto:

**Comment by wilhelmberg** [comment]
Strange, I couldn't replicate this with my projects (downgraded and upgraded to verify).

Style and Source Projects?

Do you have spaces in your path?
That shouldn't be a problem, but could you try to move the project folder into another folder with no spaces, just to verify?
e.g. into `C:\testproject\`

**Comment by Forna73** [comment]
Hi!
Any space in file name nor in project name.
I tried to move the folder but nothing.
I just installed the 0.30 and nothing...
I didn't try to downgrade cause I don't know how to get the 0.27.

2015-09-17 16:46 GMT+02:00 Wilhelm Berg notifications@github.com:

**Comment by wilhelmberg** [comment]
Hm, any special characters in path of file names maybe?

Any chance you could share your project, that I can have a look at it?
You can make it available as download somewhere or send it to me: `<MY-FIRST-NAME> AT mapbox DOT com`.

In case you want to check with old `0.2.7`:
https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x64-v0.2.7.exe

**Comment by Forna73** [comment]
I opened the files with notepad++ and with the new mapbox I restarted 
from scratch copying and pasting the rules I wrote.
... so I have a fresh file.

Il 18/09/2015 13:22, Wilhelm Berg ha scritto:

**Comment by wilhelmberg** [comment]
Do I understand correctly, that you re-created `project.yml` by copying the contents of it into a new `project.yml`?
And that solved the error?

**Comment by Forna73** [comment]
I started a New project, created the styles and pasted the content of each
one  by copying the rules with notepad++ and saved the project.
Il 19/set/2015 10:08, "Wilhelm Berg" notifications@github.com ha scritto:

**Comment by wilhelmberg** [comment]
Interesting, never had this before.
Thanks for letting us know, should I ever occur again.
