### ISSUE TITLE
Cannot upgrade to 0.3.1

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-studio-classic#1468]
@flippmoke Mapbox Studio Classic is telling me to upgrade to 0.3.1

![image](https://cloud.githubusercontent.com/assets/2180540/10046589/91cc5400-61d7-11e5-9cbd-de55610d588d.png)

But the website is still on 0.3.0

![image](https://cloud.githubusercontent.com/assets/2180540/10046566/782f829c-61d7-11e5-8c96-afbf20572a54.png)

**Comment by flippmoke** [comment]
This was my mistake, we ran into a problem mid release with l linux where it failed to run and I thought I had reversed this... I guess it did not, I am looking to solve this ASAP

**Comment by flippmoke** [comment]
@katydecorah this should be fixed now
