### ISSUE TITLE
Mapbox Studio v0.3.1 application for Windows 64 bit appears to start with a spinning indicator but then it immediately closes

### ISSUE THREAD

**Issue by linnybsailor** [mapbox/mapbox-studio-classic#1471]
PROBLEM: I open the Mapbox Studio v0.3.1 application. It appears to start with a spinning indicator in the application box but then it suddenly closes. Repeat attempts to open have the same result

I have uninstalled and reinstalled. Problem still persists.

Cheers,
LB

------ WHAT'S YOUR ENVIRONMENT?
Windows 7 - 64bit
I downloaded the 64bit installer, version 0.3.1
from https://www.mapbox.com/mapbox-studio-classic/#win64

------ WHAT'S YOUR DATA?
No data yet

------ WHAT HAVE YOU DONE SO FAR?
I have followed the trouble shooting steps from this thread #1406 (comment) and made sure I had all 8 files from the download https://github.com/mapbox/mapbox-studio-classic/issues/1423 

-and-

Tried the following from https://github.com/mapbox/mapbox-studio-classic/wiki/Windows-Troubleshooting   --Section "Things to Try"

Start Mapbox Studio from the commandline
- Same issue, app closes immediately
  Message: 
  server process pid 5772 
  Renderer process started
  Mapbox-studio exited normally

If the above did not work, try:
type cd "C:\Program Files\mapbox-studio\resources\app", ENTER
type vendor\node index.js, ENTER

Message: 
node.exe - Entry Point Not Found
The procedure entry point_telemetry_main_invoke_trigger could not be located in the dynamic link library VCRUNTIME140.dll.

------ WHAT DO YOU WANT TO ACHIEVE?
I would like to open Mapbox Studio and try your product

**Comment by wilhelmberg** [comment]
@linnybsailor thanks for the detailed report.

Unfortunately #1406 and #1423 are only valid for **0.2.7** and do more harm than good with versions +0.2.8.

Please try the following:
- uninstall Mapbox Studio Classic
- make sure, that `C:\Program Files\mapbox-studio` is really gone
  - the files you copied manually might still be there
  - if the directory still exists, delete it completely
- reinstall with the installer
- redo:

```
cd "C:\Program Files\mapbox-studio\resources\app"
vendor\node index.js
```

What's the error message now?

**Comment by linnybsailor** [comment]
Thank you for the prompt response! 

I have followed your above directions. Attached is the error message. 

![croppercapture 192](https://cloud.githubusercontent.com/assets/14898867/10193514/9e46f990-6751-11e5-9366-9f719f063976.jpg)

**Comment by wilhelmberg** [comment]
@linnybsailor please try this:
- delete `%USERPROFILE%\.mapbox-studio` <- paste this into the address bar of File Explorer to find it
- make sure, that it is really gone, e.g. press F5 to refresh the folder listing
- run `vendor\node.exe index.js` again

Still errors?

**Comment by linnybsailor** [comment]
Followed the above. Doesn't appear to have errors any longer - see attached

![croppercapture 193](https://cloud.githubusercontent.com/assets/14898867/10194551/6878b55a-6757-11e5-9968-0bd3fd146d00.jpg)

The application still opens briefly and quickly closes when I tested again.

**Comment by wilhelmberg** [comment]
ok, seems to be working now (`Mapbox Studio @ http://localhost:3000/`).

Problem is, you cannot have two instances running at the same time.

Either you start 
- via `node.exe index.js`
  - open your browser at http://localhost:3000 and use Mapbox Studio Classic there
  - go back to the console when you are finished and press `Ctrl+c` to quit Studio or close the console window
- or via the Programs shortcut

Starting Mapbox Studio Classic twice (1x console, 1x via Programs) most certainly left an unusable `%USERPROFILE%\.mapbox-studio\app.db.compacted` that has to be removed.
- close every console window
- check via Task Manager, that no `node.exe` or `mapbox-studio.exe` processes are running. If there are, terminate them
- delete `%USERPROFILE%\.mapbox-studio\app.db.compacted`

Now it should work.

**Comment by linnybsailor** [comment]
Your first option worked! Thank you so much
