### ISSUE TITLE
No projects drawer /new projects button - Ubuntu?

### ISSUE THREAD

**Issue by martyclark** [mapbox/mapbox-studio-classic#1476]
Hi,

I'm attempting to run Mapbox Classic on Ubuntu 14.04 - starts up ok, logged into my Mapbox account, and options to choose style for new project appear. However, when I next run Mapbox Classic, opens to a default project style and no project drawer/project option anywhere in sight. If I logout of my account and back in again I get new create project options. Is this an issue with the app, or an account issue - i.e. I only have the free mapbox account?

Thanks

Martyn

**Comment by pecbarnes2** [comment]
Hello 
 I have same issue than Martyn above, "I'm attempting to run Mapbox Classic on Ubuntu 14.04 - starts up ok, logged into my Mapbox account, and options to choose style for new project appear. However, when I next run Mapbox Classic, opens to a default project style and no project drawer/project option anywhere in sight."
Thank you in advance for any clue
PEC

**Comment by wilhelmberg** [comment]
Please see https://github.com/mapbox/mapbox-studio-classic/issues/1488#issuecomment-151093881
