### ISSUE TITLE
More clearly show state in #settings mode

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#148]
It is unclear what the close button in the top right corner does, because this panel doesn't feel enough like a modal on top of active project, it feels like a separate page. We should expose the active project more clearly and ensure the close button in the top right is clearly for closing this modal, not exiting the project.

Thanks for taking note of this @nickidlugash

**Comment by yhahn** [comment]
y def not opposed to a rethinking of how this pane is laid out. My only notes are
- **Fully modal.** You shouldn't be able to get to make changes to your carto, map preview, or datasource layers in this state (though it's fine to see them).
- **Browser (?)** In the past the style project switcher/source switcher have been a separate state but I combined at some point. Not wedded to this idea and it arguably adds to the confusion. One thing I am pretty sure is we don't need a separate _page/place_ for the project switcher, e.g. tm2 does not need a "dashboard".

**Comment by samanpwbb** [comment]
I'm not seeing a need for anything drastic. If we added a map thumbnail / map title to the right column, to clarify that these are settings specifically for your active project, this ambiguity might go away. I introduced stronger contrast between the two panels, which helps.

**Comment by samanpwbb** [comment]
I solved this in mbbase just by clarifying the corner action with cccff2603e407b7901f8aa20a98a29e1817ff4bb:
![screen shot 2014-03-05 at 1 24 28 am](https://f.cloud.github.com/assets/108094/2330238/d60509f4-a42e-11e3-875a-9b22dd40aba7.png)
