### ISSUE TITLE
Visibility of roads/railway on zoom <11

### ISSUE THREAD

**Issue by dkonopka** [mapbox/mapbox-studio-classic#1482]
Hey,

I read a lot about mapbox studio and i know that from default tiles on zooms like 10,11 are not displaying smaller roads. 

But maybe you have some solutions that I could display roads on zooming out?

**Comment by arminrosu** [comment]
I have the same issue, it seems weird and counterintuitive.

This has been discussed in issue #1316.

> If you want rail at higher zoom levels, you will need to [create your own data source](https://www.mapbox.com/help/source-quickstart/).

Bummer. Hope that helps :)
