### ISSUE TITLE
Can't see geojson or shapefiles while creating new source

### ISSUE THREAD

**Issue by mapperfr** [mapbox/mapbox-studio-classic#1483]
(Not sure if it is the good place to post this request for assistance, sorry if it's not !)

Mapbox Studio Classic 0.3.2. doesn't display the vector files I'm importing while creating a new source : there isn't any error message and it acts as if everything was doing ok, except that i can't see the file. It happens with both geojson and shapefiles. I tried to play with zoom levels, to change the CRS, to save, to refresh, nothing changes. 

Here are some example files I'm working with : http://we.tl/wydgW075hp

Thanks for your help !

**Comment by wilhelmberg** [comment]
@JeremyG 

Works for me.

When adding data with a small spatial extent you might want to manually pan and zoom to the area where you data is located.

Or use the search button (magnifying glass) to do so:

![image](https://cloud.githubusercontent.com/assets/4549888/10637217/9b25f23e-7804-11e5-8bcd-75be61ffa3cb.png)

**Comment by mapperfr** [comment]
Great, now I can find it indeed. I didn't think about searching for the area, as I thought the software would automatically center the map view on the features of the layer (this could actually be considered as a feature request for MSC... I'll look for existing tickets about it).
Thanks a lot @BergWerkGIS !

**Comment by wilhelmberg** [comment]
> I thought the software would automatically center the map view on the features of the layer

Yeah, you are right, this feature is broken at the moment.
Clicking on the symbol left to the layer name should zoom to the layer extent.
Working on it: https://github.com/mapbox/mapbox-studio-classic/issues/1487
