### ISSUE TITLE
Unable to read PostgreSQL meta data

### ISSUE THREAD

**Issue by MichaelIAO** [mapbox/mapbox-studio-classic#1484]
Hello Mapbox,

I have a problem exporting data (longitude/latitude data) from my Postgres databank into Mapbox Studio. The configuration and the SQL-query works well.
![github 1](https://cloud.githubusercontent.com/assets/15235170/10643563/db58f17a-7823-11e5-8e37-e535c1a631f2.jpg)
![github 2](https://cloud.githubusercontent.com/assets/15235170/10643580/e8dd46e8-7823-11e5-98d9-2869e8051932.jpg)
![github 3](https://cloud.githubusercontent.com/assets/15235170/10643579/e8db2d68-7823-11e5-82fc-3a5420915c13.jpg)

However, no data is exported. Checking the layer, following error occurs:

![github 4](https://cloud.githubusercontent.com/assets/15235170/10643589/f2ea57a2-7823-11e5-920b-efe5294f4124.jpg)

How can I solve that issue? Is there something wrong with the connection between Mapbox and PostgreSQL / PostGIS?

Thank you very much for your help in advance.

Kind regards,
Michael

**Comment by wilhelmberg** [comment]
@MichaelIAO `zoom to layer` is broken for PostGIS connections.

In the meantime you could try the workaround described [here](https://github.com/mapbox/mapbox-studio-classic/issues/1483#issuecomment-149887537) to zoom to your data.

Tracking here: https://github.com/mapbox/mapbox-studio-classic/issues/1487
