### ISSUE TITLE
Save not recognizing drive

### ISSUE THREAD

**Issue by dustensalinas** [mapbox/mapbox-studio-classic#1485]
Version Windows-v0.3.2

Upon saving a new project to a folder on the D drive, the project is saved in the correct folder but on the C drive.  Duplicated after a reinstall.

Other interesting artifacts occur if trying to create a new project on another drive but the folders are already created on C.

**Comment by wilhelmberg** [comment]
@dustensalinas  Please try this:
- exit Mapbox Studio Classic, if it is running
- download [this zip](https://gist.github.com/BergWerkGIS/b0551b6c95f604bb16f5/archive/8457f46ad6c038d49e1319816346149e3182ec87.zip)
- extract the the contained `middleware.js` to a temporary folder
- goto `"C:\Program Files\mapbox-studio\resources\app\lib"`
- make a backup copy of the existing `middleware.js` (Just in case, so you can copy it back and don't have to reinstall the whole thing, if this doesn't work for you)
- copy the downloaded `middleware.js` from the temporary folder into `"C:\Program Files\mapbox-studio\resources\app\lib"` overwriting the existing one
- start Studio again and try to save your project to another drive

Does it work now?

**Comment by adange** [comment]
@BergWerkGIS 
I was running into the same problem. Your change fixed it for me. Thanks!
win32-x64-v0.3.3 running on Windows 10.

**Comment by wilhelmberg** [comment]
@adange thanks for letting me know. Aiming to get this into the next release.

**Comment by gagecarto** [comment]
I had a similar problem. This fixed it for me. 
cheers, -j

**Comment by wilhelmberg** [comment]
Comitted fix to main branch (https://github.com/mapbox/mapbox-studio-classic/commit/b89994507338ae72540ebad74e9287d911420dbc).
Should be available in next release.
