### ISSUE TITLE
mapbox studio classic : no projects drawer from mapbox-studio-linux-x64-v0.3.2.zip

### ISSUE THREAD

**Issue by pecbarnes2** [mapbox/mapbox-studio-classic#1488]
Hello
 I downloaded mapbox-studio-linux-x64-v0.3.2.zip from here https://www.mapbox.com/mapbox-studio-classic/#linux

I have same issue than the issue reported by Martyn some time ago, "I'm attempting to run Mapbox Classic on Ubuntu 14.04 - starts up ok, logged into my Mapbox account, and options to choose style for new project appear. However, when I next run Mapbox Classic, opens to a default project style and no project drawer/project option anywhere in sight."

Thank you in advance for any clue

PEC

**Comment by wilhelmberg** [comment]
@pecbarnes2 @martyclark
You might want to take a look at the `Getting Started` guide:
https://www.mapbox.com/guides/getting-started-studio/

In particular:
https://www.mapbox.com/guides/getting-started-studio/#start-style
https://www.mapbox.com/guides/getting-started-studio/#start-source

![image](https://cloud.githubusercontent.com/assets/4549888/10726663/659319e8-7bd4-11e5-8597-f83e52ebfdaa.png)

![newproject_source](https://cloud.githubusercontent.com/assets/4549888/10726676/7d29e67c-7bd4-11e5-9fe4-7eabf1710235.gif)

**Comment by pecbarnes2** [comment]
I had a look at the link you provide, and thank you for this. As you can see from this screenshot below, I do not have any 'Projects' button at the bottom left, but I have instead a 'Styles and Sources' button. 
![screenshot from 2015-10-26 19 16 30](https://cloud.githubusercontent.com/assets/15314422/10738142/32b4db1e-7c16-11e5-8fd7-76364276078d.png)
So it remains a mystery for me
Have you tried to install 'MapBox Studio Classic' on Ubuntu 14.04 ?
Thanks

**Comment by martyclark** [comment]
Same here @pecbarnes2 - I have a 'styles and sources' button, not
'projects'.

Has something changed since the guide was written, as it seems like the
documentation and the version of mapboxclassic I'm using do not match.

I'm just running mapboxclassic from the atom script, I haven't installed
it...

**Comment by ajashton** [comment]
The documentation needs to be updated to reflect the latest changes but "Styles & Sources" is the same button as the previous "Projects" button. It was renamed to be more specific but functions exactly the same otherwise.
