### ISSUE TITLE
Error connection on PostGis

### ISSUE THREAD

**Issue by Amrizhan** [mapbox/mapbox-studio-classic#1499]
Hi there
I am using Postgis data which was added via osm2pgsql. The Source Data was pbf format. I sow that i can add shape data, but nothing about pbf

Ok so during loading postgis data source into Mapbox Studio Classic i have error message  "Missing required field "table" (type=data) for layer "postgis" 

I found info here #839, but it dosnt give me answer to my questions like:
1. What is my geom field?
2. Geom table?
3. Key?

**Comment by wilhelmberg** [comment]
You have to look into your PostGIS database and see what tables/fields are available.

You need a SQL statement to query data from PostGIS.
e.g.:

```
(SELECT * FROM osm-ocean) as data
```

Then 

In this example:
- `geom field` => `geom`, but might also be `the_geom`, `wkb_geom` or something else
- `geom table` => `osm_ocean`. the table name of the data you inserted into PostGIS
- `key` => `tid`, but might also be `id`, `gid` or something else. It's the unique identifier of each data row in the geom table

![image](https://cloud.githubusercontent.com/assets/4549888/10879309/906043c4-8153-11e5-904a-1f5455f1a569.png)

**Comment by Amrizhan** [comment]
Thank you, this is works for me,
Additional one quiestion:
Where i can find typical SQL query with style and zoomlevels for typical planet_osm_data

**Comment by amyleew** [comment]
@Amrizhan - there is a section in our PostGIS manual on [SQL queries](https://www.mapbox.com/help/postgis-manual/#sql-queries) and make sure you have our [PostGIS Vector Tile utility](https://www.mapbox.com/help/postgis-manual/#add-postgis) added to your database to use the zoom and label grid functions.
