### ISSUE TITLE
error installing tilelive-bridge --> node-mapnik-1.4 not found  (ubuntu)

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-studio-classic#150]
Hello,
while installing tm2 i got few problems with npm install. So i try to install each module a time.
when i try 
nmp install tilelive-bridge

i got this error:

368 http 404 https://github.com/mapbox/tilelive-bridge/tarball/node-mapnik-1.4
369 error fetch failed https://github.com/mapbox/tilelive-bridge/tarball/node-mapnik-1.4
370 silly lockFile 8d9f9130-e-bridge-tarball-node-mapnik-1-4 https://github.com/mapbox/tilelive-bridge/tarball/node-mapnik-1.4
371 silly lockFile 8d9f9130-e-bridge-tarball-node-mapnik-1-4 https://github.com/mapbox/tilelive-bridge/tarball/node-mapnik-1.4
372 error Error: 404 Not Found

**Comment by yhahn** [comment]
@andriaz can you try again after git pull'ing to make sure you have this commit?

https://github.com/mapbox/tm2/commit/76bb543329bdd1a68898cc170817fc5a4067626d

**Comment by yhahn** [comment]
Reopen if still occurring.
