### ISSUE TITLE
Error: could not create converter for SQL_ASCII

### ISSUE THREAD

**Issue by mavinothkumar** [mapbox/mapbox-studio-classic#1503]
Hi,

Am trying to connect the db from remote using postgis method. I have given the data and click save, its doesn't show anything, when I open the developer tool I got this message as response,

Error: could not create converter for SQL_ASCII 

The same data and configuration works perfectly on local machine.

Any solution to fix this ?

**Comment by wilhelmberg** [comment]
@vinothkumarma seems the character sets of your databases are setup differently.
Try to setup your database with with `UTF8` character set:
http://www.postgresql.org/docs/9.4/static/multibyte.html#CHARSET-TABLE

**Comment by mavinothkumar** [comment]
yes, its worked. These are the process I did,
1. Took backup the DB
2. Created a new DB with UTF8
3. Changed the client_encoding = 'UTF8'; in DB backup file
4. Uploaded the backup file to new DB.

Worked perfectly.

Thanks

**Comment by wilhelmberg** [comment]
:+1:
