### ISSUE TITLE
Layer missing from static image export in Comic! style

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#1506]
I'm not getting the road layer in a static image export from [this classic style](https://api.mapbox.com/v4/faraday2.0896bd7e/page.html?access_token=pk.eyJ1IjoiZmFyYWRheTIiLCJhIjoiTUVHbDl5OCJ9.buFaqIdaIM3iXr1BOYKpsQ#17/44.47995/-73.21803):

![comic-demo2](https://cloud.githubusercontent.com/assets/735463/11256311/2f72c596-8e19-11e5-95c7-027029efa0f4.png)

This is using `mapbox-streets-v5` source and a custom data source (one building only). I had thought it might have something to do with the image-based road rendering, but I tried an export from the "pencil" style (with even more image dependence) and it worked fine:

<img width="644" alt="screenshot 2015-11-18 17 29 41" src="https://cloud.githubusercontent.com/assets/735463/11256451/f9e8ff70-8e19-11e5-95fa-c48e4ff5b0df.png">

**Comment by chrisrogers** [comment]
I am having the exact same problem. @wboykinm did you find a solution?

**Comment by ajashton** [comment]
> I had thought it might have something to do with the image-based road rendering

I think this is it - line pattern images do not scale, so your print-scaled image (`@3x`? `@4x`?) is still only rendering line-patterns at `@1x` where the pixels are tiny and barely visible. You can see faint ghosty roads in your image if you squint.

I think the only solution would be to create larger versions of the pattern images that look ridiculously oversized `@1x` but normal at print scale.

**Comment by chrisrogers** [comment]
Thank you for the suggestion! I'll try it out.

**Comment by wboykinm** [comment]
That's awesome. Thanks!
