### ISSUE TITLE
View map while in #docs mode

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#151]
User should be able to view docs and edit map at the same time. I would use this feature all the time, especially when playing with carto features that are rare or hard to remember (composite operations).

One way to do this would be to limit the #docs panel to 50% or so of screen height. Rather than modifying #docs mode, we could add a new mode ( #docs-preview) that showed map.

An alternative approach would be to follow the #layers pattern, with a slideout drawer. Downside to this is that it interferes with the spatial relationships in place in the UI.

**Comment by tristen** [comment]
> An alternative approach would be to follow the #layers pattern, with a slideout drawer. Downside to this is that it interferes with the spatial relationships in place in the UI.

I kind of like this approach and doesn't introduce a new mode. It might be nice to only support a view like this on larger screens and go back to a 50/50 split with the docs covering the map on smaller screens. ie:

```
                  LARGE SCREENS
 +----------+------------------------+----------+
 |          |                        |          |
 |          |                        |          |
 |          |                        |          |
 |   DOCS   |          MAP           |  EDITOR  |
 |          |                        |          |
 |          |                        |          |
 |          |                        |          |
 +----------+------------------------+----------+
                      MOBILE
 +----------------------+-----------------------+
 |                      |                       |
 |                      |                       |
 |                      |                       |
 |        DOCS          |         EDITOR        |
 |                      |                       |
 |                      |                       |
 |                      |                       |
 +----------------------+-----------------------+
```

**Comment by tristen** [comment]
Or actually, maybe a 50% split for the editor is better. previewing doesn't necessarily need to occupy that much room. So like:
- [25% map] [50% editor] [25% Docs]
- Move the toggle switch to the right ![screen shot 2014-03-04 at 9 47 33 am](https://f.cloud.github.com/assets/61150/2322041/fc592f50-a3ab-11e3-81d1-ca08a57ff5ca.png)
- Slide out drawer from the right.

**Comment by edenh** [comment]
@tristen I like your approach to moving the toggle switch to the right. It would also be nice to see the data pane while viewing the code and map. Could we do something like this:

![screen shot 2014-03-05 at 1 47 41 pm](https://f.cloud.github.com/assets/1577766/2338992/112b8f2c-a4b0-11e3-88be-f92f4848bfd4.png)

This result in a consolidated 'get help' area with either docs or data ref. Open would result in a 30% split between the panes.

**Comment by samanpwbb** [comment]
How about: 
![screen shot 2014-03-05 at 4 54 58 pm](https://f.cloud.github.com/assets/108094/2339053/d2e753e4-a4b0-11e3-92fb-27df89c90058.png)

**Comment by tmcw** [comment]
For reference docs, saman's suggestion reminds me of how adobe brackets does this, pretty effectively

![2014-03-05 at 4 59 pm](https://f.cloud.github.com/assets/32314/2339120/84f77064-a4b1-11e3-9ee1-90260f2c7337.png)

**Comment by edenh** [comment]
@tmcw ha I was about to reference brackets. I think the best solution really is contextual help like this with a more comprehensive _external_ docs window.

**Comment by wilhelmberg** [comment]
I would love to have the possibility to resize the panels by myself.
Not fixed to 50%, 30% or whatever.
Reason: I'm using several monitors in portrait mode (https://twitter.com/WilhelmBerg/status/372707259970617344/) and aligning the edges of the panels to the bezels between the monitors is really a PITA when moving windows around or resizing them.

**Comment by samanpwbb** [comment]
I'm going to experiment with alternative approaches to docs today.

**Comment by samanpwbb** [comment]
plan: 
![screen shot 2014-03-13 at 2 28 54 pm](https://f.cloud.github.com/assets/108094/2413344/5da37864-aadd-11e3-9b8b-3caa96c3840b.png)

**Comment by edenh** [comment]
:+1: looks good

**Comment by samanpwbb** [comment]
Done with #208
