### ISSUE TITLE
Source locked (custom layer order)

### ISSUE THREAD

**Issue by seonajoo26** [mapbox/mapbox-studio-classic#1510]
I'm trying to change the vector tile source (following this instruction: https://www.mapbox.com/help/source-quickstart/#changing-source) but when I hit 'Layer's and try to change source, it says the source is locked. Also, after I crated a source I couldn't view it in the data page. What can I do to fix this?

**Comment by katydecorah** [comment]
@seonajoo26 you can unlock the style manually to manipulate the layers, check out https://www.mapbox.com/help/style-manual/#custom-layer-order for more information

> Also, after I crated a source I couldn't view it in the data page.

Can you send us a screenshot at https://www.mapbox.com/contact/, someone on the team will help you debug!
