### ISSUE TITLE
Automate conversion from spatialite to mbtiles

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-studio-classic#1511]
I have successfully been able to use Mapbox Studio Classic to import spatialite and convert it to mbtiles. If I wanted to automate this, what source code should I be looking at? Does Mapbox Studio use something like Mapnik to do this conversion?

Thanks.

**Comment by wilhelmberg** [comment]
duplicate of https://github.com/mapnik/node-mapnik/issues/571
