### ISSUE TITLE
Mapbox Studio Classic - Data Source Limit

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [mapbox/mapbox-studio-classic#1520]
Is there a limit to the number of data sources when defining map styles? Or maybe a character limit imposed on 'source:' in the project.yml flie?  I've been unable to add data sources after a certain point, unless i remove other sources first.  I couldn't find this documented anywhere.  If this is an inappropriate question for this github repo I can take this down and put it up on GIS Stack Exchange or somewhere else.

**Comment by wilhelmberg** [comment]
@wheredoesyourmindgo the limit for composting sources is 15.
If you are working with custom sources you could try to combine some of them (where it makes sense).

**Comment by wheredoesyourmindgo** [comment]
Appreciate the clarification.
