### ISSUE TITLE
Styled markers do not appear

### ISSUE THREAD

**Issue by sebastiantiede** [mapbox/mapbox-studio-classic#1521]
According to the mapbox studio tutorial https://www.mapbox.com/help/source-quickstart/.
Styled markers do not appear:

![bildschirmfoto 2016-01-13 um 11 51 22](https://cloud.githubusercontent.com/assets/6308134/12292486/ad761c54-b9ed-11e5-80fe-2ba641c9712b.png)
![bildschirmfoto 2016-01-13 um 11 57 30](https://cloud.githubusercontent.com/assets/6308134/12292485/ad709dba-b9ed-11e5-9b85-a77413d6246f.png)

any ideas?
thanks

**Comment by sebastiantiede** [comment]
mh, got it. only works in combination with a style

**Comment by sebastiantiede** [comment]
Ah, wait, not my fault:
after some changes and undo changes the markers disappear again.
Does anyone have any experience with the problem?

**Comment by wilhelmberg** [comment]
@sebastiantiede 

Because of `marker-comp-op: screen;` you have to set your map background to something other than `white` to see the markers.
The tutorial assumes a background map.

![image](https://cloud.githubusercontent.com/assets/4549888/12350133/67753fee-bb75-11e5-8be2-978bd0756235.png)
