### ISSUE TITLE
Upgrade mapbox-upload?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1525]
@willwhite - studio classic is running ~4.1.0 but latest is 4.2.1- should studio classic get upgraded? Asking because I'm working on a new release and it would be easy to hit if you see a benefit.

**Comment by springmeyer** [comment]
bump @willwhite

**Comment by willwhite** [comment]
Upgrade sounds good. It should be seamless. We can switch this
automatically use the newest version in the 4.x.x series.

On Thursday, January 28, 2016, Dane Springmeyer notifications@github.com
wrote:

> bump @willwhite https://github.com/willwhite
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapbox/mapbox-studio-classic/issues/1525#issuecomment-176303172
> .

## 

202-250-3633 | will@mapbox.com | @willwhitedc
