### ISSUE TITLE
Merge mbbase

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#153]
Lots of polish to do here still. My list for merging mbbase looks like this right now:
- [x] Cleanup background tones (can we get away with removing fill-dark / fill-light?)
- [x] Cleanup large screen media queries (keep @ajashton happy)
- [x] One last round of cleanup to custom styles
- [x] Re-introduce panel drop shadow along map
- [ ] Style x-ray popup
- [ ] Fix autocomplete dropdown
- [ ] Ensure all class event triggers are working

I know more will come up as I work.

**Comment by ajashton** [comment]
I don't have strong feelings on the blue either way, but if we keep it this text will need more contrast:

![](http://i.imgur.com/hnDoc0M.png)

The horizontal rules in the layers list on the other hand (in both Style and Source mode) could use some toning down. They seem to overpower the text:

![](http://i.imgur.com/B1UeRae.png)

Also, long source names are not handled [edit: but master doesn't either]:

![](http://i.imgur.com/5DSbkpv.png)

**Comment by ian29** [comment]
agree w/ @ajashton that the horizontal rules are a bit distracting.

also the keylines around the source editor forms were initially very distracting but im getting used to them.
![image](https://f.cloud.github.com/assets/1056106/2334954/12f9a630-a47f-11e3-87d3-49bdaa3afed7.png)

the extent field could be wider - this is often a string of 4 long numbers
![image](https://f.cloud.github.com/assets/1056106/2334979/2d739e1c-a47f-11e3-8633-9df94a582d6d.png)

**Comment by samanpwbb** [comment]
This stuff is great - keep flagging things guys. At the moment we only have 1 keyline style. I'll look into some ways to work with this.

**Comment by samanpwbb** [comment]
Closed replaced by https://github.com/mapbox/tm2/pull/164
