### ISSUE TITLE
Import geojson with markers

### ISSUE THREAD

**Issue by yamila-moreno** [mapbox/mapbox-studio-classic#1535]
I think I have found a bug when importing a geojson with markers (points).

No matter the size or color I assign in the geojson file, all the markers are loaded with medium size and grey colour. I've tried with different geojsons, colors and sizes and the behaviour is consistently unexpected.

If you need further information, I'll be glad to help.

**Comment by tmcw** [comment]
GeoJSON doesn't have a style component; you'll need to style your data in CartoCSS.
