### ISSUE TITLE
Not able to lauch Mapbox Studio classis, after installing it in my local.

### ISSUE THREAD

**Issue by Sumati2** [mapbox/mapbox-studio-classic#1537]
Hi team,
I recently  downloaded Mapbox Studio Classic in my local desktop. But I am not able to lauch it as it is asking me to connect to my account. But I am not getting how to connect to my account using through that tool.
Please let me know how to lauch it asap.
Regards,
Sumati

**Comment by tmcw** [comment]
Sorry, we no longer provide support for Mapbox Studio Classic.
