### ISSUE TITLE
Show when data is loading/done/broken in source editor 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#155]
When I add a new source I have a hard time knowing if my source is bad or if it just hasn't rendered on the map yet.

**Comment by ian29** [comment]
big +1. 

also, many errors are getting `console.log()`'d, and it would be great to surface at least some of these in the UI.

**Comment by samanpwbb** [comment]
At the very least lets add a notice to the source UI after saving that says something like, "your data may take up to a few minutes to render".

**Comment by yhahn** [comment]
Fixed by https://github.com/mapbox/tm2/commit/c11d53f03eaf90961c67985976d8445e2962ec07.

Other cases like having a bad projection is basically not detectable automatically. Fixes there will have to be at doing better projection detection or so.
