### ISSUE TITLE
Disallow source center's that are outside min/maxzoom bounds

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#156]
Or bad news bears.

cc @ian29 @aaronlidman

**Comment by ian29** [comment]
yesh.

**Comment by ian29** [comment]
also require a zoom level param. i just rendered an mbtiles without a zoom center, and tm2 does not complain.

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/pull/562
