### ISSUE TITLE
Is Mapbox-studio definitely gone ?

### ISSUE THREAD

**Issue by Biboba** [mapbox/mapbox-studio-classic#1562]
Hello,

Don't know if it is the proper place to ask, but I am wondering if it is possible to download somewhere mapbox-studio and not mapbox-studio-classic for using Mapbox GL Style instead of CartoCSS.

Cheers,

Nicolas

**Comment by gravitystorm** [comment]
The "new" `mapbox-studio` (the online, GL based one) is proprietary. It can only be used on mapbox.com and they haven't released the code behind it. It isn't "gone", it was just never released.

`mapbox-studio-classic` (this one, that uses CartoCSS and mapnik) is the only open-source vector-tiles-based design studio that Mapbox have released.

**Comment by Biboba** [comment]
Thanks for the answer. 
Too bad but good to know. 
FYI, there is still a NPM package for mapbox-studio so it can be a bit confusing with all those identical names :
https://www.npmjs.com/package/mapbox-studio

**Comment by wilhelmberg** [comment]
@Biboba Mabox Studio Classic is available for download here:
https://www.mapbox.com/mapbox-studio-classic/

**Comment by tmcw** [comment]
Closing; we've covered this topic. Mapbox Studio ([/mapbox-studio](https://www.mapbox.com/mapbox-studio/)) is an online replacement for Mapbox Studio Classic, built with open source components. Mapbox Studio Classic (this) is still available for download and will be potentially maintained by volunteers.
