### ISSUE TITLE
mbbase: save doesn't work in source mode

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#157]
Eg open a source and tick one of the inspector boxes.
- clicking the save button does nothing
- ctrl-s brings up the browser's save-page dialog and overlays a spinner on the screen that never goes away

**Comment by tristen** [comment]
I'm sure this has something to do with a change I made. Will be sure to hit this when #152 is covered.

**Comment by samanpwbb** [comment]
Done in mbbase
