### ISSUE TITLE
Straight lines in MapBox Studio.

### ISSUE THREAD

**Issue by oddsson** [mapbox/mapbox-studio-classic#1570]
Would it be possible to add a "hold shift for a straight line" feature in MapBox Studio, similar to the one in Google Drawing where if you press and hold the Shift key while drawing a line the line gets fixed to a certain degree.

Try it yourself in Google Drawing:
1. Open a new Google Drawing document in Google Drive.
2. Press and hold the Shift key while drawing a new line.

This is what I want in MapBox Studio when drawing a LineString.

**Comment by mcwhittemore** [comment]
Ívar,

Thanks for your request. We are currently tracking this request in `mapbox-gl-draw` which is the tool we use to for drawing in Studio. Please feel free to ask about the status of this there. To help keep issue clutter here down, I'm going to close this issue.

https://github.com/mapbox/mapbox-gl-draw/issues/2

Regards,
Matthew
