### ISSUE TITLE
UI to delete old, unwanted sources from menu?

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#158]
Currently they just build up forever unless you delete or manually edit app.db.

**Comment by samanpwbb** [comment]
@ajashton / @yhahn have either of you thought about how/if this should work for local sources? Right now TileMill is in an in-between place where you half expect it to manage files in a self-contained and half expect to need to work with your the file system separately. My thinking is that local files should just be managed by the user, independently of the TileMill UI.

**Comment by samanpwbb** [comment]
This also leads me to ponder about deleting / removing styles. If we leave local sources along, these should be left alone as well.

Edit: then again, an 'x' button on sources to not delete the files, but remove the references, actually does make sense. I will hold off on anything here until I hear some second opinions.

**Comment by yhahn** [comment]
> Edit: then again, a 'x' button on sources to not delete the files, but remove the references, actually does make sense. I will hold off on anything here until I hear some second opinions.

Let's do this. Don't delete any files, just TM2s awareness of the obj in your history.

**Comment by ajashton** [comment]
> Don't delete any files, just TM2s awareness of the obj in your history.

:+1:

**Comment by samanpwbb** [comment]
Have this started with 87e91841eafc064838d9859c998de3a7f5df0f5d, needs: 
- [x] Add to source side
- [ ] Fix error reporting, inform user that delete doesn't work on active project (ideally, hide/disable del action altogether on active project)

**Comment by samanpwbb** [comment]
Covered with https://github.com/mapbox/tm2/pull/196

**Comment by ajashton** [comment]
The delete buttons got removed a while back. Was it intentional, or can we restore them?
