### ISSUE TITLE
Breaks in roads, corners and roundabouts.

### ISSUE THREAD

**Issue by 0XE4** [mapbox/mapbox-studio-classic#1582]
I am having the issue when exporting to a PNG. You can see 'breaks' or cracks along the roads, mostly on anything that isn't at a 90 degree angle.  

Is this due to cartoCSS needing changes, or an issue with the renderer itself?

![take](https://user-images.githubusercontent.com/16703464/36564144-391ce040-1814-11e8-81c1-53964e459d8f.PNG)

**Comment by ajashton** [comment]
It looks like you're using `line-cap: butt` - you'll want to use `line-cap: square` or `line-cap: round` to hide these cracks. It's not a bug, just the nature of that particular line-cap style. (`butt` is useful for some things, but not road networks.)

**Comment by 0XE4** [comment]
Thank you @ajashton
