### ISSUE TITLE
Invalid GL Json

### ISSUE THREAD

**Issue by elprincipe47** [mapbox/mapbox-studio-classic#1585]
Hi,
I am trying to add a Layer to my Style in Mapbox Studio but I am getting an Error : Invalid GL Json
NB : My Geojson is Valid json according to http://geojsonlint.com

![image](https://user-images.githubusercontent.com/16051114/45219321-66909e80-b2a2-11e8-9197-daf6b4835105.png)

**Comment by mzdraper** [comment]
Hi, it isn't possible to transfer styles from Mapbox Studio Classic to Mapbox Studio. While Mapbox Studio Classic styles were built using CartoCSS, Mapbox Studio now uses the Mapbox GL Style Specification. The Mapbox GL style is an object that defines what data to draw in the map, the order to draw it in, and how to style it. The style’s JSON structure is specific to the Mapbox GL Native renderer implementation, making cross-compatibility with CartoCSS-based styles impossible. 

To start styling with Mapbox Studio, check out our [Mapbox Studio Manual](https://mapbox.com/help/studio-manual/) for a comprehensive guide to using Mapbox Studio.
