### ISSUE TITLE
Autocomplete hints

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-studio-classic#161]
![screen shot 2014-03-05 at 2 13 56 pm](https://f.cloud.github.com/assets/1577766/2339253/8b9daf8a-a4b3-11e3-865f-ce9d2eb2b706.png)

http://codemirror.net/demo/complete.html
*as an option cc/@tmcw

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/issues/388
