### ISSUE TITLE
Can't cancel export

### ISSUE THREAD

**Issue by MateoV** [mapbox/mapbox-studio-classic#162]
I started and subsequently hit cancel on an export of a source. However, the export starts again every time that source is opened and prevents me from exporting any other source (there is no button, I assume it is hidden if it detects an export happening in the background). At this point I must force quit tm2 because the export continuously restarts. Seems to be a routing bug but I can't determine where it's coming from.

![tm2-export-bug](https://f.cloud.github.com/assets/843058/2339398/5ac90178-a4b5-11e3-99eb-f51aa004b4d0.gif)

Steps already taken that haven't fixed it:
- reinstalled tm2
- cleared tm2 cache
- cleared browser cache + cookies

/cc @springmeyer @yhahn

**Comment by ian29** [comment]
i can replicate, fwiw

**Comment by ian29** [comment]
looks like this was fixed? i can no longer replicate. @MateoV you can confirm that you no longer see this bug, right?

**Comment by MateoV** [comment]
The offending source still resumed export when opening, so I just deleted it. Has not occurred on any subsequent cancellation attempts.
