### ISSUE TITLE
Always show .mss or never show .mss for file tabs

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#168]
It is required here to add .mss to your filename:
![screen shot 2014-03-06 at 11 47 27 am](https://f.cloud.github.com/assets/108094/2347655/06f476d2-a54f-11e3-8662-d83a868dabe0.png)

but in the UI, tabs show up without suffixes:
![screen shot 2014-03-06 at 11 48 01 am](https://f.cloud.github.com/assets/108094/2347663/16c46734-a54f-11e3-9ee0-f33b85e997cf.png)

We should either: 
1. Always hide .mss from users (not require it when creating new tabs)
2. Always show .mss

**Comment by edenh** [comment]
If the only tabs are .mss tabs, we should drop the .mss from the new tab overlay.

**Comment by samanpwbb** [comment]
:+1:

**Comment by edenh** [comment]
https://github.com/mapbox/tm2/commit/bbf7782a87eaf51eef5ef52836195893f3d7a4c0
