### ISSUE TITLE
document available fonts

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#17]
The full names of the default fonts should be available in the interface. Bonus: previews.

**Comment by wboykinm** [comment]
+1000 - but the ones you've already got in there are a lot of fun.

**Comment by yhahn** [comment]
Will take a look at this.

**Comment by yhahn** [comment]
![tmp-fonts-1](https://f.cloud.github.com/assets/83384/857925/d09addcc-f55b-11e2-96a8-71fc8ea5d234.png)
![tmp-fonts-2](https://f.cloud.github.com/assets/83384/857926/d0a70408-f55b-11e2-9708-c3954cd30091.png)

**Comment by ian29** [comment]
:yum:
