### ISSUE TITLE
Support for GPX as a Layer Source

### ISSUE THREAD

**Issue by skorasaurus** [mapbox/mapbox-studio-classic#170]
Just curious if you're planning to support GPX files as a layer source, didn't see it listed a possible source option. 

(obviously, could just convert it into another format as a workaround)

**Comment by springmeyer** [comment]
Yes, all OGR datasources we support in TileMill 1 will eventually be supported. But we want to do this right. I've created #171 to track actually adding support for OGR datasource like GPX that contain one or more layers inside.

**Comment by skorasaurus** [comment]
No problem; thanks for the prompt and informative response! :)
