### ISSUE TITLE
Source Layer UI specific to OGR+GDAL datasources

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#171]
There are a variety of geodata formats which can contain more than one layer, like GPX (tracks, waypoints, routes), or ESRI FileGDB (can contain arbitrary layers of raster or vector).

In TileMill 1 we never respected this complexity and the user experience suffered.

Here is a sketch of how this could be done better:
1. Create a list of known file extensions that may contain multiple layers, eg: `[gpx,gdb,mdb]`
2. When one of these types is detected, instead of presenting the layer UI, first try opening the files and query their layers (this can be done with `node-mapnik`)
3. Generate a modal drop down menu that forces the user to choose a layer by name
4. Now that we know the layer we can now try to detect the SRS (however this is currently not possible since `node-srs` does not know how to reach into datasources yet - would need proper GDAL/OGR bindings to open datasources)
5. Then forward along to the format Layer UI for the user to set other layer options

**Comment by springmeyer** [comment]
Regarding point 4 above:

> would need proper GDAL/OGR bindings to open datasources

@sgillies and I are working on this: looking at using and contributing to https://github.com/naturalatlas/node-gdal and https://github.com/naturalatlas/node-ogr. Steps I see are: kick the tires on the bindings in general, make sure test coverage is good for opening layers and projection detection, figure out whether node-srs is needed anymore, and then commence with node-pre-gyp'fying.

**Comment by yhahn** [comment]
@GretaCB this is about a different file format but touches on a very similar issue we discussed:

> When one of these types is detected instead of presenting the layer UI instead first try opening the files and query their layers (this can be done with node-mapnik)

There may be some reason to flip the order of layer addition from:
1. Choose type of layer to add (postgis, geojson, kml, gpx, etc.)
2. Pick file for the layer

To:
1. Pick file to add (what about postgis/and other non-file type data???)
2. Edit layer(s) that are automatically defined/added

A third alternative would be similar to our current flow but maybe repetitive:
1. Choose type of layer to add (postgis, geojson, kml, gpx, etc.)
2. Pick file for the layer
3. Pick a layer from the file to use

**Comment by springmeyer** [comment]
I would really love to support drag-and-drop in tm2. This might sound silly/off scope but its actually very very useful/fast. QGIS allows this: you drag and drop a shapefile's `.shp` and the layer is automatically added. In QGIS if you drag and drop a `.gpx` you get presented with a menu of layers to choose from. So, that is another point for just starting with "Pick a file to add" and not forcing a choice of the type first. This would rely on file extension to do the right thing and I think its worth it.

**Comment by yhahn** [comment]
:+1:

**Comment by GretaCB** [comment]
Is the vision to get rid of all of the separate "Configure" windows for each filetype, and have single Browse window/modal? 

@yhahn What do you mean by "Edit layer(s)" above?

**Comment by springmeyer** [comment]
Noting that this issue was closed because both mapnik-omnivore and node-gdal came online and allowed support for formats like GPX which has multiple layers (#926). However unlike GPX many other multi-layer formats may have a different projection per layer (like postgis, filegdb, etc). Tracking this issue at https://github.com/mapbox/mapnik-omnivore/issues/72
