### ISSUE TITLE
reset selected source editor tabs when dismissing editor

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#173]
Right now, if user tabs to 'fields' tab in one layer, exits, then opens a new layer, 'fields' tab will still be active. We should always default back to conf tab.

**Comment by ajashton** [comment]
I think this is similar to / the same as https://github.com/mapbox/tm2/issues/100 ?

**Comment by samanpwbb** [comment]
Ya, closing in favor of #100
