### ISSUE TITLE
Challenge: make layer type dropdown look good cross-platform

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#174]
There is probably only sadness down this road.

Ubuntu + Firefox, too tall:

![](http://i.imgur.com/VE7b2PO.png)

Ubuntu + Chrome, too short:

![](http://i.imgur.com/wWcs4Tv.png)

**Comment by samanpwbb** [comment]
It's pretty easy to set height on these guys - i think we can get close without too much effort.

Edit, heh, we can do this but then you get the old school dropdown: 
![screen shot 2014-03-06 at 5 59 38 pm](https://f.cloud.github.com/assets/108094/2351956/13394092-a583-11e3-9ea7-bed4ca31d796.png)

**Comment by kapouer** [comment]
My humble experience led me to believe the "select dropdown" was not a good UI element to use. Almost every time it is present somewhere, another way of presenting the choices can be used that doesn't suffer from this impossibility to style it cross-browser. Get rid of it !

**Comment by tmcw** [comment]
@kapouer we're open to concrete suggestions - what other kind of UI element might work here?

**Comment by kapouer** [comment]
Well, the simplest idea is to replace the `<select>` by a `<ul>` list. Of course it's not a drop-in replacement.

**Comment by samanpwbb** [comment]
I would be game for working no replacements for the `<select>` elements. As long as it's scalable and easy to maintain.

**Comment by samanpwbb** [comment]
Attempt at https://github.com/mapbox/tm2/pull/185

**Comment by samanpwbb** [comment]
Merged #185
