### ISSUE TITLE
don't require refresh after clicking inspect checkbox

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#176]
@yhahn is there a reason why refreshing map is required after clicking inspect checkbox on source layer list? 
![screen shot 2014-03-07 at 2 40 58 pm](https://f.cloud.github.com/assets/108094/2361367/6d4cfda0-a630-11e3-9151-14ab4f81c55c.png)

Can we just auto-refresh page when user clicks this?

**Comment by yhahn** [comment]
y, to get the inspection change we also have to do a save/update of the source.

If you have other changes going on forcing the save on this interaction could save changes the user was not expecting.

I think this could be reworked but will require some pretty significant changes deeper down.

**Comment by samanpwbb** [comment]
> y, to get the inspection change we also have to do a save/update of the source.

Right now it's a usability issue. To work with this and not against it: after user has clicked the mag. glass, we show a popup like, "save map to inspect [x] layer".

**Comment by yhahn** [comment]
y something like this would be fine for now.

**Comment by samanpwbb** [comment]
Here's a try: https://github.com/mapbox/tm2/pull/177

**Comment by samanpwbb** [comment]
Done-ish.
