### ISSUE TITLE
Improve add remote source panel

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#178]
We should do this now:

![screen_shot_2014-03-07_at_4_44_17_pm](https://f.cloud.github.com/assets/108094/2362971/9303624a-a645-11e3-8a8b-1fd7c2ca51d6.png)

With expectations to evolve it once mapbox account authorization is unlocked.

**Comment by samanpwbb** [comment]
Re-opening, this would be an easy way to help users understand this part of TileMill.

**Comment by rclark** [comment]
@samanpwbb would it list only curated sources, or would it list a user's own sources as well? Could this also provide a simple way for users to build a composite data source?

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/commit/8125eae8b2019b6639a7772baab9443b94f37192
