### ISSUE TITLE
retina icon color

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-studio-classic#179]
![screen shot 2014-03-07 at 4 45 30 pm](https://f.cloud.github.com/assets/1577766/2363971/841512e0-a65b-11e3-8db4-96da19294f1e.png)

@samanpwbb I'm seeing white icons for <code>a.icon:not(.button)</code> on retina. Probably due to https://github.com/mapbox/tm2/blob/master/ext/base/base.css#L2258 ?

**Comment by samanpwbb** [comment]
Fixed in https://github.com/mapbox/tm2/commit/b3e449efd24d0bdbd9b067f304e5e6da5d5612e8
