### ISSUE TITLE
Ubuntu Linux Install Fail

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#18]
Obviously a nonessential problem, but `npm install` failed [with the following errors reported](https://gist.github.com/wboykinm/5478331), seemingly based on a tarball failure. Following up with `node index.js` failed for lack of underscore.

On Ubuntu Quantal

**Comment by wboykinm** [comment]
The install fails a little bit differently as root user. [Here's the full debug log](https://gist.github.com/wboykinm/5478370).

**Comment by springmeyer** [comment]
Not sure what is up - can't see anything obvious in those logs.

Both node v0.8.x and v0.10.x should work. I've fixed a few things recently in dependencies. Can you try again and let me know if you hit the same error?

Dane

**Comment by wboykinm** [comment]
Old node version was holding it up. Maybe note the version requirement.

**Comment by yhahn** [comment]
Hrm does this no longer work? https://github.com/mapbox/tm2/blob/master/package.json#L6

**Comment by springmeyer** [comment]
@yhahn https://github.com/mapbox/tm2/commit/d54a7bb703a807cd5bb4eb6d7f8e3054e8befff5

**Comment by yhahn** [comment]
o `enginesStrict` eh : )

**Comment by springmeyer** [comment]
closing, @wboykinm - if you hit errors when you re-try with new instructions (https://github.com/mapbox/tm2/commit/2b314cb65a8bbaad1bc7c5214a2724644d5652b7) please post a new issue.

**Comment by springmeyer** [comment]
ugh, `enginesStrict` does not seem to work though. odd. Tested with node v0.10.5 and modified package.json to only declare 0.8.x support...

**Comment by wboykinm** [comment]
Errors? What errors? [This is maaaaaarvelous](http://www.flickr.com/photos/65259390@N08/8723304773/)!
