### ISSUE TITLE
UI tests

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#184]
Tests for UI interaction need to be built out to ensure we don't break interactions moving forward.

Looks like mocha is already in place for API side tests my plan would be to use mocha for this as well.

**Comment by yhahn** [comment]
@tristen let me know if you want to sync up here -- curious to see what you're thinking.

**Comment by yhahn** [comment]
- [x] **Add a template var `test` to the style template.** The vars to this template are passed in here (https://github.com/mapbox/tm2/blob/master/index.js#L148-L155). If you add a value like `test: 'test' in req.query,` then in the template you'll be able to only include test scripts if `test` is in the querystring.
- [x] **Include chai, mocha, and a test lib for the style page in the template.** Do this at the end.
- [x] **Write a really simple test assertion.** And get it to run by going to the style page at like http://localhost:3000/style?id=tmstyle:///tmp-1371d3fb&test=true

Then let's hook it up to travis + phantom.

**Comment by tristen** [comment]
https://github.com/mapbox/tm2/pull/194
