### ISSUE TITLE
Search usability improvements

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#191]
- [x] cmd+f when search is already open should not open browser search.
- [x] Allow user to create a new search based on old search. Right now if a search is in, no way to reset it and start a new search.
- [x] cmd+g only works after search has been started. Cannot start a search with cmd+g.
- [ ] inform user of number of search results or if search result failed.
- [x] Clarify that user must press 'return' to view results. A 'go' button will solve this problem.
- [x] Allow user to press escape to dismiss search UI (currently only works if input is active)
- [ ] On switching tabs, dismiss search from formerly active tab.
- [x] Do not obscure code with search bar
- [x] When dismissing search, remove all highlights in code.

**Comment by ajashton** [comment]
Also: the first two lines are hidden by the search UI. Possibly minor, but if you're treating search as a "don't make me think" mode, you could easily miss something you're searching for.

> switching tabs should dismiss search from formerly active tab

What about: same search is applied to new tab automatically? Given that the same variables, filters, etc can be used across stylesheets, searching across an entire project might be a common task.

**Comment by samanpwbb** [comment]
Closing for now - search is acceptable.
