### ISSUE TITLE
Light cleanup of new tab creation

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#192]
Now that we don't require a user from entering `.mss` we should make sure a file extension isn't added to the filename on tab creation.

![tab-creation](https://f.cloud.github.com/assets/61150/2388929/3a09f88e-a947-11e3-8de4-88dcdf31e4c1.gif)

**Comment by samanpwbb** [comment]
Here's what I'd like to see:
1. Automatically append '.mss' to the end of the filename, like this:
   ![screen shot 2014-03-11 at 2 05 43 pm](https://f.cloud.github.com/assets/108094/2388973/d279b1d6-a947-11e3-9105-477aa161a129.png)
2. Show '.mss' on the tabs. Users should know what kind of file they are writing to. TM2 should correctly educate users about the makeup of a TM2 project in the file system - it's important to be aware of this if you're using TM2.

**Comment by samanpwbb** [comment]
Will be wrapped in to #201
