### ISSUE TITLE
new layout broken at  >1580px

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#198]
started after https://github.com/mapbox/tm2/pull/195

![image](https://f.cloud.github.com/assets/1056106/2400710/9512d2d4-aa0d-11e3-9e5c-6bce1dd35eeb.png)

@edenh @samanpwbb

**Comment by edenh** [comment]
@ian29 I can't reproduce. Is this still an issue after https://github.com/mapbox/tm2/commit/8e0f2e7dbd88702929ebc644e9a7f735618552d4 ?

**Comment by connor** [comment]
@edenh works fine for me now (at 2421px wide).

![](http://cl.ly/image/1p2e3z461L2j/Screen%20Shot%202014-03-13%20at%2010.25.42.png)

**Comment by edenh** [comment]
Thanks @connor
