### ISSUE TITLE
Profiling tools

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#20]
Brainstormed some concepts on the train to help designers determine how fast/slow their styles are in terms of rendering speed.

Will prototype.

cc @ian29 @ajashton @springmeyer

**Comment by springmeyer** [comment]
Great, curious to hear your ideas. Starting really high level I think will be good - like just providing quick feedback on aggregate tile load times (maybe reporting a small sparkline of last 10 saves?) or a quick hover per tile mode. I logged more low level ideas previously at https://github.com/mapbox/mapbox-streets/issues/368

**Comment by yhahn** [comment]
y agreed

**Comment by yhahn** [comment]
I've started some experiments with this in the `renderstats` branch. Currently focusing on measuring render time (ie. excludes time to download/cache hit vector tiles, map compile/load time, etc.) as it's the most relevant stat for the designer to tune for.

The code so far stores min, max, and avg for tile draws. I wanted to see if this stat would yield consistent enough results to be useful. So far, it looks like yes, with max sometimes being an outlier (e.g. you start watching a youtube video while your map is loading === single max outlier).

![stats-1](https://f.cloud.github.com/assets/83384/494140/108d8e78-bb89-11e2-8733-bd3b9ee89832.png)

![stats-2](https://f.cloud.github.com/assets/83384/494143/48dd27de-bb89-11e2-8016-4f91a7536bbe.png)

![stats-3](https://f.cloud.github.com/assets/83384/494144/48ee73c2-bb89-11e2-8cb6-56080d109b26.png)

Next question for me is how it feels to use these stats and whether they can actually be used during the design process. Would love for you guys to try it out @ajashton @ian29 @springmeyer 

---

ps. I also briefly tried storing stats on a _per-tile basis_ and quickly backed out. My brief notes: a lot of overhead, difficult to convey data in an actionable manner, or rather, possibly too much detail overall to be useful.

**Comment by yhahn** [comment]
Merged.
