### ISSUE TITLE
Clarify forms

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#201]
![screen shot 2014-03-12 at 3 07 20 pm](https://f.cloud.github.com/assets/58878/2401768/caf78744-aa19-11e3-8f81-0a47dd43fd65.png)

What requested format?

Only figured it out through trial and error. The html indicates a `\w+` pattern, which should be explained in the interface somewhere.

**Comment by samanpwbb** [comment]
Yeah, we need helper text for this throughout the UI

**Comment by samanpwbb** [comment]
Done in #227
