### ISSUE TITLE
Rework projects view

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#207]
We could clarify the meaning of the left and right panels of the projects view by reworking the layout a bit. 

Here's a first sketch:
![screen shot 2014-03-13 at 2 44 26 pm](https://f.cloud.github.com/assets/108094/2413568/8bc19760-aadf-11e3-917f-5f2915c5d7ba.png)

This also makes #206 easier to solve for projects panel.

**Comment by tristen** [comment]
Oh I like how this separates the headspace a **projects settings** vs **other projects + sources** in the 2nd wire.

**Comment by samanpwbb** [comment]
Covered in https://github.com/mapbox/tm2/pull/218
