### ISSUE TITLE
cmd+d conflict

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#211]
cmd+d is delete line in codemirror
it's open data panel in tm2

**Comment by incanus** [comment]
The cmd-d shortcut traditionally on OS X means either "go to desktop" (in file picker panels) or "throw away unsaved changes" in unsaved changes prompts.

**Comment by samanpwbb** [comment]
cmd-d is also 'add-bookmark' in chrome. Not a good keybinding to use.

**Comment by incanus** [comment]
Same in Safari, actually -- forgot since I never use it.

**Comment by kkaefer** [comment]
Other shortcuts conflict too, e.g. Cmd+H, Cmd+Alt+I
