### ISSUE TITLE
make fields selectable in layer view

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#219]
would be great if you could copy+paste fields from the layer fiew into your CartoCSS

![image](https://f.cloud.github.com/assets/1056106/2425786/ded666ac-abba-11e3-9a59-f807a94bb045.png)

**Comment by samanpwbb** [comment]
Oops, fixed with https://github.com/mapbox/tm2/commit/1a5a984c7e7d2822163b2e37fc5237df667eb785
