### ISSUE TITLE
Deleting projects from within app

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#22]
Out of curiosity ss this something you expect to be able to do? I find that other desktop apps generally don't provide this so was curious what your take is.

**Comment by ian29** [comment]
i have a lot of trash projects that would create serious clutter without an easy delete option

**Comment by yhahn** [comment]
do u have a file manager

**Comment by ajashton** [comment]
Probably best to leave this to the file manager, where it's clear to the user what is being removed. From the TileMill UI there could be confusion around whether its deleting from disk or simply 'forgetting' about it from the screen.

**Comment by ajashton** [comment]
Also if the user is doing things correctly they should have to `git rm` to remove anything :P
