### ISSUE TITLE
Code Window Scroll Bug - Chrome

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#23]
On Ubuntu 12.04 - just on Chrome 26 (FF works fine) - the scrolling behavior of the code window is wonky, like there's a rubber band holding the text to the top. [Video here](http://youtu.be/VP-JFRMrsF8).

**Comment by ajashton** [comment]
Weird. Doesn't happen in Chrome 27 on 13.04

**Comment by wboykinm** [comment]
Considering market saturation of 12.04 you can probably ignore it then :)
