### ISSUE TITLE
When toggling back to default map/code view, change "x" icon to "minimize" icon?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#231]
To me, the "x" icon doesn't make sense:
![screen shot 2014-03-19 at 1 12 51 pm](https://f.cloud.github.com/assets/5607844/2463547/13be6182-af8d-11e3-9c61-5b1b4356fe06.png)
![screen shot 2014-03-19 at 1 12 42 pm](https://f.cloud.github.com/assets/5607844/2463469/637045ca-af8c-11e3-8ab9-5649a274e092.png)

I think it would make more sense for it to be a "minamize" icon that matches the "fullscreen" icon, since you aren't exiting the map entirely but just undoing the fullscreen state:
![](https://cdn4.iconfinder.com/data/icons/eldorado-player/40/window_close-128.png)

I notice that using an "x" to undo a fullscreen state is a convention we use in base (we don't even have a "minimize" icon). I don't think this is intuitive unless the fullscreen is a modal – which in this case, it's not. 

Does anyone else have an opinion on this?

**Comment by edenh** [comment]
I suggest we go with the <code>brackets</code> icon to be explicit about where the button leads. 

![screen shot 2014-03-19 at 10 49 30 am](https://f.cloud.github.com/assets/1577766/2463727/dd6cf10a-af8e-11e3-8a19-2c1c77f418c0.png)

**Comment by samanpwbb** [comment]
now simply changing bg color. I think this works well.
