### ISSUE TITLE
Bookmarks duplicated on every save

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#232]
![screen shot 2014-03-19 at 6 24 08 pm](https://f.cloud.github.com/assets/108094/2466813/3634600e-afb5-11e3-82aa-b30ae883a6ba.png)

**Comment by edenh** [comment]
@samanpwbb I'm having trouble reproducing this. Could you try clearing <code>tm2.bookmarks</code> from local storage?
