### ISSUE TITLE
Save a project even if there are errors on the page.

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#236]
I lost a few minutes worth of work designing a map when I:
1. Dropped a variable value declared in a **stylesheet-one.mss** used in **stylesheet-two.mss**
2. Continued working in **stylesheet-one.mss**, clicked save and restarted tm2. 

There are a couple ways I can think of to combat this:
1. Only allow variable values to be used in the stylesheet it's in. or [expose them](https://github.com/mapbox/tm2/issues/119)
2. Save a project even if there are errors on the page.
3. Surface inline carto errors
4. is a pretty debatable idea as the map would obviously fail to render. Other ideas?

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/issues/286
