### ISSUE TITLE
Source viewer isn't working

### ISSUE THREAD

**Issue by mojodna** [mapbox/mapbox-studio-classic#238]
http://localhost:3000/source?id=mapbox:///mapbox.mapbox-streets-v4 should display source data as a slippy map.  Since updating today, it has stopped requesting tiles.  (Not sure when this regressed, as I haven't used the source viewer/editor since the most recent spike started).

**Comment by samanpwbb** [comment]
Hm, this should work in latest master. What errors are you seeing? Did you rebuild your node_modules after updating?

**Comment by mojodna** [comment]
No errors.  Rebuilt `node_modules/` against Node-0.10.26.

![screen shot 2014-03-24 at 3 10 57 pm](https://f.cloud.github.com/assets/45/2506028/37707cc4-b3a1-11e3-8dc1-a53011c3113f.png)

**Comment by mojodna** [comment]
Err, scratch that.  Switching to proper `master` mostly works.  Probably something unstashed sticking around.
