### ISSUE TITLE
fix positioning of error notice

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#240]
![screen shot 2014-03-25 at 10 58 06 am](https://f.cloud.github.com/assets/108094/2516220/b7501bb6-b44b-11e3-961e-99727d87ae83.png)

Guessing this broken when upgrading codemirror

**Comment by edenh** [comment]
@samanpwbb where was this error notice positioned before the upgrade?

**Comment by samanpwbb** [comment]
The yellow highlight covered the line number

**Comment by aaronlidman** [comment]
Previously:
![screen shot 2014-03-25 at 7 58 18 pm](https://f.cloud.github.com/assets/58878/2519784/63cd21ae-b479-11e3-8a68-c313b8815680.png)

I'm working on this.
