### ISSUE TITLE
List remote source layer properties

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-studio-classic#243]
It would be nice to reference layer properties while in source view without having to click on an actual feature. Currently, only local source layers have a toggled pane for fields and their descriptions:

![screen shot 2014-03-25 at 4 28 50 pm](https://f.cloud.github.com/assets/1577766/2519641/6b4eaa22-b476-11e3-8861-80d964e3c149.png)

We should:
- [x] Clarify this pane with better formatting (possibly add column headings?)
- [x] Add this pane when inspecting remote sources as well, with un-editable description fields

**Comment by samanpwbb** [comment]
Closed with https://github.com/mapbox/tm2/pull/252
