### ISSUE TITLE
Make setting/understanding projection easier in source editor  

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#245]
Right now, loading up a shapefile that is in WGS84 defaults to 900913 and the data looks broken. Unless you already know about projections and formats, there's no way to know that you need to switch it over. 

Can we clarify the situation by asking user for projection off the bat /  adding help text to projection dropdown / autodetecting format / ???

**Comment by ajashton** [comment]
TM1 is able to autodetect projections in most cases; I assume we can have the same functionality for TM2? Also somewhat related: #98

**Comment by yhahn** [comment]
Long quest. We don't want to implement this in the same way it was done in TM1.

**Comment by springmeyer** [comment]
To do this better from my perspective we need to tackle #171.

**Comment by yhahn** [comment]
Rough outline in my head is
- [ ] Add a route that the UI can hit to request srs autodetection for a given filepath ... (?)
- [ ] The route calls some library (node-srs ? subset of millstone https://github.com/mapbox/millstone/blob/master/lib/millstone.js#L899-L944?) that detects srs for the file
- [ ] UI takes that value and includes it in the form

**Comment by yhahn** [comment]
@GretaCB here's the meta-background ticket.

**Comment by yhahn** [comment]
@GretaCB did this.
