### ISSUE TITLE
geojson sources appear to not work

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#246]
I tried to use geojson from https://github.com/benbalter/dc-maps/blob/master/abra-licensee.geojson - it passes http://jsonlint.com/ just fine, but errors in TM2 with a file not found:

![screen shot 2014-03-26 at 3 02 16 pm](https://f.cloud.github.com/assets/108094/2529301/2f2b458e-b519-11e3-8360-6c3d308f76cb.png)

**Comment by ian29** [comment]
geojson sources work for me consistently. @samanpwbb maybe your geojson is weirdly formatted? can you post? 

or can we close?

**Comment by samanpwbb** [comment]
Okay, now geojson sources are working. They definitely weren't for a while. Tested with https://github.com/benbalter/congressional-districts/blob/2233c76ca5bb059582d796f053775d8859198ec5/IL/04.geojson and works just fine.
