### ISSUE TITLE
JS error after deleting source in source mode

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#247]
Steps to reproduce:
1. Make a new project
2. Add json data source
3. Save
4. Delete that source
5. Add a new data source
6. Upon saving, I get this error: `Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

Attempting to add future data sources give the same error.

The source of the error is at: https://github.com/mapbox/tm2/blob/106c948869b9e37a1aded0ae2fbbf6f0b66748d6/templates/source._#L538

Possibly related to #246

**Comment by yhahn** [comment]
Hrmm, no longer seeing this and makes sense since gridControl is removed. Closing.
