### ISSUE TITLE
Clicking zoom or bookmark buttons in fullscreen mode

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#249]
If you're in fullscreen map mode and you click one of the buttons at the bottom left, you get kicked out of full screen mode.

**Comment by samanpwbb** [comment]
Moving away from :target-based toggle for search + returning false on controls would solve these problems, and agree would be nicer.

**Comment by yhahn** [comment]
Not going to do this, we're designing around exclusive states for now.
