### ISSUE TITLE
Add error handling for text-face-name

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#25]
Ubuntu 12.04, FF 20.0 . . .

TM2 fails to throw an error when an invalid font is plugged into `text-face-name`, instead it just [doesn't render the affected tiles](http://flic.kr/p/ej6Kov). 

TM1 (or whatever you're calling it), handles this with the usual highlight and verbose error:
`Invalid value for text-face-name, the type font is expected. Umpqua (of type string) was given. (line X)`

**Comment by yhahn** [comment]
Should be addressed by https://github.com/mapbox/tm2/commit/f77c3312c1b0468cbd3918d5d6a49bb6c190227d
