### ISSUE TITLE
Composited source names get too long for the UI

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#250]
In both the layers list header and in the source selection UI ("+ Data" button), something like "Mapbox Streets V4 + NE Bathymetry + My Custom Layer" gets truncated so it's hard to tell different composited sources apart.

One idea other than just showing the full source name somehow would be to allow custom names for composited sources rather than "Name1 + Name2 + etc"

![](http://i.imgur.com/1WZB7hN.png)

**Comment by yhahn** [comment]
Almost certainly not going to fix with custom names, but if you could name them customly what would you name such a composite?

**Comment by ajashton** [comment]
Something project specific or just a short nickname. Like streets + terrain + bathymetry might be "Outdoors". If I'm working with a custom layer, I might want the title to be just focused on that part (eg "My favorite hiking trail").

**Comment by samanpwbb** [comment]
I un-truncated the data source name here, seems to work fine.

**Comment by ajashton** [comment]
Still an issue for the source selection. These are all different sources:

![](http://i.imgur.com/vtYWmLQ.png)

**Comment by yhahn** [comment]
@ajashton guessing you wouldn't miss all these `No description.`s ? @samanpwbb what do you think about nuking the descriptions which seem like they're becoming less important and letting the title wrap here?

**Comment by samanpwbb** [comment]
@yhahn i am halfway through this right now. Planning on shrinking the data source listing in a few ways. This should be more differentiated from the settings source list to avoid confusion.

**Comment by yhahn** [comment]
:+1:

**Comment by samanpwbb** [comment]
:arrow_right:   https://github.com/mapbox/tm2/pull/278

**Comment by samanpwbb** [comment]
Closed with #278
