### ISSUE TITLE
Emphasize/clarify zoom bounds settings in source mode 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#251]
Easy to miss zoom level settings when making vector tiles. User _needs_ to think about this for both individual layers and for entire source. For the longest time, I was trying to upload simple vector tiles from csv's/shp files and getting `Invalid upload Error: Tilesource has invalid longitude as center` errors

**Comment by yhahn** [comment]
@samanpwbb let's voice on this sometime -- I'd love to try to advance tech to the point where these settings can disappear/be configured automatically.
