### ISSUE TITLE
Direct upload to mapbox.com

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#258]

**Comment by yhahn** [comment]
Let's discuss : )

**Comment by aaronlidman** [comment]
Style uploading is in place. If tm2z uploads are enabled on your account, you should see an upload button.

**Comment by jqtrde** [comment]
That's awesome, congrats! :+1: 

Any way I can get this enabled for my account? (jacques)

**Comment by animaux** [comment]
I’d like to know how to be able to enable this for my account too. What is the official way? (ar@animaux.de)

**Comment by brockpetrie** [comment]
Any updates on this? Would love to be able to publish my map to my account. Not seeing any upload functionality anywhere, in TM2 nor Mapbox.

**Comment by yhahn** [comment]
style uploads are in place, follow https://github.com/mapbox/tm2/issues/472 for sources
