### ISSUE TITLE
Installing TM2

### ISSUE THREAD

**Issue by patrikkernke** [mapbox/mapbox-studio-classic#26]
Hello TM-2 Team,
By installing TM2 with your manual at github I receive an error: "npm-gyp rebuild failed with 1". It is happening at the "npm install" command. Can you help me please?

**Comment by springmeyer** [comment]
Can you paste the whole error? `npm-gyp rebuild failed with 1` does not provide anything helpful, only the outcome.

**Comment by springmeyer** [comment]
@chargol - did you see my question?

**Comment by ivancamilov** [comment]
I think I have the same problem. Here's a gist of my output when running npm install https://gist.github.com/ivancamilov/5746531.

I'm trying to install it on Ubuntu Precise.

**Comment by springmeyer** [comment]
@ivancamilov - looks like you have a problem with your mapnik version. Are you running v2.2.0. If not you should be. Check your mapnik version with `mapnik-config -v`.

**Comment by JAYSONHOOGY** [comment]
I am not able to run TM2 after following the instructions. I get the following info. 
https://gist.github.com/JAYSONHOOGY/5763299

**Comment by springmeyer** [comment]
@JAYSONHOOGY - that error indicates the node-mapnik did not install properly (the error would have flown by in earlier terminal output). Can you tell me 1) what node version you are running, 2) how you installed mapnik itself, and when, and 3) what is the output if you  do `npm install https://github.com/mapnik/node-mapnik/tarball/vector-tile`

**Comment by JAYSONHOOGY** [comment]
@springmeyer 1) Sorry I am a noob and I don't know how to get the version of node. 2) I had Tilemill 1 initially installed but uninstalled it before trying to install TM2, so mapnik must have been installed with this version, but I assumed it would update with the commands for installing TM2. 3) Here is the output. https://gist.github.com/JAYSONHOOGY/5771633

**Comment by JAYSONHOOGY** [comment]
@springmeyer I have created a fresh install of Ubuntu and installed TM2 and it is now running fine.

**Comment by springmeyer** [comment]
great, thanks for following up.
