### ISSUE TITLE
adding a new sql layer fails with invalid protocol error

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#262]
on 03df6ae
1. create a new source project 
2. add a sqlite or postgis layer
3. see this guy:

![image](https://cloud.githubusercontent.com/assets/1056106/2555159/266420f8-b6bb-11e3-9db5-49dddf64940c.png)

doesnt happen with csv/geojson/shp data source

**Comment by ian29** [comment]
happens after #241. previous commit (9e40612) lets you add postgres/sqlite layers just fine

**Comment by springmeyer** [comment]
Second time this has broken recently. #226 was also just postgis/sqlite. We need tests for all supported sources.

**Comment by ian29** [comment]
still hitting this as of e5e3e2b : |

**Comment by ian29** [comment]
fixed by #282
