### ISSUE TITLE
Adding style to map doesn't report carto error, prevents map save

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#265]
![screen shot 2014-03-28 at 6 11 51 pm](https://cloud.githubusercontent.com/assets/108094/2555842/10605186-b6c6-11e3-9e33-58075c706996.png)

That `line-color: red;` line gives me an error in the console, but no signifier anywhere in the UI. When I try to save my map, I see a spinner, so it looks like the map saved. However, the console error tells me that the save doesn't actually go through (and it doesn't). 

This could be related to https://github.com/mapbox/tm2/issues/85

**Comment by tristen** [comment]
Also #236 ?

**Comment by aaronlidman** [comment]
@samanpwbb you still seeing this? Works as intended for me.

![screen shot 2014-04-04 at 4 19 07 pm](https://cloud.githubusercontent.com/assets/58878/2619928/7b43f6a4-bc36-11e3-93ad-b5a4a168dcea.png)

**Comment by ajashton** [comment]
If the error occurs on a line not currently visible in your editor, there is no indication that something went wrong. It looks like a successful save.
