### ISSUE TITLE
baselayer on by default

### ISSUE THREAD

**Issue by MateoV** [mapbox/mapbox-studio-classic#268]
I feel like if a baselayer is defined this toggle should be on by default. In my experience you would want this on the vast majority of the time and it is a little annoying having to hit the toggle every time the project is opened.

**Comment by samanpwbb** [comment]
This could be confusing for users who are building base-maps. A newbie would not know necessarily know where the base-layer ends and their style begins.

We should however store the baselayer toggle setting between page refreshes.

**Comment by MateoV** [comment]
> We should however store the baselayer toggle setting between page refreshes.

Yes, saving its state would be enough.

**Comment by samanpwbb** [comment]
talked with @yhahn - on by default is fine because new maps don't have any baselayer at all, so this would not actually lead to confusion.
