### ISSUE TITLE
Mapnik S3 URL is busted

### ISSUE THREAD

**Issue by zeke** [mapbox/mapbox-studio-classic#27]
I'm here at SOTMUS, trying to set up TM2, but the S3 url in [the gist](https://gist.github.com/springmeyer/f2f85aad63f1597ddd5b) mentioned in [the readme](https://github.com/mapbox/tm2/commit/507044bf3270e0defad2c52a9ed89f14d32dfa1b#L0R11) seems to be 404ing.

http://mapnik.s3.amazonaws.com/dist/mapnik-osx-v2.1.0-1105-g98d7b66.tar.bz2

**Comment by springmeyer** [comment]
recommended route now is to install mapnik v2.2.0 via homebrew, see 93793c545c8045363fc37acb22559c3700e1c756

**Comment by zeke** [comment]
Per @springmeyer's recommendation I did a `brew install mapnik`, but I'm still getting errors on `npm install`: 

```
> mapnik@1.0.0 install /Users/zeke/code/forks/tm2/node_modules/mapnik
> node-gyp rebuild

  CXX(target) Release/obj.target/_mapnik/src/node_mapnik.o
In file included from ../src/node_mapnik.cpp:12:
../src/mapnik_geometry.hpp:8:10: fatal error: 'mapnik/geometry.hpp' file not found
#include <mapnik/geometry.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/_mapnik/src/node_mapnik.o] Error 1
```

Full stack trace at https://gist.github.com/zeke/5736594

**Comment by springmeyer** [comment]
what does `mapnik-config -v` return for you?

**Comment by zeke** [comment]
```
~/code/forks/tm2 master  → mapnik-config -v
2.2.0
```

**Comment by springmeyer** [comment]
@zeke - that looks right. It might be that you have duplicate mapnik installs via brew. Can you check that?

**Comment by springmeyer** [comment]
or it could be that you installed the mapnik.pkg (which does not provide headers). you'll need to ensure, if that is the case, that the homebrew version is installed.
