### ISSUE TITLE
Disable 'package' and 'upload' buttons on tmp maps

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#270]
![screen shot 2014-04-01 at 4 37 00 pm](https://cloud.githubusercontent.com/assets/58878/2584378/c8a3cd26-b9dd-11e3-8663-7299d82e5c62.png)

Because packaging tmp maps causes the server to crash, which should also be fixed. Should use the brand new .pill .disabled class.

OR

prompt to save if those buttons get clicked on a tmp map

**Comment by springmeyer** [comment]
related: #104
