### ISSUE TITLE
update layer list to reflect layers config in project.yml

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#272]
if user has duplicated or re-ordered data in layer list, reflect this in the project's data inspection sidebar.

**Comment by samanpwbb** [comment]
@yhahn I started this with https://github.com/mapbox/mapbox-studio/compare/layer-list-up

One thing to figure out first: there are a couple competing concepts around sources right now: 
- Configuring layers in the project.yml doesn't have any concept of separate sources - everything just goes in one flat list.
- The 'sources' object in the style template on the other hand assumes multiple sources.
- In the UI, right now we treat everything like one single source even if a style references multiple sources.

I don't have my head fully wrapped around this, but I think we need to make a decision between a) representing each source separately in the UI _or_ b) reinforce the single _composite source_, toss out the idea of multiple sources. I like option b) - I think it's simpler for users or more straightforward to represent in the UI, especially when we get into layer re-ordering.

**Comment by samanpwbb** [comment]
One more thing: In preparation for work on layer re-ordering, would it also make sense to automatically save data layers to and then read them from a project's yaml file?

**Comment by yhahn** [comment]
**b** is the way to go. There is no representation of the ingredient sources once they're composited together in vector tiles and we shouldn't pretend that there is.

@samanpwbb let's punt on any plans to actually edit the layer list in this fashion and focus on just showing customizations if a power user has provided them.

**Comment by samanpwbb** [comment]
This is done.
