### ISSUE TITLE
cursor positioning around color swatch is broken

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#273]
Codemirror doesn't correctly display cursor position around swatches. Not exactly sure how to describe the behavior right now, but it is not what I would expect.

**Comment by edenh** [comment]
I know _exactly_ what you mean. As a somewhat-temporary fix for the cursor problem, we can place the palettes at the end of the line. This does create a few weird edge cases:

![screen shot 2014-04-01 at 6 26 24 pm](https://cloud.githubusercontent.com/assets/1577766/2586632/1e715e62-ba06-11e3-8b63-edc10fc641cc.png)

**Comment by samanpwbb** [comment]
Ah, much better. Closing for now, we can make a new issue to address related issues.
