### ISSUE TITLE
search does not work in firefox

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#281]
type in any place, hit enter, go nowhere

**Comment by ajashton** [comment]
In addition to not showing any results, search now messes up the css (in both master and design-adjustments):

![](http://i.imgur.com/PmGf7Dx.png)

**Comment by samanpwbb** [comment]
Ya - this needs a refactor. Will take a look.

**Comment by samanpwbb** [comment]
Works now.

**Comment by ingalls** [comment]
I'm afraid this still doesn't work in firefox.
