### ISSUE TITLE
Retina mode

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-studio-classic#283]
It'd be great to have a button that would switch on `detectRetina: true` for when working on a retina screen/developing for a retina screen.

Right now you can scale text/items on tiles but the tile itself cannot be scaled down to `128px` within tm2.

cc @samanpwbb

**Comment by rclark** [comment]
:+1: I tried throwing in `detectRetina` but it didn't work the way I expected it to.

**Comment by bsudekum** [comment]
@rclark it can be tricky to get it to work sometimes, make sure you're applying it to the tileLayer and not the map. Something like:

```
L.mapbox.map('map','mapid.foo',{
  tileLayer: {
    detectRetina: true
  }
});
```

Also, if we want this to be available to all users, regardless if they're on a retina screen or not, we can add `L.Browser.retina = true;` to force leaflet into retina mode.

**Comment by yhahn** [comment]
Tracking here https://github.com/mapbox/tm2/issues/329. This will be a bit different from the current retina mode in mapbox.js and will likely involve an update to mapbox.js that handles 512x512, 1024x1024, etc. tiles.
