### ISSUE TITLE
return mapid on successful style upload to mapbox.com

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#285]
i dont know how much work this would be, but it would be great to have a copiable mapid in the dialog letting you know that your style has successfully uploaded. 

![](http://cl.ly/image/380K0p2w212N/Image%202014-04-09%20at%204.41.20%20PM.png)

@aaronlidman

**Comment by aaronlidman** [comment]
@ian29 Yep agree. I can expose a mapid easily but I'd prefer to link directly to an open map pane on mapbox.com/data, something like `http://mapbox.com/data?mapid=awesomemap.ian29` which will open that exact map.

We have an internal ticket (3757) about this.
