### ISSUE TITLE
Automatically fix/fill file name extensions for users everywhere

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#288]
Let users either use or omit extension when naming files, add it for them after submission. Right now we do this for mss tabs but not elsewhere in the app and it's confusing.

**Comment by aaronlidman** [comment]
I'll try hitting this before I'm out next week but no promises, big weekend.

**Comment by aaronlidman** [comment]
Done in https://github.com/mapbox/tm2/pull/325.
