### ISSUE TITLE
No tabs after removing the last tab

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#295]
![no-tab](https://cloud.githubusercontent.com/assets/58878/2698839/3d769040-c3ff-11e3-8cbe-f347295df48d.gif)

Fix the UI or don't allow the last tab to be removed.

The actual stylesheet is created, I'm guessing we just need a better selector.

**Comment by samanpwbb** [comment]
Should be a pretty easy fix with a better selector.
