### ISSUE TITLE
Scrolling issues in Chrome

### ISSUE THREAD

**Issue by jqtrde** [mapbox/mapbox-studio-classic#296]
Running `OSX 10.9.2` with `Chrome 33.0.1750.152`.

Scrolling in the editing panel causes it to disappear. The only way I'm able to restore visibility is by zooming in on the map. Doesn't happen in Firefox.

![](http://i.imgur.com/myZszg7.gif)

Anyone else?

**Comment by springmeyer** [comment]
have not tested, but curious: do you see any js errors in the js console?

**Comment by jqtrde** [comment]
Nope, nothing in the console. Chrome has been acting wonky in some other situations for me as well. If no one else is having the same issue I'll go ahead and close this.
