### ISSUE TITLE
TM2 only for generating map tiles?

### ISSUE THREAD

**Issue by crofty** [mapbox/mapbox-studio-classic#30]
Hi,
I've used tilemill in the past and I'm just starting to take a look at tm2 - thanks for releasing them.

Is tm2 only for generating map tiles?  The reason I ask is that I used to use tilemill from the command line to generate maps of arbitrary size with custom styles.  I know this functionality doesn't exist in tm2 but is something like this even possible when using a vector tile source or is the only output map tiles?

Thanks

**Comment by yhahn** [comment]
@crofty it's our plan to make it possible to generate images of arbitrary size/bounds with TM2 eventually. Will keep you posted here.

**Comment by crofty** [comment]
@yhahn is it possible for you to give me a high level run down of the things that need to be done in order to generate images of arbitrary size?  It's something that I would like to start exploring.

**Comment by dkniffin** [comment]
I'd be interested in this breakdown as well. I was thinking of trying to take a stab at some sort of export functionality, but I have no idea where I'd start.
