### ISSUE TITLE
Seeing "No spaces allowed" error when filename does not contain spaces

### ISSUE THREAD

**Issue by zeke** [mapbox/mapbox-studio-classic#304]
![no-spaces](https://cloud.githubusercontent.com/assets/2289/2714071/5e35fc3e-c4f0-11e3-816a-bbe75399502f.png)

**Comment by samanpwbb** [comment]
@zeke nice catch. This needs to match the regex ( https://github.com/mapbox/tm2/blob/master/templates/source._#L215)

**Comment by samanpwbb** [comment]
fixed with https://github.com/mapbox/tm2/pull/303
