### ISSUE TITLE
add additional source to style 

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#306]
currently the UI there's no way to add an _additional_ vector tile source to your style project. the UI allows you to change vector tile sources for your style, but you can't add an additional vector tile source. 

adding a new composited vector tile source seems like a reasonable workflow: imagine you have a basemap style (remote) that you rarely change, but you want to swap out vector tile data being composited with that remote basemap. it would not be fun to have to first create composited source, and then reference that in you style. 

you already have a style, and you just want to add some data on top. 

cc @samanpwbb

**Comment by yhahn** [comment]
Compositing sources together isn't particularly more posh now but there's no extra step of adding the source and then backtracking to add to your map. Closing for now.
