### ISSUE TITLE
unable to change Map background color at zoom levels.

### ISSUE THREAD

**Issue by ericsond** [mapbox/mapbox-studio-classic#317]
I'd like to be able to change the background color at a particular zoom level. There doesn't seem to be a way to do this through:

Map {
  background-color: #ff0000;
}

Ideally there is a polygon on the lowest layer that can be controlled via css.

Here is a work around described in this thread but wondering if there is a cleaner solution?
http://gis.stackexchange.com/questions/71908/cartocss-different-background-colors-of-map-element

**Comment by springmeyer** [comment]
I'd recommend sticking with the workaround of adding an entire planet polygon layer. There is not a cleaner solution at this point. If this feature were added it would be implemented in [Mapnik](https://github.com/mapnik/mapnik) and then would also need to be supported by [Carto](https://github.com/mapbox/carto). Then tm2 would be able to support it.
