### ISSUE TITLE
Fields don't show up until entire source is saved

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#318]
After loading a new layer for a source from a shapefile I noticed that no fields would show up even though the shapefile layer had seemingly been added/saved by choosing it and clicking "done". Its fields would not display until the entire source was saved. This is going to be very confusing for new users.

**Comment by yhahn** [comment]
_Done_ button is hooked up to updating now. Once we land more datasource inspection we can update even sooner, probably on any change to the filepath https://github.com/mapbox/tm2/issues/171
