### ISSUE TITLE
Source/style extensions

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#321]
Both sources and styles use `.tm2`, it's confusing as they are not interoperable in source/style panes and leads to errors when opening the wrong type.

I'm partial to changing sources to `.tm2source` and leaving styles as `.tm2`.

Thoughts?

**Comment by lxbarth** [comment]
Give sources `.vt` extension for vector tiles? Or `.vtf` for vector tile file or `.vtiles` to go with `.mbtiles` flow?

**Comment by ajashton** [comment]
Need to finish the opening projects side of this. I took a quick look but couldn't figure out where to make the change.

**Comment by aaronlidman** [comment]
@ajashton Can you try that ^ fix?

**Comment by ajashton** [comment]
:+1:
