### ISSUE TITLE
source export doesnt save changes?

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#323]
i often change the zoom levels around right before exporting, but if i don't hit the save button first, an export doesn't respect any last-minute changes (i.e. changes to the zoom  range)

**Comment by ian29** [comment]
not sure if it's desirable to have the `export` button function as `save+export`. i see at least 2 options to clarify what's going on:
1. have the button say `save+export`, and have the button do that
2. disable `export` button until project is saved

**Comment by aaronlidman** [comment]
Same as style packaging/uploading? Save then export.

**Comment by ian29** [comment]
i think the problem is that the current flow allows you make changes to your project, hit export, and have you export reflect a past state of your project. again, just needs clarification.

**Comment by sgillies** [comment]
@ian29 I just stumbled over the same thing. How about a 3rd option: save when a zoom slider is released?

**Comment by samanpwbb** [comment]
> disable export button until project is saved

I like this approach.

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/pull/568

**Comment by ian29** [comment]
\o/
