### ISSUE TITLE
Local PostGIS OSM Source - "missing parameter..."

### ISSUE THREAD

**Issue by srsjojo** [mapbox/mapbox-studio-classic#326]
I'm trying to host my own local OSM data for Washington State. I've loaded the geofrabrik extract into Posgres with `osm2pgsql`. When I go to the Sources tab and add a new PostGIS source I put in the exact info from the `\conninfo` command in `psql`. When I hit "Save" I get an error at the bottom that says 

`Postgis Plugin: missing parameter encountered during parsing of layer <layername> in Layer at line 18` 

and the Terminal where I launched `tm2` says 

`[Error: Postgis Plugin: missing <table> parameter]`

**Comment by springmeyer** [comment]
Its quite confusing - the UI needs more work, but to get this working you want to go to the `SQL` tab for the postgis layer and enter the table name in the large box:

![screenshot 2014-04-25 18 01 32](https://cloud.githubusercontent.com/assets/20300/2807118/747f8f3c-ccde-11e3-940c-a7e48f17848d.png)

**Comment by srsjojo** [comment]
That's awesome, thanks Dane. Will I want to put in all the tables under the same layer?

``` planet_osm_line
planet_osm_nodes
planet_osm_point 
planet_osm_polygon
planet_osm_rels 
planet_osm_roads   
planet_osm_ways    
```

**Comment by springmeyer** [comment]
no, you need a new layer per table. And that textarea either supports the tablename or a subquery in the same format as TileMill 1 (step 6 at https://www.mapbox.com/tilemill/docs/guides/postgis-work/).
