### ISSUE TITLE
saving in the UI destroys layers array

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#330]
1. manually edit the `layers` array in `project.yml` in text editor + save changes
2. restart tm2, as with all manual edit to `project.yml`
3. save project via tm2 UI
4. look at `project.yml`, layers array is no more. 
- this looks specific to the `layers` object, as changes to `center` persist after saving subsequent changes in the UI.
- this seems to be a newish development

**Comment by aaronlidman** [comment]
![](http://media.giphy.com/media/LVsmysvGBiZEs/giphy.gif)

**Comment by ian29** [comment]
also happens to the `bounds` object : \

**Comment by aaronlidman** [comment]
![](http://media.giphy.com/media/13yEy26lZIvDJm/giphy.gif)

**Comment by ian29** [comment]
havent seen this for months, closing.
