### ISSUE TITLE
Tabs disappear after 10

### ISSUE THREAD

**Issue by ingalls** [mapbox/mapbox-studio-classic#332]
If more than 10 tabs are opened the buttons get wrapped underneath the editor pane making them difficult to access.

![screen shot 2014-05-06 at 12 28 50 pm](https://cloud.githubusercontent.com/assets/1297009/2892334/bc10f4b6-d53b-11e3-87df-354d49e799e4.png)

**Comment by yhahn** [comment]
^^ you can add more CSS if you need more tabs : )

https://github.com/mapbox/tm2/blob/master/app/style.css#L37-L59
