### ISSUE TITLE
Tabs Not being deleted

### ISSUE THREAD

**Issue by ingalls** [mapbox/mapbox-studio-classic#333]
If a tab is created, deleted, and then attempted to be created again tm2 does not allow the creation. This suggests that the stylesheet is not actually being deleted.

![tm2error2](https://cloud.githubusercontent.com/assets/1297009/2892524/fbf747e0-d53d-11e3-9d19-19b7289f3283.gif)

**Comment by aaronlidman** [comment]
Probably my bad on #325. I'll look into it.
