### ISSUE TITLE
Modals lose context

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#335]
Right now as soon as a user enters a modal, they exit their current context (defined by the target in the URL), because the modal takes over the context and isn't aware of where it came from. Normally, users expect modal to behave as overlays on top of context, that when dismissed, allow user to return to the previous context. We should seriously consider dropping target based interaction for modals to avoid this dilemma.

Refs: https://github.com/mapbox/tm2/issues/334

**Comment by yhahn** [comment]
Yep, I can look into a sketch that uses something more node-like for modals, e.g.

```
modal('somemodal', options, function(err, data) {
    // callback is called once modal is closed or action is complete
});
```
