### ISSUE TITLE
Inspect button should be toggleable

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-studio-classic#341]
![screen shot 2014-05-08 at 6 03 16 pm](https://cloud.githubusercontent.com/assets/58878/2922125/2628a840-d6fd-11e3-9fa2-479c96eefc34.png)

There's currently no way to turn off inspect mode, it behaves like radio buttons.

Clicking on an already selected button should toggle it.

**Comment by yhahn** [comment]
Possibly being nuked shortly in https://github.com/mapbox/tm2/tree/inspector

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/pull/342
