### ISSUE TITLE
Cannot export mbtiles

### ISSUE THREAD

**Issue by dbaldwin** [mapbox/mapbox-studio-classic#351]
Hi, I'm new here so I apologize if this is a known issue. We have been following the TM2 project for a few months and have been working with various daily builds for OS X. The most recent build (tm2-osx-2014-05-11-8b4328d) will not allow us to export mbtiles. I get redirected to a url such as the following:

http://localhost:3000/mbtiles?id=tmsource:///Users/db/Desktop/medina_rivers.tm2source

But no export status, just a blank screen. Looking at the node console there don't appear any errors or messages.

**Comment by yhahn** [comment]
y, looks like a visual issue -- some stale css needs updating. Will have a fix shortly.

**Comment by yhahn** [comment]
@dbaldwin should do the trick for you -- please reopen if you run into it again on the next build.

**Comment by dbaldwin** [comment]
@yhahn Thanks for the prompt reply. Exporting works great now.
