### ISSUE TITLE
layer drawing order

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-studio-classic#359]
can tilemill 2 specify drawing order for layers within a source?
the layers are dragable, but this doesn't seem to affect the rendering.

**Comment by yhahn** [comment]
Yes, the layer order affects drawing order once you start styling a source. When inspecting a source the the layer UI the layers are drawn in order but use the screen comp-op mode (https://github.com/mapbox/tilelive-vector/blob/master/templates/layer.xml#L1) so visually there is more or less no effect.

**Comment by ghost** [comment]
Right, it only matters once we move to the style interface of course. I was wondering about how to influence the layer order. It seemed like changing the orders of layers in the xml/yml wasn't having effect, but now it seems to be working. I must have been mixed up.

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/issues/363 for reference, may be an issue in the UI currently.
