### ISSUE TITLE
UI icons don't work in Firefox

### ISSUE THREAD

**Issue by gravitystorm** [mapbox/mapbox-studio-classic#36]
The UI icons rely on `background-position-x` (and `-y`) CSS properies to move around the sprite, but this isn't a w3c standard and doesn't work on Firefox.

https://github.com/mapbox/tm2/blob/master/app/base.css#L157

http://stackoverflow.com/questions/9653685/is-background-position-x-background-position-y-a-standard-w3c-css-property

It makes it somewhat challenging to navigate around!

**Comment by yhahn** [comment]
y sorry about that, will fix this up at some point : )

**Comment by ajashton** [comment]
fixed now
