### ISSUE TITLE
a elements need an href

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#361]
Modal refactor seems to have left us with `a` elements with no href attribute. Hovering over these elements doesn't trigger pointer cursor. If the link is just for triggering js event, use `#`. Seems to mostly affect empty states in source mode.

**Comment by yhahn** [comment]
Slight change to recommendation here -- I often use a hash state that reflects a reasonable target as a stopgap/nonbreaking tactic in the event that js event handler is delayed in being attached, e.g. during a page load.

In many cases this is `#` but if a modal is derivative of another state (e.g. `#layers` => change source) you may want to use that state instead.
