### ISSUE TITLE
No way to add a remote source that is not a Mapbox source

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-studio-classic#367]
I have my own server serving vector PBF tiles and would like to add it as a source, but I cannot seem to find a way to add a remote vector tile source that is not a Mapbox source.

**Comment by gravitystorm** [comment]
Yeah, I've run into the same problem when adding a non-mapbox http source, and have to edit the project.yml file by hand to make it work.

https://github.com/mapbox/tm2/blob/master/templates/modalsources.html#L46 is the template and https://github.com/mapbox/tm2/blob/master/app/style.js#L263 is the implementation for adding mapbox layers - perhaps these can be cloned and reworked for an equivalent for non-mapbox http sources.

**Comment by yhahn** [comment]
Taking.
