### ISSUE TITLE
Is »classic MBTiles-Export« even planned for TM2?

### ISSUE THREAD

**Issue by animaux** [mapbox/mapbox-studio-classic#373]
Or will it always only be exporting styles for external tile servers or Mapbox accounts?

**Comment by yhahn** [comment]
TM2 to won't be exporting image tiles again -- vector tiles + styling dynamically is much more versatile.

**Comment by animaux** [comment]
Thanks @yhahn. Good to hear a definite word about this. You are of course right. But MBTiles were a nice and simple way to serve tiles independently. Guess I have to embrace the future :)

**Comment by wboykinm** [comment]
. . . and hang onto a copy of TM1 on a VM :) _Update_: Aha - I thought they were still using different versions of mapnik . . .

**Comment by animaux** [comment]
@wboykinm no need for a VM, they work happily side by side :)

No problem sticking with TM1 for now, it’s just that styling with TM2 is so much smoother.

**Comment by tkrajacic** [comment]
Can't TM2 export vector tiles to an mbtiles file?

**Comment by animaux** [comment]
@tkrajacic My question was regarding raster mbtiles.

**Comment by tkrajacic** [comment]
@animaux sorry, I misinterpreted then, but since I haven't tried out TM2 yet, I wonder if the vector tile in mbtiles format does work indeed? ;)

**Comment by animaux** [comment]
As far as I understand vector tiles are a source-format rather than rendered tiles.

**Comment by yhahn** [comment]
@tkrajacic yes, https://github.com/mapbox/tm2#exporting-and-uploading-a-source-mbtiles

**Comment by animaux** [comment]
A bit confusing both types are called .mbtiles …

**Comment by tkrajacic** [comment]
@yhahn brilliant, I knew I read it somwhere already :)
@animaux Well, a `mov` file can also contain many kinds of different formats. It's just a container such as `mbtiles`
