### ISSUE TITLE
Cannot zoom in & out

### ISSUE THREAD

**Issue by dbaldwin** [mapbox/mapbox-studio-classic#374]
In the latest TM2 build I'm no longer to zoom with the plus/minus buttons in the UI. It's not completely unusable since I'm able to zoom using my trackpad, but wanted to mention. The build I'm using on OS X is tm2-osx-2014-05-18-792705f

Thanks,
Dennis

**Comment by dbaldwin** [comment]
BTW I should mention that this appears to only be a problem when in "source" view. It looks like zoom in/out functionality was removed here:

https://github.com/mapbox/tm2/commit/feff6b476cb52c6d500769b4c39bc4849e4141e5#diff-487c1365e5c2efc56989c5d0310a01a3L94

I'd be more than happy to submit a patch but am new to this project and am uncertain of the process.

**Comment by yhahn** [comment]
Oops, will be an easy fix.
