### ISSUE TITLE
Kicking the tires on naturalatlas node-gdal

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-studio-classic#377]
Background: https://github.com/mapbox/tm2/issues/171#issuecomment-43236258.

I hate to say it, @springmeyer @tmcw, but https://github.com/naturalatlas/node-gdal instantly feels wrong to me.

```
> var gdal = require('..')
> var ds = gdal.open('/Users/sean/code/rasterio/rasterio/tests/data/RGB.byte.tif', 'r')
Error: update must be an integer
    at repl:1:15
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

It wants `0` not `'r'` for the mode argument. Is this right for Node? It's wrong for Python, which is partly why I wrote Fiona and Rasterio ;)

```
> var ds = gdal.open('/Users/sean/code/rasterio/rasterio/tests/data/RGB.byte.tif', 0)
undefined
> ds.getRasterCount()
3
```

There we go. But then...

```
> ds.close()
undefined
> ds.getRasterCount()
Segmentation fault: 11
```

Oof. It's not ready for production and the interface looks like it's the same as the awful SWIG-generated one for gdal.py. I predict it has the same gotchas.

I think we can do better.

**Comment by tmcw** [comment]
> Is this right for Node?

No way, y - this interface looks cruddy and non-idiomatic. We can definitely do better.

**Comment by sgillies** [comment]
What would idiomatic access to raster data look like? Rasterio's is built around Numpy, and that's how I avoid Band objects, but the Node community doesn't have something quite as mature yet, does it?

Would Fiona's interface be useful for Node? Call an `open()` function to get a container of GeoJSON-ish data?

**Comment by tmcw** [comment]
>  Rasterio's is built around Numpy, and that's how I avoid Band objects, but the Node community doesn't have something quite as mature yet, does it?

Closest would be [ndarray](https://github.com/mikolalysenko/ndarray) probably, but I don't know if that would scale well to raster-data-size datasets.
