### ISSUE TITLE
ensure tests can be run cross platform

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#381]
We are currently using bash for the tests. Perhaps we could have a node.js test runner instead?

I pushed a start at this to https://github.com/mapbox/tm2/tree/cross-platform-tests but I'm seeing problematic behavior on os x. After the tests run 3-4 node processes come back from the dead, eat all my CPU, and make a second run fail hard. I presume we need to also port the client test runner to node.js, but I've not had a chance to do that yet.

**Comment by yhahn** [comment]
Hrm, I wonder for now if we can leave the client-side/phantom tests out of the appveyor test run? So npm test will just run mocha and only travis will run the client-side tests?

**Comment by springmeyer** [comment]
:+1:

**Comment by springmeyer** [comment]
nice, your change got the tests actually to run on appveyor (https://ci.appveyor.com/project/springmeyer/tm2/build/1.0.9#L813). They expose that something is broken with the windows build of gdal and also a few failing tests. There should be more output showing up for the failing tests. @BergWerkGIS  and I have observed this problem before - some loss of stderr/stdout - not sure what is going on.

**Comment by wilhelmberg** [comment]
I've also seen that plugin error pop up from time to time, because node-mapnik is not able to locate `mapnik.dll`.
Don't know why. Maybe we still have a hardcoded reference to `C:\dev2` somewhere?

You could try adding the path to mapnik.dll manually and see if this solves the problem.

**Comment by springmeyer** [comment]
@BergWerkGIS you are exactly right. Helped me see a solution, tracking at https://github.com/mapnik/node-mapnik/issues/258
