### ISSUE TITLE
Having a remote source as well as a local source?

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-studio-classic#382]
Is is possible to have a remote source like Mapbox Streets V4 which is the default one and ADD a local shape file as a source?

I figured out that i can add a local shape file as source, but then just have that one...
What I'd like to do is to add some extra information to a source like Mapbox Streets V4.

Btw. there is no "Mapbox Outdoors" source available yet, right?

**Comment by yhahn** [comment]
- Once a local source is uploaded to Mapbox the Mapbox API can composite them together
- Default source for mapbox vector terrain + streets added here https://github.com/mapbox/tm2/commit/8125eae8b2019b6639a7772baab9443b94f37192

**Comment by asherkin** [comment]
While it's great that the Mapbox API can composite them together - that's not a local source.

**Comment by alex88** [comment]
Would be a nice thing to have
