### ISSUE TITLE
url.parse() with windows paths

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#384]
One of the early assumptions of tm2 -- that source/style IDs should be represented as URIs with protocols + filepaths -- seems like it's going to meet some tough love from the windows world.

```
> url.parse('tms://c:\program files');
  slashes: true,
  auth: null,
  host: 'c',
  port: null,
  hostname: 'c',
  hash: null,
  search: null,
  query: null,
  pathname: '/:program%20files',
  path: '/:program%20files',
  href: 'tms://c/:program%20files' }
```

Well... that's terrifying : | Going to mull on this a bit.

**Comment by yhahn** [comment]
Some clues from how browsers use `file://` on Windows:

![file](http://devproconnections.com/site-files/devproconnections.com/files/archive/devproconnections.com/content/content/145221/unsafejavascript.png)

```
> url.parse('tmstyle:///C:/some/path');
{ protocol: 'tmstyle:',
  slashes: true,
  auth: null,
  host: '',
  port: null,
  hostname: '',
  hash: null,
  search: null,
  query: null,
  pathname: '/C:/some/path',
  path: '/C:/some/path',
  href: 'tmstyle:///C:/some/path' }
```

**Comment by springmeyer** [comment]
trying to do `url.parse('tmstyle:///C:/some/path');` looks more promising. In most cases in Node.js you can use forward slashes for windows.
