### ISSUE TITLE
Indenting: Spaces and Tabs

### ISSUE THREAD

**Issue by nilshoerrmann** [mapbox/mapbox-studio-classic#386]
The style editor (= Codemirror) completely messes up indentation if you are using tabs (things won't line up anymore; if you create new lines, indentation combines spaces and tabs). 

The interface doesn't suggest, that tabs aren't supported, so I expected both to work just fine. But it seems like spaces are prefered. If that's the case, the editor should convert tabs to the correct number of spaces in order to keep things consistent in my eyes.

**Comment by samanpwbb** [comment]
Fixed with #392

**Comment by nilshoerrmann** [comment]
Great, thanks!
