### ISSUE TITLE
Style Errors

### ISSUE THREAD

**Issue by nilshoerrmann** [mapbox/mapbox-studio-classic#387]
If an error occurs while saving styles, there are a few usability issues:
- It's not clear to the user that an error occured actually – the map will just not update. 
- The line causing the error will get a light yellow line number:
  1. the highlighting is quite unobtrusive,
  2. the highlighting might easily be out of sight (= out of your current scroll area),
  3. you won't notice the highlighting at all, if the error occured in another tab.

I'd expect the following behaviour:
1. A general notification about the error, not as a modal window, but as some kind of status note above the tab bar.
2. A highlighting of the related tab, if it's not the current one.

**Comment by samanpwbb** [comment]
Started this in [`error-alert` branch](https://github.com/mapbox/tm2/compare/error-alert?expand=1):

![screen shot 2014-07-02 at 6 41 55 pm](https://cloud.githubusercontent.com/assets/108094/3463468/024ffb90-023a-11e4-88eb-ad2058056fff.png)

Not properly implemented, but it'll work well with a bit of polish.
