### ISSUE TITLE
Carto CSS suggestions

### ISSUE THREAD

**Issue by nilshoerrmann** [mapbox/mapbox-studio-classic#388]
Although Carto CSS looks a lot like normal CSS, most of its declarations have nothing in common with CSS. So especially if you are new to Carto CSS, it would be helpful to get on-the-fly suggestions while you're typing.

Also it would be a time saver, if the editor suggested existing variable names, as soon as you type `@` (similar to how user suggestion work here on Github).

**Comment by nilshoerrmann** [comment]
The second part seems to be related to #119.

**Comment by tmcw** [comment]
This is already supported in TM1, needs to be ported.
