### ISSUE TITLE
Tabs and Execution Order

### ISSUE THREAD

**Issue by nilshoerrmann** [mapbox/mapbox-studio-classic#390]
If I have style declarations for the same map feature in different files, one overriding the other, TM2 doesn't make the execution order clear: Does the file in the first tab get executed first? 

If so, why can't I reorder tabs? (At least using Firefox 29 on Mavericks.)
If not so, how is the execution order determined?

**Comment by yhahn** [comment]
Yes, the tabs are compiled in order.

https://github.com/mapbox/tm2/pull/233

**Comment by nilshoerrmann** [comment]
Right, but how do I change the tab order?

**Comment by samanpwbb** [comment]
@nilshoerrmann I can take a look at enabling tab ordering + ensuring cascade adjusts according to tab order. #233 is a bit of an incomplete implementation.
