### ISSUE TITLE
errors in sql query dont return user to sql editor

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#396]
in source mode:
1. make a bad edit to your sql for a postgis or sqlite source
2. read at the error
3. get returned to layers overview

ideally the sql error modal should return users to the sql editor so you dont have to click to get back to where you need to be to fix the project.

**Comment by yhahn** [comment]
No to this for now -- err modals are generic and show when the error occurs and aren't going to direct UI flow beyond that.
