### ISSUE TITLE
Using carto to generate data.xml

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#4]
Per chat convo with @tmcw, https://github.com/mapbox/carto/commit/5d626d3c10f15984752349c0dd717de5f46fa235 breaks tm2's usage of carto for generating style-less mapnik XML for datasources.

Carto's behavior of skipping layers that have no styles defined for them is totally sensible for the rest of the world, so will have to do some meditation on how to proceed here (flag in carto? would it make sense to anyone else? should tm2 just template its own datasource XML (not that much code)?)

Going to pin to a hash for now.

**Comment by springmeyer** [comment]
once https://github.com/mapbox/carto/issues/247 is fixed there will be strong incentive in my mind to start pulling in an updated tag of carto, so this issue should track that.

**Comment by springmeyer** [comment]
the original issue that was solved and broke tm2 usage (https://github.com/mapbox/carto/issues/244) is now a non-critical and could be rolled back. The reason for this is that latest Mapnik also can avoid the overhead of empty styles after https://github.com/mapnik/mapnik/commit/0d8f415070ea527d0045d3f7f864511e35478b64 | https://github.com/mapnik/mapnik/issues/1670
