### ISSUE TITLE
Can't export .Mbtiles

### ISSUE THREAD

**Issue by clemenslermen** [mapbox/mapbox-studio-classic#405]
"Exporting a TM2 source project will give you an MBTiles file containing vector tiles that you can upload to Mapbox.com and use as a source for TM2 style projects."

In my TM2 there is only a "save" button on this position. After saving, there is also a "package" and "upload" button.
How can I export .mbtiles? Will they also be able to be used with leaflet and mapbox tilestream?

**Comment by yhahn** [comment]
See https://github.com/mapbox/tm2/issues/373.

TM2 can export vector tiles from sources and package up styles for deployment on the Mapbox API (coming soon for all accounts).
