### ISSUE TITLE
feature inspection on source not working

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#410]
When creating a source with a json file as a layer, click interaction to view feature data is not working, with this error:
![screen shot 2014-06-02 at 4 12 19 pm](https://cloud.githubusercontent.com/assets/108094/3152746/514dd95c-ea92-11e3-91a2-f638deeff6a2.png)

Here's the source I'm using: https://gist.github.com/samanpwbb/cc310c8651a5ba2dd344

**Comment by yhahn** [comment]
Can you see if you're updated to tilelive-vector 0.12.1? See

https://github.com/mapbox/tm2/issues/376

**Comment by samanpwbb** [comment]
Re-installed modules and looks like I'm using v 0.13.0 : https://github.com/mapbox/tm2/blob/master/package.json#L34

**Comment by yhahn** [comment]
^^ fixed.
