### ISSUE TITLE
Incomplete/missing shapefile data at low zoom levels

### ISSUE THREAD

**Issue by MateoV** [mapbox/mapbox-studio-classic#415]
TM2 is having issues with a particular shapefile (link below). There is no data or incomplete data at low zoom levels where there should be. Once zoomed into z6 it is all there.

There doesn't seem to be anything obviously wrong with the file itself as it works fine in TM1 and QGIS.

_TM2 - z4_
![localhost_3000_style id tmstyle____tmp-24d269bb](https://cloud.githubusercontent.com/assets/843058/3178786/3dc5d2da-ec1e-11e3-884d-b78a214677a0.jpg)

_TM1 - z4_
![tilemill](https://cloud.githubusercontent.com/assets/843058/3178801/7977c748-ec1e-11e3-85ce-cab1040e7be3.jpg)

[shapefile](https://www.dropbox.com/s/b21mxsh6jlhkzf8/NEXTMap_with_DTM_reproj.zip)

**Comment by ian29** [comment]
are these many, tiny polygons? i've seen some weirdness with displaying tiny polygons at low zoom levels - i assumed it was related to mapnik-side simplification but haven't investigated

**Comment by MateoV** [comment]
That is what they are, yes. You might be on to something with simplification.

**Comment by springmeyer** [comment]
yep, this is likely dropping of features that look to Mapnik to be smaller than a pixel.

**Comment by MateoV** [comment]
Cool thanks. I'll close this if it's working as intended.
