### ISSUE TITLE
Empty state of Local Sources

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#417]
By default this will be empty for most users. There should be some text there clarifying what the panel is for. (It could be confused for a way to access local GIS files directly or so).

![screen-shot-2014-06-05-at-10-37-27](https://cloud.githubusercontent.com/assets/126952/3189922/ac0d5484-ecc8-11e3-8eb4-2e622d5c2f11.png)

**Comment by samanpwbb** [comment]
Added.
