### ISSUE TITLE
Baselayer not working?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#420]
I can't get a baselayer to show up in my tm2 projects. I tested out multiple baselayer IDs, but otherwise am not sure what else to do to troubleshoot.

/cc @yhahn @samanpwbb

**Comment by GretaCB** [comment]
@nickidlugash 
When was the last time you updated your tm2? And are you getting any errors?
I'm wondering if this might have something to do with my updates.

**Comment by nickidlugash** [comment]
@GretaCB I last updated yesterday, although this wasn't working before then, either. I think before yesterday, I last updated a couple of weeks ago. I don't seem to be getting any errors related to this.

**Comment by yhahn** [comment]
@samanpwbb or I can take a look at this later today. @GretaCB I doubt it's related to your changes since this is a UI thing on the style editor side (not source editor).
