### ISSUE TITLE
TM2 Installation error

### ISSUE THREAD

**Issue by apaleja** [mapbox/mapbox-studio-classic#423]
`Ubuntu 12.04`     `node -v: v0.10.28`

Ran through the source install steps as described [here](https://github.com/mapbox/tm2#ubuntu-linux).

Getting the following error on `npm install`:

```
npm ERR! mapnik@1.4.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@1.4.5 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
```

In case any other information I missed, `npm-debug` can be found [here](https://gist.github.com/apaleja/549679bef7caeb4ca74d) and `npm install` terminal output is [here](https://gist.github.com/apaleja/8ebff26fa5b85dab60ee).

**Comment by springmeyer** [comment]
Can you provide the full output you seen in your terminal when you do `npm install`? Thanks for providing the `npm-debug` log but its actually more useful to see whats in the terminal.

**Comment by apaleja** [comment]
@springmeyer , I've  updated the post with `npm install` terminal output.

**Comment by springmeyer** [comment]
Thanks @apaleja - The problem is that you are running a 32 bit version of linux and I don't provide 32 bit node-mapnik binaries yet (https://github.com/mapnik/node-mapnik/issues/267).

So, the two possible solutions are:
1. You switch to a 64 bit linux installation; or
2. You install Mapnik externally, confirm that `mapnik-config` is on your path, and then proceed with the tm2 installation again.

**Comment by apaleja** [comment]
@springmeyer, I switched to 12.04 64 bit and now installation completed successfully. But when I tried to access it I am getting error `No active OAuth account`. and terminal output is :

```
Error: No active OAuth account
    at loadRemote (/home/pc/tm2/lib/source.js:325:27)
    at Function.source.info (/home/pc/tm2/lib/source.js:359:9)
    at new source (/home/pc/tm2/lib/source.js:77:12)
    at Object.tilelive.load (/home/pc/tm2/node_modules/tilelive/lib/tilelive.js:97:19)
    at Function.style.toXML (/home/pc/tm2/lib/style.js:134:14)
    at Function.style.save (/home/pc/tm2/lib/style.js:99:11)
    at write (/home/pc/tm2/lib/middleware.js:77:15)
    at middleware.writeStyle (/home/pc/tm2/lib/middleware.js:96:5)
    at callbacks (/home/pc/tm2/node_modules/express/lib/router/index.js:161:37)
    at /home/pc/tm2/lib/middleware.js:189:13
```

**Comment by mick** [comment]
@apaleja did it prompt you to log in with your mapbox account?

Try going to `http://localhost:3000/unauthorize` to re auth.

**Comment by apaleja** [comment]
@mike, No it didn't prompt me to login in. It redirected me to `http://localhost:3000/new/style`.
Re auth worked as you suggested. Thank you very much.

**Comment by incanus** [comment]
I'm seeing the same thing as @apaleja on several binary builds + source install. 

Going to `http://localhost:3000/unauthorize` fixes it.
