### ISSUE TITLE
UI for source MBTiles export

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-studio-classic#43]
Right now this required running tilelive copy on the command line.

**Comment by yhahn** [comment]
@TODO
- [x] limit bounds of export. Would be _great_ to autodetect this...
- [ ] upload. Implement `mapbox-upload` API in separate module?
- [ ] oauth ...

**Comment by yhahn** [comment]
Main remaining work: https://github.com/mapbox/tm2/issues/45
