### ISSUE TITLE
Broken style upload: drawtime max exceeded

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#435]
I've a 'broken' TM2 style: "Invalid upload. Error: drawtime max exceeded limit of 1000ms"

What does it mean and how should I look to correct it?

**Comment by yhahn** [comment]
@ashleyclough this is the API's current (and cryptic) way of saying that your style is too slow -- it takes some of the tiles longer than 1s to render.

Look into simplifying your style or data and keep an eye on how quickly tiles render as you're working.
