### ISSUE TITLE
First TM2 install - got `No Active 0Auth account`

### ISSUE THREAD

**Issue by kjwandtke** [mapbox/mapbox-studio-classic#436]
I just installed TM2 and got this error:

![image](https://cloud.githubusercontent.com/assets/5872831/3262248/388c1cc0-f263-11e3-9958-174e6ccdb4bd.png)

**Comment by robpvn** [comment]
I saw a comment on this in issue #423 : Try going to `http://localhost:3000/unauthorize` to re auth.

**Comment by erf** [comment]
Worked for me - Thanks!

**Comment by miccolis** [comment]
Closing this - the bug already has a ticket.
