### ISSUE TITLE
Print Map Testing: Workflow and Printed Results

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#439]
Last Friday, I used and printed maps with @camilleanne's [initial Print Tool](http://www.mapbox.com/labs/print-coordinates) with the goal to print a DC map at 3 different zoom levels. I combined the tool with Photoshop and used @ian29's Wheatpaste custom map design. This test was a good exercise to gauge if colors, road lines, text halos, textured patterns and text labels, etc. need finessing from web to print.

The biggest issue was the bounding box being attached to the zoom. Since print is in  inches not pixels the boundary will most likely be outside of what you can see on the screen. Therefore your bounding box is essentially independent of your zoom preference. Also every change in zoom changes the bounding box. I know @camilleanne is working on a solution to this within the TM2 interface.
#### Web to Print Workflow
- There was no "search location" or "bookmark" ability, so I jumped back and forth between the TM2 and the print tool to make sure my bounding box was producing the area I wanted. However, this has been solved since the tool is now in TM2 but if it was separated this functionally would be ideal to add.

![](http://amyleew.github.io/images/06.13.2014_Printed-Maps-Process/in%20tm2%20z12.jpg)
_in tm2_

![](http://amyleew.github.io/images/06.13.2014_Printed-Maps-Process/tweak%20bounds%20.jpg)
_tweaking bounds_
-  As stated above, it took a bit of back and forth adjusting the boundaries from a low zoom level then scaling into a high zoom for the final image while making sure it was not too big to render.

![](http://amyleew.github.io/images/06.13.2014_Printed-Maps-Process/starting%20....jpg)

![](http://amyleew.github.io/images/06.13.2014_Printed-Maps-Process/again%20smaller%20bounds.jpg)
#### Final Prints

We got 3 awesome DC maps at 18x24"!

![all](https://cloud.githubusercontent.com/assets/4587826/3302069/7228c614-f631-11e3-8f7b-7325ec48dfd8.jpg)

![close](https://cloud.githubusercontent.com/assets/4587826/3302086/89428cea-f631-11e3-9085-561b1cf6a14b.jpg)

![table](https://cloud.githubusercontent.com/assets/4587826/3302088/8bd03bba-f631-11e3-9aeb-2ae8bcf4434e.jpg)
#### Next Steps
- Keep printing and looking for best practices with web to print
- Work with UI in TM2 and offer feedback 

/cc @nickidlugash @yhahn  @samanpwbb @ajashton

**Comment by ghost** [comment]
@amyleew Cool! What kind of printer did you use?

**Comment by amyleew** [comment]
@wsnook thanks! the high-quality printer at Fedex.
