### ISSUE TITLE
Static UI: User stories for printing

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#441]
@amyleew per voice, let's identify as many different user stories for using the static UI for printing maps, and then go through the workflow of using tm2 as these users. 

_A few variables to think about_
- Does the user know the exact dimensions they want? 
- Is the user printing a large scale poster, or outputting smaller images to incorporate into a layout (book, report, etc)?
- Did the user design the map specifically for printing, or is s/he repurposing a live map?
- Will the user need to make a bunch of images from the same map, in different locations? Or maybe images of the exact same location on different maps?
- Does the user have an exact geographical bound for the image?

/cc @camilleanne

**Comment by wboykinm** [comment]
- As a user I would like to perform rudimentary markup (title, text box, image) on my print map so that I don't have to mess around with GIMP or Inkscape in order to create a full composition.
- As a user I recognize how frighteningly close this is to a GIS-platform print layout toolset, and would like to avoid all appearances of unhipness.

**Comment by yhahn** [comment]
... awkward silence ...

**Comment by springmeyer** [comment]
@wboykinm I agree on usefulness, but... this would be a serious technical lift on the mapnik side for generation (map canvas + other elements) and would be duplicating the UI layout functionality that is the core value of Inkscape/Illustrator/etc. So it seems like it would be a distraction for us to take this on. For the record I'll note that a variety of Mapnik users have tackled their print+layout needs on top of Mapnik via command line / automated tools like https://github.com/pnorman/mapbook / https://github.com/mapnik/mapnik/blob/master/bindings/python/mapnik/printing.py

**Comment by wboykinm** [comment]
Totally, and no real worries here. I'm just noticing that's the first question I get when I point out the new print feature: "Awesome! How do I add a title?"
