### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#444]
After talking with @nickidlugash - I think it would be a good idea to save bookmarks to something like a `bookmarks.yml` file that lives in project directories. This would make the hard work of finding good bookmarks persist, while also enabling easy bookmark sharing across projects and between users.

**Comment by samanpwbb** [comment]
New plan:
- ~~Add history to search for user-based "bookmarking".~~
- Create a central repository of useful bookmarks and build a UI for accessing them in TM2. Right off the bat, everyone will know where to look for unique features or be able to quickly navigate between major cities.

**Comment by samanpwbb** [comment]
This is what we should do:
![screen shot 2014-06-25 at 1 41 27 pm](https://cloud.githubusercontent.com/assets/108094/3389123/1113fbda-fc91-11e3-83a5-bf44f721e811.png)

Having personal bookmarks is going to be important, especially if the print use case catches on.

**Comment by skorasaurus** [comment]
as a tilemill (and now tm2) user for >2 years. I am loving this. 

There's been so many times that I'm brainstorming and testing a new design and wanted to quickly see how it would look in different areas.

**Comment by samanpwbb** [comment]
More working through this problem.

Combine user bookmarks with search into one compact convenient feature:
![searchbookmark](https://cloud.githubusercontent.com/assets/108094/3391867/cab95928-fcae-11e3-98fe-ce7220be59ae.png)

Saved / curated "bookmarks" become a "gazetteer" feature for extensive documenting + browsing of Maps:
![gazetteer](https://cloud.githubusercontent.com/assets/108094/3391850/aa3a9f2c-fcae-11e3-9182-a30edf6092d5.png)

Next step is to start sketching some of this out in code and see how it feels.
