### ISSUE TITLE
Can't work offline (again)

### ISSUE THREAD

**Issue by gravitystorm** [mapbox/mapbox-studio-classic#446]
It's not possible to work offline with the current version of Tilemill2. c.f. #79 and #292

When offline, http://localhost:3000/new/style gives:

`getaddrinfo ENOTFOUND`

It's trying to look up api.mapbox.com . Setting that in /etc/hosts to 127.0.0.1 doesn't help much, since tm2 then errors out on requests to e.g. `http://127.0.0.1/api/Map`

By changing various references to mapbox.com in the code, and bypassing `middleware.basemap`, [I managed to get things partially working](https://twitter.com/gravitystorm/status/476765385359126528) on my way to sotmeu, but it was unnecessarily difficult!

tm2 should allow you to work with existing projects with non-mapbox sources when working offline.

**Comment by yhahn** [comment]
This is working again. Will mull on whether automated testing of this is reasonable to do.
