### ISSUE TITLE
OSM & other attribution in print

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#447]
Currently, there is no attribution saved in exported static maps either in metadata or on the image. How does this sit with us?

**Comment by yhahn** [comment]
I think this is fine for now -- TM1 had the same situation where the user was expected to attribute appropriately in whatever context they were using the image.

Perhaps an extra feature we can add down the line is embedding of the attribution field from the in the corner of your image.

**Comment by tmcw** [comment]
Yeah, would stray away from doing this - feels too similar to the north-arrow case, in which anyone who cares enough to print high-dpi maps will also want to do something custom
