### ISSUE TITLE
Wrong quotes used in style editor

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-studio-classic#448]
![](http://recordit.co/ispf0sIMiq.gif)

When writing a filter, the wrong quotation mark gets inserted. This causes a syntax error until you go back and re-type the quotation mark. Happens with single and double quotes.

![](http://cl.ly/image/1p2t1f0f0O2t/Screen%20Shot%202014-06-18%20at%202.46.08%20PM.png)

**Comment by tmcw** [comment]
Are you using OSX Mavericks and you haven't unchecked this:

![2014-07-08 at 10 43 am](https://cloud.githubusercontent.com/assets/32314/3511262/5163b280-06ae-11e4-8c6d-efd44ce8acc4.png)

We probably need some more code to ensure that this _really terrible idea from Apple_ does not impede progress.

**Comment by ekelleyv** [comment]
Yup I have that on. All text editors seem to get it right, so it may just be a matter of switching those particular characters out with their sane alternatives.

**Comment by wboykinm** [comment]
Well this explains a lot . . .

**Comment by tmcw** [comment]
Unfortunately other text editors are native applications, whereas this is a web app, so we are beholden to Chrome's amount of control here, which appears to be nil.
