### ISSUE TITLE
Static UI: Edit and lock pixel and inch dimensions

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#452]
Per voice w/ @camilleanne additional functionality for pixel & inch dimensions:
- editable pixel dimensions
- editable inch dimensions
- "lock"-able dimension values (so they function separate from zoom)
- save dimension values like bookmarks

/cc @yhahn @lxbarth @nickidlugash

**Comment by ghost** [comment]
That sounds awesome :+1:

**Comment by nickidlugash** [comment]
Great! Excited for these updates, @amyleew and @camilleanne.

**Comment by camilleanne** [comment]
Alright! e222de4 gave us lockable dimensions, f8a0e414 allows you to edit the pixel & inch dimensions.

saving dimensions like bookmarks might involve some of this magic #444

go play with https://github.com/mapbox/tm2/tree/export-static-ui-v2 please!

**Comment by camilleanne** [comment]
There's been some issues relating to Windows support and this work, so if the pngs for the resize handles give you issues in github, refer to this: https://github.com/mapbox/tm2/issues/445#issuecomment-46506974

**Comment by amyleew** [comment]
@camilleanne pulled and checked https://github.com/mapbox/tm2/tree/export-static-ui-v2 works like a charm... i'll keep testing :+1:
