### ISSUE TITLE
Scale > 4 for print resolution

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#455]
We fudge a higher 'resolution' for print by increasing the size of tiles. If a 256x256 tile is assumed standard resolution, we pretend to increase the resolution by increasing the tile size to 512 (144 ppi), 1024 (288 ppi). The resulting images exported at a scale higher than 1 are still screen resolution (~72ppi), but significantly larger than they would be otherwise since they are the dimension a higher resolution image would be if not constrained to the same dimensions a 72 dpi image would be.

Right now I've limited the scale to 4 for simplicity (https://github.com/mapbox/tm2/blob/master/index.js#L200), which means that the highest 'resolution' we are getting is the equivalent of a 288ppi image.

@amyleew @nickidlugash how high would you want ppi to go? 600? Are round numbers preferable? Are there standards like 300 ppi we should be shooting for instead of 72, 144, & 288?

**Comment by amyleew** [comment]
@camilleanne yes, 600 dpi is a good max. ppl at times go higher, but 600 dpi is actually plenty!
a good standard set: 150, 300, and 600. 

also, DPI (dots per inch) and PPI (pixels per inch) are technically interchangeable but most people call it DPI and the PPI may confuse some.

**Comment by camilleanne** [comment]
@amyleew I'll let you and @nickidlugash figure out dpi vs. ppi: https://github.com/mapbox/tm2/pull/428#issuecomment-46264366

**Comment by camilleanne** [comment]
did some experimenting with fractional scales for tile size, the place where the tiles meet isn't very clean when you provide a fraction of a scale.

scale of 2.08: 
![retired_pirate2-z8_-75 2975_-53 1336_-72 2296_-51 249_2](https://cloud.githubusercontent.com/assets/3952537/3346994/2711e208-f8d1-11e3-9bef-169d7c9d1b81.png)

Scale of 2: 
![retired_pirate2-z8_-75 2975_-53 1336_-72 2296_-51 249_2 1](https://cloud.githubusercontent.com/assets/3952537/3346995/2e2fe846-f8d1-11e3-9e46-94a1e6443a23.png)

**Comment by nickidlugash** [comment]
@amyleew I think PPI is technically correct, as it correlates to the pixel dimensions. (DPI is a measurement for print resolution and I think doesn't come into play this early in the workflow). I'll double check when I'm on my computer, but I believe photoshop uses "PPI" in its "image size" modal.

Also +1 for 150, 300, 600.

**Comment by nickidlugash** [comment]
@camilleanne so no 150, 300, 600? Or are there options for cleaning up tile edges?

**Comment by camilleanne** [comment]
@nickidlugash this was just my first pass at it. It's just not going to be as simple as just saying "okay, 150ppi should be 2.08 scale" and sending that over. I need to take a look at mapnik and see what I can do.

**Comment by yhahn** [comment]
@camilleanne my first guess at making non-integer scale factors work would be to "snap" a float scale factor to the nearest value that gives integer tile dimensions in both tilelive-vector and abaculus.

One possibility is that the seams above are visible because tile px sizes and tile x/y offsets (in abaculus) need to be even to the pixel. So hopefully using a scale value that multiplies to an even integer value will give better results.

Example:

```
// This number is likely what Mapnik is using above.
2.08 * 256 = 532.48

// Convert 2.08 to the nearest float that provides an even result when multipled by 256
Math.round(2.08 * 256) = 532
532 / 256 = 2.078125
```

**Comment by camilleanne** [comment]
@yhahn correct as always. fixed in b9f73742f

@nickidlugash @amyleew any reason to keep 72ppi around? right now it looks like: 

![screen shot 2014-06-23 at 3 40 24 pm](https://cloud.githubusercontent.com/assets/3952537/3365051/9cdf3d48-fb27-11e3-889c-ca61f067e720.png)

**Comment by ghost** [comment]
I like that export tab.

**Comment by camilleanne** [comment]
just merged https://github.com/mapbox/tm2/pull/454 which has options: 150ppi, 300ppi, 600ppi. lets open another ticket if we need to bring back 72/screen res for some reason.
