### ISSUE TITLE
Upgrade mapbox.js when ready

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#460]
- [x] Drop middleware with basemap creation
- [x] Geocode using api token + mapbox-places-v1
- [x] Drop basemap option from projects
- [x] Review custom @2x tile handler code, maybe can be dropped

I can take a look at this when you have a beta/dev build (?) ready. cc @jfirebaugh

**Comment by jfirebaugh** [comment]
@yhahn v2.0.0-beta1 is released on the CDN and ready for you.

**Comment by samanpwbb** [comment]
@yhahn I am not sure how to get access to the api token. Do you think you could point me in the right direction?

**Comment by samanpwbb** [comment]
Covered in https://github.com/mapbox/tm2/pull/471
