### ISSUE TITLE
Remove templates UI

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#461]
![nuke-templates-ui](https://cloud.githubusercontent.com/assets/83384/3359015/03a51802-fae4-11e3-89c8-fb36e6240e29.png)

Let's nuke the templates/interaction UI. We can leave the `.yml` templating functionality so that pro users can still add these in at the code level if they want.

**Comment by samanpwbb** [comment]
Covered in https://github.com/mapbox/tm2/pull/465 - awaiting merge.
