### ISSUE TITLE
Polish/rethink early carto docs

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#462]
![cartodocs](https://cloud.githubusercontent.com/assets/83384/3360501/83b6ee80-faf3-11e3-8ece-a9845ae22c21.png)

The carto reference is great. The first 40% of prose/examples/text not sure.

We haven't rethought this content from the ground up in quite some time and I'm curious if it actually helps anybody. OTOH
- Less text, maybe exactly 1 example that makes your eyes say: OH this is like CSS
- Turn any referential material into collapsible blocks of styling like the rest of the reference: color functions, special selectors/filters
- Remove all the rest of the prose ?

**Comment by ghost** [comment]
Based on my experiences (primarily with TM1) with using CartoCSS I think it would be great to have a comprehensive reference that shows everything you can do with CartoCSS in a pretty compact format where it's easy read through the whole thing from start to finish. I'm thinking syntax guide + full function reference.

[edit: removed some comments whose time has not yet come]

**Comment by samanpwbb** [comment]
Carto reference should be the first thing you see. This is generally useful while working on a map style, even for experienced users. It's annoying to have to scroll past the top 40%. I think we should totally cut it for now. 

I like the idea of including nothing but the link to the external manual + one example at the top (maybe moving a more extensive intro to carto to onboarding stage???). I'll give this a shot.

**Comment by nilshoerrmann** [comment]
It would be helpful to have a more dynamic documentation that filters automatically based on the given context:
1. When I edit styles, it would be good to automatically see the documentation of the property I'm currently at.
2. When I type, auto-completion of properties and value suggestions would make most documentation look-ups superfluous.

Personally, I don't think TM2 needs to display the full documentation as long as it gives this kind of contextual help.

**Comment by gravitystorm** [comment]
I've taught a few people tilemill 1, and always explain the documentation in the same way - I even did the same thing at sotm-eu a few weeks ago:

https://www.youtube.com/watch?feature=player_detailpage&v=W7La0UXec3A#t=1976

I explain that the 'manual' is a good place for when you're learning tilemill, and the 'carto reference' is something that you return to over and over while working on the stylesheets themselves. Personally I don't find the manual useful but then again I'm no longer a beginner at this.

So I don't agree with @samanpwbb that the 'carto referefence should be the first thing you see'. The manual should be the first documentation that you see, but certainly the carto reference should be one-click away and not buried behind the manual.

**Comment by yhahn** [comment]
Closing for now per @samanpwbb's work. Next round will be reframed with more actionables.
