### ISSUE TITLE
Clicking profile pictures is not intuitive

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-studio-classic#474]
Clicking the profile icon is not an intuitive way to find show map styles/source data. The UI is getting pretty crowded but I do not think it should be buried in it's current location. Perhaps it would better fit in as a pill button with `Settings` and `Save`. 

Clicking the user profile image should probably only bring up auth/remote sources.

cc @samanpwbb 

![](https://i.cloudup.com/bBpXFJ_nJS-3000x3000.png)

**Comment by samanpwbb** [comment]
Fixed.
