### ISSUE TITLE
remove geojson & shapefile layer templates?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#489]
Can we cut https://github.com/mapbox/tm2/blob/master/templates/layergeojson.html and https://github.com/mapbox/tm2/blob/master/templates/layershape.html now that we have https://github.com/mapbox/tm2/blob/master/templates/layerogr.html ?

**Comment by yhahn** [comment]
- shapefile template is still in use
- @GretaCB geojson is using ogr now ya? When you add topojson will it also be via ogr?

**Comment by GretaCB** [comment]
@yhahn geojson is using ogr mapnik datasource, yes. The topojson question is [still pending](https://github.com/mapbox/mapnik-omnivore/issues/8#issuecomment-47542642). My guess is topojson will also be using ogr, but not 100% certain.

@samanpwbb the geojson template can go.

**Comment by samanpwbb** [comment]
removed geojson. :+1:
