### ISSUE TITLE
more readable / user friendly projection form?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#490]
@GretaCB any ideas for making this a little more comprehensible for those not versed in projections?

![screen shot 2014-06-30 at 7 19 50 pm](https://cloud.githubusercontent.com/assets/108094/3437263/00d32d3e-00ad-11e4-92a0-b17ff3d45f2c.png)

A design that provides some more hints to users as to how to interact with this would be nice as well. Can we bring back a drop down + have a flag if the layer was  or was not correctly autodetected? If we're really good at autodetecting, we should make this harder to manipulate.

**Comment by yhahn** [comment]
This is a read-only field now for most datasources and is displayed basically for debugging when the field is autodetected.

We probably just need to style it better so it's clear it's read-only in these cases.

**Comment by GretaCB** [comment]
@samanpwbb 
Related discussion: https://github.com/mapbox/tm2/issues/98

It's pretty much just a "window" into the source's projection.

As far as styling it to signify read-only, we could:
- add "(read-only)" to the Title
- grey out the background of the input box
- and not allow this to happen when a user clicks on it:
  ![screen shot 2014-07-02 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/1209162/3461073/52b3f06c-021e-11e4-8459-fa29108b5c0f.png)

Displaying the projection differently to be more comprehensible makes me wonder how most users will use the Source UI and whether or not there are plans to make projection editable in the future. Seems ok to leave it as is for now, but as the use of the tool becomes more apparent down the road, I would definitely be interested in revisiting interaction with projections.

**Comment by GretaCB** [comment]
@samanpwbb @yhahn 
If the above style suggestions seem ok, I can implement those today.

**Comment by samanpwbb** [comment]
@GretaCB ya, you should be able to just add `readonly disabled` attributes (not classes) to the element and it'll make what you want happen.

**Comment by wboykinm** [comment]
I have yet to see the happy medium between "Text box with defs" and the usual GIS selector-beast:

![2014-07-02_1537](https://cloud.githubusercontent.com/assets/735463/3461262/91ff85fe-0220-11e4-840e-9cf86f784587.png)

**Comment by yhahn** [comment]
@GretaCB got it
