### ISSUE TITLE
improve flow for changing style source

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#495]
Say I'm working on a style that's compositing a few layers, eg `aj.map-aopvneiaw,mapbox.mapbox-streets-v5,aj.npejwxit` and I want to change one of the layers to something else. I can't edit the current source string or even copy & paste it from anywhere in the UI, I need to retype the whole thing. (I might be doing this often on a project as I switch between different dev versions of a source I'm working on.)
### ideas

Pre-populate the Mapbox ID field with the current source string?

Make it more like Mapbox.com?

![](http://i.imgur.com/UTP9hls.png)

**Comment by yhahn** [comment]
This field is prepopulated making it easier to add/remove mapids.
