### ISSUE TITLE
always show mapid when viewing source(s)

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#496]
i often need/want to know what mapid i'm styling - would be great to always display this in the sources/layers list: 

![](http://cl.ly/image/1G0I1o0T1212/Image%202014-07-01%20at%2012.09.47%20PM.png)

**Comment by samanpwbb** [comment]
I wrapped a fix for this into https://github.com/mapbox/mapbox-studio/pull/729
