### ISSUE TITLE
Web Service(s) Support?

### ISSUE THREAD

**Issue by srsjojo** [mapbox/mapbox-studio-classic#497]
Hello,

I was wondering if you had any plans to support consuming web mapping services like  WMS, TMS, WFS, WCS, or REST?

Thanks,
~Stephen

**Comment by yhahn** [comment]
No, TM2 only works vector tile sources:

https://github.com/mapbox/tm2#what-are-vector-tiles

It's on our list to add UI support for non-mapbox vt sources https://github.com/mapbox/tm2/issues/367.
