### ISSUE TITLE
optimize fonts in font panel  

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#498]
We're loading dozens of individual font images in the font panel and it causes slowdown when opening. How practical would it be to sprite these and only require a single image load?

**Comment by yhahn** [comment]
Need to mull. Sprites sound both promising and unpromising -- it'll require a huge image rerender every time you add a font/switch projects with a different set of fonts ...

**Comment by yhahn** [comment]
Per chat, one idea to try is nesting fonts in families in the DOM so we can hide/show them in groups and also eliminate the scrollbar of death.

If I look at this probably my first stab will be for some known list of suffixes (regular/bold/semibold/italic/book/etc.), chopping them off, and considering the previous part of a font name its "family".

**Comment by yhahn** [comment]
Def addresses the perf issues. Will PR for review -- we can tweak the family grouping logic in further iterations I think.
