### ISSUE TITLE
Make 'create style from source' button awesome

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#505]
![screen_shot_2014-07-01_at_7_02_29_pm](https://cloud.githubusercontent.com/assets/108094/3450122/c861dcda-0173-11e4-9e9f-6a01eabae7af.png)

Right now, clicking this button creates a new style with a reference to a local source. This is great! Until you decide you want to use that style, in which case you hit a dead end with no clear route forward.

_instead_

what if we: 

Check if the source has been uploaded to Mapbox.com. If yes, start a new source with a reference to the remote version. If _no_, ask user if they want to upload. If user says 'yes', we upload the source for them, _then_ create a new style from it with the remote source. If user says 'no' we warn them that they won't be able to upload the style _but_ still allow them to make it.

**Comment by yhahn** [comment]
Grabbing for coordination with https://github.com/mapbox/tm2/issues/472

**Comment by camilleanne** [comment]
@yhahn this would go great with a 'dirty' flag in data.yml that says 'upload before you continue,' or if we could diff what's local and what's on mapbox.com

**Comment by camilleanne** [comment]
@samanpwbb could you review https://github.com/mapbox/tm2/compare/sourcetostyle as a quick patch for the trap part of this now that we have source uploads (https://github.com/mapbox/tm2/pull/531)?

**Comment by samanpwbb** [comment]
![screen shot 2014-07-17 at 12 49 16 pm](https://cloud.githubusercontent.com/assets/108094/3616373/4ecf937e-0dd2-11e4-8ac6-bd29aa4eebba.png)

Short term I think this is okay. I would change the actions though. Make one prominent and one secondary, and remove the "no," and "yes," parts from the buttons.

![screen shot 2014-07-17 at 1 05 51 pm](https://cloud.githubusercontent.com/assets/108094/3616561/a60619c2-0dd4-11e4-9787-d620cdc1eed4.png)

Do you have a plan for streamlining the flow if a user hasn't uploaded? Right now, as you probably know it's a little roundabout. Ideally after clicking upload, the processing + uploading steps are combined and don't require more user actions, and the user is redirected to a new style afterwards.

**Comment by yhahn** [comment]
> Do you have a plan for streamlining the flow if a user hasn't uploaded?

lol. so many plans

**Comment by camilleanne** [comment]
Yes, so many plans for the flow. In the meantime I fixed my spelling error. Is that first line too big?
![screen shot 2014-07-17 at 10 54 00 am](https://cloud.githubusercontent.com/assets/3952537/3617168/a6da12f2-0ddb-11e4-98ee-1bbdc7ff71e1.png)

**Comment by samanpwbb** [comment]
See this now, not sure we need the second line 'would you like to proceed with a local source' - or if we do need it, move it below the 'upload to mapbox' button. _Lastly_ nitpick: I would use little icons instead of big icons, and the `harddrive` rather than `folder` icon for the 'use source locally' button.

**Comment by camilleanne** [comment]
this is why you're here, saman. 
![screen shot 2014-07-17 at 11 01 35 am](https://cloud.githubusercontent.com/assets/3952537/3617243/792be208-0ddc-11e4-942e-d9c703505acb.png)
