### ISSUE TITLE
Disallow upload + inform user about styles with local sources.

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#506]
If user has style that references a local source:
1. Add a warning in settings about the fact that the style is referencing local sources.
2. Disable upload and package buttons.

**Comment by yhahn** [comment]
Some notes:

### Always prompt from source editor

The use of the source mapid in this action has surprise-trapped a few people.
- https://github.com/mapbox/tm2/blob/master/app/source.js#L545-L546

I'm wondering if we should try _always_ prompting on this action -- if there is a mapid:

```
- Use remote source (`mapid`)
- Use local source
```

If not, the current

```
- Upload to Mapbox
- Use local source
```

### Block from style editor

Block local sources from being packaged here:

https://github.com/mapbox/tm2/blob/master/lib/style.js#L295

And let the error affect the rest of the system.
