### ISSUE TITLE
Add starter style selection step after clicking 'new style'

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#507]
Give user a choice of starter styles:
![screen shot 2014-07-01 at 7 10 33 pm](https://cloud.githubusercontent.com/assets/108094/3450159/dbb963ce-0174-11e4-91f5-af887f741081.png)

Styles to include:
- Good old default starter style
- OSM Bright
- Something with terrain?
- Something with satellite?
- A totally blank canvas?

**Comment by ian29** [comment]
+1

**Comment by yhahn** [comment]
Taking

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/pull/614
