### ISSUE TITLE
Add "tips" to New TM2 UI

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#513]
The ["tips"](https://github.com/mapbox/tm2/blob/master/HOWTO-cartoCSS.md) section that lived at the top of the old UI docs were super helpful. Can they be tossed back in under the Misc. category at the bottom? 

//cc @samanpwbb @yhahn @nickidlugash

**Comment by yhahn** [comment]
I think they got moved here? https://github.com/mapbox/tm2/blob/master/HOWTO-cartoCSS.md

**Comment by amyleew** [comment]
I meant in the UI. Could be useful for newer users.

**Comment by samanpwbb** [comment]
New users, we will have good thorough outside of app documentation. 

It is worth experimenting with boiling down some of the tips, like functions/operations into more reference-y format and bring them back.

**Comment by yhahn** [comment]
@amyleew background here: https://github.com/mapbox/tm2/issues/462

The content needs a go-over and then we can figure out if it really does belong in the UI or not.

**Comment by amyleew** [comment]
@yhahn  yeah... still think the overview is essential, esp. for trouble-shooting. could be it's own tab beneath docs so it's a quicker to find. called syntax or guide as @wsnook said. it's just super helpful when you're learning... maybe i won't care as much in a few months!

it's the difference between _how to style data_ and _how code CartoCSS_.

**Comment by yhahn** [comment]
@ajashton moved over his great carto guides here https://github.com/mapbox/mapbox-studio/tree/mb-pages/docs
