### ISSUE TITLE
Sources broken in tm2

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#515]
on the most recent pull from master (b0122ece0c7) all my sources turn black after importing as soon as I save. If I try to export them they are redonkulously small (20-30kb). Not sure yet where they're going.

I also can't add new data, it just stays black and nothing actually seems to be imported, but the data.yml looks fine.
![borkedsource2](https://cloud.githubusercontent.com/assets/3952537/3477286/963c4e9a-0315-11e4-95f3-ac01db906b04.gif)

**Comment by yhahn** [comment]
^^ @GretaCB looks like the biggest culprit. Apparently `disabled` on a form element omits it from form value collection O___o

Writing tests for this now.

**Comment by GretaCB** [comment]
Oh man, I killed TM2 single-handedly. But good catch. http://www.coderanch.com/t/485380/HTML-CSS-JavaScript/Disabled-field

**Comment by camilleanne** [comment]
@GretaCB has this been fixed?

**Comment by GretaCB** [comment]
yes
