### ISSUE TITLE
Source: could not detect min/max zoom

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-studio-classic#521]
![2014-07-08 at 10 46 am](https://cloud.githubusercontent.com/assets/32314/3511292/996d40f0-06ae-11e4-8d8e-fba7ee153e8a.png)

Getting this on trying to add a new GeoJSON file as a source.

**Comment by GretaCB** [comment]
hey @tmcw , mind sending me the GeoJSON file? I can take a look at what's going on in `mapnik-omnivore`

**Comment by GretaCB** [comment]
mapnik-omnivore was erroring out for tiles that didnt end in a 1,1 tile when iterating down through the number of tiles. Fixed.
