### ISSUE TITLE
More details on 'pro' font usage?

### ISSUE THREAD

**Issue by gravitystorm** [mapbox/mapbox-studio-classic#523]
tm2 now [comes with 'pro' fonts](https://github.com/mapbox/tm2/blob/c02cb8a95a1dea1cfe88b3d340b560a844102b23/package.json#L36), but with little information about them. I don't think there's a public repo for them so I'm posting this here instead.

The readme[1] states "The license covers use of these fonts for Mapbox Studio only." I'm guessing I can substitute 'Mapbox Studio' and 'tm2' here, but even then it's unclear what is or is not permitted. 
- Can I print out maps using these fonts? And sell them?
- Can I export map images with these fonts to mbtiles and use them in an app? And sell that app?
- Can I distribute the fonts within an app and render on-device?
- Can I use them within tm2 and host the created map images online?
- Can I use them in a custom fork of tm2?

It would be worthwhile highlighting in the UI which fonts are pro fonts and which are fully reusable, or even having an option to hide the 'pro' fonts entirely to prevent inadvertent misuse.

[1] Which you can only find by [reading the package.json, finding the tarfile url and extracting the contents](http://hitchhikersguidequotes.tumblr.com/post/14333727462/mr-prosser-but-mr-dent-the-plans-have-been)

**Comment by yhahn** [comment]
Yes, I'll look into documenting how the app license (in each individiual font dir) applies in specific cases.

In general right now consider their use available for:
- Designing styles in TM2
- Deploying those styles to Mapbox as a Mapbox user
- Printing/exporting static images from TM2

All other uses and any redistribution of the fonts in forks or other packages that are not TM2 is strictly prohibited.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-common-questions.md#what-cancant-i-do-with-pro-fonts
