### ISSUE TITLE
Add CMYK color values as Export for Print

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-studio-classic#524]
@camilleanne  - Can we add the functionality of exporting CMYK color values instead of RGB color values? This is specifically helpful when printing the color Black. CMYK values render a "Rich Black" which absorbs on the paper better and is more legible. It essentially adds a bit of CMY into the K. RGB values are just 100% K. 

//cc @lxbarth @nickidlugash @jjhurlock

**Comment by yhahn** [comment]
Not low hanging and would require a dive in mapnik. Let's do this conversion in other programs for now.
