### ISSUE TITLE
Source: New Layer import takes forever to error

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#526]
I've noticed on some .shp files I've tried to import that I will try to submit the file and clicking the button doesn't seem to do anything. That's because it's made this request `http://localhost:3000/metadata?file=/Users/camille/Downloads/ne_10m_graticules_all/ne_10m_graticules_30.shp` and it's still pending and waiting. Eventually (a minute or two later) you see "(failed)
net::ERR_EMPTY_RESPONSE" in the network tab and this:

![screen shot 2014-07-10 at 4 38 20 pm](https://cloud.githubusercontent.com/assets/3952537/3546850/4cb945ea-088b-11e4-9696-075ce9bf0910.png)

**Comment by ghost** [comment]
do you use sync or async io calls for reading those files?

**Comment by ghost** [comment]
and are you familiar with all the events for http://nodejs.org/api/stream.html#stream_class_stream_readable ?

**Comment by yhahn** [comment]
@camilleanne can you add these hangers to a branch in https://github.com/mapbox/mapnik-test-data/tree/master/data/shp and @GretaCB or I can take a look?

**Comment by GretaCB** [comment]
@camilleanne Looks like there are a couple things happening in `mapnik-omnivore`: 
- This bug you found helped me find a callback error. Woot! 
- `mapnik-omnivore` is having trouble setting min/max zoom for these graticule sources. I'm looking into this now.

**Comment by GretaCB** [comment]
@camilleanne this issue should be fixed with my [last tm2 update](https://github.com/mapbox/tm2/commit/45d2f331052fee37ce436761d5ef4554d43c802e) (fixed mapnik-omnivore).
