### ISSUE TITLE
Font coverage preview

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-studio-classic#527]
See https://github.com/mapbox/node-fontnik/pull/57 + https://github.com/mapbox/font-scope - we could quickly show a preview of language & geo coverage of a specific font stack.

**Comment by yhahn** [comment]
Awesome idea.

**Comment by mikemorris** [comment]
:+1:

I've talked with @nickidlugash before about how this could be quite helpful.

**Comment by nickidlugash** [comment]
Yes! :thumbsup: @mikemorris and I literally talked about implementation of this exact tool two days ago @tmcw Let me know if you're jumping on this – I'd love to help out.

**Comment by tmcw** [comment]
Status: getting coverage tables is complete, but I haven't had the bandwidth to write a fast enough script that would turn OSM Planet -> grids of character frequencies worldwide. Would be a 'fun challenge' for someone with hella osmium c++ skills

**Comment by springmeyer** [comment]
@tmcw happy to offer osmium c++ help, but I think I saw you already knocked this outa the part with go? Let me know :)
