### ISSUE TITLE
Source data zoom availability seems wrong

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-studio-classic#530]
These aren't actually all available at z0+, are they?
![screen shot 2014-07-14 at 6 38 06 pm](https://cloud.githubusercontent.com/assets/3170312/3579494/b8d3d8de-0bc0-11e4-9321-08bfc98828c5.png)

**Comment by yhahn** [comment]
No, looks like a UI issue where it's interpreting no data on zoom level ranges as "everywhere yeah!" Will take a look.
