### ISSUE TITLE
Error when Mapbox account's profile name is not populated

### ISSUE THREAD

**Issue by ebrelsford** [mapbox/mapbox-studio-classic#532]
I got this error when I logged in to TM2 with a Mapbox account with no `name`:

```
style template: Cannot read property 'name' of undefined
```

![selection_014](https://cloud.githubusercontent.com/assets/375002/3585714/3b78d9f2-0c29-11e4-8819-3b0ae151e37c.png)

Pressing `back` just gets the same error again.

**Comment by yhahn** [comment]
Can't reproduce -- let me know if there's any more details that could help track this down here.
