### ISSUE TITLE
Login fails on self-signed certificates

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox-studio-classic#535]
Reported from a Mapbox customer. Is this something we can fix / create a workaround for?

> While http://localhost:3000/unauthorize redirects to a working login page, the page still crashes when attempting to login. However I have worked out what is causing the problem: our proxy returns self-signed SSL certificates, which throw errors in passport (the node module used for authentication). I have not been able to find a workaround for this.

**Comment by springmeyer** [comment]
Can you get any more details about what the error was. It might be similar to mapbox/tilemill#2393

**Comment by springmeyer** [comment]
This problem is clearly due to lacking proxy support, but we are working on getting this working now: let's track at #860.
