### ISSUE TITLE
Automatically fit to bounds on initial data import

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#537]
In source mode, when a data source is first imported, map should fit to bounds of that source. This will provide a gut-check for the user that the data is what they expected it to be, and be in line with the user's intention, which is likely to work with this new source.

**Comment by GretaCB** [comment]
If I understand correctly when you say "source mode", I think this is related to https://github.com/mapbox/tm2/issues/540

**Comment by samanpwbb** [comment]
This issue is asking to "force" the `js-zoom-to` function right away when a datasource gets imported.

**Comment by GretaCB** [comment]
Ah, I already have that in the source-raster branch. I'll add it to master right quick.

**Comment by GretaCB** [comment]
Done.
https://github.com/mapbox/tm2/commit/1834d32f10e742f14491b985059a5e5fd1a29609
