### ISSUE TITLE
crash after upload to mapbox.com

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mapbox-studio-classic#542]
> /Users/karenShea/clones/tm2/lib/source.js:550
>         source.toHash(info.id, function(err, file) {
>                           ^
> TypeError: Cannot read property 'id' of undefined
>     at /Users/karenShea/clones/tm2/lib/source.js:550:27
>     at /Users/karenShea/clones/tm2/lib/source.js:380:24
>     at fs.js:266:14
>     at Object.oncomplete (fs.js:107:15)

Got this error after uploading custom data source to mapbox.com. Data uploaded fine, but local app crashed.

**Comment by kottmann** [comment]
I experienced the same problem. In addition to the error on the command line the web ui doesn't give any indication that the server crashed. The ui just shows the progress bar at 100%.
