### ISSUE TITLE
UI: ambiguous 'done' button in data source editor

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mapbox-studio-classic#544]
I find the 'Done' button under the 'Configure' tab to be misleading in the custom data source editor. If it saves changes maybe it should say save?

I've also considered maybe not having a 'Done' or 'Save' button there at all if we already have a 'Save' button in the left side navigation and the keyboard 'command save' option too. Too many choices? Perhaps a more effective option would be to visually indicate some way that there are unsaved changes (like the save button is a different color or there's an icon somewhere...)

**Comment by samanpwbb** [comment]
Replaced by https://github.com/mapbox/mapbox-studio/issues/844
