### ISSUE TITLE
UI: ambiguous 'x' button in data source editor

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mapbox-studio-classic#545]
![screen shot 2014-07-23 at 5 12 53 pm](https://cloud.githubusercontent.com/assets/5521326/3680366/2ac0bc48-12ae-11e4-8bbe-588153dee0b9.png)

Even if the 'Done' button weren't there for saving, the 'x' in the top corner of this layer editing screen feels a bit like closing out of something without saving, but as I understand it, it just moves you out of editing that layer and back to the list of all the data layers. Perhaps we could communicate the 'back' aspect more clearly with a back arrow instead? 

Or even better this interface could be set up with tabs like in the mapbox studio editor, except tabs of the data layers not carto styles.

**Comment by samanpwbb** [comment]
Replaced by https://github.com/mapbox/mapbox-studio/issues/844
