### ISSUE TITLE
What is the id of a layer?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-studio-classic#546]
![2014-07-24 at 12 29 pm](https://cloud.githubusercontent.com/assets/32314/3691162/aec88bf0-134f-11e4-8bc3-0a56e817424b.png)

**Comment by yhahn** [comment]
or this

**Comment by tmcw** [comment]
?

**Comment by tmcw** [comment]
If it's OGRGeoJSON, can we add a `#` in front?

**Comment by yhahn** [comment]
y sounds good
