### ISSUE TITLE
Move print UI into style editor

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox-studio-classic#553]
A pain point is switching contexts between the styling interface (i.e. hiding or showing certain styles or labels) and the 'Export Image' pane.

Ideally, we preserve state (zoom level, bounding box, crop) as you toggle between modes without having to rely on the bookmarking interface, which doesn't suffice for fast switching.

**Comment by yhahn** [comment]
Let's sketch this as moving the export image UI into the main style editor so the state is shared. Should be simpler than trying to move the state back and forth.
