### ISSUE TITLE
Update style/source client tests to use Real (tm) projects

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#561]
With recent refactoring should be possible for source/style project tests to incorporate actions that were previously not tested because of tmp-project nature.
- [x] style/source saving
- [x] style upload
- [ ] create style from source action
- [ ] source layer rename
- [ ] source layer rename no-op
- [x] style package dl blocked with local source

**Comment by camilleanne** [comment]
test for package dl (might be fudging it a bit): https://github.com/mapbox/mapbox-studio/commit/35d5a451deb85dd5d2fb4f534b017cc45694a0ef

**Comment by yhahn** [comment]
works for me

**Comment by yhahn** [comment]
We're in a good spot here.
