### ISSUE TITLE
Build fails with checksum error

### ISSUE THREAD

**Issue by kottmann** [mapbox/mapbox-studio-classic#564]
I updated to the latest version n(1ef56320c957f3a368372c7acedecdbbf99936a4) but now building fails with a checksum error.

Here is the error I get on Fedora 20:

npm install
...
<snip>

Error: shasum check failed for /home/xyz/tmp/npm-30393-yxwc42Im/1406636590386-0.7470777868293226/tmp.tgz
npm ERR! Expected: 7a1b1db81f4188056b1801f139d646d136015e68
npm ERR! Actual:   0651ed56153ee10ebe7b0e069bd5c5d7c37501a6
npm ERR!     at /usr/lib/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)

**Comment by yhahn** [comment]
Usually this means npm had a crummy download on a bad connection. Reopen if persists.
