### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by nerik** [mapbox/mapbox-studio-classic#566]
I'm not sure if it's considered an issue, in case it's not I'm sorry, but :
- I haven't found any other way to use custom fonts other than placing them to node_modules/mapbox-studio-default-fonts/. Is there any other way? Is it documented somewhere?
- any project with custom fonts uploaded to Mapbox appear as 'Broken' in Mapbox's 'Data' page

Thanks !

**Comment by yhahn** [comment]
See https://github.com/mapbox/tm2/issues/395
