### ISSUE TITLE
Blurry map preview

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#58]
Latest master gives me a blurry map preview. Below are an example raw tile, a screenshot of what was displayed by Chrome, and a difference of the two. 3D CSS transforms not working right perhaps?

![](http://ubuntuone.com/2zfrpZQj6tpeozXb5UD8UF)
![](http://ubuntuone.com/69DdnGkaLc0pnDgOooG8SQ)
![](http://ubuntuone.com/6QQfidzLhoLKB6h45lBEas)

**Comment by yhahn** [comment]
Let me know if reverting https://github.com/mapbox/tm2/commit/a0ca2cb7553bcd452c9e16c49b04a8143fc8da44 fixes it.

**Comment by ajashton** [comment]
Yes, it also fixed #57

**Comment by ajashton** [comment]
Reverted in 3084747ae36ffbb2e35dacc134bbc3c2f354a396
