### ISSUE TITLE
Investigate getport

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#581]
Max is using https://www.npmjs.org/package/getport in dat. Maybe worth consideration?
- If user specifies port explicitly in command line use it and fail hard if it can't be used
- Otherwise, grab a port in some range of ports

We'll want to do this to at least avoid getting blocked on 3000 which is super common.

**Comment by jfirebaugh** [comment]
`server.listen(0)` will also auto-select an unused port.

**Comment by jfirebaugh** [comment]
Hmm, actually I'm reading stuff that says it's not guaranteed to be unused.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/pull/587
