### ISSUE TITLE
Allow use of multiple sources

### ISSUE THREAD

**Issue by caged** [mapbox/mapbox-studio-classic#595]
There doesn't appear to be a way to use multiple sources.  I have many scenarios where I'd like to use the Mapbox street+terrain layers combined with additional layers from local sources.  

As a concrete example, I have a building dataset for Portland, OR that contains many more buildings and much more detail than the default building dataset included in the official Mapbox source.  I'd love to "turn off" the Mapbox buildings layer, and use the local dataset that I have, without losing the streets, terrain, etc. layers from the Mapbox source.

**Comment by yhahn** [comment]
See https://github.com/mapbox/mapbox-studio/blob/master/HOWTO-styles.md#compositing-remote-sources

**Comment by caged** [comment]
Perfect!  Thanks.
