### ISSUE TITLE
Source export is unexpectedly slow

### ISSUE THREAD

**Issue by caged** [mapbox/mapbox-studio-classic#600]
> Export times can vary widely depending on your data and desired number of zoom levels - anywhere from a few minutes to many hours.

I've read this disclaimer, but I'm seeing exports that will likely take days on very simple datasets.  I've imported [Natural Earth graticules at 1º (6.2mb)](http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_graticules_1.zip) (zip) and selected a single zoom level at 12 and left the default buffer for the layer at 8.   

When trying to export this, I'm getting some times that seem very slow for a simple, small dataset.   About 0.1% movement every 5 minutes.   I've tried the "Upload" and "MBTiles Export" options.  Both seem to have this issue.

![screen shot 2014-08-03 at 11 51 31 am](https://cloud.githubusercontent.com/assets/25/3791496/5946e4a8-1b40-11e4-9c77-49bc589bdb03.png)

![screen shot 2014-08-03 at 12 03 58 pm](https://cloud.githubusercontent.com/assets/25/3791505/fa5b6b3e-1b40-11e4-9685-b45cdc8ced6e.png)

**Comment by yhahn** [comment]
Hrm, hard to say OTOH -- I get similar results with 12-12 but off the bat this seems like pretty poor settings for this dataset.
- z12-12 is a lot of tiles (16777216)
- the dataset is not detailed enough to warrant this -- you will probably not be able to notice the difference between this and a z0-8 export or so
- resource utilization (`htop`) seems good in both cases

**Comment by caged** [comment]
> z12-12 is a lot of tiles (16777216)

@yhahn oh, interesting.  It'd be great to have this number visible somewhere before the export to keep people from shooting themselves in the foot.  I swapped zoom levels down to `2-4` and saw very quick export times, more along the lines of what I would expect.  Perhaps exporting 17mm tiles just takes a long time! :no_good:

**Comment by ajashton** [comment]
Apart from the large number of tiles, part of the problem is likely the lack `.index` file, the special type of index that Mapnik uses for Shapefiles. This can be created with the `shapeindex` command-line utility (provided by Mapnik) and will greatly speed up shapefile exports.
