### ISSUE TITLE
Odd geometry

### ISSUE THREAD

**Issue by srsjojo** [mapbox/mapbox-studio-classic#604]
After importing OSM data to postgres and adding it as a local source I get odd, oversimplified geometry showing up:

![screen shot 2014-08-03 at 9 29 51 pm](https://cloud.githubusercontent.com/assets/7338435/3792655/827af08c-1b7f-11e4-996c-b66005d4735d.png)

Here is the same data loaded in QGIS:

![screen shot 2014-08-03 at 10 37 15 pm](https://cloud.githubusercontent.com/assets/7338435/3792683/583a334a-1b80-11e4-9bff-886b0e4a9132.png)

As I'm completely out of my depth, I'm sure it's something I did incorrectly. Where did I go wrong?
Thanks,
~Stephen

**Comment by yhahn** [comment]
Try setting a higher maxzoom on your source. See https://github.com/mapbox/mapbox-studio/blob/master/HOWTO-sources.md#project-settings for more information.
