### ISSUE TITLE
Save to Mapbox instead of Upload to mapbox after initial upload?

### ISSUE THREAD

**Issue by mberg** [mapbox/mapbox-studio-classic#609]
Just a minor suggestion, I think it might make more sense to say "Save to Mapbox" instead of upload.  I understand upload initially. After that, it feels like I'm just saving updates of my style to Mapbox (updating) even though I realize in the background it's a re-upload.

![screen shot 2014-08-04 at 2 24 56 pm](https://cloud.githubusercontent.com/assets/57921/3796480/2d721412-1bca-11e4-9b52-4e08b420b22a.png)

**Comment by ajashton** [comment]
"Save" could set false expectations - a project uploaded to Mapbox is not a copy or backup of the .tm2 project. What's uploaded to Mapbox is a tm2z package, and you cannot go backwards from tm2z -> .tm2 / CartoCSS if you lose the original local copy.

Perhaps even "Upload" is not clear enough in this regard and should be "Export style to Mapbox" or something.

**Comment by mberg** [comment]
But if you modify a style,  the next typical step will be to apply those
changes to mapbox no?   Each time I hit upload I'm not creating a new
project just updating it right?

**Comment by mberg** [comment]
Sorry back again.

So I fixed it so it renders in studio properly.  However, when I upload to
mapbox it says the dataset is broken.

I'm guessing it's because the data source (23MB) is well past the 2000
point limit.

So it that limit brand new?  If so, it's a serious serious bummer.  The
point of mapbox is being able to create big maps.  2000 points is still
leaflet country.   Is this just a limitation to vector maps? ie) can I
still bake my town tiles with more?

Here's what I tried to process.

ona.e32d149c

I've been the biggest fan of mapbox you can imagine.  I was / am extremely
excited by the potential of vector tiles.  This limitation (as I
understand) is potentially crippling.  The whole point of vector is to be
able to process bigger maps without the burden of baking.

Anyways, hope I'm maybe understanding this wrong.  If you are going to push
people towards vector I don't see how they can live under that limit.

Thanks,

Matt

**Comment by yhahn** [comment]
@mberg the 2000 point limit does not apply to vector source uploads. It looks like your upload failed for a different reason:

> Invalid upload Error: At least one tile exceeds the draw time limit of 1000ms. Please optimize your styles.

You'll want to make sure your style performs well as you design by keeping an eye on the drawtimes on your map -- usually this is due to dense low zoom tiles that should use simplified data or can be omitted entirely.

**Comment by mberg** [comment]
Young - awesome thanks for the clarification.  That's great, great news.

Just curious is that relate to the number of points for when people are
annotating maps using the mapbox interface?

So just as reference it's happening when I'm trying to style this layer.

ona.57a05d11

This is map of enumerated structures (from space) basically households that
are going to be targeted for malaria spraying.  I get render times of over
1000 ms when I zoom out to level 7 or so.  I think probably because it's
trying to render all those points in a single view.

I think the culprit is I had allow-overlap-true.   Which is pretty default
practice when you are baking tiles.  I remove it and now the render times
seem to be under 1000 ms (maxing at 500ms).

If I got up a zoom level to zoom 6 I can't avoid going over the 1000 ms
limit (2500ms+).  Any recommendations on what you can do there?  It would
be a bit of a pain (and a lot different experience then baking that doesn't
have this limitation) if I have to create a different source for specific
zoom levels.    If that's the workaround though please let me know.

Thanks for your help with this.

Matt

  background-color: #fff;
}

#all_june5_pt {
  marker-width: 2px;
  marker-line-color: yellow;
  marker-fill: yellow;
  marker-fill-opacity: 0.7;
}

**Comment by yhahn** [comment]
> Just curious is that relate to the number of points for when people are
> annotating maps using the mapbox interface?

Yes, the feature limits described on https://www.mapbox.com/plans/ are for the online editor.

> Any recommendations on what you can do there?

Yes, for point-based maps this is a common problem where at lower zoom levels  you often may attempt to represent thousands or millions of points in a single tile. We have some approaches to this internally but the solutions are complex -- we are still working on ways to make this accessible and easy to use for most people.

Quick overview of approaches:
1. **Does not exist yet: source vector tile postprocessor.** Like image or audio processing filters you slap onto the end of your toolchain -- you can imagine adding a plugin to your vector source at processing time that drops overlapping points < z7 or so.
2. **Import into postgis and write zoom-specific queries.** This is the main approach we've taken internally to date to simplify/reduce data density at lower zooms.
3. **Exclude points at the style level.** Often if you are working with a datasource that has sequential IDs or other attributes that can write a carto filter that simulate a filter using id entropy:
   
   ```
   #all_june5_pt[zoom<=7][id =~ '.*[0123]']
   #all_june5_pt[zoom>=8] {
       ...
   }
   ```
   
   This rule would drop any features at z7 or below that have ids that don't end with the digits 0-3.

cc @ajashton @ian29 for other tips

**Comment by mberg** [comment]
Thanks this is helpful.

On point limit, I'd probably add a bit of a disclaimer as I think you'll
probably freak a lot of people like me out.

On number #2 what query method are you using?   If you give me a brief
description I can research it.

I'm basically maxing out at 2500ms so the 1000 ms is pretty limiting.  I'm
sure there's good reasons for your limits.  Until you come up with more
user friendly approaches though bumping the hard cap up may help.  Again,
this is just an end-users perspective and I have no idea the decisions that
are having to be made related to the backend.

I'm also guessing the speeds I'm seeing on mapbox studio are rendering
machine specific and might not matchup with the cloud processing.  As a
result, it's truly guesswork.

On the positive side, it's magical watching that many points render so fast
/ with styling locally.
