### ISSUE TITLE
Windows uninstaller does not remove deep deep deep paths

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#611]
There are super-deep node_modules paths that the window uninstaller fails to remove. Attempts like this https://github.com/mapbox/mapbox-studio/commit/87c1f9a8dc184b766420517ba1bbfd61dc8dd520 ended in failure.

Try again another time.

**Comment by wilhelmberg** [comment]
@yhahn 
What a coincidence, just yesterday I tried to get rid of the same problem:

https://github.com/BergWerkGIS/delete-directory-tree
https://github.com/BergWerkGIS/delete-directory-tree/releases/tag/0.1

It can be used like this: `delete-directory-tree [/Q] <directory>`

At the moment the release linked above is x64 and depends on the .NET Framework 4.5, as my language of choice is `C#` and I wanted to have something quick.

Could you try if it works for your problem, too?
If it does, I suggest we create a C++ x86 version to be more versatile.
What do you think?

**Comment by yhahn** [comment]
@BergWerkGIS yes -- currently I am running into this in the context of our uninstaller so I will have to see if this can be run from there:

https://github.com/mapbox/mapbox-studio/blob/atom-child/scripts/mapbox-studio.nsi#L111

I will let you know how it goes and report back here.

**Comment by wilhelmberg** [comment]
Just pushed a [new delete-tree version](https://github.com/BergWerkGIS/delete-directory-tree/releases/tag/0.2).
This one resets hidden and read-only attributes for folders and files (if current user has the rights to do so) before deleting.

Also had my first try on a [C++ version](https://github.com/BergWerkGIS/delete-directory-tree/blob/master/delete-directory-tree-cpp/delete-directory-tree-cpp.cpp).
It is not ready for use yet, but it made me remember why I ran into the arms of C# as soon as it came out.
Oh, sooooooo many different types of strings.
:smirk:

**Comment by wilhelmberg** [comment]
@yhahn FYI:
New [release of delete-directory-tree](https://github.com/BergWerkGIS/delete-directory-tree/releases).
Include .Net/Cpp x86/x64.

**Comment by springmeyer** [comment]
@BergWerkGIS - great work on getting this working + a c++ version.

I see two challenges in integrating an tool like `dtt.exe` inside the Mapbox studio uninstaller

1) Can NSIS, which auto-builds the installer, call out to a separate program to do work like deleting directories? I sounds like it should be able to call out in a subprocess: http://stackoverflow.com/questions/11708779/exec-vs-execwait-vs-execshell-vs-nsexecexec-vs-nsexecexectolog-vs-nsexecex.

2) Assuming 1) is solvable then the next question would be how bundling would work. We could have Mapbox Studio install `dtt.exe` as part of installation so that when you go to uninstall it would be available. However I'm not sure about the timing of things - how could the `dtt.exe` tool be used to uninstall the directory that it iself is inside? Perhaps it could be use to delete the `node_modules` and then once that was done the standard NSIS `RMDir` could delete the enclosing directory that contains `dtt.exe`?

**Comment by wilhelmberg** [comment]
Reading the SO post, it seems to me that `ExecWait` is the way to go (for node_modules) and then use NSIS `RMDir` for the main directory.

**Comment by springmeyer** [comment]
> Reading the SO post, it seems to me that ExecWait is the way to go (for node_modules) and then use NSIS RMDir for the main directory.

Great, feel free to give this a try in a branch. Travis will run things so you can test it.

**Comment by wilhelmberg** [comment]
@yhahn or @springmeyer 
I might be missing something obvious, but how to I get the installer that has been created by nsis from travis?

**Comment by yhahn** [comment]
@BergWerkGIS it is uploaded to s3 so you can download it at:

```
https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-ia32-<gitsha>.exe
```

The url is in the logs of publish builds, e.g. https://travis-ci.org/mapbox/mapbox-studio/jobs/35459762#L1532

**Comment by wilhelmberg** [comment]
Thanks. I looked through the log, but missed this line.

**Comment by yhahn** [comment]
@springmeyer @BergWerkGIS I'm wondering if this would be a simpler approach to this:

**Goal:** eliminate very deep paths in `node_modules` tree. The main directories not being removed are ones in deep `node-pre-gyp` dependency trees -- inparticular `mapnik-omnivore/node_modules/gdal/node_modules/node-pre-gyp/node_modules/*` and `mbtiles/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/*`.
- [ ] Update node-pre-gyp semver declarations in mapnik, sqlite3 to be looser (i.e. use `~`)
- [ ] Add `node-pre-gyp` as base-level dependency of mapbox-studio
- [ ] On `postinstall` run `npm dedupe node-pre-gyp` to collapse deps for this down

I've tested this on a local branch to confirm the dedupe works once the semvers all accept the base pre-gyp version. It won't affect the bundled pre-gyp's use at install time and the base deps' main job will be for the runtime APIs.

@springmeyer see any issues with this? I can roll PRs for mapnik + node-sqlite3 if this sounds good.

**Comment by springmeyer** [comment]
@yhahn sounds good. This feels similar to what motivated me to start working on https://github.com/mapbox/node-pre-gyp/pull/80, but using `npm dedupe` is a nice shortcut.
