### ISSUE TITLE
Update OS X signing for Yosemite

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#616]
https://developer.apple.com/library/prerelease/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG205

No actions atm. Will require an os x version update from travis.

cc @incanus

**Comment by springmeyer** [comment]
anything left to do here?

**Comment by yhahn** [comment]
Nope, this happened.
