### ISSUE TITLE
Can't change layer name after importing a source

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox-studio-classic#618]
After importing a file that was converted using ogr2ogr, I can't change the layer name, which is problematic when other sources have the same name:

![1407260496](https://cloud.githubusercontent.com/assets/200357/3815921/fdae6d06-1cc9-11e4-9fed-6037665c8c62.png)

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/pull/619
