### ISSUE TITLE
Using old tilemill projects

### ISSUE THREAD

**Issue by andyburgess1978** [mapbox/mapbox-studio-classic#62]
Is there a way yet to use TileMill (v0.10.1) projects in TileMill 2? Or use data from a Postgres database?

**Comment by yhahn** [comment]
@MobileAndyB no, and a programmatic migration is looking harder than ever. It's pretty straightforward to move Postgres queries over from a TM1 project to a [TM2 source](https://github.com/mapbox/tm2#creating-a-source-with-tm2) however and it's where I'd recommend starting.
