### ISSUE TITLE
can we avoid triggering OS X firewall dialog?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-studio-classic#621]
Is there a way to listen to only local loopback requests, so as to avoid this dialog when you launch for the first time with Mac OS Firewall enabled:

![image](https://cloud.githubusercontent.com/assets/98601/3819622/b313438e-1cec-11e4-8941-87fa62beed8f.png)

There shouldn't be any reason Mapbox Studio needs to accept non-localhost traffic, and in fact for security reasons it should not be allowed to do so.

**Comment by incanus** [comment]
Yes. Related: https://github.com/mapbox/tilemill/issues/2224

**Comment by jfirebaugh** [comment]
I'm curious if doing [`server.listen(port, "127.0.0.1")`](http://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback) (i.e. listening only on localhost) is enough to avoid the prompt entirely.

**Comment by yhahn** [comment]
Sounds good, let's give this a try today.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/commit/df9027d5ad9e2a8513048d7501e670c2b37d4fe3 seemed to work for me on a test mac.

@jfirebaugh when you are bored want to give it a whirl?
