### ISSUE TITLE
Windows: no borders, not resizeable, not useable for average user

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/mapbox-studio-classic#626]
On my W7 64bit, with three monitors in protait mode (1080x1920 each), MapBox Studio sticks to the main monitor with a window size of 960x600 and doesn't have any borders.

With the mouse, I cannot resize or move it arround.
It works via keyboard, but I don't think the average user will be aware of this functionality:
**Move:** Press Alt+Space -> Move -> use cursor keys to move arround
**Resize:** Press Alt+Space -> Size -> use Shit+cursor keys to resize

BTW:
1. I would love to have the CSS text area to be resizeable, so that I can align it with the bezels between the monitors myself.
2. I cannot add labels to this issue.

Orginal size:
![mapbox-studio_no-borders](https://cloud.githubusercontent.com/assets/4549888/3823251/c50066b8-1d36-11e4-9358-92ef2519808b.png)

**Comment by yhahn** [comment]
Hrm, @BergWerkGIS that is def weird -- in my testing so far the window gets title and border and so avoids all these problems.

I will see if I can get on W7 to test.

**Comment by wilhelmberg** [comment]
I don't have any special multi-monitor window managers or display drivers or any other kind of software that messes with the appearance of windows.
Only thing: I'm using the classic design that mimics WinXP.

**Comment by wilhelmberg** [comment]
On vanilla W8 it looks much better:

![mapbox-studio_w8](https://cloud.githubusercontent.com/assets/4549888/3827625/86895c9e-1d6f-11e4-9312-8a25aad0fe65.png)

**Comment by wilhelmberg** [comment]
I checked on two other W7 machines (with default W7 Areo theme): no borders.

**Comment by yhahn** [comment]
@BergWerkGIS I'm guessing this is an upstream issue in [atom-shell](https://github.com/atom/atom-shell) so we should confirm.
- [ ] Grab latest atom-shell here (we're still on 0.15.1 but easy to upgrade) https://github.com/atom/atom-shell/releases
- [ ] Confirm whether the problem occurs on the atom-shell placeholder app
- [ ] If it does, let's cut a ticket

**Comment by wilhelmberg** [comment]
@yhahn 
Yes, you are correct, it is an upstream issue:

atom shell 0.15.1:
![atom-shell-0 15 1](https://cloud.githubusercontent.com/assets/4549888/3842479/a22aec6a-1e37-11e4-961b-8ebc8784f7da.png)

atom shell 0.15.4:
![atom-shell-0 15 4](https://cloud.githubusercontent.com/assets/4549888/3842485/ad1ce4a2-1e37-11e4-8180-ee209ba26ae8.png)

**Comment by yhahn** [comment]
Ok sweet, we can look into updating to 0.15.4 today.

**Comment by yhahn** [comment]
@BergWerkGIS want to give https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-ia32-atom0154.exe a shot?

**Comment by wilhelmberg** [comment]
Yeeessssss!

![mapbox-studio-atom0154](https://cloud.githubusercontent.com/assets/4549888/3845405/2b393b1e-1e52-11e4-8d8f-16bef8ec3db8.png)

**Comment by yhahn** [comment]
w00t
