### ISSUE TITLE
Windows: Crash when adding data source with EPSG:31254

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/mapbox-studio-classic#627]
Adding data with EPSG:4326 works.

When I try to add this shapefile (http://www.BergWerk-GIS.at/dl/mapbox/Seilbahn.zip) the proj4 string is correctly identified:

```
+proj=tmerc +lat_0=0 +lon_0=10.33333333333333 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +units=m +no_defs
```

http://spatialreference.org/ref/epsg/31254/

As soon as I click on `Done` MBStudio crashes.

Maybe it could also be a problem with the path used:

```
C:\Users\bergw\_Projekte\LaRegV\ProfilTool-Erweiterung\VoGisData-Peter\Seilbahn\seilbahn.shp
```

**Comment by wilhelmberg** [comment]
Sorry!
Reading the docs definitely helps :smirk: 

```
Currently Mapbox Studio only accepts input files in either WGS84 (aka EPSG:4326) or 900913 (aka EPSG:3857). If you have data in other projections, you should reproject it to 900913 before adding it as a layer.
```

**Comment by yhahn** [comment]
Hrm, that text is old : )

**Comment by springmeyer** [comment]
bump @BergWerkGIS  - still hitting this?

**Comment by wilhelmberg** [comment]
Nope, works.
