### ISSUE TITLE
Invalid upload - Error: Unpacking failed.

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#628]
I'm getting lots of 'Invalid upload - Error: Unpacking failed' errors, even from the simplest styling package. Any idea what may be causing the problem?

**Comment by yhahn** [comment]
@ashleyclough hm, would you mind uploading an export of your tm2 style as a tm2z package for review?

**Comment by ashleyclough** [comment]
Here: https://www.dropbox.com/s/zh9p1qw0vfnmnj7/os_streets_places.tm2z

**Comment by yhahn** [comment]
@ashleyclough it looks like your style is using sources that do not perform well at lower zoom levels. I would recommend setting your minzoom to z9 or 10 or so on your style.

I will look into improving the source creation to warn if vector tiles become too large for rendering.
