### ISSUE TITLE
Roads being cut off at edge of tiles - Data from Postgre

### ISSUE THREAD

**Issue by matthewbrunsdon1** [mapbox/mapbox-studio-classic#63]
Hey Guys,

I have a TM2 instance with road/basemap data being powered by a Postgre database - we have set the map buffer size to be higher (512) than the default as this was a suggestion however this has not fixed the issue.

At the edge of the tiles the roads are getting cut off (see screenshot)... Has anyone experienced this issue before? 

Thanks,
Matt.

![roads-cut](https://f.cloud.github.com/assets/5555313/1224002/fda42148-2738-11e3-8125-115061af405c.png)

**Comment by yhahn** [comment]
@matthewbrunsdon1 you likely need to increase the buffer-size on your road layer to about 0.5x-1x the max stroke width you expect to use on your road style.
