### ISSUE TITLE
Better feedback when opening large rasters

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#633]
I have a 1.3 GB geotiff I tried to add as a source layer.  After choosing the file in the browser and hitting `select` mb-studio appears to do nothing at all. I'm still able to click around and try selecting other files. After about 40 seconds then the browser window closed and presented the error `Failed to set min/max zoom`.

**Comment by yhahn** [comment]
@GretaCB want to start by adding a loading class to the modal here and removing when evthing is complete (either success/error) ?

https://github.com/mapbox/mapbox-studio/blob/master/app/source.js#L228

@springmeyer if you can link to the source raster @GretaCB can prob debug where the detection's failing.

**Comment by GretaCB** [comment]
Jumping on this....three weeks later :/

**Comment by GretaCB** [comment]
Merged. https://github.com/mapbox/mapbox-studio/pull/725
