### ISSUE TITLE
Copyright author

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#639]
On the darwin build the LICENCE at the top of the document reads:

> Copyright (c) 2014 GitHub Inc.

**Comment by yhahn** [comment]
What build was this in? I'll do a more recent build today -- I think @camilleanne fixed this here https://github.com/mapbox/mapbox-studio/blob/master/scripts/build-atom.sh#L65-L66

**Comment by tristen** [comment]
The build cited here: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-darwin-x64-fcaf7c2.zip

**Comment by yhahn** [comment]
Sweet, this has been fixed since.
