### ISSUE TITLE
Image-filter doesn't obey zoom level restrictions

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-studio-classic#642]
I'm trying to conditionally blur the hillshade layer (demonstration at zoom-level 10 so it shouldn't matter whether it's commented out or not:

![mbs-issue-demo](https://cloud.githubusercontent.com/assets/7108211/3880968/9c3c0f14-2189-11e4-8dfc-bf2d590373af.gif)

Still using the browser hosted version if that's relevant.

**Comment by ajashton** [comment]
This is a limitation of how Mapnik and CartoCSS work. `image-filters` (like `comp-op`) is a style-level property, meaning it will always apply to the whole style regardless of filters. To work around this you can create multiple style attachments - see [this example](https://github.com/mapbox/mapbox-outdoors.tm2/blob/master/style.mss#L164-L206).

**Comment by drewbo** [comment]
Awesome, thanks
