### ISSUE TITLE
Mapbox Studio uploader and raster sources

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mapbox-studio-classic#643]
I've uncovered a little problem with raster sources in Mapbox Studio.

I was working with a geotiff I needed to first reproject with gdal via `gdalwarp -s_srs EPSG:27700 -t_srs EPSG:3857 SX99.TIF 25k_new.tif` into web mercator. From the Mapbox Studio application I add it as a new layer, save and then hit 'Upload to Mapbox'. The file is uploaded online and I get this message. 
![itFails](https://cloud.githubusercontent.com/assets/5521326/3883249/6ff0d28a-219f-11e4-8a4f-4f6015371f3a.png)

When I upload the exact same file onto Mapbox.com via the Mapbox.com uploader on my /Data page, the upload works, I have a mapid I can use as a remote source in Mapbox Studio.

@GretaCB reports that the uploaders from mapbox studio and mapbox.com are different, and this is holding true for raster source uploads.

@yhahn @camilleanne @ian29

**Comment by yhahn** [comment]
It looks like the minzoom on this project was set to 0 making it too small at that size to show up at all and leading to an upload with 0 tiles.

This should be fixed once https://github.com/mapbox/mapnik-omnivore/pull/23 is rolled into a new omnivore release.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/commit/82be54faa8deb4b836339247f6ef2be25392ad2b
