### ISSUE TITLE
Image raster source support

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#646]
Image raster sources (that are not composited with vector sources) are currently broken. The fix is somewhat complex.
- [x] source.js should stop setting vector_layers for image sources. This is basically a hack/wrong and is in place to smooth over consumption of these sources. (https://github.com/mapbox/mapbox-studio/blob/master/lib/source.js#L338-L339 should be undefined)
- [x] format pbf is wrong for image sources. Set this to webp if there's a gdal source https://github.com/mapbox/mapbox-studio/blob/master/lib/source.js#L332-L333
- [ ] consumption needs to be smarter about handling image sources without vector layers defined. Not sure what the least code-sprawl way to do this will be:
  - https://github.com/mapbox/mapbox-studio/blob/master/lib/style.js#L210-L213
  - https://github.com/mapbox/mapbox-studio/blob/master/templates/sourcelayers.html#L21
  - https://github.com/mapbox/mapbox-studio/blob/master/templates/xraydefaultcarto.mss#L4

cc @GretaCB

**Comment by GretaCB** [comment]
New branch is at https://github.com/mapbox/mapbox-studio/tree/raster_local

**Comment by yhahn** [comment]
Let's pause on this. Need to mull on the right approach some more here.

**Comment by yhahn** [comment]
Did this.
