### ISSUE TITLE
Error when accessing localhost after install

### ISSUE THREAD

**Issue by dbaldwin** [mapbox/mapbox-studio-classic#648]
I've been using TM2 for some time and recently installed the mapbox-studio project. Upon starting the server and accessing http://localhost:3000 I was redirected to: http://localhost:3000/source?id=tmsource:///Users/db/Downloads/hydro.tm2source with the following error:

Shape Plugin: shapefile '/Users/db/Downloads/_hydro_source_files/TX_Large_Waterbodies_20140605.shp' does not exist

This was an old project that I was running in TM2 and I believe it's picking up an old setting. Any ideas on how I clear this out and get to the default screen where I can create new sources and styles?

Thanks.

**Comment by ajashton** [comment]
You can clear your settings and project history by removing or renaming the file `/Users/db/.tilemill/v2/app.db` then restarting Mapbox Studio. You will need to re-authorize your Mapbox account at that point.

If you're comfortable editing a minified json file you could also just find specific references to the broken project and remove them from app.db.

**Comment by dbaldwin** [comment]
Thanks AJ, that got me going. Much appreciated!
