### ISSUE TITLE
MapBox Streets not loading

### ISSUE THREAD

**Issue by nilshoerrmann** [mapbox/mapbox-studio-classic#65]
Using Safari 6.0.5 on Mac OS 10.7.5, MapBox Street is not loading. I get this error in the console, referencing a line in `Editor.prototype.refresh`:

``` js
TypeError: 'undefined' is not an object (evaluating 'map.options.minZoom = this.model.get('minzoom')')     style:3012
```

It's working just fine in Firefox.

**Comment by yhahn** [comment]
Please reopen if still happening.
