### ISSUE TITLE
Only open color picker when clicking actual color, not hex value

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox-studio-classic#650]
Refs https://github.com/mapbox/mapbox-studio/issues/125#issuecomment-51973519

I found myself clicking into a hex color to quickly change a color to a different hex value, or highlighting to replace it with a copy-pasted hex. The fancy dancy color picker coming up is a bit disruptive for us old school "touch-and-typers" and even after saving to see the changes, the color picker lingers like an awkward, uninvited party guest.

![colorpick](https://cloud.githubusercontent.com/assets/200357/3897424/7434a64c-2261-11e4-95c0-53493941aaac.gif)

How about: raise color picker when hitting the little color circle to the left, otherwise leave text interactions alone.

**Comment by samanpwbb** [comment]
The behavior is definitely not ideal right now. This would be doable, but would requiring modifying the plugin: https://github.com/mapbox/mapbox-studio/blob/master/ext/inlet.js#L1065-L1083 - and I'm not sure we want to go there.

**Comment by srsjojo** [comment]
+1 @heyitsgarrett

Alternatively: Enable/disable the Fancy Dancy©  color picker in settings somewhere

**Comment by yhahn** [comment]
No.
