### ISSUE TITLE
Add source button should be named "Add", not "Update"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-studio-classic#652]
"Update" sounds like it will change the currently selected source.

**Comment by karenzshea** [comment]
I probably am overlooking some important usefulness, but I'm wondering if we need to have it at all. 

'Add'-ing a source from there on the /data page means uploading an entirely new set of .mbtiles, which is more or less the same as adding a source from 'Upload data' and deleting the old one.
