### ISSUE TITLE
Saving source clobbers comments in YAML

### ISSUE THREAD

**Issue by pnorman** [mapbox/mapbox-studio-classic#655]
When editing a layer in the YAML and saving the source, mapbox-studio removes any comments in the YAML.

To reproduce
1. Clone [natural-earth-tm2](https://github.com/mapbox/natural-earth-tm2)
2. Edit `natural-earth.tm2source/data.yml` to add a comment in a layer
3. Open `natural-earth.tm2source` in mapbox-studio
4. Edit a different layer
5. Save

The comment is now gone.

**Comment by tmcw** [comment]
I don't think [most implementations](https://github.com/nodeca/js-yaml) would allow you to permit comments in YAML for parsing and generation... this might not be fixable in any simple way.

**Comment by pnorman** [comment]
Any YAML implementation needs to permit [comments](http://www.yaml.org/spec/1.2/spec.html#id2767100) - but comments must not have any effect on the serialization tree or representation graph.

This is the old problem of a configuration file that can either be written to by hand or by a GUI. I guess the solution here is to never edit `data.yml` through the GUI, but only with a text editor.
