### ISSUE TITLE
Divide by zero with !pixel_width!

### ISSUE THREAD

**Issue by pnorman** [mapbox/mapbox-studio-classic#659]
With SQL like

``` sql
(SELECT 
    ST_PointOnSurface(geom) AS label_geom, id
  FROM water
  WHERE label IS NOT NULL 
    AND geom && !bbox!
    AND ST_Area(geom)/(!pixel_width!*!pixel_height!) > 10
) AS water_labels
```

I get a divide by zero error. 

```
Postgis Plugin: ERROR:  division by zero

in executeQuery Full sql was: 'SELECT ST_SRID("label_geom") AS srid FROM (SELECT 
    ST_PointOnSurface(geom) AS label_geom, id
  FROM water
  WHERE label IS NOT NULL 
    AND geom && 'BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d
    AND ST_Area(geom)/(0*0) > 10
) AS water_labels
 WHERE "label_geom" IS NOT NULL LIMIT 1;'
```

I'm reporting this here rather than Mapnik because the [equivalent SQL](https://github.com/pnorman/openstreetmap-carto/commit/d8afe6fc0c4d5b104a7726d49634b1001a667a8e) works fine in TM1.

The solution might be a change in Mapnik or a change mapbox-studio.

**Comment by springmeyer** [comment]
I doubt it has anything to do with either Tilemill or Mapbox-studio. This post (http://sqlbrain.wordpress.com/2009/10/06/avoid-sql-divide-by-zero-errors-by-using-nullif/) seems to indicate that it happens only when no rows are returned. So the lack of error in Tilemill may be because some rows are being returned.

**Comment by yhahn** [comment]
Pls reopen if it's clear this is a studio-specific issue.

**Comment by pnorman** [comment]
> I doubt it has anything to do with either Tilemill or Mapbox-studio.

Thinking about it, you might be right. A pixel width of 0 is absurd, and that's probably coming from Mapnik?

> This post (http://sqlbrain.wordpress.com/2009/10/06/avoid-sql-divide-by-zero-errors-by-using-nullif/)  

Ya, I've ended up using `NULLIF` to work around the divide by zero error. It might screw up the Tilemill data display, but I don't use that anyways.

> seems to indicate that it happens only when no rows are returned. So the lack of error in Tilemill may be because some rows are being returned.

That's specific to that situation, where if no rows are returned, `COUNT(*)` is 0, so you get a division by zero. In this situation it's a divide by zero regardless of how many rows would otherwise be returned.

**Comment by pnorman** [comment]
> Pls reopen if it's clear this is a studio-specific issue.

A layer with this in SQL works fine in TileMill, so it looks studio specific. I'm not sure if it should be fixed here or upstream in Mapnik.
