### ISSUE TITLE
Getting error when launching Studio

### ISSUE THREAD

**Issue by mwanee** [mapbox/mapbox-studio-classic#660]
From both the app and from within Terminal, I'm getting an error message when trying to launch Studio.

![screen shot 2014-08-14 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/5572214/3926903/c0f39a52-23f5-11e4-976e-f019f51cc45b.png)

cc @samanpwbb @yhahn @dnomadb

**Comment by incanus** [comment]
@mwanee This happened to me and in my case it was based on an old TM2 preference. Try moving yours aside. 

If you're ok with Terminal, you want to rename or move aside `~/.tilemill/v2`. 

For Finder, you can do this with `Shift-Command-G`, then entering `~/.tilemill`, then renaming the `v2` folder in that window. Then restart Studio.

**Comment by mwanee** [comment]
thanks @incanus -- literally 1 minute before you posted this, Will & Saman helped me get it up and running!
