### ISSUE TITLE
ctrl-e opens the export window instead of going to the end of a line

### ISSUE THREAD

**Issue by mojodna** [mapbox/mapbox-studio-classic#662]
My fingers are wired for readline / emacs key bindings and I keep accidentally opening the export window when meaning to jump to the end of a line.

**Comment by camilleanne** [comment]
Oh. Since I am not a member of the Church of Emacs that didn't occur to me.

**Comment by mojodna** [comment]
More OS X text field key bindings here: https://coderwall.com/p/usc8qg

**Comment by samanpwbb** [comment]
We should be able to scope export window to command key (metaKey) only, so ctrl (ctrlKey) still works for navigating code.

I'm not a linux user. @mojodna you guys have a metaKey?

**Comment by tmcw** [comment]
This isn't a unix thing, it's present in all normal textareas in osx, and in bash. We shouldn't use e for export - let's use something like `ctrl+shift+s`, which is used by [photoshop](http://helpx.adobe.com/content/dam/help/attachments/PhotoshopCC-KBSC.pdf) as save-as.
