### ISSUE TITLE
Reorder buttons in 'Settings'?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#670]
Currently the buttons are ordered like this:

![screen shot 2014-08-18 at 3 15 34 pm](https://cloud.githubusercontent.com/assets/5607844/3956535/3cfe063c-270c-11e4-97f2-2c4611ab5cd4.png)

I think it makes more sense for 'Download package' to be the second button, since this and 'Upload to Mapbox' outputs the same file type, while 'Export image' creates different file types.

**Comment by camilleanne** [comment]
I agree :thumbsup:

**Comment by samanpwbb** [comment]
Related: I don't like that there's an export image button here and also an export image button in the top right corner. Can we pick one? If I were to pick, I would keep the top right button and drop it from the list in settings, since it's behavior is different from the other settings actions.

**Comment by samanpwbb** [comment]
@nickidlugash this is an easy change to make and suggest as a pull request: https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/style.html#L146-L163

**Comment by yhahn** [comment]
Do we even need the export image button anymore?
