### ISSUE TITLE
mapnik.node not found on particular Windows

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#681]
Ran into this with @teddyumd at maptime.

Windows 7 professional x64.

Will investigate more.

cc @springmeyer

**Comment by springmeyer** [comment]
Hmm, shoot. node-mapnik@1.4.12 (currently referenced in master) should provide windows binaries. If you saw an error message let me know.

**Comment by yhahn** [comment]
@springmeyer hrm, so the file existed and the same build was working on other windows machines. Interestingly the error was about the file not being found (though the path was correct), not a C++ module require error.

**Comment by yhahn** [comment]
@springmeyer I can reproduce this error on the IE9/Win7 VM from https://www.modern.ie/en-us/virtualization-tools.

The `mapnik.node` file definitely exists and running just a bare node process and attempting to `require()` it leads to the same error message:

```
Error: The specified module could not be found.
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-ia32\mapnik.node
    at Module.load (module.js:356:32)
    ...
```

**Comment by yhahn** [comment]
NM, (headsmack) it was the need to install the visual c++ redistributable (http://www.microsoft.com/en-us/download/details.aspx?id=40784).

Going to research whether the installer can do this...

**Comment by springmeyer** [comment]
Aha. The installer was doing it previously but TileMill was still depending on the 2010 one. We need 2013 now.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/pull/738
