### ISSUE TITLE
Can't stop TM2 with Ctrl-c after exporting source

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#69]
After exporting a source MBTiles from TM2 (or starting one then cancelling it), I can no longer stop the server with ctrl-c.

**Comment by springmeyer** [comment]
ha, also just hit this.

**Comment by springmeyer** [comment]
https://github.com/mapbox/tilelive-vector/issues/41 should be fixed but does not appear to be the cause of this problem.

**Comment by ian29** [comment]
looks like this is still occurring as of 98f3273

**Comment by springmeyer** [comment]
still occurring in master. workaround either with `killall tm2` in another terminal or with this nuclear patch:

``` diff
diff --git a/lib/tm.js b/lib/tm.js
index c7d5fef..f7e93e3 100644
--- a/lib/tm.js
+++ b/lib/tm.js
@@ -14,6 +14,10 @@ tilelive.protocols['mbtiles:'] = require('mbtiles');

 var tm = {};

+process.on('SIGINT', function() {
+    process.exit(0);
+});
+
 // Set or get config.
 tm.db;
 tm._config = {
```

**Comment by yhahn** [comment]
Fixed via tilelive upgrade.
