### ISSUE TITLE
more interesting/detailed default style

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#7]
Show off more of the data

**Comment by yhahn** [comment]
y a couple params here
- 1 stylesheet/file
- no image assets for now
- hrm fonts hrm would be great to bundle some open ones with tm2 and use one of them?

**Comment by springmeyer** [comment]
yes, I would love to release a new node-mapnik version that completely stops trying to register any fonts and leave this up to tm2/tilemill. Bundling a few in the app sounds good to me.

**Comment by ajashton** [comment]
Here is something I came up with: https://gist.github.com/ajashton/49da609fb8ec21cd7aa2

I used [Source Sans](http://sourceforge.net/adobe/sourcesans) but could change this to Open Sans or something else.

Not sure how to approach adding this to TM2 given the current default style is just a string in index.js

**Comment by yhahn** [comment]
Greato, next actions for you @ajashton 
- [x] Put it in its own repo (`tm2-default-style` or so?)
- [x] Add a `package.json` similar to that in mapbox-streets
- [x] Add an entry for it in tm2 `package.json`
- [x] Check that npm install for tm2 pulls it into the `node_modules` directory

I can take it from there.

**Comment by ajashton** [comment]
to @yhahn

**Comment by yhahn** [comment]
Basics in place, needs #8 to do font path registration as well.
