### ISSUE TITLE
%20 => spaces in FS paths

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#70]
Handle spaces in folders/project names etc.

**Comment by springmeyer** [comment]
also #64

**Comment by zeke** [comment]
Saving to my `Dropbox (Personal)` directory didn't work. tm2 created a new directory with a `%20` where the space should be:

```
Dropbox (Herokai)
Dropbox (Personal)
Dropbox%20(Personal)
```

```
zeke $ tree Dropbox%20\(Personal\)
Dropbox%20(Personal)
└── MapBox
    └── parks.tm2
        ├── project.xml
        ├── project.yml
        └── style.mss
```

Interestingly when I browse that _accidental_ directory in tm2, it reads from the _original_ directory:

![http://cl.ly/image/06120t0e2t0f/Screen%20Shot%202014-04-10%20at%209.00.23%20AM.png](http://cl.ly/image/06120t0e2t0f/Screen%20Shot%202014-04-10%20at%209.00.23%20AM.png/content#.png)
