### ISSUE TITLE
Windows testing reliability

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#711]
Needs more investigation. Things I'm seeing:
- appveyor is considerably less reliable than running on my local VM
- even on local VM certain fs operations don't always seem to be complete when node says they are, e.g. (`fs.writeFileSync(foo)`, `fs.readFileSync(foo)` error 1/20 times!)

**Comment by springmeyer** [comment]
Ugh. I wonder if node v0.11.x might behave better?

**Comment by yhahn** [comment]
Tracked down a few of these issues last night. Things like this handle differently on appveyor than our VMs:

https://github.com/mapbox/mapbox-studio/commit/8654d6e9c70729c9cef0539ecc1d8014aa9b1583

Remaining issue seems to be phantomjs runs sometimes segfaulting, something I see on Mac OS X travis runs sometimes as well.
