### ISSUE TITLE
conflicting keybindings

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#712]
I realize that `Control` can be used in place of `Command` (`⌘`) for these, but they do still override the system-wide standards. 

![screen shot 2014-08-22 at 2 09 00 pm](https://cloud.githubusercontent.com/assets/17722/4017465/a8913e5a-2a40-11e4-93d9-062239cee154.png)
- `Command + H`: Hide app
- `Command + Shift + H`: Hide other apps

I'd recommend: 
- `Command + ?` for help
- Passing through `Command + Shift + H` to the system

**Comment by tmcw** [comment]
Same as #715
