### ISSUE TITLE
atom.exe Entry Point Not Found on Windows

### ISSUE THREAD

**Issue by stephankn** [mapbox/mapbox-studio-classic#718]
Installed v0.0.4 on Windows Vista 64 bit.

Trying to launch Mapbox Studio produces the following error message before the application is forcefully closed. 

```
---------------------------
atom.exe - Entry Point Not Found
---------------------------
The procedure entry point RegisterTouchWindow could not be located in the dynamic link library USER32.dll. 
---------------------------
OK   
---------------------------
```

**Comment by stephankn** [comment]
you should not call this on Windows previous of Win7.
Refer to this:
http://msdn.microsoft.com/en-us/library/windows/desktop/dd317326%28v=vs.85%29.aspx

**Comment by yhahn** [comment]
@stephankn can you confirm whether this occurs in the latest atom-shell release (the app wrapper we are using)? May be an upstream issue that needs fixing there.

https://github.com/atom/atom-shell/releases

**Comment by stephankn** [comment]
Tt also crashes with atom-shell v0.15.9. Suppose there is code missing to not call RegisterTouchWindow on unsupported versions.

I think it's an issue with Chromium. Does it support Vista at all?

If not: Instead of simply crashing a proper error message should be displayed. Best already in the installer that dependencies are not met.

**Comment by wilhelmberg** [comment]
I can confirm, that it is an upstream issue.

**Comment by mikeseeh** [comment]
We have the same problem on Windows 7.

**Comment by pistou** [comment]
Just had the same issue on Windows Vista 32 bit (install via Chocolatey)

**Comment by wilhelmberg** [comment]
@TouPye 
**Vista** is not supported. You might want to switch to a more recent OS anyway.

Keep in mind MapBox Studio 0.1.6 is 64bit only, at the moment.
On a 32 bit OS (W7 and newer), you might want to use 0.1.5:
https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-previous-releases.md

**Comment by springmeyer** [comment]
MapBox Studio v0.2.0 is now out and the installer kindly enforces at least Windows 7. Mapbox Studio v0.2.0 also uses atom-shell https://github.com/atom/atom-shell/releases/tag/v0.19.2. If anyone hits problems like this again please create a new issue.
