### ISSUE TITLE
Encountering aggressive simpliciation

### ISSUE THREAD

**Issue by caged** [mapbox/mapbox-studio-classic#72]
I'm pulling in a PostGIS source for US Census blocks, however when rendering the source, it appears there's some really aggressive simplification happening somewhere.

Here's a zoomed in version of Portland, OR which typically should contain a bunch of small square polygons. 

![screen shot 2013-10-25 at 1 03 03 pm](https://f.cloud.github.com/assets/25/1411078/05842f96-3db1-11e3-869c-f7ae36a46f99.png)

Perhaps I'm missing something or there's a setting somewhere that I need to tweak?

**Comment by yhahn** [comment]
What is the maxzoom of your source? I think it defaults to z6 which is super low...

**Comment by caged** [comment]
The zoom extent appears to be 0-22.  I tried another source, a shapefile this time, and it appears to have the same issue. [Here's a zip of the shapefile](https://dl.dropboxusercontent.com/u/602885/portland-neighborhoods.zip) (337kb).

![screen shot 2013-10-25 at 1 19 26 pm](https://f.cloud.github.com/assets/25/1411190/22599ed8-3db3-11e3-9083-4358974283ee.png)

**Comment by yhahn** [comment]
Yeah sorry this can be very confusing right now. I'm talking specifically about the source, not the style:

![tmp-source](https://f.cloud.github.com/assets/83384/1411216/b8de6d5c-3db3-11e3-8d18-bb60621a3aca.png)

**Comment by caged** [comment]
No problem.  The new UI can be a bit confusing. It was set on 6, as you suspected.  I bumped it up to 22, but there wasn't any noticeable difference when going back to the Style area and viewing the map again.

![screen shot 2013-10-25 at 1 29 56 pm](https://f.cloud.github.com/assets/25/1411252/4d3759c8-3db4-11e3-8cb5-94f1e2a1404c.png)

Let me know if if there's anything else I can take a look at.

**Comment by yhahn** [comment]
Yep, make sure your source is saved and you may need to clear all kinds of caches atm (source cache, browser cache, restart tm2):

![tmp-sourcecache](https://f.cloud.github.com/assets/83384/1411300/07c9def0-3db5-11e3-8228-ab01b65d9867.png)

**Comment by caged** [comment]
Nice.  That definitely moved things in the right direction.  Now it appears there are stray grid lines running through the area.  I've included a TileMill 1 screenshot for comparison.

**TileMill 2**

![screen shot 2013-10-25 at 1 40 44 pm](https://f.cloud.github.com/assets/25/1411336/f0eebe02-3db5-11e3-8b6b-8491693af555.png)

**TileMill 1**

![screen shot 2013-10-25 at 1 40 31 pm](https://f.cloud.github.com/assets/25/1411338/fff236b8-3db5-11e3-902c-15c6dd50bcdb.png)

**Comment by yhahn** [comment]
Yep, try increasing the buffer-size slider on the source layer to something like 4 or 8.

Save + caches will need to be cleared.

**Comment by caged** [comment]
Perfect!  That appears to have cleared things up.  Thanks for walking me through the process.  Feel free to consider this issue closed.

**Comment by yhahn** [comment]
Nope, we have had long discussions here about trying to automate this process (most of these values can have sensible defaults detected for them by a machine) so leaving this open to remind us of how painful it is : )
