### ISSUE TITLE
Projects not rendering

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#726]
Well, not totally blank - the background color is still being rendered:

![2014-08-26_1717](https://cloud.githubusercontent.com/assets/735463/4051935/a233d9a4-2d66-11e4-8d7b-44cc0e4e917e.png)
- Nothing being reported at the console (+ no crash). 
- This is happening for all projects.
- My last mapping-related action was to edit the colors of the shields (of a project based on OSM Bright 2) in GIMP. No filenames or locations were changed.

Is there a more verbose logging method I could use to get more info about this?

**Comment by yhahn** [comment]
@wboykinm update to the latest version and re-npm install (clear out your node_modules directory before).

We had some breaking changes in deps around ~0.0.3.

**Comment by wboykinm** [comment]
That did it. Thanks! And that's a pretty sweet trick how you managed to persist the Map IDs of my existing projects :)
