### ISSUE TITLE
How to add interactivity

### ISSUE THREAD

**Issue by gabrielflorit** [mapbox/mapbox-studio-classic#727]
Hello,

This is most likely user error, but I can't figure out how to add interactivity to my source?style? Not sure how to get started.

Gabriel

**Comment by yhahn** [comment]
The backstory here is that utfgrid is fast becoming a legacy technology -- the vector tile js library used by mapbox GL makes it easy to access the data in PBF vector tiles directly in the browser in a much more powerful way without an intermediary utfgrid/json format.

Until GL is prime time and ready though, studio has some behind the scenes way for you to enabled interactivity on projects. We nuked the UI for this a while ago: https://github.com/mapbox/mapbox-studio/pull/465. I'll look into adding a docs/example for how to use this soon.

**Comment by gabrielflorit** [comment]
Thanks for the note. It's incredible that "utfgrid is fast becoming a legacy technology" - a testament to how fast you guys move. Mapbox Studio is pretty amazing.

**Comment by wheredoesyourmindgo** [comment]
It appears there are some parameters such as interactivity_layer and template named in the project.yml file for Style specifics.  Could this be a place to add such behavior?  I haven't been able to get this to work but maybe someone else can.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-advanced-features.md#utfgrid-interactivity

Sorry for the delay.

**Comment by jmoe** [comment]
That link seems broken now. Is viewing the markdown in the PR the only option now?

**Comment by gabrielflorit** [comment]
@jmoe see here: https://www.mapbox.com/guides/style-quickstart/#utfgrid

**Comment by jmoe** [comment]
That's great, thanks!

**Comment by galkamax** [comment]
I get the feeling I am just overlooking something simple, but I don't see a project.yml file. My .tm2source directory has only a data.yml file, which does not have an "interactivity_layer:" parameter.

I tried adding it anyway, but that does not seem to have worked.

Any suggestions?

Thanks.

**Comment by amyleew** [comment]
@galkamax - You'll find the project.yml and `interactivity_layer` in the map style directory's `.tm2` folder. The UTFgrid is defined by map _style_ instead of in the data _source_ which is the `.tm2source` directory.

**Comment by galkamax** [comment]
Completely missed that there were two directories. Thanks a lot for the quick response.
