### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jqtrde** [mapbox/mapbox-studio-classic#73]
`osx: 10.9` `node -v: 0.10.21` `mapnik: 2.2.0`

Ran through the source install steps as described [here](https://github.com/mapbox/tm2#source-install).

Getting the following error on `node index.js`

```
dyld: lazy symbol binding failed: Symbol not found: __ZN6mapnik16datasource_cache20register_datasourcesERKSs
  Referenced from: /Users/Jacques/bin/tm2/node_modules/mapnik/lib/_mapnik.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN6mapnik16datasource_cache20register_datasourcesERKSs
  Referenced from: /Users/Jacques/bin/tm2/node_modules/mapnik/lib/_mapnik.node
  Expected in: dynamic lookup

[1]    71880 trace trap  node index.js
```

I'd happily just use one of the binaries, but [https://tilemill.s3.amazonaws.com/index.html?path=dev/](https://tilemill.s3.amazonaws.com/index.html?path=dev/) just sits at `loading...` forever.

I want to make cool maps like AJ Ashton!

:love_letter:

**Comment by springmeyer** [comment]
@jacquestardie - question: did you recompile mapnik after installing 10.9? Also reported at https://github.com/mapnik/node-mapnik/issues/189. I'm looking into it (need to get 10.9 set up first myself).

**Comment by rclark** [comment]
I had the same issue yesterday on an entirely fresh 10.9 installation. For
my part `npm install` goes fine (once I installed xcode in its entirety),
but these errors are thrown when I try and run tm2.

On Thu, Oct 31, 2013 at 12:08 PM, Dane Springmeyer <notifications@github.com

**Comment by springmeyer** [comment]
The root of problem appears to be that while libmapnik is being properly linked to libc++ (when rebuilt on 10.9) node-mapnik still ending up linking to libstdc++. Linking to 2 different incompatible c++ standard libraries is not going to work. Node itself is also linking to libstdc++ (even when I compile from source on homebrew).

So, I have no viable workaround yet: will continue investigating tomorrow.

**Comment by springmeyer** [comment]
Found a workaround:

``` sh
rm -rf node_modules/
export CXXFLAGS="-mmacosx-version-min=10.9"
export CFLAGS="-mmacosx-version-min=10.9"
export LDFLAGS="-mmacosx-version-min=10.9"
npm install
```

**Comment by thomasgalambos** [comment]
It works, thank you!

**Comment by jqtrde** [comment]
works here too, thanks @springmeyer

**Comment by springmeyer** [comment]
@jacquestardie - glad the workaround fixed your source compile. However the binaries should work. Can you tell me which binary you tried and provide more detail about the hang? I just tested the latest one: http://tilemill.s3.amazonaws.com/dev/tm2-osx-2013-11-01-d734ec2.tar.gz. I needed to edit my security settings to be able to run the `start.command`, but otherwise things worked:
![screen shot 2013-11-01 at 12 47 37 pm](https://f.cloud.github.com/assets/20300/1456546/8a58f5ee-432e-11e3-8802-df19601ecc87.png)

**Comment by jqtrde** [comment]
Didn't actually get to try any of the binaries. https://tilemill.s3.amazonaws.com/index.html?path=dev/ just sits and hangs for me.

![](http://i.imgur.com/vyvbgW7.png)

Can wait here 30m, and it'll just keep `loading...`. I've tried with different connections, always using Chrome.

**Comment by jqtrde** [comment]
Just tried Safari, opened immediately..

**Comment by springmeyer** [comment]
ah, I see. cool, well can you try http://tilemill.s3.amazonaws.com/dev/tm2-osx-2013-11-01-d734ec2.tar.gz ? I'd also be interested if you can detect any differences in performance between the binary and your source compiled version, but no worries if you can't.

**Comment by jqtrde** [comment]
yep, grabbing it now

**Comment by jqtrde** [comment]
The binary is certainly more stable than what I compiled.

I get a `segfault` when I try to affect any of the options in the compiled version. In addition, the basemap itself doesn't render with the source build. Meanwhile, the binary works fine.

I'm hoping to get around to actually making and uploading a map later today, if I have any issues I'll post em up.

**Comment by springmeyer** [comment]
@jacquestardie - thanks for the details. Regarding uploading: there is no support for uploading at this time.

**Comment by cappelaere** [comment]
Just add the same problem installing node-mapnik in a node.js app.  Thank you for the workaround.
Pat.

**Comment by Pana** [comment]
TKS, this works for me

**Comment by connor** [comment]
Workaround worked for me! Thanks @springmeyer

**Comment by springmeyer** [comment]
@connor - great, thanks for the followup!

**Comment by zzolo** [comment]
I can confirm that the workaround that @springmeyer mentioned worked for me.
https://github.com/mapbox/tm2/issues/73#issuecomment-27548009

**Comment by springmeyer** [comment]
Note: the final solution I arrived at to avoid this issue was https://github.com/mapnik/node-mapnik/commit/e21503b34bce8b084fb027dfb66eaf5ce18c8b17. But overall this only ever a problem with source installed node-mapnik + externally compiled mapnik on 10.9 and luckily this is much more of a rare case now that node-mapnik ships with https://github.com/mapbox/node-pre-gyp binaries.

**Comment by andfinally** [comment]
Thanks! springmeyer's workaround worked for me too
