### ISSUE TITLE
Calculate extents of PostGIS-loaded data

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#731]
All my postgres WGS84 data sources show extent of '-180,-85.0511,180,85.0511' which looks more like the entire globe rather than the UK-based data that should be something like '-8.58,49.89,1.76,60.85' reported by postgis.

Should the subtle 'zoom to extent' marker icon use the extents values? It would make finding my source data easier.

**Comment by yhahn** [comment]
Yes, postgres layers currently don't have their extents properly autodetected for them. Something to look into.

**Comment by springmeyer** [comment]
this was fixed as part of https://github.com/mapbox/mapbox-studio/pull/1199
