### ISSUE TITLE
Cannot read property 'accesstoken' of undefined

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#737]
From a user running v0.0.5:

> I downloaded and installed Mapbox Studio on my computer - running Mac OS X 10.9.4 - and then tried to Connect to my Mapbox account. After I entered my login details, the program gave the error pictured in the jpg I've attached, and seems stuck on this screen.
> 
> I've tried pressing the white X, the program appears to refresh the screen but it does not change.
> I've also tried to uninstall and reinstall. Again, this makes no difference.

Also tried revoking access on account and going through the process again with no luck.

**Comment by yhahn** [comment]
Please have the user post a copy (in a gist) of `~/.mapbox-studio/app.log`.

**Comment by KcKal** [comment]
Hey there, I've had the same issue on a Windows machine and I'm running v0.0.6 and did a quick gist for you. The issue worked out precisely in the same fashion as it did for the user above. 

https://gist.github.com/KcKal/f684010b2c2849b2a89a

**Comment by lunaeidolon** [comment]
My app.log, same error.

[app.log](http://cl.ly/XKVp)

**Comment by yhahn** [comment]
Should be fixed in next release by above.

**Comment by KcKal** [comment]
Yeap, I edited the few lines of code on local and it worked for me.
