### ISSUE TITLE
file save / download dialog should have sane default

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#741]
When you go to save a static image, package, etc., you get a native file save dialog: 

![screen shot 2014-08-28 at 4 02 10 pm](https://cloud.githubusercontent.com/assets/17722/4084316/79761412-2f07-11e4-8ccb-24e4b96752f4.png)

However, this just pre-fills with the extension, which starts will a dot and as such will get saved as a hidden file if nothing else is done. 

It also defaults to the hard drive root, which is weird and will fail for non-admins. 

We should pre-fill a sane default like `Untitled.png` or whatever. Atom might have facilities to help with the inevitable de-dupe / overwrite scenario, too.

**Comment by incanus** [comment]
Possibly related, though it looks like currently we just leave it up to the Chromium core to prompt for unrecognized binaries. 

https://github.com/atom/atom-shell/blob/master/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback

**Comment by yhahn** [comment]
FYI this is all handled here:

https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/atom.js

and is a client-side hack/stopgap for a developing atom-shell API around intercepting/handling requests.

**Comment by yhahn** [comment]
@camilleanne hit this.
