### ISSUE TITLE
blank codemirror on refresh/first open

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#742]
When first opening a style, I see: 
![screen shot 2014-08-29 at 1 14 54 pm](https://cloud.githubusercontent.com/assets/108094/4093772/b48306fc-2fa0-11e4-9566-22fdee8be545.png)

Need to click the tab to access the style. Happens for all projects.

**Comment by mikemorris** [comment]
CodeMirror has some bug around needing to call `.refresh()` if it starts in a hidden `div`

https://github.com/prose/prose/blob/4f803867a5ad4cd8b019176839ca5f5e8889ed29/app/views/file.js#L347

http://stackoverflow.com/questions/17086538/codemirror-content-not-visible-in-bootstrap-modal-until-it-is-clicked
https://github.com/angular-ui/angular-ui-OLDREPO/issues/245

**Comment by samanpwbb** [comment]
Fixed by https://github.com/mapbox/mapbox-studio/commit/e4ab6ff86891b47cfd5155350c33376feb2dd54d
