### ISSUE TITLE
prefix ids of layer entries in source mode

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#745]
Ran into this disaster with a source named "map" and again with a layer named 'full:
![screen shot 2014-08-30 at 5 38 28 pm](https://cloud.githubusercontent.com/assets/108094/4100303/1f2029b6-308e-11e4-9feb-693143c3fd1e.png)

**Comment by samanpwbb** [comment]
I kept running into this so I made a local fix. My fix prefixes the ID of the layer with 'item-'. This requires doing a lot of `$(this).attr('id')` -> `$(this).attr('id').split('item-').pop();`. 

@yhahn I know it's not in line with patterns elsewhere in the app, but might be cleaner to just use another attribute to store the layer name besides ID?

**Comment by yhahn** [comment]
> but might be cleaner to just use another attribute to store the layer name besides ID

yez
