### ISSUE TITLE
Stronger relationship between "Add" and Places

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#747]
The add button looks like it's on the same hierarchy as the others.

![2014-08-30 at 10 34 pm](https://cloud.githubusercontent.com/assets/61150/4100823/9b8e8cc6-30b7-11e4-9366-4f7c7d9ba8ea.png)

To make the relationship stronger:
- The background of the "Add" button could be darker? 
- Use a plus (+) icon instead of spelling out "Add"

**Comment by peterqliu** [comment]
Agreed. I suggest 

1) returning Places to the left sidebar (since it's not an action dealing with the current map view, but one that's toggling a new view), and 

2) changing Add to "Add New Place", in order to strengthen the connection between the two buttons

**Comment by yhahn** [comment]
> returning Places to the left sidebar (since it's not an action dealing with the current map view, but one that's toggling a new view), and

Let's keep this where this is now and see how users actually interact with this feature. The interaction isn't perfect but it only takes using it once or twice to figure out how it works.

**Comment by tmcw** [comment]
Noting that we're seeing one or two users in support tripping over this thinking it will add sources and not getting any informative feedback after clicking it.

**Comment by samanpwbb** [comment]
> Noting that we're seeing one or two users in support tripping over this thinking it will add sources and not getting any informative feedback after clicking it.

oof, that's bad. I will fix this :P
