### ISSUE TITLE
Saved center of exported source can be invalid

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#75]
I exported an mbtiles from z0-7, but the saved center happened to be at z8. Makes sense for the source but not the exported mbtiles. Could either be fixed here or should things that read the mbtiles be more flexible?

**Comment by yhahn** [comment]
Heh, this is no longer invalid because of overzooming... guess technology overtook our spec : P

Will meditate.

**Comment by yhahn** [comment]
https://github.com/mapbox/tm2/issues/156
