### ISSUE TITLE
Clicking 'upload to mapbox' should reset upload screen

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#750]
I made a change to a geoJSON source, clicked 'upload', and hit this screen:
![screen shot 2014-08-31 at 8 36 43 pm](https://cloud.githubusercontent.com/assets/108094/4103708/3dbd27a6-3170-11e4-8487-328a6e3d43e6.png)

To upload, I needed to click the 'redo upload' button.

**Comment by yhahn** [comment]
Refactoring the state management around this this is not a priority. Click **redo upload** for now.
