### ISSUE TITLE
Windows 7 atom.exe permissions error

### ISSUE THREAD

**Issue by cartdeco** [mapbox/mapbox-studio-classic#751]
Hi Guys,

Am trying to run Mapbox-studio v 0.0.6 on Windows 7 and can't get past this:

![image](https://cloud.githubusercontent.com/assets/2177209/4103794/f21d4024-3174-11e4-9fda-b14d56cd636f.png)

Any clues on how to fix?

**Comment by wilhelmberg** [comment]
It seems you are on 32bit Window 7, correct?
Or did you manually choose **not** to install into `C:\Program Files (x86)`?

**Comment by cartdeco** [comment]
Yes 32 bit. Have solved the problem. This seems to be related to the Sophos virus scanner issue. Disabling Sophos in the Services panel fixes this.

**Comment by yhahn** [comment]
@cartdeco ok, this is an instance of https://github.com/mapbox/mapbox-studio/issues/828 ?

Going to close here and track there -- reopen if not the case.

**Comment by bladepeter** [comment]
I running mapbox studio on win7 x64,the process running , then colsed itself,why?

**Comment by springmeyer** [comment]
@bladepeter see https://github.com/mapbox/mapbox-studio/issues/976#issuecomment-61400660 for a workaround until we get a new release out.
