### ISSUE TITLE
Emphasize open-able files in file browser

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#755]
The gray ones are the ones you can open: 

![screen shot 2014-09-02 at 2 46 15 pm](https://cloud.githubusercontent.com/assets/108094/4123775/7f1e91d2-32d1-11e4-8908-a3226414413a.png)

This is a bit backwards (and my fault upstream in base... but not sure about an easy solution besides override base in mapbox studio).

**Comment by springmeyer** [comment]
:+1 this has tripped me up too.

**Comment by camilleanne** [comment]
What's the chance we could have an icon for .tm2 and .tmsource that's not a folder when viewing in mapbox studio?

**Comment by yhahn** [comment]
Good call

**Comment by incanus** [comment]
Depending how far down the hole you want to go: 

https://github.com/atom/atom-shell/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback

> The `filters` specifies an array of file types that can be displayed or selected, an example is:
> 
> ``` js
>   filters: [
>     { name: 'Images', extensions: ['jpg', 'png', 'gif'] },
>     { name: 'Movies', extensions: ['mkv', 'avi', 'mp4'] },
>    { name: 'Custom File Type', extensions: ['as'] },
>   ]
> ```

**Comment by samanpwbb** [comment]
Doing this in `design-cleanup`:
![screen shot 2014-09-09 at 12 14 54 pm](https://cloud.githubusercontent.com/assets/108094/4205041/9ff85cb0-383c-11e4-996e-20da408e8f67.png)
