### ISSUE TITLE
Uninstaller doesn't remove Program Files directory

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/mapbox-studio-classic#756]
After using the uninstaller this directory structure is still there:
![mstudio-orphan-diretories](https://cloud.githubusercontent.com/assets/4549888/4137525/e5a192e0-3387-11e4-8627-e89fcbb92c3b.png)

**Comment by yhahn** [comment]
@BergWerkGIS same as https://github.com/mapbox/mapbox-studio/issues/611 right?

**Comment by wilhelmberg** [comment]
More or less, yes.
I was under the impression that with #611 there are several directory trees that are left behind.
Now it's only the folder `integration` (and the path leading to it).
If this is a double, please close.

**Comment by yhahn** [comment]
Yep.
