### ISSUE TITLE
Export MBTiles locally

### ISSUE THREAD

**Issue by alexkurtz** [mapbox/mapbox-studio-classic#770]
Hi! I would like to know if it is (or will be) possible to create tiles that can be stored locally (for example, to locally test a server) without having to upload to Mapbox.

**Comment by yhahn** [comment]
Studio only exports vector tiles in to MBTiles files -- you can render these on your own server in conjunction with a style if you like but they are not static image files like you may be used to.

We're viewing static image files for maps as a legacy approach to web maps at this point. Hidpi/retina devices and on-device rendering makes it necessary to serve 256x256, 512x512, 150+ dpi images on the fly and also send data in different formats to the client for rendering.
