### ISSUE TITLE
Race condition on end of upload

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#773]
While investigating uploads found a race condition where [`source.info`](https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/source.js#L380-L455) is being called in the middle of `source.save` writing `data.yml` to disk, so `source.info` outputs `null` and errors as `null` is invalid YML. 

This causes the end of the upload to hang indefinitely in the UI, even though the upload completed successfully.

**Comment by mick** [comment]
@camilleanne I was just uploading a source and it hung in the UI at 100%, and mapbox.com now says it is broken

**Comment by camilleanne** [comment]
@mick can you open up your developer tools and tell me if you see a 500 error in there?

**Comment by mick** [comment]
Sorry I had already restarted the upload.
