### ISSUE TITLE
Style mode map center is wrong

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#776]
We're doing some bad things with the map container div, causing bookmark jumps, the UI display, and map-zooms to behave unexpectedly.

See how my map container is _not_ centered and the width of the container is much larger than the visible map:
![screen shot 2014-09-06 at 2 01 41 pm](https://cloud.githubusercontent.com/assets/108094/4176007/04c680c6-35f0-11e4-832f-5f0e7e284e20.png)

**Comment by yhahn** [comment]
The map width is purposeful and is how the fullscreen mode works (just CSS transforms of other panes/shifts).

It's positioning is probably not centered as a result of the min-width refactor from a few iterations ago.

**Comment by yhahn** [comment]
@samanpwbb going to close this -- reopen if you see a way to have this work while having min-widths on ui container elements. Basically as you resize the window the positioning of the map would have to change to maintain an exact visual center.
