### ISSUE TITLE
Bigger better thumbs

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#783]
- Use abaculus so it's accurate to project center, not just a nabbed tile
- At least 512x512 with @2x scale? Should we go bigger?

cc @camilleanne @samanpwbb

**Comment by camilleanne** [comment]
how are the current thumbs made?

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/style.js#L362-L382

**Comment by camilleanne** [comment]
https://github.com/mapbox/mapbox-studio/pull/802
