### ISSUE TITLE
source creation dead end

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#785]
`Projects > Sources > New source`

Then try to do pretty anything else with the app ever again _besides_ create a custom source. Exception: switch to making a new style instead.

**Comment by yhahn** [comment]
What are you expecting here?

**Comment by incanus** [comment]
This discourages experimentation, as if you accidentally click here and don't want to / can't yet add a source, you have to quit the app to move on. Contrast with the top-right `x` to _Start a new style project_, open any of the left-hand drawers, browse the filesystem, etc.

**Comment by yhahn** [comment]
k, not concerned about this. https://github.com/mapbox/mapbox-studio/commit/3a5b3a251fef8cb500566165d2ab60d2c8446e81#commitcomment-7697357 manages expectations better with a pit of despair thumbnail for new sources.
