### ISSUE TITLE
Clarify to user that styles/sources are temporary until 'save as'

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#788]
Follow up to #787

Do this:
![screen shot 2014-09-08 at 2 42 05 pm](https://cloud.githubusercontent.com/assets/108094/4190702/e8633ffc-3787-11e4-98db-30e6799f0fbf.png)

(in spirit, not like.. actually like this). More strongly differentiating the 'save as' and 'save' buttons might be the key.

**Comment by incanus** [comment]
Combined with this is the fact that you don't get an indication of unsaved state ever in the app. As just one OS cue, typically on OS X you get a "dirty window" indicator: 

![screen shot 2014-09-08 at 11 50 38 am](https://cloud.githubusercontent.com/assets/17722/4190862/33327e52-3789-11e4-8dc5-4ff7bbf097b2.png)

**Comment by incanus** [comment]
Related: 
- Tie to source fill being edited: https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#browserwindowsetrepresentedfilenamefilename
- Mark window dirty: https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#browserwindowisdocumentedited

**Comment by samanpwbb** [comment]
Just voiced with @yhahn - plan moving forward is to break out separate 'refresh' and 'save' functions.
- Save would continue to work as it does now, with one notable exception: first save triggers save as.  
- Add a 'refresh' function that passes style and source updates to the map but doesn't save them to disk.

**Comment by samanpwbb** [comment]
Replaced with https://github.com/mapbox/mapbox-studio/issues/844
