### ISSUE TITLE
Crash when running offline

### ISSUE THREAD

**Issue by gravitystorm** [mapbox/mapbox-studio-classic#79]
Tilemill 2 crashes when various remote urls are unavailable, for example when working on local-only sources while offline.

The following urls always need to be accessible to avoid crashing:

in lib/tm.js

```
var defaultSources = [
    'mapbox:///mapbox.mapbox-streets-v4'
];
```

and in node_modules/tm2-default-style/project.yml

```
sources:
  - mapbox:///mapbox.mapbox-streets-v3
```

These can be temporarily changed to accessible urls (e.g. localhost) in order to navigate to whichever offline-compatible project you need to work on.

**Comment by springmeyer** [comment]
Thanks for the heads up on this problem.

**Comment by springmeyer** [comment]
I ran into what could be a similar problem - when only trying to access sources the app crashed when offline. I worked around it by removing the `~/.tilemill/v2/app.db`. After removing that file then I could restart the app and access `http://localhost:3000/new/source` without a net connection.

**Comment by gravitystorm** [comment]
I'm going to close this since the codebase is now substantially different.
