### ISSUE TITLE
styles out of date

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#790]
If you publish a custom ~~source~~ style, then click the new map ID, you are taken to `/styles`. However, there is a lag time between this possible initial open and the style showing up — not even a "processing" indication. 

![anigif-1410203578](https://cloud.githubusercontent.com/assets/17722/4191268/343ec9b0-378c-11e4-996f-d69c77bad65b.gif)

**Comment by yhahn** [comment]
You're publishing a style. The link for this is fixed in mb-pages.

**Comment by incanus** [comment]
Sorry, first line should have read `If you publish a custom style`, so this stands. Not a busted link, but rather a data delay issue.

**Comment by yhahn** [comment]
o ic. This is a Mapbox API issue, going to reticket internally.
