### ISSUE TITLE
Easier/more self-explanatory source change UI

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#792]
This screen is confusing + makes it difficult to make composite sources:
![screen shot 2014-09-08 at 4 29 11 pm](https://cloud.githubusercontent.com/assets/108094/4192323/d2771a74-3796-11e4-8458-58562555c1e9.png)

You can't copy layer IDs and it's not that obvious what the purpose of the field at the bottom is or how to use it.

I see two ways to make this a smoother: 
#### Option A
1. Click a list item to update the input field with the ID of the list item you clicked. Then, Click the 'update' button to initiate the source switch.
2. Allow user to copy map IDs, either with zeroclipboard (if there's flash support in atom), or just by making it easier to select + copy the ID. This way, they can make a new composite source a bit easier by clicking an existing source, then copy-ing the ID from another source.
### Option B

Implement an actual compositing UI:
- Do not include composite sources in this list, to prevent user from compositing two composite sources.
- Allow user to click to toggle a source on, which adds that source to the input field. Click another, and that layer is added as well.

**Comment by yhahn** [comment]
y, per our last discussion let's go for A.
