### ISSUE TITLE
New data source from Postgis opens to wrong tab

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mapbox-studio-classic#793]
![screen shot 2014-09-08 at 12 02 09 pm](https://cloud.githubusercontent.com/assets/5521326/4192553/fef3a142-3798-11e4-8c78-c5aba7391b9d.png)

This pretty minor – when adding a new layer from postgis in a data source project, the first page you land on is the 'SQL' page but the tab indicates you're on 'Configure'. It fixes itself after clicking around to another tab. Happens most of the time for me.

**Comment by samanpwbb** [comment]
The real bug here is, I believe, that the active panel is not correctly reset when you close the layer pane and then re-open a different layer.
