### ISSUE TITLE
.tm2 files hidden in Style 'save-as' modal

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#794]
There are at least 20 or so .tm2 folders/styles in this directory, but I can't see them when saving a style, so I can neither save over an older style with the same name, or make sure I'm avoiding an existing namespace. 

I will get an error however, if I try to use an existing name, but I won't know until I get the error that there is a conflict.
![screen shot 2014-09-08 at 1 52 34 pm](https://cloud.githubusercontent.com/assets/3952537/4192691/71311770-379a-11e4-84c1-a8ceb8133532.png)

**Comment by camilleanne** [comment]
Looks like .tm2 files are hidden in [Style](https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/style.js#L338) and [Source](https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/source.js#L150) save modals, but you can see .tm2source files in the source save modal. 

Is there a reason for this?

**Comment by samanpwbb** [comment]
Sounds like a bug.

**Comment by camilleanne** [comment]
#810
