### ISSUE TITLE
Places does not work if port 3000 is not available

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#798]
If something else is running on port 3000 when mbstudio opens the app starts fine (due to getport magic after #587) but it appears that the places functionality silently fails (seen on workshop participants mac - after stopping other node.js server on 3000 and restarting mbstudio places started working). I noticed `app/print.js` also looks like it has a hardcoded `localhost:3000`

**Comment by tristen** [comment]
Related? I was running Mapbox Studio on port `3001` and after saving a place "Bogata Colombia", making an edit and saving I got this error:

![screen shot 2014-09-09 at 11 33 32 am](https://cloud.githubusercontent.com/assets/61150/4206011/b219e260-3846-11e4-85a6-933a1977b639.png)

Opening studio in the browser instead didn't throw any errors.

**Comment by yhahn** [comment]
@tristen not related...

**Comment by camilleanne** [comment]
@springmeyer I ran another unrelated thing on port 3000, and ran Mapbox Studio on 3001 and Places worked fine. The print hardcoding is a bug tho

**Comment by camilleanne** [comment]
Not sure what was going on with the workshop participants mac, but I don't think it was because port 3000 was unavailable. Haven't been able to replicate that.

fixing print.js bug here: https://github.com/mapbox/mapbox-studio/pull/806

**Comment by springmeyer** [comment]
> but I don't think it was because port 3000 was unavailable. Haven't been able to replicate that.

All I know is what I saw:
- He clicked on places and saw no maps appear and no errors (we did not look in the logs)
- He had an express server running on port 3000 from a different workshop demo
- He stopped that server and restarted mbstudio and then the places started working

If you can't replicate then perhaps places being broken was a side effect of some other javascript error.

**Comment by MattSidor** [comment]
@camilleanne How do you modify the default port in Mapbox Studio?

**Comment by camilleanne** [comment]
@seadour 
If you are running Mapbox Studio from your command line (instead of the packaged desktop app), you can set the port when you start Mapbox Studio: `node index.js --port=8000`

Alternatively, you can get into the guts of it and modify this line: https://github.com/mapbox/mapbox-studio/blob/9f9de6cc8bf171716ec6126fae9b960e390b1f50/index-server.js#L25

**Comment by MattSidor** [comment]
@camilleanne Fantastic, thank you.
