### ISSUE TITLE
Emphasize zoom level in the editor

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-studio-classic#799]
Knowing the zoom value when designing a map is an important part of the workflow. Right now it its: 
1. Tucked between lat, lng and render time which is secondary info at best.
2. A muted grey
3. Its prefixed with a `z` not `zoom` which takes some brain to know what that means.

Even knowing where it is I have to search for it every time:

![2014-09-09 at 1 30 pm](https://cloud.githubusercontent.com/assets/61150/4206144/d6dccd78-3847-11e4-98b5-8d33ef92188f.png)

In contrast, TileMill has a pretty nice display for this

![screen shot 2014-09-09 at 1 37 58 pm](https://cloud.githubusercontent.com/assets/61150/4206173/154c018c-3848-11e4-9805-c47f30fb91bb.png)

**Comment by nickidlugash** [comment]
Agreed. 1. and 2. in particular I think are issues.

**Comment by wboykinm** [comment]
Thirded. I always lose a few seconds surfacing from my UI reflexes to find the dang thing.
