### ISSUE TITLE
Free font library

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#8]
Want to collect this list? I think we can pull it in as a dependency as well, `tm2-default-fonts` or so.

**Comment by ajashton** [comment]
About how many are you thinking? Here's an initial list I pulled together from FontSquirrel's popular fonts listing.

## Definitely
- Source Sans Pro
- Open Sans
- PT Sans
- Colaborate
- Roboto
- Lato
- Droid Serif
- Vollkorn
- Charis SIL
- Crimson
- Merriweather

## Maybe
- Cantarell
- Quicksand
- Bebas Neue
- League Gothic
- TitilliumText
- Yanone Kaffeesatz
- Raleway
- TeX Gyre Heros
- Gentium
- BPreplay

**Comment by yhahn** [comment]
I like the length of your def list. It's easier to add than remove so good to start small.

**Comment by ajashton** [comment]
Repo [here](https://github.com/mapbox/tm2-default-fonts) and dependency added in eadd437f25ff39ac586c43f19472bd86ec6792df
