### ISSUE TITLE
Style/source name pattern matches '+'

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#804]
this pattern [`[\w+\d+\.\s\/_-]+`](https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/modalbrowsersave.html#L11) will match a style name like `alpha+beta.tm2`, but that's not a valid file name for studio. Seems to only be a problem for the `+` character.

![screen shot 2014-09-09 at 11 58 46 am](https://cloud.githubusercontent.com/assets/3952537/4207438/69904c22-3856-11e4-9f6a-3b14afed62cd.png)

**Comment by samanpwbb** [comment]
Hm, we use this pattern for checking valid source names: `(([\w+-]+\.[\w+-]+,?)+|(https?:\/\/.*))` - `[\w+-]` means any alphanum characer, or '-' or '+'. Should we prevent users from using '+' character?

**Comment by yhahn** [comment]
Let's exclude + for now since browsers like to turn + into a space (`%20`).

**Comment by camilleanne** [comment]
A `+` in a source layer name will also cause an `invalid source protocol` error so I'm going to strip those out for now as well.

**Comment by camilleanne** [comment]
#807
