### ISSUE TITLE
zoom-to-layer-extent button in the source editor

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#81]
For when you're creating a source from scratch and have no navigational hints in the black void

**Comment by yhahn** [comment]
- [x] Add a little button using base to each layer for zooming to extent
- [x] Use a `.js-zoomtolayer` select + backbone view handler for looking up extent for the layer
- [x] Zoom/pan the map to that extent

![ne bathymetry](https://cloud.githubusercontent.com/assets/83384/3059369/b72edb6e-e1ea-11e3-9358-c90669512458.png)
