### ISSUE TITLE
Failed to find font face 'Komika Hand Bold' in style 'place_label' in TextSymbolizer

### ISSUE THREAD

**Issue by bengolder** [mapbox/mapbox-studio-classic#811]
Just downloaded Mapbox Studio and opened it on OS X 10.9.4. Tried to open the Comic! example and I received this error message.

**Comment by yhahn** [comment]
@ajashton https://github.com/mapbox/mapbox-studio-comic.tm2/commit/7d7c189e45cdcaad0450d2c6070f78490512ebe3 ?

**Comment by duncangraham** [comment]
It looks like the font is called "Komika Title Bold" but in the .mss it's being referenced as "Komika Hand Bold"
