### ISSUE TITLE
Tests for example styles

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#812]
Load 'em all up to avoid https://github.com/mapbox/mapbox-studio/issues/811.

**Comment by camilleanne** [comment]
Also, double check attribution

**Comment by yhahn** [comment]
@camilleanne ha ya..., what are you going to test for?
- [x] assert that mapid is empty or unset
- [ ] ~~assert that ? about attribution~~

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/pull/819
