### ISSUE TITLE
Loose Leaf style attribution

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-studio-classic#814]
Defaults to TM2.

![screen shot 2014-09-10 at 11 03 11 am](https://cloud.githubusercontent.com/assets/3952537/4222560/c9d77560-3914-11e4-8fe4-92653040ec7c.png)

cc @tristen

**Comment by yhahn** [comment]
@tristen can you make a PR that updates the looseleaf version?

**Comment by yhahn** [comment]
I got this in an upcoming PR.
