### ISSUE TITLE
Error in sources/styles panel

### ISSUE THREAD

**Issue by esisa** [mapbox/mapbox-studio-classic#815]
After upgrading to 0.1.0 I get the text in the sources/style panel partly underneath the thumbnail 

![skjermbilde 2014-09-10 kl 20 13 20](https://cloud.githubusercontent.com/assets/660586/4222779/7afa06b8-3916-11e4-9597-a3a9439d89ce.png)

**Comment by samanpwbb** [comment]
Can you try quitting and re-opening Mapbox Studio? I am almost certain this is a caching issue related to the upgrade.

**Comment by esisa** [comment]
Correct :-)
