### ISSUE TITLE
Unable to access local drives other than C: ?

### ISSUE THREAD

**Issue by flemmens** [mapbox/mapbox-studio-classic#824]
When I try to open a local .shp file, there is no way to select the drive letter, it only display the C:\, is there any way to select the drive ?

**Comment by MarkWS** [comment]
Same on my end, would be nice to have access to other dirves.
Win 7 Pro

**Comment by springmeyer** [comment]
Noting the fix in tilemill that may or may not help with solving this one: https://github.com/mapbox/tilemill/issues/1679

**Comment by Reach-Above** [comment]
This would be great to have.

**Comment by wilhelmberg** [comment]
Maybe leave the enumeration of drives to a native module?
Like [node-usb-detection](https://github.com/KABA-CCEAC/node-usb-detection).

I think [GetLogicalDriveStrings](http://msdn.microsoft.com/en-us/library/aa364975%28VS.85%29.aspx) would probably be a good starting point. Or [GetLogicalDrives](http://msdn.microsoft.com/en-us/library/aa364972%28v=vs.85%29.aspx), which returns a bitmask (position 0 = A, position 1 = B, ...).

**Comment by springmeyer** [comment]
@BergWerkGIS perhaps. This is the really cheap solution I can up with previously: https://github.com/mapbox/tilemill/commit/696f142b6e500bea9f8367b1a5a596709989d080. Other than being slow for lots of mapped drives can be see any major pitfalls?

**Comment by yhahn** [comment]
lol I just read this code

**Comment by wilhelmberg** [comment]
@springmeyer 
Well, uhm, yeah. :smirk: Brute force at its best.
Despite to being slow I don't see any major pitfalls.
Even Windows itself takes quite some time to open Explorer if there are slow drives in your machine or mapped network drives (e.g. sleeping NAS).

**Comment by yelper** [comment]
A quick fix might be to create a NTFS symlink (`mklink` on the command line) on C:\ to the data directory. I do agree that this needs to be fixed, however!

**Comment by gagecarto** [comment]
This would be a really helpful feature of MapBox Studio

**Comment by aaronpdennis** [comment]
We're trying to teach Mapbox Studio in a class at a large university. In the computer labs, students only have limited access to the C:\ drive. We'll be able to save there, but it would be much more useful if we could access other drives.

**Comment by springmeyer** [comment]
@aaronlidman thanks, we are planning on getting this working soon.

**Comment by jimutt** [comment]
Any updates on this? As map data can take up pretty large amounts of disk space it feels quite restraining to be limited to only using the c-drive.

**Comment by springmeyer** [comment]
@BergWerkGIS - is this still on your radar? If not, I can take a look: let me know.

**Comment by wilhelmberg** [comment]
@springmeyer y, still on my radar, but I would like to keep focused on current tasks for the rest of this week to finally get them out and running.
Don't know if it's too late for the planned 0.2.6 milestone, but I could look into this issue next week.

**Comment by jimutt** [comment]
Sounds great that you're still having this on your mind! My SSD-drive which I use mainly for the OS doesn't really want me to put a lot of GIS-data on there as well ;) Though I understand if there are other tasks you consider more important than this one but I'm sure there are many people who would appreciate the possibility of using other drives.

**Comment by wilhelmberg** [comment]
@flemmens @MarkWS @jimutt @aaronpdennis @gagecarto @yelper @Reach-Above 

Would you mind a try, if you are able to access other drives with this version:
64bit: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x64-windrives.exe
32bit: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x86-windrives.exe

---

@yhahn 

Since you are assigned, could you review?

https://github.com/mapbox/mapbox-studio/commit/windrives

I've put the detection of drives directly into `/browse`:
**pro:** drives might change during a Studio session, e.g. external hard drive gets connected
**con:** might take a while, if there a several sleeping or network drives. Maybe we could display a wait cursor during drive detection?

**Comment by springmeyer** [comment]
@BergWerkGIS I'm happy to review, I've assigned to myself. I'm still learning how to add tests to studio. That is the next thing this needs.

**Comment by wilhelmberg** [comment]
merged into current dev branch:
https://github.com/mapbox/mapbox-studio/pull/1435
