### ISSUE TITLE
Incremental updates

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-studio-classic#825]
We should investigate incremental updates to avoid having to redownload 150MB for every minor update.

**Comment by yhahn** [comment]
Only interested if there's a well maintained solution for this on all 3 platforms : ) Closing, reopen if you find that!

**Comment by kkaefer** [comment]
Maybe Google Courgette: http://www.chromium.org/developers/design-documents/software-updates-courgette?
