### ISSUE TITLE
Program Crashes when selecting the "Fonts" tab

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#826]
Win 7 Pro
MBS v0.1.0
The program crashes when selecting the "Fonts" navigation tab on the top left.
v.0.0.8 did not crash but 0.0.7 did.
Seems the bug is back.

**Comment by yhahn** [comment]
@MarkWS interesting -- could you post `app.log` again?

**Comment by MarkWS** [comment]
this was fixed with version 0.4 and up.
