### ISSUE TITLE
Project saved in Styles?

### ISSUE THREAD

**Issue by cappelaere** [mapbox/mapbox-studio-classic#829]
Using Mapbox-Studio, I can upload a project to Mapbox and get a Map ID.  However, when I go to web and log in, the project is loaded under "Styles" and not "Projects".
Am I doing something wrong in the GUI?
Thanks.
Pat.

**Comment by willwhite** [comment]
Hi Pat,

That is expected behavior. Styles upload from Studio will appear on the Styles tab of mapbox.com.

Will

**Comment by cappelaere** [comment]
I was really expecting to upload a project though and see it in the “projects” section.
How do I do that then?
Thanks,
Pat.

**Comment by willwhite** [comment]
Mapbox.com projects are different from Mapbox Studio Styles so they are each listed on their respective tabs. It is not possible to customize the UI in this way.

**Comment by cappelaere** [comment]
But Studio allows me to add a data source to a style and save it (as a style).  This does not seem that different to me from a project. In my case, I want to show flood maps and have them hosted on Mapbox.  What would be the right flow?
Thanks.
Pat.

**Comment by cappelaere** [comment]
It does say that this is a Map Studio that is replacing TileMill for vectors.  So I am expecting to be able to use it for my vector projects. Is this wrong?  or is it not quite ready yet?

**Comment by willwhite** [comment]
Sorry for the confusion. I think the terminology is not completely clear right now. Studio Styles use vector tiles for their data sources and are created/edited using the Mapbox Studio desktop app.

Meantwhile, mapbox.com projects use a different rendering technology and can only be edited on Mapbox.com. They don't interact with Mapbox Studio or vector tiles.

> I want to show flood maps and have them hosted on Mapbox.

Once you upload your Studio style it is hosted on Mapbox under the Styles tab. From there you can embed it on your site or application using the Mapbox [developer tools](https://www.mapbox.com/developers/). Is there something specific that you are looking to do?

**Comment by cappelaere** [comment]
Will,

Thank you for clarification.  This is a little confusing but you guys are running at the speed of light.
Since my flood maps are in geojson format, they can be vectorized and used as a data source in a “style”.
I am fine with uploading them as “styles” for the time being (and avoid confusion)
So I just need to have issue with Mapbox Outdoors  #830 resolved at some point or work around it.
Thank you.
Pat.
