### ISSUE TITLE
Mapbox outdoors locked?

### ISSUE THREAD

**Issue by cappelaere** [mapbox/mapbox-studio-classic#830]
I select a new project and Mapbox Outdoors style.
Then go to Layers to add a data source
at the top, it says: "Source locked (custom layer order)" and I cannot change source.
It works with at least with Basic and OSM Bright 2 styles...
Thanks.
Pat.

**Comment by yhahn** [comment]
Yes, this is an advanced feature that Mapbox Outdoors uses to customize the layer order/instances from the vector tile source (https://github.com/mapbox/mapbox-studio-mapbox-outdoors.tm2/blob/master/project.yml#L19-L44).

I'll add this to our docs in an advanced section.

**Comment by cappelaere** [comment]
Thanks.  Please let me know how to work around this to get a terrain background for the maps.  This is really cool to have to show floods.  I will be showing this feature to NASA Servir at end of month in Huntsville.  Great work.

**Comment by yhahn** [comment]
@cappelaere added docs for what's going on here:

https://www.mapbox.com/guides/style-manual/#custom-layer-order

For your specific case you'll want to do two things:
1. Add the mapid of your additional vector tile source to the end of the `source:` field, e.g.
   
   ```
   source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,<yourmapid>"
   ```
2. Add one or more entries to `layers:` for the custom layers you want to style.

**Comment by gagecarto** [comment]
@yhahn - looking for the link you reference but its broken.

**Comment by springmeyer** [comment]
@gagecarto moved to https://www.mapbox.com/guides/style-manual/#custom-layer-order /cc @amyleew

**Comment by jerald-acacus** [comment]
@yhahn I followed your steps and was able to add new layers and apply styles. However, Source is still locked. Is this normal? So if I want to add new layers I add it in my own tileset, upload and then style?
