### ISSUE TITLE
Source Quickstart style bug when uploading layers

### ISSUE THREAD

**Issue by standyro** [mapbox/mapbox-studio-classic#834]
Experienced this UI/style bug when following the <a href="https://www.mapbox.com/mapbox-studio/source-quickstart/">Source Quickstart tutorial</a> and uploading a data layer. Fixes itself by clicking add one now, and closing window.

<img src="http://i.imgur.com/qmlf6fY.png" title="Hosted by imgur.com" />

**Comment by samanpwbb** [comment]
This is now fixed.
