### ISSUE TITLE
center zoom value must be greater than or equal to minzoom x

### ISSUE THREAD

**Issue by cappelaere** [mapbox/mapbox-studio-classic#836]
I was trying to adjust my settings minzoom to something > 0 and save the style when I got that error.
It is not obvious how to change the center zoom value here....
It would be great to be able to save the style at current center and zoom values with min/maxzoom defined in the settings.  It does not seem to do this.
Thanks.
Pat.

**Comment by mapperfr** [comment]
Same problem here !

**Comment by yhahn** [comment]
Addressed in #842.
