### ISSUE TITLE
publishing to Mapbox

### ISSUE THREAD

**Issue by jqtrde** [mapbox/mapbox-studio-classic#84]
I'd love be able to be able to publish tiles generated with TM2 to Mapbox. Is there a means to do that?

Hack-ey solutions are welcome!

**Comment by yhahn** [comment]
Yes, coming soon : )

**Comment by jqtrde** [comment]
:metal:

Any ideas on timeframe? Getting ready to start a new project, would like to use TM2, but will use the original if this is still a few months off.

**Comment by wprater** [comment]
wanting to push vector tile styles to mapbox too!  any news?

**Comment by samanpwbb** [comment]
Duplicate of https://github.com/mapbox/tm2/issues/258
