### ISSUE TITLE
Overlaid transparent polygons across tile borders

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#840]
In TileMill I was able to render a single layer of overlapping polygons in a single data source to produce a range of composite colours on a blue-neutral-green spectrum. I can't find a suitable data buffer value that will allow me to reproduce the effect in Mapbox Studio - I've tried 0 and 64 and a range of intermediate values but always get tile join lines as shown in the image.

Each individual polygon has a polygon-opacity: 0.6 and the entire layer has an opacity: 0.8. I've tried different attachments and polygon fills without success. It looks like an issue where particular polygons are either absent or duplicated in adjacent tiles. Any ideas how I may be able to get it to work?

![studio transparent polygon overlay](https://cloud.githubusercontent.com/assets/912721/4270081/37dd7c68-3cc5-11e4-951c-58771ade95db.jpg)

**Comment by yhahn** [comment]
@ashleyclough I've not seen this issue before with transparent polygons. To rule out one of the possibilities could you set your map's image format to **png (24-bit)** if it isn't already? It's possible the 8-bit alpha png generation is squashing some of the transparency out of different tiles.

**Comment by ashleyclough** [comment]
That's sorted it - all now rendering correctly. Thanks.

**Comment by yhahn** [comment]
:+1:
