### ISSUE TITLE
Where is gridLayer/utf interactivity data?

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#841]
Where is embedded data and how do I get to it with the mapbox.js API? Is read from a source or a style? In TileMill we were able to attach 'teaser' data that could be interrogated by the JS API - the data is in my source files but the current version of Studio and its documentation doesn't seem to mention it (or at least I can't find it).

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-advanced-features.md
