### ISSUE TITLE
[source mode] Refresh map preview after delete 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#843]
After deleting a layer, layer still displays in xray preview until you take another action that refreshes the map.

**Comment by yhahn** [comment]
@samanpwbb can you roll these into a quest ticket that is about all actions in source mode leading to refresh? We have like half a dozen piecemeal tickets that skirt the issue.

**Comment by samanpwbb** [comment]
:+1:

**Comment by samanpwbb** [comment]
Replaced by https://github.com/mapbox/mapbox-studio/issues/844
