### ISSUE TITLE
[source + style] refresh quest

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#844]
### Style usability adjustments:
- [x]  Divide saving to disk and refreshing into separate actions. `cmd+s` -> saves to disk, ~~`cmd+r`~~ `cmd+space` (for now?) -> refreshes map view.
- [x] Ensure alert notice is triggered if user tries to exit screen if work is unsaved (even if it's fully 'refreshed').
- [x] Add a visually disabled, 'saved' state to save button so user always knows if work is already fully saved:
  ![screen shot 2014-09-15 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/108094/4275573/ac89bd50-3cfd-11e4-831d-93ed78a69fd9.png)
- [x] Ensure export/upload options in settings panel are disabled unless map is fully saved. ~~(Combining this point with above point, we could rework export action to replace the save action in the sidebar when the map is saved.~~
- [x] If source or style is temporary, `cmd+s` action triggers save as dialog. All subsequent `cmd+s` actions trigger regular save.
### Source usability adjustments:
- [x]  Divide saving to disk and refreshing into separate actions. `cmd+s` -> saves to disk, ~~`cmd+r`~~ `cmd+space` (for now?) -> refreshes map view.
- [x] Ensure alert notice is triggered if user tries to exit screen if work is unsaved (even if it's fully 'refreshed').
- [x] Add a visually disabled, 'saved' state to save button so user always knows if work is already fully saved:
  ![screen shot 2014-09-15 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/108094/4275573/ac89bd50-3cfd-11e4-831d-93ed78a69fd9.png)
- [x] Ensure export/upload options in settings panel are disabled unless map is fully saved. ~~(Combining this point with above point, we could rework export action to replace the save action in the sidebar when the map is saved.~~
- [x] If style is temporary, `cmd+s` action triggers save as dialog. All subsequent `cmd+s` actions trigger regular save.
### Source-specific usability adjustments:
- [x] Auto refresh after clicking select button + reading the data (#536):
  ![screen_shot_2014-09-15_at_1_14_03_pm](https://cloud.githubusercontent.com/assets/108094/4275317/bfbb62ae-3cfb-11e4-9d3b-b4f2cb911e9f.png)
- [x] Remove close button from layer panes, auto refresh after making changes (#545 / #544):
  ![screen_shot_2014-09-15_at_1_15_56_pm](https://cloud.githubusercontent.com/assets/108094/4275352/0404d0b2-3cfc-11e4-940f-8a56b7a64d8b.png)
- [x] ~~Auto refresh when clicking the hide or delete buttons in layer list, remove refresh option from list + refresh overlay from map:~~ **this does something different...**
  ![screen_shot_2014-09-15_at_1_20_27_pm](https://cloud.githubusercontent.com/assets/108094/4275456/aac9a986-3cfc-11e4-87a3-9fdfc941bc1a.png)
- [x] Add a refresh action to the SQL query input somewhere. _Not sure about this one - we may want to continue to rely on a save action here for viewing updates_:
  ![screen shot 2014-09-15 at 1 32 07 pm](https://cloud.githubusercontent.com/assets/108094/4275662/570676e2-3cfe-11e4-895e-8435e6daaf48.png)

**Comment by yhahn** [comment]
@samanpwbb got through the first chunk of this on the style side in `refreshquest`. Will focus on source editor tomorrow.

Went with `ctrl+space` for now because `ctrl+r` is refresh in browsers. `ctrl+spaces` isn't great either (I think this is often taken for locale switching) but is less overloaded in the context of a browser I think.
