### ISSUE TITLE
Importing old TileMill projects

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#847]
Has anyone imported their old TileMill projects into MBS and if so can you enplane how?
We have some projects that reference a local DB so I don't think we can just cut and past the CSS
I'm still on v0.1 so this and accessing other drives may be resolved by now.

**Comment by wboykinm** [comment]
FWIW I've mostly been copying the `.mss` bits and pasting them in, then sorting out what sources can be made available. The sources architecture has changed a lot, making a project port difficult to envision.

Related is #849
