### ISSUE TITLE
Add Natural Earth remote sources

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#849]
It was always nice that Tilemill had the Natural Earth sources on a CDN with easy access. @GretaCB @yhahn - would it be crazy onerous to serve those from a Mapbox vector tile endpoint? Graticules and bathymetry in particular would be useful to just have at the ready, and they can't take up even a fraction of the bandwidth occupied by streets, terrain and satellite.

**Comment by GretaCB** [comment]
Hey @wboykinm , thanks for the note. We're currently working on [getting Natural Earth vector data into Mapbox Studio](https://github.com/mapbox/natural-earth-tm2).

**Comment by wboykinm** [comment]
:+1:
