### ISSUE TITLE
Exporting Images at z18+

### ISSUE THREAD

**Issue by jeichert** [mapbox/mapbox-studio-classic#853]
Been trying to export images at z18 a few times, only 49% of image size, however it seems to hang, and never finish exporting, while at z17 it exports immediately.  Anyone else have this issue?

**Comment by camilleanne** [comment]
@jeichert Large images (49% can still be 10,000 x 10,000 pixels) require stitching many tiles together and may take a couple of minutes to complete. There may be a condition where that process is interrupted however, and may hang. Are you navigating anywhere else within Mapbox Studio or something similar while waiting for the export?

**Comment by jeichert** [comment]
I just gave it a couple more shots, and it seems to be working better, I was able to do a number of exports at z18 and z19.  So it may have just been a weird error with my computer or something. Thanks!
