### ISSUE TITLE
no save modal for unchanged default style or source project 

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#855]
if you land on a the default style or source projects, and then try to navigate away, you'll be prompted to save your changes. dont show this modal for untouched default projects 

![](http://cl.ly/image/3T3D1f0p2w2V/Image%202014-09-17%20at%204.49.37%20PM.png)

cc @samanpwbb

**Comment by yhahn** [comment]
Cool, we just need to nuke the changed classes from:
- https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/style.html#L38
- https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/source.html#L29

and update tests.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/pull/861
