### ISSUE TITLE
Dead end if save errors

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#858]
Tried to save a project with a reference to a nonexistent svg file. When first attempting to 'save as', I get an error about the missing file and it seems like I was not able to save. Then, I try to 'save as' again and see:
![screen shot 2014-09-17 at 6 38 34 pm](https://cloud.githubusercontent.com/assets/108094/4312578/c02ce35e-3ebb-11e4-8ed7-5d86b410bfee.png)

hit this again with a simple carto error.

**Comment by yhahn** [comment]
zxvlkj
