### ISSUE TITLE
Better empty state for tiffs

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#863]
Loaded a tiff, it looks fine, here's the 'fields' screen:

![screen shot 2014-09-18 at 12 32 22 pm](https://cloud.githubusercontent.com/assets/108094/4323562/73b3b930-3f51-11e4-8918-3d7e75733bc6.png)

@GretaCB are there cases where tiffs will have fields? 

We might want to solve this my simply changing the text to 'no fields' or something.

**Comment by GretaCB** [comment]
@samanpwbb right now there are no cases where tiffs will have fields. So yeah, probably just show a generic 'no fields' message for rasters.

**Comment by samanpwbb** [comment]
Fixed with https://github.com/mapbox/mapbox-studio/commit/b7992a35e533f3ca0d78bcadc11ec4adc1a2bbef
