### ISSUE TITLE
Set changed if layer is deleted

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#865]
![2014-09-18 13_19_47](https://cloud.githubusercontent.com/assets/108094/4324215/0441ba78-3f58-11e4-82d6-823362405281.gif)

After deleting layer, save button state should change and alert should appear on page exit.

**Comment by yariksheptykin** [comment]
Hi! This could be fixed by appending window.editor.changed(); at the end of the Modal.show handler in app/source.js:372.
I can send a pull request for this if somebody helps me writing a test.

**Comment by samanpwbb** [comment]
I've got it covered :)

**Comment by yariksheptykin** [comment]
Good! Area there any docs on writing tests for the studio?
