### ISSUE TITLE
scale tile URL argument

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-studio-classic#87]
Would be nice to be able to request retina tiles on the fly by tile URL argument for such things as live preview of styles on mobile devices.

**Comment by yhahn** [comment]
- [x] Add a scale factor express param to these routes
- [x] Pass on to tilelive-vector to override project-level scale param

**Comment by camilleanne** [comment]
branch 512 of tm2 and tilelive-vector has these things now.
e.g. `http://localhost:3000/style/16/34349/22970@2x.png?id=tmstyle:///...`
goes up to `@4x`
