### ISSUE TITLE
Style export status indication

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#874]
Add loading + success states after exporting an image.

**Comment by camilleanne** [comment]
This is hard -- I don't remember why exactly, but it's hard to pass a 'success' state back to the client. I will look into it again.

**Comment by samanpwbb** [comment]
Ya, @yhahn mentioned that it may be better to wait until atom shell handles downloads.

**Comment by yhahn** [comment]
Stopgap for now ^^ -- anything that's generic for the browser would prob require image exports to take part in the app task/state system. Not worth it atm.
