### ISSUE TITLE
Calculate source extents for sources in non WGS84/900913 projections

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#883]
This extent function currently only handles WGS84/900913 source files. Source layers in any other projection are being skipped leading to extent calculations of ~ -180,-85.0511,180,85.0511 -- aka, way too large.

https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/source.js#L294-L320

Look into maybe using node mapnik's projection API for handling this.

https://github.com/mapnik/node-mapnik/blob/master/test/projection.test.js

cc @GretaCB

**Comment by springmeyer** [comment]
:+1:

**Comment by GretaCB** [comment]
PR here: https://github.com/mapbox/mapbox-studio/pull/887

~~Merging.~~ Merged.
