### ISSUE TITLE
tm2 screencast

### ISSUE THREAD

**Issue by ryantroyford** [mapbox/mapbox-studio-classic#89]
@nickidlugash @gundersen 

we're gonna make a screencast to show off tm2 and blow people's minds.

a few thoughts right off the bat:
- this isn't a walkthrough or instructional video. it should be fast and exciting. think of it like a tm2 demo reel with a little more behind-the-scenes stuff.
- we need to choose our coolest maps. from ian's wheatpaste map to AJ's pencil map to the clean-but-unique financial times stuff. 
- as @gundersen mentioned to me, nobody knows you can do most of this stuff with tm2. we need to approach it with the intent of informing, while still keeping it rad.

**Comment by gundersen** [comment]
Basically a version of @ajashton screencast: https://www.mapbox.com/blog/vector-tiles-tilemill2-preview, but focused just on SF, custom fonts, something really unique w/ patterns.

**Comment by wboykinm** [comment]
The majesty of [Spokane](http://www.flickr.com/photos/vtcraghead/11490011703/), the thrill of [Topeka](http://www.flickr.com/photos/vtcraghead/11489945584/) . . .

**Comment by migurski** [comment]
The lake of [Oakland](http://mike.teczno.com/notes/lake-merritt.html)…

**Comment by incanus** [comment]
![](http://www.draplin.com/pics/021909_port_of_portland_sign.jpg)

**Comment by ryantroyford** [comment]
[merged](https://github.com/mapbox/mapbox.github.com/pull/3255).
