### ISSUE TITLE
Upload source project crashes MB Studio every time on specific data.(Windows)

### ISSUE THREAD

**Issue by diligentpig** [mapbox/mapbox-studio-classic#891]
Reproduce steps:
1. Download SF footprints data here: https://data.sfgov.org/Geographic-Locations-and-Boundaries/Building-Footprints-Zipped-Shapefile-Format-/jezr-5bxm
2. In mapbox studio, new a source project and add a new layer which data source is the SF footprints shapefile downloaded above.
3. Save the project, and in setting page, click "Upload to Mapbox":
![image](https://cloud.githubusercontent.com/assets/845955/4414749/45f6ebac-451e-11e4-9727-a9c000e16b72.png)

4.mapbox studio will crash every time no matter how I tune the parameters about the project.

Do I miss some key step or this is most far we can get now?

**Comment by springmeyer** [comment]
We are working on and very close to releasing a 64 bit version of Mapbox studio for windows. It may be that the memory needed to render the data is exceeding what the current, 32 bit, app is allowed to use. Just a guess. Anyway, we will take a closer look. Thanks for the report.

**Comment by springmeyer** [comment]
Another idea: this shapefile has a lot of attribute fields. You might try editing the data to remove all the attributes you don't need and then try again. (Note: in the future we plan to provide a mechanism to strip attributes on the fly to save space).

**Comment by diligentpig** [comment]
Hi @springmeyer , thank you for your quick replay, and by follow your suggestion, I drop several fields of the shapefile and keep only about 5 or 6 fields, than I add it to Mapbox Studio, finally I uploaded the data successfully to my accout! Cheers:)

PS: With original data, while upload, usage of memory of node.exe quickly raise up to 900MB and then it crashed Mapbox Studio. With the modified data which has fewer fields, memory used by node.exe always keep under 200MB+, so the upload can successfully finished. I think you are right:)

**Comment by wilhelmberg** [comment]
My 2 cents:

Studio crashed the first 3 times I tried to add the shapefile and clicked on 'Done'.
With the 4th try adding was successfull.
Upload seemed to hang for quite some time at 0.1% before I killed it.
node.exe was idling at 0 to 1% CPU and 95MB RAM.

ArcGIS 'Check Geometry' found about 20 self intersecting geometries.
QGIS 2.4 'Topology Checker' reports 557 invalid geometries.

After removing all fields except one adding the shapefile works every time.
Upload still fails for me.

**Comment by springmeyer** [comment]
@diligentpig - would be great if you could download the latest release (https://www.mapbox.com/mapbox-studio/) and try your original data again. The app is now 64 bit and should be able to cope with more data on windows. There are still a number of optimizations we could make, but I bet your case will work now. Let me know in a new issue if it does not and we can look closer together.
