### ISSUE TITLE
color picker (again)

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#894]
Was curious, so I sketched out how [spectrum](http://bgrins.github.io/spectrum/) might work (https://github.com/mapbox/mapbox-studio/commit/3fa3e3f908427755403f0bd33683d730c1228255):

![2014-09-27 02_34_37](https://cloud.githubusercontent.com/assets/108094/4429959/604e9fac-4610-11e4-926b-8ea642aa8c15.gif)

This is just a prototype that I wrote quickly with jquery, but I think all the concepts (using spectrum, piggy-backing on the codemirror palette plugin) could be integrated directly into the palette plugin or turned into a plugin of it's own that depends on palette. Basically: turn paleete swatch into an input that modifies the following color code.

Spectrum behaves exactly as I expect a color picker to behave and I don't see this causing any unintended side effects.

**Comment by samanpwbb** [comment]
Done: https://github.com/mapbox/mapbox-studio/pull/895

**Comment by gundersen** [comment]
Lets blog the color picker once we go live @samanpwbb
