### ISSUE TITLE
Appveyor test failures that don't show up in travis

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#897]
Appveyor tests are failing:
- https://ci.appveyor.com/project/Mapbox/mapbox-studio/build/1.0.1121
- https://ci.appveyor.com/project/Mapbox/mapbox-studio/build/1.0.1135

Both are failing on the same thing - front end source layer modal tests.

On the other hand, the Travis tests are passing those same tests:
- https://travis-ci.org/mapbox/mapbox-studio/builds/36391771
- https://travis-ci.org/mapbox/mapbox-studio/builds/36472908

**Comment by yhahn** [comment]
Made some headway on this but haven't 100% stabilized this.

**Comment by samanpwbb** [comment]
Got another unexpected test failure, this one is x86 only:

https://ci.appveyor.com/project/Mapbox/mapbox-studio/build/1.0.1320 `source exit 1`.

**Comment by springmeyer** [comment]
closing, appveyor is back from vacation.
