### ISSUE TITLE
OSX binary package

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#9]
Been working on a script to build standalone package for OSX of tm2.

First working result is now available at: http://tilemill.s3.amazonaws.com/index.html?path=dev/

Next steps:
- [x] - work to reduce the size of the package
- [x] - set up script on cron on osx build machine
- [x] - node v0.10.x support - node-eio is blocker

**Comment by incanus** [comment]
This runs well for me and looks great. Love the new style, too.

**Comment by springmeyer** [comment]
done, this script (https://gist.github.com/springmeyer/e312f51bc3ddc1e0da5e) is running on a cron every hour and pushing builds that can be browsed at http://tilemill.s3.amazonaws.com/index.html?path=dev/

**Comment by kkaefer** [comment]
Can you change the filename template to include Y-m-d before the hash so that they are sorted by date?

**Comment by springmeyer** [comment]
yes, good idea. I'd also like to move to using the output of `git describe` once we have made a first annotated tag.

**Comment by springmeyer** [comment]
@kkaefer filename changed now to include Y-m-d, thanks. Not sure if my js s3 browser hack will respect the sorting, but we'll see soon.
