### ISSUE TITLE
Save button stuck on both states

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-studio-classic#905]
In 0.1.3, Save button appears to be stuck in both states:
![screen shot 2014-09-30 at 9 32 34 pm](https://cloud.githubusercontent.com/assets/134753/4470359/80a0ca5c-4924-11e4-9cc9-ccd261d216f5.png)

/cc @samanpwbb

**Comment by samanpwbb** [comment]
Can you try to restart studio a couple times? I wouldn't  be surprised if this were a caching issue

**Comment by geografa** [comment]
Negative. 
- I opened 0.1.2
- it prompted for the update, I downloaded
- closed 0.1.2
- installed 0.1.3 and opened
- restarted multiple times
- cleared ~/.mapbox-studio cache

**Comment by samanpwbb** [comment]
Can you list steps to reproduce? I'm not seeing it.

**Comment by geografa** [comment]
ugh. not seeing it now. Steps were listed above - just a update of the app. Possible last restart cleared this. Sorry to bother - closing for now.
