### ISSUE TITLE
v0.1.3 postgres layers control lost

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#906]
The recent v0.1.3 update has lost the top right controls to manage postgres layers:

![studio 013 postgres layers missing](https://cloud.githubusercontent.com/assets/912721/4472598/5dcda39a-4949-11e4-8c9b-623b4dbbc241.jpg)

Also odd 'SaveSaved' text top left.

**Comment by samanpwbb** [comment]
Hi Ashley, this is almost certainly a caching problem. Can you try restarting Studio a few times to see if the problem persists?

**Comment by ashleyclough** [comment]
That's sorted it, thanks.

Is the change to a default black checkerboard background for styles a conscious decision or a similar caching/temporary problem? I notice if I specifically render a map background in white and then remove it the default returns to the white checkerboard of previous versions.

**Comment by samanpwbb** [comment]
Great.

The color of the checkerboard is based on the background color you've defined for your `Map` layer. With no background set, it's dark gray.
