### ISSUE TITLE
Cache bust for next release 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#907]
Every release seems to cause major problems for users on first run because of caching issues. We should make sure node atom is pulling fresh assets when there's a version bump.

Not sure if there's tm1 precedence for this or what. Would this technique work for us? http://stackoverflow.com/questions/9692665/cache-busting-via-params - requires updating asset path names in templates with each release,

**Comment by yhahn** [comment]
I wonder if adding a nocache kind of querystring to the CSS URLs will do the trick:

https://github.com/mapbox/mapbox-studio/blob/mb-pages/templates/style.html#L25-L28
