### ISSUE TITLE
Problem when initial save contains CartoCSS error

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#910]
1. Create a new style project
2. Enter some invalid CartoCSS
3. Ctrl+S to save-as
4. Get error about invalid CartoCSS, close modal & fix the code.
5. Ctrl+S again, get error "Destination path /whatever.tm2 exists"

The Save As button does work at this point, its just the keyboard shortcut that raises the error.

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/issues/858
