### ISSUE TITLE
Save button displays 2 states

### ISSUE THREAD

**Issue by davo** [mapbox/mapbox-studio-classic#911]
The "Save" button is displaying 2 states: "Save" and "Saved" at the same time.

In Mapbox Studio Version 0.1.3 for Mac.

![screen shot 2014-10-01 at 3 25 50 pm](https://cloud.githubusercontent.com/assets/76307/4480598/b3fcca6c-4998-11e4-8a38-5b9fd4ca3ac8.png)

**Comment by samanpwbb** [comment]
@davo see https://github.com/mapbox/mapbox-studio/issues/905
