### ISSUE TITLE
UI bugs in v0.1.3

### ISSUE THREAD

**Issue by luiscape** [mapbox/mapbox-studio-classic#914]
After installing v0.1.3 I've been seeing a number of UI related bugs. The overall functionality seems to be fine thus far though. 

I'm on a Mac OSX (10.9.4)

![screen shot 2014-10-01 at 4 24 16 pm](https://cloud.githubusercontent.com/assets/953118/4482469/f123589c-49a8-11e4-8264-a56313901f34.png)

**Comment by samanpwbb** [comment]
@luiscape I am almost positive that this is a caching issue. Can you try quitting Studio and restarting a couple times? See https://github.com/mapbox/mapbox-studio/issues/907
