### ISSUE TITLE
Background tile layer option for source editor

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#92]
This would be very useful for context, especially when designing a minimal vector source from scratch. Could also help identify/verify issues in your data.

**Comment by heyitsgarrett** [comment]
@ajashton What kind of layer do you see here? A simplified version of Mapbox Streets?

**Comment by yhahn** [comment]
Let's not work on this right now -- this would affect how the xray style works upstream in tilelive-vector and don't think it makes sense for this to require more contextual data than your actual data layer.
