### ISSUE TITLE
can't "Create style from this source" after adding a layer

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-studio-classic#939]
1. New project, Blank source
2. New layer from a file
3. Click on "Create style from this source":

![image](https://cloud.githubusercontent.com/assets/98601/4567266/8a929052-4f2f-11e4-8141-8a2a6c6cf1fc.png)

Result: it doesn't do anything. Is it disabled? Hard to tell, since grey text is so prevalent in the UI. If it is disabled, I should have some indication as why, and what I need to do to make it enabled.

**Comment by samanpwbb** [comment]
> If it is disabled, I should have some indication as why, and what I need to do to make it enabled.

ya, this is the pattern we use elsewhere:
![screen shot 2014-10-08 at 5 13 45 pm](https://cloud.githubusercontent.com/assets/108094/4567323/0419ab7c-4f30-11e4-850e-6136dbb53a79.png)

**Comment by amoeba** [comment]
I just ran into this issue. You need to save your source first. Then you will see the text become white and clickable.
