### ISSUE TITLE
Export Mbtiles download feature. -- bug. no download files showing.

### ISSUE THREAD

**Issue by chriscalip** [mapbox/mapbox-studio-classic#944]
Occuring in both Windows 7 and MAC OS.
Shapefile with about 652K of features .. and 4 attributes.
Generated mbtiles; but at the download phase.. saving file yields nothing.

**Comment by chriscalip** [comment]
I can see the in ~/.mapbox-studio/cache

**Comment by dbaldwin** [comment]
Just wanted to share that I'm seeing this issue as well with OS X and MapBox Studio 0.1.5.

**Comment by franckl** [comment]
+1 OSX and studio 0.1.6

**Comment by mtirwin** [comment]
Looks like we've isolated the error. Doesn't happen when accessing Studio through the browser, only when trying to download through the Atom environment.

`Uncaught TypeError: Cannot read property 'show' of undefined atom.js`

**Comment by ashleyclough** [comment]
It's not quite the same thing - whilst running directly in the browser does indeed allow me to export the mbtiles, I still can't do a direct upload.

**Comment by esisa** [comment]
Same thing happens for me with Mapbox Studio 0.2.2
