### ISSUE TITLE
Downloading Studio upgrade is a never-ending loop

### ISSUE THREAD

**Issue by alianthes** [mapbox/mapbox-studio-classic#951]
I can only download the upgrade for Studio over and over again. Upon opening the new version I get this prompt every time (despite deleting all old remnants):  

![](https://s3.amazonaws.com/uploads.hipchat.com/81832/1108700/KzEHvgXclBaun66/Screenshot%202014-10-22%2010.21.02.png)  

cc @yhahn @camilleanne

**Comment by MarkWS** [comment]
I'm on version 0.1.5 and upgraded to 0.6
now v0.6 fails to start so I've moved back to version 0.5
Win 7 pro, 64bit

**Comment by wilhelmberg** [comment]
@MarkWS 
The problem appears, because 0.1.6 is now a 64bit app.

On Windows you can do the following:
- manually uninstall 0.1.5:
  - go to the Control Panel
  - choose `Uninstall a program`
  - select `mapbox studio`
  - afterwards make sure that `C:\Program Files (x86)\mapbox-studio` is gone
  - if not, delete it
- install 0.1.6
  - verify that it has been installed into `C:\Program Files\mapbox-studio`

If Mapbox studio just shows the white/gray loading screen and then disappears, delete `C:\Users\<YOUR_USER_NAME>\.mapbox-studio`.

**Comment by ffepora** [comment]
I have the same problem on win7 64bits, but the solution doesn't work. And it is not possible to moved back to version 0.1.5, because the problem is now the same with this version.

**Comment by wilhelmberg** [comment]
With `problem` you mean just seeing the loading screen and then MapBox Studio disappears?
Have you tried deleting `C:\Users\<YOUR_USER_NAME>\.mapbox-studio`?

**Comment by ffepora** [comment]
yes exactly. I have deleted C:\Users<YOUR_USER_NAME>.mapbox-studio and the problem is the same.

**Comment by wilhelmberg** [comment]
@ffepora are you working with shapefiles locally?
At the moment it seems there are some problems with shapefiles on Windows.

You could try to create a spatial index with the `shapeindex.exe`, which you can find here:

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64\
```

e.g.:

```
cd <DIRECTORY\WITH\SHAPEFILE>
"C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-x64" <YOUR-SHAPE-FILE>.shp
```

Do this with all the shapefiles you have in your local source.

Do this help?

**Comment by ffepora** [comment]
I have shapefiles on my local disk, but i don't use them in mapbox. I jsu use the mapbox street data. Is it possible that shapefiles can make trouble on Mapbox Studio startup ?

**Comment by wilhelmberg** [comment]
No, they won't do any harm if you don't use them with MapBox studio.

Have you tried starting Studio several times?
Does your `C:\Users\<USER>\.mapbox-studio\app.log` contain any messages except `Mapbox Studio @ http://localhost:3000/`?

**Comment by chadwilcomb** [comment]
I recently downloaded version 0.1.6 and am getting the same issue referenced above (just seeing the loading screen and then MapBox Studio disappears). I had previously installed version 0.1.0 (it was removed during install of 0.1.6) but had never run it that I recall.

I followed the steps listed <a href="https://github.com/mapbox/mapbox-studio/issues/951#issuecomment-60475603">here</a>, including deleting the <code>C:\Users<YOUR_USER_NAME>.mapbox-studio</code> directory but I still get the loading screen and then MapBox Studio disappears.

I am running Windows 7 Enterprise SP1, 64-bit

**Comment by ffepora** [comment]
@BergWerkGIS my app.log file is empty, without the mention ~~Mapbox Studio @ http://localhost:3000/~~

**Comment by chadwilcomb** [comment]
Yes, forgot to mention, my app.log file is empty as well. 

A colleague of mine mentioned he had a similar issue but after starting the application 4-5 times, it finally opened. I have not had such luck.

**Comment by springmeyer** [comment]
v0.2.0 should fix both of the issues described above:
- startup fails (window closes before you see anything)
- upgrade windows keeps on prompting

If startup still does not work for anyone finding this issue can you please try these steps to fix it: https://github.com/mapbox/mapbox-studio/issues/969#issuecomment-64313694
