### ISSUE TITLE
Docs on where logs are

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#956]
Logs get put in `~/.mapbox-studio/app.log` I learned from reading the changelog, but ideally we could have a docs page to point users at to help in debugging crashes.

**Comment by ian29** [comment]
big huge +1

also we should add this to `CONTRIBUTING.md`

**Comment by camilleanne** [comment]
Also users on mac can access them from the menu bar --> Help --> Application Log

**Comment by alexrollin** [comment]
Windows?

**Comment by mohsentaleb** [comment]
I'm also looking for log file path in windows.

**Comment by wilhelmberg** [comment]
@discursives @mohsentaleb 
`%USERPROFILE%\.mapbox-studio`
See [here](https://github.com/mapbox/mapbox-studio/issues/1118#issuecomment-69325780)

**Comment by camilleanne** [comment]
now in `CONTRIBUTING.md`
