### ISSUE TITLE
Link to old binaries on https://www.mapbox.com/mapbox-studio/

### ISSUE THREAD

**Issue by artemp** [mapbox/mapbox-studio-classic#958]
A new version of Mapbox Studio is available
Your version: 0.1.5 Latest version: 0.1.6

https://www.mapbox.com/mapbox-studio/#darwin still points to 0.1.5

**Comment by samanpwbb** [comment]
Agh, sorry. I did this out of sync. Should be updated any minute now.

**Comment by artemp** [comment]
No worries, cheers!
