### ISSUE TITLE
Binary download link points to 0.1.5. Should point to 0.1.6

### ISSUE THREAD

**Issue by jqtrde** [mapbox/mapbox-studio-classic#959]
Starting Mapbox Studio 0.1.5 prompts you to download 0.1.6, which takes you to [mapbox.com/mapbox-studio](https://www.mapbox.com/mapbox-studio/#darwin), which shows a download link for the old 0.1.5 version.

The link to the [0.1.6 binary](https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-darwin-x64-v0.1.6.zip) does work.

**Comment by samanpwbb** [comment]
Should be fixed now.
