### ISSUE TITLE
Fonts, how to load custom fonts?

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#963]
has anyone loaded fonts from the local font directory or loaded any other fonts that are not part of MBS? With TileMill it was rather easy to locate the font directory, I'm having a hard time figuring out how to load our font sets with the new MBS? 
Thanks.

**Comment by samanpwbb** [comment]
This feature is on it's way: https://github.com/mapbox/mapbox-studio/issues/395

**Comment by MarkWS** [comment]
Any new news on this?we are at a standstill until we can load our own fonts.
Thanks.

**Comment by samanpwbb** [comment]
@MarkWS check out https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-advanced-features.md#custom-fonts -> if you built Mapbox Studio from source this feature is available now. Expect a proper release in a few days.
