### ISSUE TITLE
Cannot run studio on linux ubuntu 13.10

### ISSUE THREAD

**Issue by jaksky** [mapbox/mapbox-studio-classic#965]
1/ download the zip 
2/ unpack
3/
bro@home:~/Development/mapbox-studio-linux-x64-v0.1.6$ ./atom  
bash: ./atom: cannot run a binary file

Version OS:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:        13.10
Codename:       saucy

**Comment by yhahn** [comment]
@jaksky are you on a 32-bit ubuntu install?

**Comment by caarloshugo** [comment]
how can i run it in 32?

**Comment by springmeyer** [comment]
@caarloshugo 32 bit linux is not supported via the provided packages. I would highly recommend using a 64 bit system. If you can't for some reason, then a source install would be needed: #898

**Comment by caarloshugo** [comment]
Ok, I will try with 64t bit, thank you!
