### ISSUE TITLE
Testing mapnik 3 font-scoping

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-studio-classic#968]
@samanpwbb per convo, we should be able to test this out already.
- [x] Add packageable font extensions to this filter: https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/style.js#L440-L449
- [x] Create a test style with a local custom font + package
- [x] Test how it handles when uploaded to Mapbox API

**Comment by samanpwbb** [comment]
https://github.com/mapbox/mapbox-studio/pull/973
