### ISSUE TITLE
Application Will Not Start

### ISSUE THREAD

**Issue by WEMcode** [mapbox/mapbox-studio-classic#969]
System Windows 7 64-bit OS.
Version: 0.1.6

Behaviour:
Application screen is white with spinning loader; Application then closes.

Other Notes:
Nothing in the system or application event log.

Rollback Behaviour:
Reverted to 0.1.5 and everything loads - projects and account included.
Project was created with 0.1.5 application was not upgraded prior to this.

**Comment by wilhelmberg** [comment]
@cdunsingwem Could you try the steps outlined [here](https://github.com/mapbox/mapbox-studio/issues/951#issuecomment-60475603) and report back, if that solved your problem.

**Comment by WEMcode** [comment]
I followed these steps and problem persists:

**manually uninstall 0.1.5:**
- go to the Control Panel
- choose Uninstall a program
- select mapbox studio
- afterwards make sure that C:\Program Files (x86)\mapbox-studio is gone
- if not, delete it

**install 0.1.6**
- verify that it has been installed into C:\Program Files\mapbox-studio

If Mapbox studio just shows the white/gray loading screen and then disappears, delete C:\Users<YOUR_USER_NAME>.mapbox-studio.

Even after this step: Mapbox studio _continues_ to show the white/gray loading screen and then disappear.

**Comment by jordantrain** [comment]
Same thing here.  See later comments in issue #974.

**Comment by wilhelmberg** [comment]
@cdunsingwem could you try the steps outlined [here](https://github.com/mapbox/mapbox-studio/issues/976#issuecomment-61400660) with a 0.1.6 install and tell if this works for you?

**Comment by springmeyer** [comment]
@jordantrain and @cdunsingwem can you try this build: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x64-windows-cpp11.exe and let me know if it works for you?

**Comment by springmeyer** [comment]
fixed by #1040 - thanks @BergWerkGIS for making this happen

**Comment by springmeyer** [comment]
v0.2.0 is now available for download: https://www.mapbox.com/mapbox-studio

**Comment by WEMcode** [comment]
I downloaded v0.2.0 this and am seeing no change. Loading screen then application closes.

**Comment by springmeyer** [comment]
@cdunsingwem the v0.2.0 installers are currently temporarily unavailable at https://www.mapbox.com/mapbox-studio/, so I'm not sure how you downloaded it?

**Comment by WEMcode** [comment]
It was available on the 19th (I downloaded it then). I see that it is no longer available. Shouldn't this ticket still be open?

**Comment by springmeyer** [comment]
@cdunsingwem - thanks for clarifying. Re-opening this ticket so we can try to resolve why this is happening on your system. I will ping here once we have a new installer for you to test.

**Comment by springmeyer** [comment]
@cdunsingwem - can you try:
- Rebooting your machine (this should effectively stop any background process that might be running and preventing the install from working, notably "atom.exe" processes)
- Upon rebooting then re-run the mapbox-studio v0.2.0 installer and make sure you don't have Mapbox Studio running at the same time

After doing this then try starting Mapbox Studio again - and let me know if it works.
