### ISSUE TITLE
Toolbar buttons have mismatched icons

### ISSUE THREAD

**Issue by lqb2** [mapbox/mapbox-studio-classic#971]
Almost all of the buttons are mismatched. The search function (tied to the far left/first button) is wrong, the zoom buttons are the search icon and some alien thing, etc.

![screen shot 2014-10-28 at 9 50 23 am](https://cloud.githubusercontent.com/assets/6601609/4809338/ba7e4128-5eaa-11e4-8c13-7eb84a1909c4.png)

**Comment by samanpwbb** [comment]
Hey @lqb2 - this is a caching isssue, can you try restarting the app a few times and see if the problem persists?

**Comment by lqb2** [comment]
Three restarts fixed it. Thanks.
