### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by jordantrain** [mapbox/mapbox-studio-classic#974]
Upgraded mapbox studio to v.0.1.6 after removing mapbox studio and manually deleting C:\Program Files\mapbox-studio.  On startup the program crashes with an uncaught exception Error: Spawn UNKNOWN at exports._ernoException (util.js:742:11)  ...  Machine is running Windows 7.

**Comment by wilhelmberg** [comment]
@jordantrain 
Maybe you deleted the wrong directory. You should delete
`C:\Program Files (x86)\mapbox-studio` not
`C:\Program Files\mapbox-studio`.

Could you run the 0.1.6 installer again and see if that solves the problem?

**Comment by jordantrain** [comment]
Thanks for responding.  My Windows 7 32 bit OS machine does not have a Program Files (x86) directory, only a Program Files directory.  I have tried removing and reinstalling the app several times.  I finally gave up and was able to reinstall the 0.1.5 version of Mapbox Studio and it works fine, though I would like to be able to access the new features in the current release.

**Comment by wilhelmberg** [comment]
Oh, sorry, I forgot to ask about your architecture.
Latest Mapbox Studio is 64bit only.
Any chance you upgrade to a 64bit OS?

**Comment by jordantrain** [comment]
Not on this machine.  How about doing an OS check before seducing people to upgrade their software?   There was no mention that the update was for 64 bit OS only.   I am lucky I still had the original setup.exe file for 0.1.5 lying around.  I really didn't want to clone or install the source code of the historic releases and compile from there and I never could find a link to compiled earlier releases.

**Comment by yhahn** [comment]
@jordantrain sorry about the bumpy ride.
- we added a list of previous releases here: https://github.com/mapbox/mapbox-studio/blob/mb-pages/docs/0000-01-01-previous-releases.md
- the 64 bit switch was mentioned in the changelog here: https://github.com/mapbox/mapbox-studio/blob/mb-pages/CHANGELOG.md#016

We can look into linking to the changelog from the update page in the future.

**Comment by jordantrain** [comment]
I just did a fresh install of v.0.1.6 on a Windows 8 64 bit OS machine.   No version of mapbox has ever been on this machine.  The app launches to show the white screen with the progress circle, then closes down immediately.  Can't get past the white screen.  Any ideas?

**Comment by wilhelmberg** [comment]
@jordantrain We are working on the problem, but are still looking for the real cause of this behavior.
As odd as it may seem, just restarting Studio several times might help.

**Comment by wilhelmberg** [comment]
@jordantrain Could you try the steps outlined [here](https://github.com/mapbox/mapbox-studio/issues/976#issuecomment-61400660) (assumes 0.1.6 on 64bit machine) and tell me if it works for you, too?

**Comment by lhilarides** [comment]
@BergWerkGIS I experienced the same issue on a 64bit Windows 7 machine and your solution solved it. Thanks!

**Comment by wilhelmberg** [comment]
@lhilarides Thanks. Good to know. We are working hard on a new release.

**Comment by alexrollin** [comment]
FYI I tried the solution on a fresh install and it didn't work.
On the machine where the patch worked, it was previously running an earlier
version. I installed 1.6, tried opening it, discovered the issue, patched,
and then found success.

On the 2nd machine, I did a fresh install of 1.6 and patched it before even
opening MS. The program will not open, and it doesn't even show a grey
loading hint, it just stays white. Doesn't crash, but doesn't do anything
else, either.  This is the very same installer used on the other machine.

## 

Alex

**Comment by tpstigers** [comment]
I had the same problem running on Windows 8.1 64bit.  Replacing gdal.node and node.exe worked for me.

Thanks!

**Comment by springmeyer** [comment]
thanks for the report @tpstigers. Update here is that we are still working overtime to release an official update that applies this fix - it is taking some time since we want to make sure this is the last time this type of glitch happens.

**Comment by jordantrain** [comment]
Thanks, Dane.  It's a great product... looking forward to using it some
more.
- Jordan

On Fri, Nov 7, 2014 at 5:11 PM, Dane Springmeyer notifications@github.com
wrote:

> thanks for the report @tpstigers https://github.com/tpstigers. Update
> here is that we are still working overtime to release an official update
> that applies this fix - it is taking some time since we want to make sure
> this is the last time this type of glitch happens.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapbox/mapbox-studio/issues/974#issuecomment-62234205
> .

## 

-Jordan

**Comment by springmeyer** [comment]
Anyone here on OS X 10.8, can you try this mapbox-studio build: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-darwin-x64-windows-cpp11.zip

Anyone on windows can you try this build: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x64-windows-cpp11.exe

And report back how they work?

**Comment by tpstigers** [comment]
Just installed and ran it on my Windows 8.1 box.  Started up and ran just fine.  I poked around a bit and everything was fine, but I won't have time to really put it through its paces until later this weekend.

**Comment by andymiller-gb** [comment]
Hi Dane

I'm on OS 10.9 and it seems to work fine. (Sorry if that's a bit vague but I'm  a newbie to MapBox so I don't know enough yet to do more than launch it and have a look around).

**Comment by springmeyer** [comment]
Thanks for the testing feedback everyone and to @BergWerkGIS for figuring out and helping fix the problems. This will be fixed in the next release that will land anytime now: #1040

**Comment by springmeyer** [comment]
v0.2.0 is now available for download: https://www.mapbox.com/mapbox-studio

**Comment by dchadney** [comment]
My installation was working fine on version 1.5. Just upgraded to v0.2.0 and now it's crashing every time I open it. Tried uninstalling, deleting the directory, replacing gdal.node and node.exe, installing in C:\Program Files (x86)\mapbox-studio and in C:\Program Files\mapbox-studio.... nothing works. I am on Windows 7.

**Comment by springmeyer** [comment]
@dchadney can you fetch the logs (which are located in a fill called `app.log` in your user's directory in a folder called .mapbox-studio) and post them here?

**Comment by wilhelmberg** [comment]
@dchadney 

If `app.log` does not contain any useful information, it would of great help for us, if you have the time to work through this gist:
[Debug Mapbox Studio](https://gist.github.com/BergWerkGIS/534a5e74301c5607af5c)

Let me know, if you need further assistance.

**Comment by votivate** [comment]
I was experiencing the issue of MapBox Studio closing immediately after opening in Win 7 and discovered that it started working when I uninstalled, manually deleted the .mapbox-studio folder in my C:\Users\user folder, then reinstalling. It started opening fine after that.
