### ISSUE TITLE
Can't export image with local source

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#975]
Mentioned in #691, but there's no technical reason why static image export should be disabled when using a local source, right? Also it's not obvious that the "Use remote source to share" warning in the settings panel is related to the image export button.

**Comment by tkrajacic** [comment]
Interestingly, the Natural Earth example can be exported as image, and I would consider this a local source (it is being imported into the local PostGIS database isn't it?)

I never really understood why some features are disabled (from looking at the interface)

I just guessed that Mapbox wants to sell their service, so other sources' features are "crippled" in Mapbox Studio (which is of course an understandable choice)

**Comment by wilhelmberg** [comment]
Works for me :smirk: 

![image](https://cloud.githubusercontent.com/assets/4549888/9732273/cdbfd6be-5622-11e5-976a-d34105cb94e0.png)
