### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Jaxattack** [mapbox/mapbox-studio-classic#976]
Using Mac OSX 10.8.5, 

Mapbox Studio opens with the grey loader/spinner screen, and then immediately closes/crashes. Every time

**Comment by geografa** [comment]
Hey @Jaxattack - currently, Mapbox Studio is only available for 10.9 and higher. https://github.com/mapbox/mapbox-studio/#depends

**Comment by sindile** [comment]
The same is happening with Windows 8.1 64bit
This after downloading and installing mapbox-studio-win32-x64-v0.1.6

**Comment by springmeyer** [comment]
thanks for these reports @Jaxattack and @sindile - we are working on understanding the problem and will hope to have a new release soon to fix these issues.

**Comment by jasonpomerleau** [comment]
I have same issue as @sindile, mapbox-studio-win32-x64-v0.1.6. Happy to provide any info requested.

**Comment by wilhelmberg** [comment]
@jpomer74 If you have some time to spend, you could follow my gist about [debugging mapbox-studio](https://gist.github.com/BergWerkGIS/534a5e74301c5607af5c).

Let me know, if you need any further assistance in doing so.

**Comment by srrichter** [comment]
I have the same issue on Windows 7 x64. I started the gist with WinDbg and it stopped at ntdll's ZwTerminateProcess, allowing me to see an error with stacktrace in the mapbox-studio window saying that it could not find the gdal node. The path it tried is "C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik-omnivore\node_modules\gdal\lib\binding\gdal.node", where I do have a gdal.node. It seems like loading the node fails.

**Comment by wilhelmberg** [comment]
Very strange. Never seen this before. Could you post the log file from `c:\mbslog\` to a gist?

**Comment by wilhelmberg** [comment]
@srrichter would you mind downloading [this zip](https://dl.dropboxusercontent.com/u/13256369/gdal-node.zip) and replacing the following files (please make a backup of the existing files, just in case) in your 0.1.6 install:

Replace `gdal.node` in

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik-omnivore\node_modules\gdal\lib\binding\
```

Replace `node.exe` in

```
C:\Program Files\mapbox-studio\resources\app\vendor\
```

Does Mapbox Studio still crash?

**Comment by ColoGISpro** [comment]
I was experiencing the startup crash issue using mapbox-studio-win32-x64-v0.1.6.  I downloaded @BergWerkGIS Zip and replaced the two files noted above.

That fixed it for me!  Thank you @BergWerkGIS .

**Comment by springmeyer** [comment]
Great! Thanks for testing @ColoGISpro!

**Comment by sindile** [comment]
I have replaced the files as per @BergWerkGIS.

Mapbox Studio works, Thank you.

**Comment by alexrollin** [comment]
Also (again) on Win7 64., I tried the zips, yay! it goes again!

**Comment by wilhelmberg** [comment]
@discursives Thanks for letting us know.

**Comment by jasonpomerleau** [comment]
This fixed it for me as well; thanks. I was away this weekend, sorry I couldn't assist w/testing, but looks like you've got it.

**Comment by wilhelmberg** [comment]
@jpomer74 that's what weekends are for :smile: 
Thanks for your feedback, good to know that it is fixed for you, too.

**Comment by bladepeter** [comment]
this fixed worked,thanks @BergWerkGIS

**Comment by jasonwoo** [comment]
Thanks for this fix @BergWerkGIS. It was a huge help. (Windows 7 64bit)

**Comment by springmeyer** [comment]
Anyone here on OS X 10.8, can you try this mapbox-studio build: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-darwin-x64-windows-cpp11.zip

Anyone on windows can you try this build: https://mapbox.s3.amazonaws.com/mapbox-studio/mapbox-studio-win32-x64-windows-cpp11.exe

And report back how they work?

**Comment by maptastik** [comment]
Thanks for the fix @BergWerkGIS. It did the job!

**Comment by MarkWS** [comment]
That worked for me as well. Thanks!

**Comment by springmeyer** [comment]
Thanks for the testing feedback everyone and to @BergWerkGIS for figuring out and helping fix the problems. This will be fixed in the next release that will land anytime now: #1040

**Comment by springmeyer** [comment]
v0.2.0 is now available for download: https://www.mapbox.com/mapbox-studio

**Comment by GeertClaes** [comment]
I just downloaded and installed the latest version of MapBox Studio and it crashes on startup just as the op described.  Does one still need to patch this using the workaround described by @BergWerkGIS above??

**Comment by wilhelmberg** [comment]
@GeertClaes no, these instructions are obsolete now.

Please try the following:
- make sure (via Task Manager) that no `node.exe` or `mapbox-studio.exe` processes are running. If there are, kill them
- open a console:
  - press: Windows key + r
  - type `cmd`
  - ENTER
- `cd "C:\Program Files\mapbox-studio\resources\app"`
- `vendor\node.exe index.js`

What is the result of the above procedure?
- If the message contains `Mapbox Studio @ http://localhost:3000/` then it works:
  - open your browser at http://localhost:3000/
  - check if you can use Mapbox Studio Classic
  - when you are finished testing, goto back to the console and press `Ctrl+c` to end Mapbox Studio
  - you should be able to start it via the application shortcut, too
- If there is an error message, post it here.

**Comment by GeertClaes** [comment]
I did get go through the steps and I did get 
<Fri, 02 Oct 2015 11:03:35 GMT> Mapbox Studio @ http://localhost:3000/

I opened the browser at http://localhost:3000/

It showed a page asking to "Connect to your Mapbox account to get started."  When clicking the Connect button the following error popped-up:

<Fri, 02 Oct 2015 11:05:20 GMT> error 500 { [Error: Cannot find Mapbox API at ht
tps://a.tiles.mapbox.com]
  method: 'GET',
  url: '/oauth/config?MapboxAPITile=https%3A%2F%2Fa.tiles.mapbox.com' }

The MapBox Studio still crashes upon startup (I assume this is what you meant with MapBox Studio Classic?)

**Comment by wilhelmberg** [comment]
New naming: Previous offline `Mapbox Studio` became `Mapbox Studio Classic`.
New online version (https://www.mapbox.com/mapbox-studio/) is just `Mapbox Studio`.

Two problems:
- there cannot be two running instances of Mapbox Studio Classic at the same time. Either you start it via console or via the application shortcut. So it is expected to crash via application shortcut if you also started it via console before
- It seems you are behind a proxy (`Error: Cannot find Mapbox API`)

Proxy support is a problem that has been nagging us for quite some time.
Because of third party libraries that are out of our control `Mapbox Studio Classic` has to be started with direct internet access when used the very first time (Authentication with Mapbox).

Afterwards it can be used behind a proxy, but has to be started from the console every time, as you have to set the proxy manually:

```
SET HTTP_PROXY=http://<PROXY-IP>:<PROXY-PORT>
SET HTTPS_PROXY=http://<PROXY-IP>:<PROXY-PORT>
```

and then start via `vendor\node index`.

**Comment by GeertClaes** [comment]
I have a feeling this will not work because we are indeed behind a proxy but the connection uses  a pac configuration file.

**Comment by wilhelmberg** [comment]
Proxy pac:
You could try to download the pac (paste the pac url into the browser's address bar, most of the time it downloads just fine) and extract the proxy information (it's a text file) and then set `HTTP_PROXY`/`HTTPS_PROXY` via console.

First start:
Maybe you could try to authenticate at home and then copy over the `%USERPROFILE%\.mapbox-studio` folder to your machine at work.
Although I must admit, I haven't tried that and don't know, if it will work.
