### ISSUE TITLE
Source editor: Support custom input projections

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-studio-classic#98]
Right now the only choices are WG84 and Web Mercator. Is this an intentional restriction for performance, or should we support any input like TM1?

**Comment by yhahn** [comment]
- [x] Change projection dropdown to textfield on all the `mapnik-omnivore` layer templates
- [x] Have the mapnik omnivore metadata inspection autofill the projection string

**Comment by GretaCB** [comment]
@yhahn Will the projection text field autofill after uploading the file, therefore being just a read-only field?
Or...will the value of the projection text box be editable and therefore, the value within the input box changes the output of the map?

**Comment by yhahn** [comment]
Not sure ... I think editing this field directly is like a super power-user-expert use case and for everyone else is basically a trap : |

**Comment by GretaCB** [comment]
@yhahn 
Ok, for now I will just add the straight up projection string (`+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs`) and make it read-only.

**Comment by yhahn** [comment]
:+1:
