### ISSUE TITLE
Nest "Add" button under Places

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-studio-classic#980]
![2014-10-30 at 3 33 pm](https://cloud.githubusercontent.com/assets/32314/4850674/a8e77372-606b-11e4-84d2-6377b6f50bdf.png)

This button isn't very clear in what it does: adds what? Can we either
- Rename it "Add Place"
- Or only show it when you are in the places UI

**Comment by yhahn** [comment]
https://github.com/mapbox/mapbox-studio/issues/747
