### ISSUE TITLE
Labels Cut Off at Tile Border in Online Tiles and Exported Flat Images

### ISSUE THREAD

**Issue by alexrollin** [mapbox/mapbox-studio-classic#990]
I have a lot of labels but the cutoff applies at various zoom levels whether they are particularly dense or not 

MS 1.6 patched on win7/64

Is there a way to adjust meta tile size? Setting meta tiles to 8 in TM1 fixed this in 98% of my own cases.

**Comment by alexrollin** [comment]
This image shows how consistant the cropping is. 
![20141104_094651](https://cloud.githubusercontent.com/assets/114659/4894117/e7e63798-63cc-11e4-828f-73670e41d602.jpg)

**Comment by yhahn** [comment]
@discursives hrm, what is the buffer size on the layer you're using? Based on the placement of your labels you will need a large buffer to accommodate the text across tile boundaries.

Note: you can increase the buffer size beyond 64 by editing the `data.yml` of your source project directly.

**Comment by alexrollin** [comment]
I have only defaults.
Would you please advise a buffer size?
Data is geojson 3000 points at 3.5mb as vector data layer.
In TM I ran as high as 1024.

**Comment by alexrollin** [comment]
OIC this is a different kind of buffer:

https://www.mapbox.com/mapbox-studio/source-manual/

I am sorry, I cannot find an example of data.yml

Can you point me at something?  And perhaps 128 will be enough?

## 

Alex

**Comment by alexrollin** [comment]
Are data.yml files used on Windows? Can someone give me a pointer for how to create the data.yml file from ...other project information?

**Comment by ajashton** [comment]
@discursives data.yml files exist automatically for all Mapbox Studio source projects, you shouldn't have to create one yourself. It exists inside the `*.tm2source` project folder. After making changes to the yml file in a text editor you'll need to restart Mapbox Studio and re-export your source project. To see the changes in your style project, hit the refresh button in the layers panel.

**Comment by alexrollin** [comment]
i set the layer to 256 , but, seems i need 512 set in the yml file, eh?

thanks.

## 

Alex
