### ISSUE TITLE
Any news on adding custom Fonts?

### ISSUE THREAD

**Issue by MarkWS** [mapbox/mapbox-studio-classic#991]
any news when the next version will be able to handle custom fonts? We are at a standstill until we can load our own fonts.
Thanks..

**Comment by springmeyer** [comment]
Yes, the next version will support custom fonts and we will be sharing details on this via the mapbox blog as soon as we get to a stable release (currently focused on Windows stability).

**Comment by MarkWS** [comment]
That's great! Thanks...

**Comment by wboykinm** [comment]
Thanks Dane; it works great.

**Comment by fallenartist** [comment]
Awesome, looking forward to the release.
