### ISSUE TITLE
Reapeated labels on polygon feature

### ISSUE THREAD

**Issue by ste-goldstein** [mapbox/mapbox-studio-classic#992]
I'm trying to label a polygon layer.
I wanted to have only one label per feature showing, but right now there is one label per feature per tile.

So the more I zoom in, the more repeated lables I have:
http://imgur.com/PBaQPUp

I tried using 
text-placement: point
and
text-placement: interior;

Is this a bug or am I missing somehting ?

**Comment by ajashton** [comment]
Hi,

This is not really a bug, just a consequence of how vector tiles work. Polygon layers should not be used directly for labeling; create a separate layer of polygon center points for the labels. See the Labeling Polygons section of the [source manual](https://www.mapbox.com/mapbox-studio/source-manual/)

**Comment by ste-goldstein** [comment]
Hi.
This was my first guess. I searched around but I missed the link you sent.
Thanks!
