### ISSUE TITLE
Easier adjustment of buffer

### ISSUE THREAD

**Issue by pnorman** [mapbox/mapbox-studio-classic#994]
I had to adjust the buffer on a layer from 8 to 16. I found myself very carefully moving the mouse, trying not to overshoot the value I wanted by a single pixel.

It would be nice to be able to input the value, or at the very least, a wider bar, as a workflow that relies on single pixel positioning of the mouse is not ideal.

**Comment by alexrollin** [comment]
mmm...where is the buffer adjustment?

## 

Alex

**Comment by pnorman** [comment]
Layer configuration

![image](https://cloud.githubusercontent.com/assets/1190866/4946176/bdffc692-6610-11e4-86a9-7050ed906de9.png)

**Comment by yhahn** [comment]
y textfield == less fancy but better in all ways right?

**Comment by pnorman** [comment]
For me yes. The advantage of a bar is that it gives some context to what a reasonable maximum is - but in my case I'm working out buffers from the style, so I get the numbers from a calculator.

**Comment by duncangraham** [comment]
I frequently bump into the same issue.
I think the best solution would be updating the value on the right as you move the slider.

**Comment by duncangraham** [comment]
I've made a branch that improves the functionality of range inputs [here](https://github.com/mapbox/mapbox-studio/tree/oninput)

![oninput](https://cloud.githubusercontent.com/assets/865298/5051600/4e00257e-6bee-11e4-9f6e-968b1de183b5.gif)

I grepped the folder for all occurrences of rangeHandler, and replaced the onchange listeners with oninput listeners.

![screen shot 2014-11-14 at 10 52 57 am](https://cloud.githubusercontent.com/assets/865298/5051603/519d3f78-6bee-11e4-9498-23c8aeeee912.png)

**Comment by duncangraham** [comment]
PR for range input improvement here https://github.com/mapbox/mapbox-studio/pull/1028
