### ISSUE TITLE
unable to read metadata

### ISSUE THREAD

**Issue by probabble** [mapbox/mapbox-studio-classic#995]
Just trying to use Studio to test out some cartocss designs on some PostGIS layers. I can connect to the db, use a query to show me the available fields, but when i click on the marker icon (I think this would "zoom-to" the extent), I get this error:

![image](https://cloud.githubusercontent.com/assets/3421159/4927290/486212ea-653a-11e4-99ca-4238134fed96.png)

![image](https://cloud.githubusercontent.com/assets/3421159/4927302/63ef1c4c-653a-11e4-9018-faa4bb70a4e4.png)

![image](https://cloud.githubusercontent.com/assets/3421159/4927356/cf2edc2c-653a-11e4-9830-6b514af5941e.png)

![image](https://cloud.githubusercontent.com/assets/3421159/4927351/c2a9c0ac-653a-11e4-9f3d-6a74dcc2fa49.png)

**Comment by kriscarle** [comment]
I'm also getting this error when using PostGIS. The message in the console is:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
GET http://localhost:3000/metadata?file=undefined 500 (Internal Server Error)
```

It looks like it may be related to #393? zoomToLayer is only implemented for local data?

A work-around is to add some sort of base layer data, e.g. a country boundaries shapefile, so you can find your data on the map. Then once you've centered the map and saved it you can remove the base layer.

**Comment by wilhelmberg** [comment]
Tracking at https://github.com/mapbox/mapbox-studio-classic/issues/1487
