### ISSUE TITLE
Zoom text (not map) when cursor is in text editor

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-studio-classic#997]
Currently, `command (+)` and `command (-)` (on OSX) zooms the map, no matter where your curser is in the UI. When the curser is in the text editor, can we change this to increasing and decreasing the text size instead?

This would be nice for doing live demoes on a projection/large screen. I currently use accessibility settings to zoom in and out the entire contents of my screen, but that is clunky and disorientating for viewers.

/cc @samanpwbb

**Comment by samanpwbb** [comment]
Sounds good. Should be easy to only override the behavior of `+` and `-` when user is interacting with map.
