### ISSUE TITLE
Add UI for displaying user-provided font names

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-studio-classic#999]

**Comment by yhahn** [comment]
Per voice, the main challenge here is making sure this list of fonts stays up to date as the user works on her map. We have a nice mechanism in the UI for updating on every save for a similar map-specific property -- the map background color -- and we can piggyback off the infrastructure we have already to add more information to this feedback loop.
- [x] update to mapnik 3.1.0
- [x] add a new call to the [map.fonts() function](https://github.com/mapnik/node-mapnik/blob/master/test/fonts.test.js#L74) after the background is passed back to pass back a list of fonts as well (`data.fonts` or so) https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/style.js#L119.
- [x] Here's the corresponding handling of the map background color update: https://github.com/mapbox/mapbox-studio/blob/mb-pages/app/style.js#L773-L778. You'll want to refresh the font listing here in the UI.
- [ ] Testing will be hard... but doable. We'll need a style with a font directory and we can test that there is font x in the listing when the carto CSS includes the directive and that it's not there when we remove it.

**Comment by springmeyer** [comment]
@samanpwbb - I've done a first pass on docs for how fonts work in Mapnik that hopefully will help you think about this: https://github.com/mapnik/node-mapnik/commit/0732841cc3e79e717225e29355613a4f3f29be17

**Comment by samanpwbb** [comment]
This is great, looks like I have some flexibility for how to implement this. Thanks @springmeyer
